import { Book, createUnit as unit } from "../book-types";

export const essential3: Book = {

    id: "4eew3",
    title: "4000 Essential English Words 3",
    subtitle: "Book 3",
    totalUnits: 30,
    units: [
      unit(1, [
        ["arise", "/əraɪz/", "paydo bo\'lmoq, tug\'ilmoq"],
        ["benefactor", "/ˈbɛnəˌfæktər/", "muruvvat ko\'rsatuvchi, xomiylik qiluvchi"],
        ["blacksmith", "/ˈblæksˌmɪθ/", "temirchi"],
        ["charitable", "/ˈʧɛrətəbəl/", "marhamatli, saxiy"],
        ["chimney", "/ˈʧɪmni/", "mo\'ri, mo\'ri quvuri"],
        ["compensate", "/ˈkɑmpənˌseɪt/", "pul to\'lamoq, qoplamoq"],
        ["encounter", "/ɪnˈkaʊnər/", "ro\'baro kelmoq, duch kelmoq"],
        ["exceed", "/ɪkˈsid/", "oshirib yubormoq, oshib ketmoq"],
        ["forge", "/fɔrʤ/", "munosabat yo\'lga qo\'ymoq, yasamoq"],
        ["humble", "/ˈhəmbəl/", "kamtar, tavozeli"],
        ["iron", "/aɪərn/", "temir"],
        ["ladder", "/ˈlædər/", "narvon, shoti"],
        ["modest", "/ˈmɑdəst/", "kamtarin, oddiy"],
        ["occupy", "/ˈɑkjəˌpaɪ/", "yashamoq, egallamoq"],
        ["penny", "/ˈpɛni/", "sent, tiyin"],
        ["preach", "/priʧ/", "va\'z o\'qimoq"],
        ["prosper", "/ˈprɑspər/", "rivojlanmoq, ravnaq topmoq"],
        ["province", "/ˈprɑvɪns/", "viloyat, provinsiya"],
        ["satisfaction", "/ˌsætɪsˈfækʃən/", "qoniqish, mamnuniyat"],
        ["sustain", "/səˈsteɪn/", "ta\'minlamoq, ushlab turmoq"],
      ]),
      unit(2, [
        ["acquire", "/əkˈwaɪər/", "topib olmoq, orttirmoq"],
        ["awkward", "/ˈɔkwərd/", "noqulay, xijolatli"],
        ["caretaker", "/ˈkɛrˌteɪkər/", "qarovchi, g\'amxo\'r"],
        ["deceive", "/dɪˈsiv/", "aldamoq, yolg\'on gapirmoq"],
        ["discourage", "/dɪˈskərɪʤ/", "umidsizlantirmoq, fikridan qaytarmoq"],
        ["fake", "/feɪk/", "sun\'iy, yasama"],
        ["hatred", "/ˈheɪtrəd/", "nafrat, yoqtirmaslik"],
        ["hut", "/hət/", "kulba, chayla"],
        ["inferior", "/ˌɪnˈfɪriər/", "past sifatli, sifatsizroq"],
        ["lodge", "/lɑʤ/", "ovchilar uyi, kulba"],
        ["neglect", "/nɪˈglɛkt/", "mensimay qaramoq, beparvo bo\'lmoq"],
        ["newcomer", "/ˈnuˌkəmər/", "yangi kelgan kishi"],
        ["offense", "/əˈfɛns/", "jinoyat, qonunbuzarlik"],
        ["overlook", "/ˈoʊvərˌlʊk/", "ahamiyat bermaslik, ko\'rmay qolmoq"],
        ["repay", "/riˈpeɪ/", "qarzni to\'lamoq, qaytarmoq"],
        ["ridiculous", "/rɪˈdɪkjələs/", "be\'mani, kulgili"],
        ["satisfactory", "/ˌsætɪsˈfæktəri/", "qoniqarli"],
        ["shepherd", "/ˈʃɛpərd/", "cho\'pon, podachi"],
        ["venture", "/ˈvɛnʧər/", "xatarli joyga bormoq"],
        ["wheat", "/wit/", "bug\'doy"],
      ]),
      unit(3, [
        ["alley", "/ˈæli/", "tor ko\'cha, alleya"],
        ["ax", "/æks/", "bolta"],
        ["bunch", "/bənʧ/", "bir bosh, bir dasta"],
        ["chore", "/ʧɔr/", "majburiy yumush, uy ishi"],
        ["decent", "/ˈdisənt/", "qoniqarli, tuzuk, durust"],
        ["disgrace", "/dɪsˈgreɪs/", "uyat, sharmandalik"],
        ["elbow", "/ˈɛlˌboʊ/", "tirsak"],
        ["grateful", "/ˈgreɪtfəl/", "minnatdor, tasakkur aytuvchi"],
        ["irritate", "/ˈɪrɪˌteɪt/", "g\'azablantirmoq, g\'ashiga tegmoq"],
        ["kid", "/kɪd/", "hazillashmoq"],
        ["loose", "/lus/", "bo\'sh, mahkamlanmagan"],
        ["offend", "/əˈfɛnd/", "xafa qilmoq, ranjitmoq"],
        ["overnight", "/ˈoʊvərˈnaɪt/", "tuni bilan, bir kechada"],
        ["persist", "/pərˈsɪst/", "davom ettirmoq, qat\'iy turmoq"],
        ["pine", "/paɪn/", "qarag\'ay"],
        ["scar", "/skɑr/", "chandiq"],
        ["sensation", "/sɛnˈseɪʃən/", "his, tuyg\'u"],
        ["sled", "/slɛd/", "chana"],
        ["tease", "/tiz/", "masxara qilmoq, ermak qilmoq"],
        ["valentine", "/ˈvælənˌtaɪn/", "mashuqa, sevgi maktubi"],
      ]),
      unit(4, [
        ["bloom", "/blum/", "gullamoq"],
        ["compact", "/ˈkɑmpækt/", "ixcham, kichik"],
        ["curl", "/kərl/", "zulf, gajak, buralma"],
        ["decay", "/dɪˈkeɪ/", "chirimoq, yemirilmoq"],
        ["dessert", "/dɪˈzərt/", "desert, shirinlik"],
        ["dip", "/dɪp/", "botirmoq, tirqitmoq"],
        ["distant", "/ˈdɪstənt/", "uzoq, olisdagi"],
        ["eclipse", "/ɪˈklɪps/", "tutilish (quyosh/oy)"],
        ["fairy", "/ˈfɛri/", "pari, elf"],
        ["grace", "/greɪs/", "nafosat, jozibali harakat"],
        ["leisure", "/ˈlɛʒər/", "bo\'sh vaqt"],
        ["mankind", "/ˈmænˈkaɪnd/", "insoniyat"],
        ["passion", "/ˈpæʃən/", "kuchli ehtiros, ishtiyoq"],
        ["pillow", "/ˈpɪloʊ/", "yostiq"],
        ["pulse", "/pəls/", "puls, tomir urishi"],
        ["refresh", "/rɪˈfrɛʃ/", "tetiklashtirmoq, rohatlantirmoq"],
        ["sneeze", "/sniz/", "aksirmoq, chuchkirmoq"],
        ["spice", "/spaɪs/", "ziravor"],
        ["whistle", "/ˈwɪsəl/", "hushtak chalmoq"],
        ["wool", "/wʊl/", "jun, yung"],
      ]),
      unit(5, [
        ["acquaint", "/əkˈweɪnt/", "tanishtirmoq"],
        ["cemetery", "/ˈsɛmɪˌtɛri/", "qabriston, mozor"],
        ["curse", "/kərs/", "qarg\'amoq, la\'natlamoq"],
        ["disguise", "/dɪsˈgaɪz/", "niqob, maska"],
        ["fancy", "/ˈfænsi/", "antiqa, dabdabali"],
        ["flashlight", "/ˈflæʃˌlaɪt/", "fonar, qo\'l fonusi"],
        ["hood", "/hʊd/", "kapyushon, bosh kiyim"],
        ["inhabitant", "/ˌɪnˈhæbɪtənt/", "istiqomat qiluvchi, fuqaro"],
        ["nourish", "/nərɪʃ/", "ovqatlantirmoq, oziqlantirmoq"],
        ["pirate", "/ˈpaɪrət/", "dengiz qaroqchisi"],
        ["publication", "/ˌpəblɪˈkeɪʃən/", "nashr, nashr qilingan asar"],
        ["riddle", "/ˈrɪdəl/", "topishmoq"],
        ["rot", "/rɑt/", "chirimoq, aynamoq"],
        ["scare", "/skɛr/", "qo\'rqitmoq"],
        ["shortly", "/ˈʃɔrtli/", "tez orada"],
        ["skeleton", "/ˈskɛlətən/", "skelet, suyaklar"],
        ["spoil", "/spɔɪl/", "achimoq, buzilmoq"],
        ["starve", "/stɑrv/", "och qolmoq, ochdan o\'lmoq"],
        ["thrill", "/θrɪl/", "hayajon, zavq"],
        ["wicked", "/ˈwɪkəd/", "yovuz, vahshiy"],
      ]),
      unit(6, [
        ["alert", "/əˈlərt/", "ogohlantirmoq"],
        ["broadcast", "/ˈbrɔdˌkæst/", "teleko\'rsatuv, radioeshittirish"],
        ["bulletin", "/ˈbʊlɪtən/", "qisqa yangiliklar, bulleten"],
        ["bump", "/bəmp/", "g\'urra, shish, turtki"],
        ["chop", "/ʧɑp/", "to\'g\'ramoq, chopmoq"],
        ["closet", "/ˈklɑzət/", "devoriy shkaf, kiyim javoni"],
        ["console", "/ˈkɑnsoʊl/", "taskin bermoq, yupatmoq"],
        ["district", "/ˈdɪstrɪkt/", "tuman, okrug"],
        ["drawer", "/drɔr/", "g\'aladon, tortma"],
        ["endure", "/ɪnˈdʊr/", "chidamoq, sabr qilmoq"],
        ["execute", "/ˈɛksəˌkjut/", "qatl etmoq, ijro etmoq"],
        ["grasp", "/græsp/", "ushlamoq, maxkam tutmoq"],
        ["rear", "/rɪr/", "orqa taraf"],
        ["senator", "/ˈsɛnətər/", "senator"],
        ["skull", "/skəl/", "bosh suyagi"],
        ["stir", "/stər/", "aralashtirmoq"],
        ["tap", "/tæp/", "asta urmoq, bosmoq"],
        ["tremendous", "/trɪˈmɛndəs/", "juda katta, ulkan"],
        ["underneath", "/ˌəndərˈniθ/", "tagida, ostida"],
        ["worm", "/wərm/", "chuvalchang"],
      ]),
      unit(7, [
        ["abandon", "/əˈbændən/", "tashlab ketmoq, tark etmoq"],
        ["ambitious", "/æmˈbɪʃəs/", "shuhratparast, intiluvchan"],
        ["bark", "/bɑrk/", "vovullamoq"],
        ["bay", "/beɪ/", "qo\'ltiq, ko\'rfaz"],
        ["brilliant", "/ˈbrɪljənt/", "juda aqlli, zukkog\'"],
        ["chin", "/ʧɪn/", "jag'"],
        ["complaint", "/kəmˈpleɪnt/", "shikoyat, arz"],
        ["deaf", "/dɛf/", "kar, qulog\'i og\'ir"],
        ["enthusiastic", "/ɪnˌθuziˈæstɪk/", "zavqlangan, g\'ayratli"],
        ["expedition", "/ˌɛkspəˈdɪʃən/", "ekspeditsiya, safar"],
        ["horizon", "/hərˈaɪzən/", "gorizont, ufq"],
        ["loyal", "/lɔɪəl/", "sodiq, vafodor"],
        ["mayor", "/meɪər/", "hokim, shahar rahbari"],
        ["mutual", "/mˈjuʧuəl/", "o\'zaro, ikki taraflama"],
        ["overweight", "/ˌoʊvərˈweɪt/", "juda semiz, ortiqcha vaznli"],
        ["refuge", "/ˈrɛfjuʤ/", "boshpana, xavfsiz joy"],
        ["restore", "/rɪˈstɔr/", "qayta tiklamoq, joyiga qo\'ymoq"],
        ["rub", "/rəb/", "ishqalamoq, ishqamoq"],
        ["senses", "/ˈsɛnsɪz/", "sezgi a\'zolari, tuyg\'ular"],
        ["veterinarian", "/ˌvɛtərəˈnɛriən/", "veterinar, hayvonlar shifokori"],
      ]),
      unit(8, [
        ["anniversary", "/ˌænəˈvərsəri/", "yillik, yubiley"],
        ["arithmetic", "/ˌɛrɪθˈmɛtɪk/", "arifmetika"],
        ["ashamed", "/əˈʃeɪmd/", "uyalgan, xijolatli"],
        ["burst", "/bərst/", "portlamoq, yorilib ketmoq"],
        ["carpenter", "/ˈkɑrpəntər/", "duradgor"],
        ["coal", "/koʊl/", "ko\'mir"],
        ["couch", "/kaʊʧ/", "divan, kushetka"],
        ["drip", "/drɪp/", "tommoq, tomchilamoq"],
        ["elegant", "/ˈɛləgənt/", "xushbichim, ko\'rkam"],
        ["fabric", "/ˈfæbrɪk/", "mato, gazlama"],
        ["highlands", "/ˈhaɪləndz/", "yassi tog\'lik, tog\'li hudud"],
        ["ivory", "/ˈaɪvəri/", "fil suyagi"],
        ["mill", "/mɪl/", "tegirmon"],
        ["needle", "/ˈnidəl/", "igna, nina"],
        ["polish", "/ˈpɑlɪʃ/", "sayqallamoq, pardoz bermoq"],
        ["sew", "/soʊ/", "tikmoq"],
        ["shed", "/ʃɛd/", "omborxona, bostirma"],
        ["thread", "/θrɛd/", "ip"],
        ["trim", "/trɪm/", "ozroq kesmoq, tekislamoq"],
        ["upwards", "/ˈəpwərdz/", "yuqoriga, tepaga"],
      ]),
      unit(9, [
        ["ail", "/eɪl/", "bezovta qilmoq, og\'ritmoq"],
        ["ally", "/ˈælaɪ/", "ittifoqchi"],
        ["boast", "/boʊst/", "maqtanmoq"],
        ["bounce", "/baʊns/", "sakratmoq, irg\'itmoq"],
        ["bully", "/ˈbʊli/", "bezori, zoravon"],
        ["carbohydrate", "/ˌkɑrboʊˈhaɪˌdreɪt/", "uglevod"],
        ["crawl", "/krɔl/", "emaklamoq"],
        ["defeat", "/dɪˈfit/", "mag\'lub etmoq"],
        ["dial", "/daɪəl/", "tsiferblat, soat yuzi"],
        ["dominant", "/ˈdɑmənənt/", "hukmron, ustun"],
        ["mercy", "/ˈmərsi/", "rahm-shavqat, shafqat"],
        ["nod", "/nɑd/", "bosh qimirlatmoq"],
        ["opponent", "/əˈpoʊnənt/", "raqib, qarshi taraf"],
        ["quarrel", "/kˈwɔrəl/", "janjallashmoq, bahslashmoq"],
        ["rival", "/ˈraɪvəl/", "raqib, musobaqadosh"],
        ["sore", "/sɔr/", "riqli"],
        ["sting", "/stɪŋ/", "chaqmoq, sanchmoq"],
        ["strain", "/streɪn/", "zo\'r bermoq, qattiq urinmoq"],
        ["torture", "/ˈtɔrʧər/", "azob, qiynoq"],
        ["wrestle", "/ˈrɛsəl/", "kurashmoq, bel olishmoq"],
      ]),
      unit(10, [
        ["absence", "/ˈæbsəns/", "yo\'qlik, mavjud emaslik"],
        ["aloud", "/əˈlaʊd/", "ovoz chiqarib, baralla"],
        ["bald", "/bɔld/", "kal, sochsiz"],
        ["blanket", "/ˈblæŋkɪt/", "adyol, ko\'rpa"],
        ["creep", "/krip/", "asta o\'rmalamoq, sekin yurmoq"],
        ["divorce", "/dɪˈvɔrs/", "nikohdan ajralish"],
        ["imitate", "/ˈɪməˌteɪt/", "taqlid qilmoq"],
        ["infant", "/ˈɪnfənt/", "go\'dak, chaqaloq"],
        ["kidnap", "/ˈkɪdˌnæp/", "odam o\'g\'irlamoq"],
        ["nap", "/næp/", "mizg\'ib olish, qisqa uyqu"],
        ["nowhere", "/ˈnoʊˌwɛr/", "hech qayerda"],
        ["pat", "/pæt/", "sekin urib qo\'ymoq"],
        ["relief", "/rɪˈlif/", "yengillik, tasalli"],
        ["reproduce", "/ˌriprəˈdus/", "nusxasini yaratmoq, ko\'paymoq"],
        ["rhyme", "/raɪm/", "qofiya"],
        ["suck", "/sək/", "so\'rmoq, emmoq"],
        ["urgent", "/ˈərʤənt/", "shoshilinch, muhim"],
        ["vanish", "/ˈvænɪʃ/", "g\'oyib bo\'lmoq, yo\'qolmoq"],
        ["wagon", "/ˈwægən/", "arava"],
        ["wrinkle", "/ˈrɪŋkəl/", "ajin"],
      ]),
      unit(11, [
        ["abnormal", "/æbˈnɔrməl/", "g\'ayrioddiy, me\'yordan tashqari"],
        ["bamboo", "/bæmˈbu/", "bambuk"],
        ["blossom", "/ˈblɑsəm/", "daraxt gul-gunchasi"],
        ["compass", "/ˈkəmpəs/", "kompas"],
        ["dialect", "/ˈdaɪəˌlɛkt/", "sheva, dialekt"],
        ["dishonest", "/dɪˈsɑnəst/", "vijdonsiz, noinsof"],
        ["dwarf", "/dwɔrf/", "gnom, pakana odam"],
        ["ecosystem", "/ˈikoʊˌsɪstəm/", "ekotizim"],
        ["fatal", "/ˈfeɪtəl/", "halokatli, o\'limga olib keladigan"],
        ["impatient", "/ˌɪmˈpeɪʃənt/", "sabrsiz, toqatsiz"],
        ["leaf", "/lif/", "barg"],
        ["manuscript", "/ˈmænjəˌskrɪpt/", "qo\'lyozma"],
        ["marsh", "/mɑrʃ/", "botqoqlik"],
        ["patience", "/ˈpeɪʃəns/", "sabr, toqat"],
        ["perfume", "/pərfˈjum/", "atir, duxi"],
        ["pond", "/pɑnd/", "hovuz, ko\'lmak"],
        ["proverb", "/ˈprɑvərb/", "maqol"],
        ["pursuit", "/pərˈsut/", "quvish, ta\'qib qilish"],
        ["recite", "/rəˈsaɪt/", "yoddan aytib bermoq"],
        ["wilderness", "/ˈwɪldərnəs/", "chakalakzor, kimsasiz joy"],
      ]),
      unit(12, [
        ["anticipate", "/ænˈtɪsəˌpeɪt/", "oldindan his qilmoq, kutmoq"],
        ["barrel", "/ˈbɛrəl/", "bochka"],
        ["beam", "/bim/", "to\'sin, nur"],
        ["casual", "/ˈkæʒəwəl/", "norasmiy, oddiy"],
        ["caution", "/ˈkɔʃən/", "ehtiyotkorlik"],
        ["contrary", "/ˈkɑntrɛri/", "zid, aksincha"],
        ["deliberate", "/dɪˈlɪbərˌeɪt/", "qasddan qilingan, o\'ylab qilingan"],
        ["dissolve", "/dɪˈzɑlv/", "eritmoq, erimoq"],
        ["explode", "/ɪkˈsploʊd/", "portlamoq"],
        ["fasten", "/ˈfæsən/", "bog\'lamoq, mahkamlamoq"],
        ["germ", "/ʤərm/", "mikrob, bakteriya"],
        ["kit", "/kɪt/", "zarur buyumlar toplami"],
        ["puff", "/pəf/", "tutun parchasi, puflash"],
        ["rag", "/ræg/", "latta, eski mato"],
        ["scatter", "/ˈskætər/", "sochib yubormoq, to\'zitmoq"],
        ["scent", "/sɛnt/", "hid, xushbo\'ylik"],
        ["steel", "/stil/", "po\'lat"],
        ["swift", "/swɪft/", "tezkor, jadal"],
        ["toss", "/tɔs/", "irg\'itmoq, otmoq"],
        ["triumph", "/traɪəmf/", "zafar, g\'alaba"],
      ]),
      unit(13, [
        ["aboard", "/əˈbɔrd/", "bortda (kema/samolyot)"],
        ["bitter", "/ˈbɪtər/", "achchiqlangan, g\'azablangan"],
        ["bullet", "/ˈbʊlət/", "o\'q"],
        ["devil", "/ˈdɛvəl/", "shayton, iblis"],
        ["drift", "/drɪft/", "oqib ketmoq, suzib yurmoq"],
        ["enforce", "/ɛnˈfɔrs/", "tatbiq etmoq, majbur qilmoq"],
        ["fountain", "/ˈfaʊntən/", "favvora, fontan"],
        ["harbor", "/ˈhɑrbər/", "gavan, kema to\'xtash joyi"],
        ["inhabit", "/ˌɪnˈhæbət/", "yashamoq, istiqomat qilmoq"],
        ["march", "/mɑrʧ/", "saf tortib yurmoq"],
        ["millionaire", "/ˌmɪljəˈnɛr/", "millioner"],
        ["port", "/pɔrt/", "port, bandargoh"],
        ["sheriff", "/ˈʃɛrɪf/", "sherif, politsiya boshlig\'i"],
        ["startle", "/ˈstɑrtəl/", "qo\'rqitib yubormoq"],
        ["sweat", "/swɛt/", "terlamoq"],
        ["trigger", "/ˈtrɪgər/", "miltiq tepkisi"],
        ["unify", "/ˈjunəˌfaɪ/", "birlashtirmoq"],
        ["vessel", "/ˈvɛsəl/", "kema, idish"],
        ["voyage", "/vɔɪəʤ/", "dengiz safari, sayohat"],
        ["worship", "/ˈwərʃɪp/", "toat-ibodat qilmoq, sig\'inmoq"],
      ]),
      unit(14, [
        ["apprentice", "/əˈprɛntɪs/", "shogird"],
        ["assure", "/əˈʃʊr/", "ishontirmoq, kafolat bermoq"],
        ["bandage", "/ˈbændɪʤ/", "bint, bog\'lovchi mato"],
        ["bleed", "/blid/", "qonamoq"],
        ["bond", "/bɑnd/", "do\'stlashmoq, rishta bog\'lamoq"],
        ["chef", "/ʃɛf/", "bosh oshpaz"],
        ["crown", "/kraʊn/", "toj"],
        ["departure", "/dɪˈpɑrʧər/", "jo\'nab ketish"],
        ["diligent", "/ˈdɪlɪʤənt/", "tirishqoq, quntli"],
        ["emperor", "/ˈɛmpərər/", "imperator, hukmdor"],
        ["fiber", "/ˈfaɪbər/", "tola, ipakiy tola"],
        ["horrible", "/ˈhɔrəbəl/", "dahshatli, judayam yomon"],
        ["impolite", "/ˌɪmpəˈlaɪt/", "odobsiz, qo\'pol"],
        ["kneel", "/nil/", "cho\'kkalamoq, tizzalamoq"],
        ["luxury", "/ˈləgʒəri/", "dabdaba, dabdabali narsa"],
        ["massive", "/ˈmæsɪv/", "juda katta, ulkan"],
        ["panic", "/ˈpænɪk/", "sarosimaga tushmoq"],
        ["priority", "/praɪˈɔrəti/", "ustuvor vazifa, birinchi darajali ish"],
        ["robe", "/roʊb/", "mantiya, xalat"],
        ["scold", "/skoʊld/", "so\'kmoq, koyimoq"],
      ]),
      unit(15, [
        ["affair", "/əˈfɛr/", "marosim, ish, voqea"],
        ["assembly", "/əˈsɛmbli/", "assambleya, yig\'ilish"],
        ["bless", "/blɛs/", "duo qilmoq, baraka tilamoq"],
        ["cereal", "/ˈsɪriəl/", "boshoqli don, nonushta doni"],
        ["cheerful", "/ˈʧɪrfəl/", "quvnoq, xursand"],
        ["diameter", "/daɪˈæmətər/", "diametr"],
        ["exploit", "/ˌɛkˈsplɔɪt/", "foydalanmoq, ekspluatatsiya qilmoq"],
        ["famine", "/ˈfæmən/", "ocharchilik"],
        ["harvest", "/ˈhɑrvəst/", "hosil, o\'rim-yig\'im"],
        ["merry", "/ˈmɛri/", "shod, xursand"],
        ["nut", "/nət/", "yong\'oq"],
        ["pardon", "/ˈpɑrdən/", "kechirmoq (kechirasiz)"],
        ["pharaoh", "/ˈfɛroʊ/", "fir\'avn"],
        ["ripe", "/raɪp/", "pishgan, yetilgan"],
        ["roast", "/roʊst/", "qovurmoq, kabob qilmoq"],
        ["routine", "/ruˈtin/", "odatiy tartib, kun tartibi"],
        ["scheme", "/skim/", "reja, loyiha"],
        ["slim", "/slɪm/", "ingichka, kelbatli"],
        ["stove", "/stoʊv/", "pech, oshxona плитаsi"],
        ["theft", "/θɛft/", "o\'g\'irlik"],
      ]),
      unit(16, [
        ["adolescent", "/ˌædəˈlɛsənt/", "o\'spirin, o\'smir"],
        ["aptitude", "/ˈæptəˌtud/", "tug\'ma iqtidor, qobiliyat"],
        ["compliment", "/ˈkɑmpləmɛnt/", "maqtab qo\'ymoq, iltifot"],
        ["hinder", "/ˈhɪndər/", "to\'sqinlik qilmoq"],
        ["journalism", "/ˈʤərnəˌlɪzəm/", "jurnalistika"],
        ["jury", "/ˈʤʊri/", "sud maslahatchilari hay\'ati"],
        ["justice", "/ˈʤəstɪs/", "adolat"],
        ["liberty", "/ˈlɪbərˌti/", "ozodlik, erkinlik"],
        ["literary", "/ˈlɪtərˌɛri/", "adabiyotga oid, badiiy"],
        ["pharmacy", "/ˈfɑrməsi/", "dorixona"],
        ["pill", "/pɪl/", "hapdori, tabletka"],
        ["presume", "/prɪˈzum/", "deb o\'ylamoq, faraz qilmoq"],
        ["privacy", "/ˈpraɪvəsi/", "xolilik, shaxsiy daxlsizlik"],
        ["punishment", "/ˈpənɪʃmənt/", "jazo"],
        ["sensible", "/ˈsɛnsəbəl/", "aqlli, mulohazali"],
        ["slice", "/slaɪs/", "burda, bo\'lak"],
        ["sorrow", "/ˈsɑroʊ/", "qayg\'u, g\'am-g\'ussa"],
        ["straw", "/strɔ/", "naycha (ichimlik uchun)"],
        ["swell", "/swɛl/", "shishmoq, kattalashmoq"],
        ["tidy", "/ˈtaɪdi/", "orasta, tartibli"],
      ]),
      unit(17, [
        ["affection", "/əˈfɛkʃən/", "mehr, samimiy tuyg\'u"],
        ["agency", "/ˈeɪʤənsi/", "agentlik, korxona"],
        ["ash", "/æʃ/", "kul"],
        ["confine", "/kənˈfaɪn/", "cheklamoq, bir joyda tutmoq"],
        ["dismiss", "/dɪsˈmɪs/", "inkor qilmoq, rad etmoq"],
        ["erupt", "/ˈirəpt/", "otilib chiqmoq (vulqon)"],
        ["fate", "/feɪt/", "taqdir, qismat"],
        ["lava", "/ˈlɑvə/", "lava, erigan qoya"],
        ["miserable", "/ˈmɪzərəbəl/", "baxtsiz, juda g\'amgin"],
        ["navigate", "/ˈnævəˌgeɪt/", "yo\'nalishni boshqarmoq"],
        ["originate", "/ərˈɪʤəˌneɪt/", "boshlanmoq, kelib chiqmoq"],
        ["remainder", "/rɪˈmeɪndər/", "qoldiq, qolgan qismi"],
        ["retrieve", "/rɪˈtriv/", "qaytarib olmoq, topib kelmoq"],
        ["shallow", "/ˈʃæloʊ/", "tekiz, chuqur bo\'lmagan"],
        ["slope", "/sloʊp/", "qiyalik, yonbag\'ir"],
        ["span", "/spæn/", "davom etmoq (vaqt oralig\'ida)"],
        ["superstition", "/ˌsupərˈstɪʃən/", "xurofot, irim"],
        ["sympathy", "/ˈsɪmpəθi/", "hamdardlik, achiniash"],
        ["vibrate", "/ˈvaɪbreɪt/", "titramoq, tebranmoq"],
        ["wander", "/ˈwɑndər/", "darbadar yurmoq, kezmoq"],
      ]),
      unit(18, [
        ["armor", "/ˈɑrmər/", "sovut, temir kiyim"],
        ["blaze", "/bleɪz/", "gurillab yonmoq"],
        ["boom", "/bum/", "guldiramoq, gulduragan ovoz chiqarmoq"],
        ["cliff", "/klɪf/", "tik qoya, tik qirg\'oq"],
        ["flame", "/fleɪm/", "olov tillari, alanga"],
        ["independence", "/ˌɪndɪˈpɛndəns/", "mustaqillik, erkinlik"],
        ["invasion", "/ˌɪnˈveɪʒən/", "bostirib kirish, hujum"],
        ["knight", "/naɪt/", "ritsar, ritsar jangchisi"],
        ["lightning", "/ˈlaɪtnɪŋ/", "chaqmoq"],
        ["rebel", "/ˈrɛbəl/", "isyonchi, isyonkor"],
        ["retreat", "/riˈtrit/", "chekinmoq, qochmoq"],
        ["revolution", "/ˌrɛvəˈluʃən/", "inqilob, to\'ntarish"],
        ["spear", "/spɪr/", "nayza"],
        ["steep", "/stip/", "tik, tik qiyalikdagi"],
        ["summit", "/ˈsəmɪt/", "cho\'qqi, eng baland nuqta"],
        ["thunder", "/ˈθəndər/", "guldurash, momaqaldiroq"],
        ["troops", "/trups/", "qo\'shinlar, askarlar"],
        ["warrior", "/ˈwɔrjər/", "jangchi, bahodir"],
        ["withdraw", "/wɪθˈdrɔ/", "ortga chekinmoq"],
        ["yield", "/jild/", "taslim bo\'lmoq, bo\'shatib bermoq"],
      ]),
      unit(19, [
        ["bench", "/bɛnʧ/", "o\'rindiq, skameyka"],
        ["confront", "/kənˈfrənt/", "yuzlashmoq, ro\'para kelmoq"],
        ["daisy", "/ˈdeɪzi/", "moychechak"],
        ["dispute", "/dɪˈspjut/", "tortishuv, bahs"],
        ["horror", "/ˈhɔrər/", "dahshat, qo\'rquv"],
        ["incident", "/ˈɪnsədənt/", "ko\'ngilsiz hodisa, voqea"],
        ["mist", "/mɪst/", "mayda tuman, bug\'"],
        ["object", "/ˈɑbʤɛkt/", "narsa, buyum"],
        ["orphan", "/ˈɔrfən/", "yetim bola"],
        ["plot", "/plɑt/", "fitna uyushtirmoq, reja tuzmoq"],
        ["pregnant", "/ˈprɛgnənt/", "homilador"],
        ["rage", "/reɪʤ/", "g\'azab, jahl"],
        ["revenge", "/riˈvɛnʤ/", "o\'ch, qasos"],
        ["shame", "/ʃeɪm/", "uyat, sharmandalik"],
        ["sigh", "/saɪ/", "xo\'rsinmoq"],
        ["sneak", "/snik/", "bildirmay sekin harakatlanmoq"],
        ["spare", "/spɛr/", "ajratib ber olmoq, ortiqcha"],
        ["stem", "/stɛm/", "poya (o\'simlik poyasi)"],
        ["supper", "/ˈsəpər/", "kechki ovqat"],
        ["tender", "/ˈtɛndər/", "yumshoq, nozik"],
      ]),
      unit(20, [
        ["beneath", "/bɪˈniθ/", "ostida, tagida"],
        ["cub", "/kəb/", "hayvon bolasi (ayiq/sher)"],
        ["dawn", "/dɔn/", "tong otishi, sahar"],
        ["dissatisfied", "/dɪˈsætəsˌfaɪd/", "qoniqmagan, norozi"],
        ["ease", "/iz/", "osonlik, yengillik"],
        ["evident", "/ˈɛvədənt/", "aniq, ravshan"],
        ["hail", "/heɪl/", "dovul, do\'l"],
        ["howl", "/haʊl/", "uvillamoq"],
        ["leap", "/lip/", "uzoqqa sakramoq"],
        ["magnificent", "/mægˈnɪfɪsənt/", "muhtasham, ko\'rkam"],
        ["necessity", "/nəˈsɛsɪti/", "zaruriyat, ehtiyoj"],
        ["outcome", "/ˈaʊtˌkəm/", "natija, yakun"],
        ["pile", "/paɪl/", "g\'aram, uyum"],
        ["profound", "/proʊˈfaʊnd/", "chuqur, mazmunli"],
        ["seize", "/siz/", "ushlab olmoq, mahkam ushlamoq"],
        ["squeeze", "/skwiz/", "qismaloqlamoq, siqmoq"],
        ["supreme", "/səˈprim/", "oliy, eng yuqori"],
        ["terrific", "/tərˈɪfɪk/", "juda zo\'r, ajoyib"],
        ["trait", "/treɪt/", "fe\'l-atvor jihati, xususiyat"],
        ["vital", "/ˈvaɪtəl/", "hayotiy muhim"],
      ]),
      unit(21, [
        ["accustomed", "/əˈkəstəmd/", "o\'rgangan, odatlantirilgan"],
        ["affirm", "/əˈfərm/", "tasdiqlamoq"],
        ["astonished", "/əˈstɑnɪʃt/", "juda hayratlangan"],
        ["bang", "/bæŋ/", "urib ovoz chiqarmoq"],
        ["clan", "/klæn/", "-aymoq"],
        ["dim", "/dɪm/", "xira, nim qorong\'u"],
        ["emphasis", "/ˈɛmfəsɪs/", "alohida e\'tibor, urg\'u"],
        ["fable", "/ˈfeɪbəl/", "masal, masaliy hikoya"],
        ["feast", "/fist/", "ziyofat, katta bazm"],
        ["glow", "/gloʊ/", "mayin nur sochmoq"],
        ["hollow", "/ˈhɑloʊ/", "g\'ovak, ichi bo\'sh"],
        ["instinct", "/ˈɪnstɪŋkt/", "instinkt, ichki tuyg\'u"],
        ["joint", "/ʤɔɪnt/", "bo\'g\'im"],
        ["leak", "/lik/", "sizib chiqmoq, teshikdan oqmoq"],
        ["physician", "/fəˈzɪʃən/", "shifokor, vrach"],
        ["sacrifice", "/ˈsækrəˌfaɪs/", "qurbon qilmoq, voz kechmoq"],
        ["stiff", "/stɪf/", "qotib qolgan, egilmaydigan"],
        ["stroke", "/stroʊk/", "silamoq, silab qo\'ymoq"],
        ["tragic", "/ˈtræʤɪk/", "fojiali, g\'amgin"],
        ["tune", "/tun/", "kuy, qo\'shiq"],
      ]),
      unit(22, [
        ["accommodate", "/əˈkɑməˌdeɪt/", "sig\'dirmoq, joy bermoq"],
        ["circus", "/ˈsərkəs/", "tsirk"],
        ["coincide", "/ˌkoʊɪnˈsaɪd/", "bir vaqtga to\'g\'ri kelmoq"],
        ["commission", "/kəˈmɪʃən/", "topshiriq bermoq (haq evaziga)"],
        ["dose", "/doʊs/", "doza, dori miqdori"],
        ["dye", "/daɪ/", "bo\'yamoq"],
        ["extent", "/ɪkˈstɛnt/", "daraja, ko\'lam"],
        ["gender", "/ˈʤɛndər/", "jins (erkak/ayol)"],
        ["headline", "/ˈhɛˌdlaɪn/", "sarlavha (gazetada)"],
        ["informal", "/ˌɪnˈfɔrməl/", "norasmiy"],
        ["inquire", "/ˌɪnkˈwaɪr/", "surishtirmoq, so\'ramoq"],
        ["messenger", "/ˈmɛsɪnʤər/", "xabarchi, elchi"],
        ["peer", "/pɪr/", "tikilib qaramoq"],
        ["portrait", "/ˈpɔrtrət/", "portret, rasm"],
        ["pose", "/poʊz/", "posa bermoq, qimirlamay turmoq"],
        ["ranch", "/rænʧ/", "katta ferma, rancho"],
        ["steer", "/stɪr/", "boshqarmoq (rulni)"],
        ["stripe", "/straɪp/", "yo\'l-yo\'l chiziq"],
        ["tame", "/teɪm/", "qo\'lga o\'rgatilgan, xonakilashtirilgan"],
        ["tempt", "/tɛmpt/", "qiziqtirmoq, yo\'ldan urmoq"],
      ]),
      unit(23, [
        ["Aborigine", "/ˌæbərˈɪʤəni/", "Avstraliya tub joy aholisi"],
        ["ban", "/bæn/", "taqiqlamoq"],
        ["cautious", "/ˈkɔʃəs/", "ehtiyotkor, hushyor"],
        ["confess", "/kənˈfɛs/", "iqror bo\'lmoq, tan olmoq"],
        ["cottage", "/ˈkɑtɪʤ/", "kottej, qishloq uyi"],
        ["daytime", "/ˈdeɪˌtaɪm/", "kunduzi, kun vaqti"],
        ["desperate", "/ˈdɛspərɪt/", "chora qidirayotgan, umidsiz"],
        ["fade", "/feɪd/", "so\'nmoq, rangi o\'chmoq"],
        ["fierce", "/fɪrs/", "g\'azabkor, vahshiy"],
        ["gamble", "/ˈgæmbəl/", "qimor o\'ynamoq"],
        ["lawn", "/lɔn/", "maysazor"],
        ["mow", "/moʊ/", "o\'rmoq (maysani)"],
        ["outlaw", "/ˈaʊˌtlɔ/", "qonundan tashqari jinoyatchi"],
        ["prospect", "/ˈprɑspɛkt/", "istiqbol, ehtimol"],
        ["purse", "/pərs/", "ayollar hamyoni"],
        ["rod", "/rɑd/", "qarmoq dasta, tayoqcha"],
        ["seldom", "/ˈsɛldəm/", "kamdan-kam, ba\'zan"],
        ["shave", "/ʃeɪv/", "soqol olmoq"],
        ["terrified", "/ˈtɛrəˌfaɪd/", "juda qo\'rqqan"],
        ["wizard", "/ˈwɪzərd/", "sehrgar, jodugar"],
      ]),
      unit(24, [
        ["baggage", "/ˈbægɪʤ/", "yuk, bagaj"],
        ["bulb", "/bəlb/", "lampochka"],
        ["bundle", "/ˈbəndəl/", "bog\'lam, boylam"],
        ["cattle", "/ˈkætəl/", "qoramol"],
        ["flee", "/fli/", "qochib ketmoq"],
        ["graze", "/greɪz/", "o\'tlamoq (maysada)"],
        ["greed", "/grid/", "ochko\'zlik"],
        ["herd", "/hərd/", "poda, gala"],
        ["initiate", "/ˌɪˈnɪʃiˌeɪt/", "boshlamoq, yo\'lga qo\'qo\'ymoq"],
        ["lane", "/leɪn/", "tor yo\'lak, tor ko\'cha"],
        ["luggage", "/ˈləgɪʤ/", "yuk, chemodanlar"],
        ["nerve", "/nərv/", "dovyuraklik, dadillik"],
        ["optimist", "/ˈɑptɪmɪst/", "optomist, xushbin kishi"],
        ["parade", "/pəreɪd/", "parad, bayramiy yurish"],
        ["pave", "/peɪv/", "yo\'lga tosh/asfalt yotqizmoq"],
        ["phantom", "/ˈfænəm/", "arvoh, sharpa"],
        ["portable", "/ˈpɔrtəbəl/", "ixcham, ko\'chma"],
        ["poster", "/ˈpoʊstər/", "plakat, e\'lon"],
        ["scratch", "/skræʧ/", "tirnamoq, tirnash"],
        ["symphony", "/ˈsɪmfəni/", "simfoniya"],
        ["widow", "/ˈwɪdoʊ/", "beva ayol"],
      ]),
      unit(25, [
        ["circulate", "/ˈsərkjəˌleɪt/", "tarqalmoq, aylantirmoq"],
        ["consequent", "/ˈkɑnsəkwənt/", "oqibatda yuz beradigan"],
        ["derive", "/dəraɪv/", "kelib chiqmoq, olmoq"],
        ["drown", "/draʊn/", "suvga cho\'kib o\'lmoq"],
        ["dynasty", "/ˈdaɪnəsti/", "sulola, dinastiya"],
        ["fraction", "/ˈfrækʃən/", "ozgina qism, kasr"],
        ["frost", "/frɔst/", "qirov, ayoz"],
        ["illusion", "/ˌɪˈluʒən/", "xayol, illyuziya"],
        ["invade", "/ˌɪnˈveɪd/", "bostirib kirmoq"],
        ["lieutenant", "/luˈtɛnənt/", "leytenant"],
        ["marine", "/mərˈin/", "dengizga oid"],
        ["merit", "/ˈmɛrət/", "xizmat, yaxshi fazilat"],
        ["navy", "/ˈneɪvi/", "harbiy-dengiz floti"],
        ["polar", "/ˈpoʊlər/", "qutbiy, muzlik"],
        ["ray", "/reɪ/", "nur, quyosh nuri"],
        ["resign", "/rɪˈzaɪn/", "iste\'foga chiqmoq, ishni topshirmoq"],
        ["suicide", "/ˈsuɪˌsaɪd/", "o\'z joniga qasd qilish"],
        ["tremble", "/ˈtrɛmbəl/", "titramoq"],
        ["underlying", "/ˌəndərˈlaɪɪŋ/", "yashirin, asosiy sabab bo\'lgan"],
        ["via", "/ˈviə/", "orqali, yordamida"],
      ]),
      unit(26, [
        ["alter", "/ˈɔltər/", "o\'zgartirmoq"],
        ["aside", "/əˈsaɪd/", "bir chekkada, yon tomonda"],
        ["autumn", "/ˈɔtəm/", "kuz"],
        ["blend", "/blɛnd/", "aralashtirmoq"],
        ["collapse", "/kəˈlæps/", "qulab tushmoq, yiqilmoq"],
        ["crush", "/krəʃ/", "maydalamoq, ezmoq"],
        ["curve", "/kərv/", "egilmoq, burilmoq"],
        ["disgusting", "/dɪsˈgəstɪŋ/", "juda yoqimsiz, jirkanch"],
        ["drain", "/dreɪn/", "oqava quvur, drenaj"],
        ["embrace", "/ɪmˈbreɪs/", "quchoqlamoq"],
        ["envy", "/ˈɛnvi/", "hasad qilmoq, havas qilmoq"],
        ["fireworks", "/ˈfaɪrˌwərks/", "mushakbozlik"],
        ["flour", "/flaʊər/", "un"],
        ["fuse", "/fjuz/", "mushak ipi, pitil"],
        ["ginger", "/ˈʤɪnʤər/", "zanjabil"],
        ["jealous", "/ˈʤɛləs/", "rashing keladigan, hasadgo\'y"],
        ["paste", "/peɪst/", "pasta, quyuq qorishma"],
        ["receipt", "/rɪˈsit/", "chekd, kvitansiya"],
        ["wipe", "/waɪp/", "artib tozalamoq"],
        ["wire", "/waɪər/", "sim, sim ip"],
      ]),
      unit(27, [
        ["acknowledge", "/ækˈnɑlɪʤ/", "tan olmoq, e\'tirof etmoq"],
        ["ambassador", "/æmˈbæsədər/", "elchi, diplomat"],
        ["blonde", "/blɑnd/", "sariq sochli ayol"],
        ["conquer", "/ˈkɑŋkər/", "fath etmoq, bosib olmoq"],
        ["drag", "/dræg/", "suyrab yurmoq, tortmoq"],
        ["exaggerate", "/ɪgˈzæʤərˌeɪt/", "bo\'rttirib ko\'rsatmoq"],
        ["heritage", "/ˈhɛrɪtɪʤ/", "meros, madaniy meros"],
        ["insult", "/ˌɪnˈsəlt/", "haqorat qilmoq"],
        ["meanwhile", "/ˈminˌwaɪl/", "shu bilan bir vaqtda"],
        ["necklace", "/ˈnɛkləs/", "marjon, munchoq"],
        ["noble", "/ˈnoʊbəl/", "aslzoda, oliyjanob kishi"],
        ["precious", "/ˈprɛʃəs/", "qimmatbaho, qadrli"],
        ["prejudice", "/ˈprɛʤədɪs/", "asossiz salbiy fikr, xurofot"],
        ["rumor", "/ˈrumər/", "mish-mish, xabar"],
        ["sin", "/sɪn/", "gunoh"],
        ["spectacle", "/ˈspɛktəkəl/", "ajoyib tomosha, manzara"],
        ["stack", "/stæk/", "taxlam, g\'aram"],
        ["suspicious", "/səˈspɪʃəs/", "gudmand, shubhalanuvchi"],
        ["tin", "/tɪn/", "mushuk, tunuka"],
        ["vase", "/vɑz/", "vaza, guldon"],
      ]),
      unit(28, [
        ["ache", "/eɪk/", "og\'rimoq"],
        ["arctic", "/ˈɑrtɪk/", "shimoliy qutbga oid, sovuq"],
        ["canal", "/kəˈnæl/", "kanal, suv yo\'li"],
        ["chemist", "/ˈkɛmɪst/", "kimyogar olim"],
        ["chill", "/ʧɪl/", "sovuqlik, izg\'irin"],
        ["congress", "/ˈkɑŋgrəs/", "kongress, parlament"],
        ["dairy", "/ˈdɛri/", "sut mahsulotlari"],
        ["descend", "/dɪˈsɛnd/", "pastga tushmoq"],
        ["grocer", "/ˈgroʊsər/", "baqqol, oziq-ovqat sotuvchisi"],
        ["hesitate", "/ˈhɛzəˌteɪt/", "ikkilanmoq, kuttirmoq"],
        ["institution", "/ˌɪnstɪˈtuʃən/", "muassasa, tashkilot"],
        ["jog", "/ʤɑg/", "sekin yugurmoq"],
        ["merchant", "/ˈmərʧənt/", "savdogar"],
        ["poke", "/poʊk/", "turtmoq, barmoq bilan turtmoq"],
        ["postpone", "/poʊstˈpoʊn/", "kechiktirmoq"],
        ["splash", "/splæʃ/", "suv sachratmoq"],
        ["stubborn", "/ˈstəbərn/", "qaysar, o\'jar"],
        ["suburb", "/ˈsəbərb/", "shahar atrofi"],
        ["tide", "/taɪd/", "dengiz ko\'tarilishi/qaytishi"],
        ["tragedy", "/ˈtræʤədi/", "fojia, tragik voqea"],
      ]),
      unit(29, [
        ["bomb", "/bɔm/", "bomba"],
        ["certificate", "/sərˈtɪfɪkət/", "guvohnoma, sertifikat"],
        ["circumstance", "/ˈsərkəmˌstæns/", "holat, vaziyat"],
        ["coffin", "/ˈkɔfɪn/", "tobut"],
        ["cope", "/koʊp/", "eplamoq, uddalamoq"],
        ["criticism", "/ˈkrɪtɪˌsɪzəm/", "tanqid"],
        ["devastate", "/ˈdɛvəˌsteɪt/", "butkul vayron qilmoq"],
        ["frown", "/fraʊn/", "qoshini chimirmoq"],
        ["gaze", "/geɪz/", "tikilib qaramoq"],
        ["glance", "/glæns/", "ko\'z yugurtirmoq, qarash"],
        ["grief", "/grif/", "chuqur g\'am, qayg\'u"],
        ["groom", "/grum/", "kuyov, kuyov jo\'ra"],
        ["license", "/ˈlaɪsəns/", "litsenziya, guvohnoma"],
        ["microscope", "/ˈmaɪkrəˌskoʊp/", "mikroskop"],
        ["nuclear", "/ˈnukliər/", "yadroviy"],
        ["portray", "/pɔrˈtreɪ/", "tasvirlamoq"],
        ["rotate", "/ˈroʊˌteɪt/", "aylantirmoq"],
        ["souvenir", "/ˌsuvəˈnɪr/", "esdalik sovg\'asi, suvenir"],
        ["submarine", "/ˌsəbmərˈin/", "suv osti kemasi"],
        ["trace", "/treɪs/", "kuzatib bormoq, izidan bormoq"],
      ]),
      unit(30, [
        ["appliance", "/əˈplaɪəns/", "maishiy texnika vositasi"],
        ["basin", "/ˈbeɪsən/", "tos, rakovina"],
        ["broom", "/brum/", "supurgi"],
        ["caterpillar", "/ˈkætəˌpɪlər/", "kapalak qurti"],
        ["cupboard", "/ˈkəbərd/", "idish javoni"],
        ["delicate", "/ˈdɛləkət/", "nozik, tez sinadigan"],
        ["emerge", "/ˈimərʤ/", "chiqib kelmoq, paydo bo\'lmoq"],
        ["handicap", "/ˈhændiˌkæp/", "jismoniy cheklanganlik, nuqson"],
        ["hook", "/hʊk/", "ilgak, ilmoq"],
        ["hop", "/hɑp/", "sakramoq, sakrab yurmoq"],
        ["laundry", "/ˈlɔndri/", "kir kiimlar"],
        ["pursue", "/pərˈsu/", "ortidan quvmoq, ketidan tushmoq"],
        ["reluctant", "/rɪˈləktənt/", "xohlamaydigan, ikkilanuvchi"],
        ["sleeve", "/sliv/", "yeng (kiim yengi)"],
        ["spine", "/spaɪn/", "umurtqa pog\'onasi"],
        ["stain", "/steɪn/", "doya, dog\'"],
        ["strip", "/strɪp/", "ensiz mato bo\'lagi, tasma"],
        ["swear", "/swɛr/", "qasam ichmoq, va\'da bermoq"],
        ["swing", "/swɪŋ/", "silkitmoq, tebranmoq"],
        ["utilize", "/ˈjutəˌlaɪz/", "foydalanmoq, ishlatmoq"],
      ]),
    ],

};
