import { Book, createUnit as unit } from "../book-types";

export const essential2: Book = {

    id: "4eew2",
    title: "4000 Essential English Words 2",
    subtitle: "Book 2",
    totalUnits: 30,
    units: [
      unit(1, [
        ["anxious", "/ˈæŋʃəs/", "xavotirlangan, tashvishlangan"],
        ["awful", "/ˈɔfəl/", "juda yomon"],
        ["consist", "/kənˈsɪst/", "iborat bo\'lmoq"],
        ["desire", "/dɪˈzaɪər/", "xohlamoq, istamoq"],
        ["eager", "/ˈigər/", "chanqoq, sabrsiz"],
        ["household", "/ˈhaʊsˌhoʊld/", "oila a\'zolari"],
        ["intent", "/ˌɪnˈtɛnt/", "niyat, maqsad"],
        ["landscape", "/ˈlænˌskeɪp/", "landshaft, manzara"],
        ["lift", "/lɪft/", "ko\'tarmoq"],
        ["load", "/loʊd/", "yuklamoq"],
        ["lung", "/ləŋ/", "o\'pka"],
        ["motion", "/ˈmoʊʃən/", "ishora, harakat"],
        ["pace", "/peɪs/", "temp, sur\'at"],
        ["polite", "/pəˈlaɪt/", "odobli, aql-xushli"],
        ["possess", "/pəˈzɛs/", "egalik qilmoq, bor bo\'lmoq"],
        ["rapidly", "/ˈræpədli/", "juda tez"],
        ["remark", "/rɪˈmɑrk/", "ta\'kidlamoq"],
        ["seek", "/sik/", "qidirmoq, izlamoq"],
        ["shine", "/ʃaɪn/", "nur taratmoq/sochmoq"],
        ["spill", "/spɪl/", "to\'kmoq, to\'kib yubormoq"],
      ]),
      unit(2, [
        ["bring", "/brɪŋ/", "keltirmoq, olib kelmoq"],
        ["castle", "/ˈkæsəl/", "qasr, saroy"],
        ["command", "/kəˈmænd/", "buyruq bermoq, buyurmoq"],
        ["counsel", "/ˈkaʊnsəl/", "maslahat bermoq"],
        ["ensure", "/ɪnˈʃʊr/", "ta\'minlamoq"],
        ["explosion", "/ɪkˈsploʊʒən/", "portlash"],
        ["jewelry", "/ˈʤuəlri/", "taqinchoq"],
        ["land", "/lænd/", "qo\'nmoq"],
        ["meteor", "/ˈmitiər/", "meteorit"],
        ["monster", "/ˈmɑnstər/", "mahluq, monster"],
        ["northern", "/ˈnɔrðərn/", "shimoliy"],
        ["remote", "/rɪˈmoʊt/", "olis, uzoq"],
        ["southern", "/ˈsəðərn/", "janubiy"],
        ["statue", "/ˈstæˌʧu/", "haykal"],
        ["steam", "/stim/", "par, bug\'"],
        ["submit", "/səbˈmɪt/", "bo\'ysunmoq, aytganini qilmoq"],
        ["temple", "/ˈtɛmpəl/", "ibodatxona"],
        ["upper", "/ˈəpər/", "yuqori, ustki"],
        ["weed", "/wid/", "begona o\'t"],
        ["wing", "/wɪŋ/", "qanot"],
      ]),
      unit(3, [
        ["arrow", "/ˈɛroʊ/", "o\'q, yoy"],
        ["battle", "/ˈbætəl/", "urush, jang"],
        ["bow", "/boʊ/", "kamon"],
        ["brave", "/breɪv/", "qo\'rqmas, jasur"],
        ["chief", "/ʧif/", "boshliq, sardor"],
        ["disadvantage", "/ˌdɪsədˈvænɪʤ/", "kamchilik, salbiy jihat"],
        ["enemy", "/ˈɛnəmi/", "dushman, g\'anim"],
        ["entrance", "/ˈɛntrəns/", "kirish yo\'li"],
        ["hardly", "/ˈhɑrdli/", "arang, zo\'rg\'a"],
        ["intend", "/ˌɪnˈtɛnd/", "niyat qilmoq"],
        ["laughter", "/ˈlæftər/", "kulgi, shodlik"],
        ["log", "/lɔg/", "g\'o\'la"],
        ["military", "/ˈmɪlɪˌtɛri/", "armiya, harbiy"],
        ["obey", "/oʊˈbeɪ/", "bo\'ysunmoq, itoat etmoq"],
        ["secure", "/sɪˈkjʊr/", "olmoq, qo\'lga kiritmoq"],
        ["steady", "/ˈstɛdi/", "barqaror, muttasil"],
        ["trust", "/trəst/", "ishonmoq, inonmoq"],
        ["twist", "/twɪst/", "aylantirib bog\'lamoq"],
        ["unless", "/ənˈlɛs/", "magan taqdirda, agar ...-masa"],
        ["weapon", "/ˈwɛpən/", "qurol-yarog\'"],
      ]),
      unit(4, [
        ["chest", "/ʧɛst/", "bag\'r, ko\'ks"],
        ["confidence", "/ˈkɑnfədɛns/", "ishonch, dadillik"],
        ["consequence", "/ˈkɑnsəkwəns/", "natija, oqibat"],
        ["disaster", "/dɪˈzæstər/", "falokat, halokat"],
        ["disturb", "/dɪˈstərb/", "tashvishga solmoq, bezovta qilmoq"],
        ["estimate", "/ˈɛstəˌmeɪt/", "taxminan hisoblamoq"],
        ["honor", "/ˈɑnər/", "sharaflamoq, hurmat qilmoq"],
        ["impress", "/ˌɪmˈprɛs/", "lol qoldirmoq"],
        ["marathon", "/ˈmɛrəˌθɑn/", "marafon"],
        ["narrow", "/ˈnɛroʊ/", "tor"],
        ["pale", "/peɪl/", "xira, oqargan"],
        ["rough", "/rəf/", "g\'adir-budur, dag\'al"],
        ["satisfy", "/ˈsætɪsˌfaɪ/", "qoniqtirmoq, mamnun qilmoq"],
        ["scream", "/skrim/", "baqirmoq, qichqirmoq"],
        ["sensitive", "/ˈsɛnsɪtɪv/", "sezuvchan, ta\'sirchan"],
        ["shade", "/ʃeɪd/", "soya"],
        ["supplement", "/ˌsəpləˈmɛnt/", "to\'ldirmoq, qo\'shmoq"],
        ["terror", "/ˈtɛrər/", "dahshat, qo\'rquv"],
        ["threat", "/θrɛt/", "xatar, xavf"],
        ["victim", "/ˈvɪktɪm/", "qurbon"],
      ]),
      unit(5, [
        ["ancestor", "/ˈænˌsɛstər/", "ajdod"],
        ["angle", "/ˈæŋgəl/", "taraf, tomon, burchak"],
        ["boot", "/but/", "etik"],
        ["border", "/ˈbɔrdər/", "chegara"],
        ["congratulate", "/kənˈgræʧəˌleɪt/", "tabriklamoq, qutlamoq"],
        ["frame", "/freɪm/", "ramka"],
        ["heaven", "/ˈhɛvən/", "jannat, osmon"],
        ["incredible", "/ˌɪnˈkrɛdəbəl/", "aqlga sig\'mas, ajoyib"],
        ["legend", "/ˈlɛʤənd/", "afsona"],
        ["praise", "/preɪz/", "maqtamoq"],
        ["proceed", "/pərˈsid/", "bir yo\'nalishda davom etmoq"],
        ["pure", "/pjʊr/", "sof, musaffo"],
        ["relative", "/ˈrɛlətɪv/", "qarindosh"],
        ["senior", "/ˈsinjər/", "katta yoshdagi, katta"],
        ["silent", "/ˈsaɪlənt/", "jim, sokin, tinch"],
        ["sink", "/sɪŋk/", "cho\'kmoq"],
        ["superior", "/suˈpɪriər/", "ustun, yuqori"],
        ["surround", "/səraʊnd/", "o\'rab olmoq"],
        ["thick", "/θɪk/", "qalin, keng"],
        ["wrap", "/ræp/", "o\'ramoq"],
      ]),
      unit(6, [
        ["abroad", "/əˈbrɔd/", "xorij, chet el"],
        ["anger", "/ˈæŋgər/", "jahlini chiqarmoq"],
        ["bride", "/braɪd/", "kelinchak, kelin"],
        ["brief", "/brif/", "qisqa"],
        ["chase", "/ʧeɪs/", "quvlamoq, quvmoq"],
        ["disappoint", "/ˌdɪsəˈpɔɪnt/", "xafa qilmoq, ko\'nglini qoldirmoq"],
        ["dive", "/daɪv/", "suvga sakramoq, sho\'ng\'imoq"],
        ["exchange", "/ɪksˈʧeɪnʤ/", "ayriboshlamoq"],
        ["favor", "/ˈfeɪvər/", "yordam, muruvvat"],
        ["fee", "/fi/", "to\'lov, badal"],
        ["forever", "/fərˈɛvər/", "abadiy, umrbod"],
        ["guy", "/gaɪ/", "erkak kishi, yigit"],
        ["lovely", "/ˈləvli/", "yoqimli, go\'zal"],
        ["mood", "/mud/", "kayfiyat"],
        ["palace", "/ˈpæləs/", "qasr, saroy"],
        ["permit", "/ˈpərˌmɪt/", "ruxsat etmoq"],
        ["protest", "/ˈproʊˌtɛst/", "norozilik bildirmoq"],
        ["sculpture", "/ˈskəlpʧər/", "haykal"],
        ["tribe", "/traɪb/", "qabila"],
        ["youth", "/juθ/", "yoshlik payti"],
      ]),
      unit(7, [
        ["basis", "/ˈbeɪsɪs/", "tartib, yo\'nalish, asos"],
        ["biology", "/baɪˈɑləʤi/", "biologiya"],
        ["cage", "/keɪʤ/", "qafas"],
        ["colleague", "/ˈkɑlig/", "hamkasb"],
        ["colony", "/ˈkɑləni/", "koloniya, mustamlaka"],
        ["debate", "/dəˈbeɪt/", "muhokama qilmoq, bahslashmoq"],
        ["depart", "/dɪˈpɑrt/", "jo\'namoq, ketmoq"],
        ["depress", "/dɪˈprɛs/", "dilini xufton qilmoq, tushkunlikka solmoq"],
        ["factual", "/ˈfækʧuəl/", "asosli, dalilga boy"],
        ["fascinate", "/ˈfæsəˌneɪt/", "maftun qilmoq, qiziqtirmoq"],
        ["mission", "/ˈmɪʃən/", "missiya, topshiriq"],
        ["nevertheless", "/ˌnɛvərðəˈlɛs/", "shunga qaramay"],
        ["occupation", "/ˌɑkjəˈpeɪʃən/", "kasb, mashg\'ulot"],
        ["overseas", "/ˈoʊvərˈsiz/", "okean orti, xorijda"],
        ["persuade", "/pərsˈweɪd/", "ko\'ndirmoq, ishonch hosil qildirmoq"],
        ["route", "/rut/", "marshrut, yo\'nalish"],
        ["ruins", "/ruɪnz/", "xaroba"],
        ["scholar", "/ˈskɑlər/", "bilimdon, olim"],
        ["significant", "/sɪgˈnɪfɪkənt/", "muhim, ahamiyatli"],
        ["volcano", "/vɑlˈkeɪnoʊ/", "vulqon"],
      ]),
      unit(8, [
        ["broad", "/brɔd/", "keng, katta"],
        ["bush", "/bʊʃ/", "buta"],
        ["capable", "/ˈkeɪpəbəl/", "qobiliyatli, o\'quvli"],
        ["cheat", "/ʧit/", "g\'irromlik qilmoq, aldamoq"],
        ["concentrate", "/ˈkɑnsənˌtreɪt/", "diqqatini jamlamoq"],
        ["conclude", "/kənˈklud/", "xulosa qilmoq"],
        ["confident", "/ˈkɑnfədənt/", "o\'ziga ishongan"],
        ["considerable", "/kənˈsɪdərəbəl/", "sezilarli, salmoqli"],
        ["convey", "/kənˈveɪ/", "ifodalamoq, yetkazmoq"],
        ["definite", "/ˈdɛfənət/", "aniq, yaqqol"],
        ["delight", "/dɪˈlaɪt/", "zavq, shavq, quvonch"],
        ["destination", "/ˌdɛstɪˈneɪʃən/", "manzil"],
        ["dictate", "/ˈdɪkˌteɪt/", "aytib yozdirmoq"],
        ["edge", "/ɛʤ/", "chet, qirra"],
        ["path", "/pæθ/", "so\'qmoq, yo\'lak"],
        ["resort", "/rɪˈzɔrt/", "asos qilib olmoq, murojaat qilmoq"],
        ["shadow", "/ˈʃæˌdoʊ/", "soya, ko\'lanka"],
        ["succeed", "/səkˈsid/", "muvaffaqiyat qozonmoq"],
        ["suspect", "/ˈsəˌspɛkt/", "deb hisoblamoq, shubhalanmoq"],
        ["valley", "/ˈvæli/", "vodiy"],
      ]),
      unit(9, [
        ["admire", "/ædˈmaɪr/", "qoyil qolmoq, tan bermoq"],
        ["aid", "/eɪd/", "yordam bermoq"],
        ["attempt", "/əˈtɛmpt/", "urinmoq, harakat qilmoq"],
        ["authority", "/əˈθɔrəti/", "vakolat, huquq, hokimiyat"],
        ["capital", "/ˈkæpɪtəl/", "poytaxt"],
        ["cooperate", "/kˈwɑpərˌeɪt/", "hamkorlik qilmoq"],
        ["defend", "/dɪˈfɛnd/", "mudofaa qilmoq, himoya qilmoq"],
        ["destruction", "/dɪˈstrəkʃən/", "vayrona, buzilish"],
        ["disorder", "/dɪˈsɔrdər/", "tartibsizlik"],
        ["division", "/dɪˈvɪʒən/", "bo\'lish, taqsimlash"],
        ["enable", "/ɪˈneɪbəl/", "imkoniyat bermoq"],
        ["frustrate", "/ˈfrəˌstreɪt/", "umidsizlantirmoq, jahlini chiqarmoq"],
        ["govern", "/ˈgəvərn/", "nazorat qilmoq, boshqarmoq"],
        ["plenty", "/ˈplɛnti/", "yetarli miqdor, mo\'l"],
        ["relieve", "/rɪˈliv/", "og\'rig\'ini yengillashtirmoq"],
        ["reputation", "/ˌrɛpjəˈteɪʃən/", "obro\'"],
        ["royal", "/rɔɪəl/", "qirollik..."],
        ["slave", "/sleɪv/", "qul"],
        ["struggle", "/ˈstrəgəl/", "kurashmoq, yoqalashmoq"],
        ["stupid", "/ˈstupɪd/", "ahmoq, tentak"],
      ]),
      unit(10, [
        ["citizen", "/ˈsɪtɪzən/", "fuqaro"],
        ["council", "/ˈkaʊnsəl/", "kengash, konsullik"],
        ["declare", "/dɪˈklɛr/", "aytmoq, e\'lon qilmoq"],
        ["enormous", "/ɪˈnɔrmɪs/", "ulkan, juda katta"],
        ["extraordinary", "/ˌɛkstrəˈɔrdəˌnɛri/", "g\'ayritabiiy, ajoyib"],
        ["fog", "/fɔg/", "tuman"],
        ["funeral", "/fˈjunərəl/", "dafn marosimi"],
        ["giant", "/ʤaɪənt/", "bahaybat, gigant"],
        ["impression", "/ˌɪmˈprɛʃən/", "taassurot"],
        ["income", "/ˈɪnˌkəm/", "daromad"],
        ["mad", "/mæd/", "badjahl, jahldor, quturgan"],
        ["ought", "/ɔt/", "kerak, lozim"],
        ["resist", "/rɪˈzɪst/", "qarshilik ko\'rsatmoq"],
        ["reveal", "/rɪˈvil/", "ko\'rsatmoq, oshkor qilmoq"],
        ["rid", "/rɪd/", "xalos qilmoq"],
        ["sword", "/sɔrd/", "qilich, shamshir"],
        ["tale", "/teɪl/", "ertak, hikoya"],
        ["trap", "/træp/", "tutqunlikda saqlamoq, tuzoqqa tushirmoq"],
        ["trial", "/traɪəl/", "sud jarayoni"],
        ["violent", "/ˈvaɪələnt/", "zo\'ravon, shiddatli"],
      ]),
      unit(11, [
        ["admission", "/ədˈmɪʃən/", "ruxsat, kirish"],
        ["astronomy", "/əˈstrɑnəmi/", "astronomiya"],
        ["blame", "/bleɪm/", "ayblamoq"],
        ["chemistry", "/ˈkɛmɪstri/", "kimyo"],
        ["despite", "/dɪˈspaɪt/", "ga qaramasdan"],
        ["dinosaur", "/ˈdaɪnəˌsɔr/", "dinozavr"],
        ["exhibit", "/ɪgˈzɪbɪt/", "eksponat, ko\'rgazma"],
        ["fame", "/feɪm/", "shon-shuhrat, obro\'"],
        ["forecast", "/ˈfɔrˌkæst/", "ob-havo ma\'lumoti, bashorat"],
        ["genius", "/ˈʤinjəs/", "juda aqlli, daho"],
        ["gentle", "/ˈʤɛnəl/", "muloyim, yuvosh"],
        ["geography", "/ʤiˈɑgrəfi/", "geografiya"],
        ["interfere", "/ˌɪnərˈfɪr/", "xalaqit bermoq, aralashmoq"],
        ["lightly", "/ˈlaɪtli/", "muloyimlik bilan, sekin"],
        ["principal", "/ˈprɪnsəpəl/", "maktab direktori"],
        ["row", "/roʊ/", "qator, saf"],
        ["shelf", "/ʃɛlf/", "tokcha"],
        ["spite", "/spaɪt/", "qasddan, jo\'rttaga (out of spite)"],
        ["super", "/ˈsupər/", "juda yaxshi, a\'lo"],
        ["wet", "/wɛt/", "nam, xo\'l"],
      ]),
      unit(12, [
        ["abuse", "/əˈbjuz/", "haqorat qilmoq, ozor bermoq"],
        ["afford", "/əˈfɔrd/", "qurbi yetmoq"],
        ["bake", "/beɪk/", "pishirmoq"],
        ["bean", "/bin/", "no\'xat, loviya"],
        ["candle", "/ˈkændəl/", "shag\'am"],
        ["convert", "/ˈkɑnvərt/", "ga aylantirmoq, o\'zgartirmoq"],
        ["debt", "/dɛt/", "qarz"],
        ["decrease", "/ˈdiˌkris/", "kamaytirmoq, pasaymoq"],
        ["fault", "/fɔlt/", "ayb, xato"],
        ["fund", "/fənd/", "fond, pul mablag\'i"],
        ["generous", "/ˈʤɛnərəs/", "saxiy, qo\'li ochiq"],
        ["ingredient", "/ˌɪnˈgridiənt/", "tarkibiy qism, ingredient"],
        ["insist", "/ˌɪnˈsɪst/", "talab qilmoq, turib olmoq"],
        ["mess", "/mɛs/", "kir, tartibsizlik"],
        ["metal", "/ˈmɛtəl/", "metall, temir"],
        ["monitor", "/ˈmɑnətər/", "kuzatib bormoq"],
        ["oppose", "/əˈpoʊz/", "qarshi chiqmoq"],
        ["passive", "/ˈpæsɪv/", "passiv, sust"],
        ["quantity", "/kˈwɑntəti/", "miqdor"],
        ["sue", "/su/", "sudga bermoq"],
      ]),
      unit(13, [
        ["anxiety", "/æŋˈzaɪəti/", "tashvish, xavotir"],
        ["army", "/ˈɑrmi/", "armiya"],
        ["billion", "/ˈbɪljən/", "milliard"],
        ["carve", "/kɑrv/", "kesmoq, o\'ymoq"],
        ["consult", "/kənˈsəlt/", "maslahatlashmoq, yordam so\'ramoq"],
        ["emergency", "/ˈimərʤənsi/", "favqulodda holat"],
        ["fortune", "/ˈfɔrʧən/", "omad, boylik"],
        ["guarantee", "/ˌgɛrənˈti/", "kafolat bermoq"],
        ["hike", "/haɪk/", "piyoda safarga chiqsmoq"],
        ["initial", "/ˌɪˈnɪʃəl/", "birinchi, dastlabki"],
        ["intense", "/ˌɪnˈtɛns/", "jadal, juda kuchli"],
        ["lend", "/lɛnd/", "berib turmoq (qarzga)"],
        ["peak", "/pik/", "cho\'qqi"],
        ["potential", "/pəˈtɛnʃəl/", "imkoniyatli, ehtimoldagi"],
        ["pride", "/praɪd/", "mamnuniyat, g\'urur"],
        ["proof", "/pruf/", "isbot, dalil"],
        ["quit", "/kwɪt/", "to\'xtatmoq, tashlamoq"],
        ["spin", "/spɪn/", "aylanmoq"],
        ["tiny", "/ˈtaɪni/", "jajji, kichkina"],
        ["tutor", "/ˈtutər/", "repetitor, murabbiy"],
      ]),
      unit(14, [
        ["apparent", "/əˈpɛrənt/", "aniq, muqarrar"],
        ["blind", "/blaɪnd/", "ko\'zi ojiz, ko\'r"],
        ["calculate", "/ˈkælkjəˌleɪt/", "hisoblamoq"],
        ["chat", "/ʧæt/", "suhbatlashmoq"],
        ["commit", "/kəˈmɪt/", "va\'da bermoq, bag\'ishlamoq"],
        ["compose", "/kəmˈpoʊz/", "tuzmoq, yaratmoq"],
        ["dormitory", "/ˈdɔrməˌtɔri/", "yotoqxona"],
        ["exhaust", "/ɪgˈzɔst/", "holdan toydirmoq, charchatmoq"],
        ["greenhouse", "/ˈgrinˌhaʊs/", "issiqxona"],
        ["ignore", "/ˌɪgˈnɔr/", "e\'tiborsiz qoldirmoq"],
        ["obvious", "/ˈɑbviəs/", "aniq, ravshan"],
        ["physics", "/ˈfɪzɪks/", "fizika"],
        ["portion", "/ˈpɔrʃən/", "qism, bo\'lak"],
        ["remind", "/riˈmaɪnd/", "eslatmoq"],
        ["secretary", "/ˈsɛkrəˌtɛri/", "kotib(a)"],
        ["severe", "/səˈvɪr/", "qattiq, jiddiy"],
        ["talent", "/ˈtælənt/", "iqtidor, talant"],
        ["thesis", "/ˈθiˌsɪs/", "tezis, ilmiy ish"],
        ["uniform", "/ˈjunəˌfɔrm/", "forma, maxsus kiyim"],
        ["vision", "/ˈvɪʒən/", "ko\'rish qobiliyati"],
      ]),
      unit(15, [
        ["absorb", "/əbˈzɔrb/", "so\'rmoq, shimmoq"],
        ["boss", "/bɔs/", "ho\'jayin, rahbar"],
        ["committee", "/kəˈmɪti/", "qo\'mita, komitet"],
        ["contract", "/ˈkɑnˌtrækt/", "shartnoma"],
        ["crew", "/kru/", "brigada, jamoa"],
        ["devote", "/dɪˈvoʊt/", "bag\'ishlamoq, sarf etmoq"],
        ["dig", "/dɪg/", "yer kovlamoq"],
        ["dine", "/daɪn/", "tushlik/ovqat qilmoq"],
        ["donate", "/ˈdoʊˌneɪt/", "in\'om qilmoq, ehson qilmoq"],
        ["double", "/ˈdəbəl/", "ikki hissa"],
        ["elevate", "/ˈɛləˌveɪt/", "balandroqqa qo\'ymoq, ko\'tarmoq"],
        ["flavor", "/ˈfleɪvər/", "ta\'m, maza"],
        ["foundation", "/faʊnˈdeɪʃən/", "jamg\'arma, poydevor"],
        ["generation", "/ˌʤɛnərˈeɪʃən/", "avlod"],
        ["handle", "/ˈhændəl/", "band, tutqich"],
        ["layer", "/leɪər/", "qatlam, qat"],
        ["mud", "/məd/", "loy"],
        ["smooth", "/smuð/", "tekis, silliq"],
        ["soil", "/sɔɪl/", "tuproq"],
        ["unique", "/juˈnik/", "g\'ayrioddiy, o\'zgacha, yagona"],
      ]),
      unit(16, [
        ["chamber", "/ˈʧeɪmbər/", "yotoqxona, xona"],
        ["deny", "/dɪˈnaɪ/", "inkor qilmoq"],
        ["document", "/ˈdɑkjəmɛnt/", "hujjat"],
        ["emphasize", "/ˈɛmfəˌsaɪz/", "ta\'kidlamoq"],
        ["fever", "/ˈfivər/", "isitma"],
        ["flu", "/flu/", "gripp"],
        ["freeze", "/friz/", "sovuqdan qotib qolmoq, muzlamoq"],
        ["gesture", "/ˈʤɛsʧər/", "imo-ishora"],
        ["interrupt", "/ˌɪntərˈəpt/", "bezovta qilmoq, bo\'lmoq"],
        ["last", "/læst/", "davom etmoq"],
        ["likeness", "/ˈlaɪknəs/", "o\'xshashlik"],
        ["moreover", "/mɔˈroʊvər/", "bundan tashqari"],
        ["perspective", "/pərˈspɛktɪv/", "nuqtayi nazar, qarash"],
        ["rational", "/ˈræʃənəl/", "idrokli, ongli, mantiqiy"],
        ["recover", "/rɪˈkəvər/", "qayta tiklanmoq, tuzalmoq"],
        ["rely", "/rɪˈlaɪ/", "suyanmoq, tayanmoq"],
        ["shock", "/ʃɑk/", "hayratda qoldirmoq, shokda qoldirmoq"],
        ["shy", "/ʃaɪ/", "uyatchan, tortinchoq"],
        ["stare", "/stɛr/", "tikilmoq"],
        ["thus", "/ðəs/", "shuning uchun, shu tariqa"],
      ]),
      unit(17, [
        ["aim", "/eɪm/", "maqsad, niyat"],
        ["attach", "/əˈtæʧ/", "biriktirmoq, ulash"],
        ["bet", "/bɛt/", "garov o\'ynamoq, tikmoq"],
        ["carriage", "/ˈkɛrəʤ/", "ot-arava, furgon"],
        ["classic", "/ˈklæsɪk/", "klassik, odatiy"],
        ["commute", "/kəmˈjut/", "qatnamoq (ishga)"],
        ["confirm", "/kənˈfərm/", "tasdiqlamoq"],
        ["criticize", "/ˈkrɪtɪˌsaɪz/", "tanqid qilmoq"],
        ["differ", "/ˈdɪfər/", "farq qilmoq"],
        ["expense", "/ɪkˈspɛns/", "xarajat, chiqim"],
        ["formal", "/ˈfɔrməl/", "rasmiy"],
        ["height", "/haɪt/", "bo\'y, balandlik"],
        ["invent", "/ˌɪnˈvɛnt/", "kashf qilmoq, ixtiro qilmoq"],
        ["junior", "/ˈʤunjər/", "kichik lavozimdagi, kichik"],
        ["labor", "/ˈleɪbər/", "mehnat, ish"],
        ["mechanic", "/mɪˈkænɪk/", "mexanik, usta"],
        ["prime", "/praɪm/", "asosiy, eng muhim"],
        ["shift", "/ʃɪft/", "ko\'chirmoq, o\'zgarmoq"],
        ["signal", "/ˈsɪgnəl/", "signal, ishora"],
        ["sincere", "/sɪnˈsɪr/", "samimiy, chin ko\'ngildan"],
      ]),
      unit(18, [
        ["ability", "/əˈbɪləˌti/", "qobiliyat, iqtidor"],
        ["agriculture", "/ˈægrɪˌkəlʧər/", "qishloq xo\'jaligi"],
        ["cartoon", "/kɑrˈtun/", "multfilm, kulgili rasm"],
        ["ceiling", "/ˈsilɪŋ/", "shift, ship"],
        ["convince", "/kənˈvɪns/", "ishontirmoq"],
        ["curious", "/ˈkjʊriəs/", "qiziquvchan"],
        ["delay", "/dɪˈleɪ/", "kechiktirmoq, kuttirmoq"],
        ["diary", "/ˈdaɪəri/", "kundalik"],
        ["element", "/ˈɛləmənt/", "element, qism"],
        ["faith", "/feɪθ/", "ishonch, e\'tiqod"],
        ["grain", "/greɪn/", "g\'alla, don"],
        ["greet", "/grit/", "salomlashmoq, kutib olmoq"],
        ["investigate", "/ˌɪnˈvɛstəˌgeɪt/", "tadqiq qilmoq, o\'rganmoq"],
        ["joy", "/ʤɔɪ/", "quvonch, shodlik"],
        ["label", "/ˈleɪbəl/", "yorliq, yorliq yopishtirmoq"],
        ["monk", "/məŋk/", "rohib, rohib kishi"],
        ["odd", "/ɑd/", "g\'alati, noodatiy"],
        ["pause", "/pɔz/", "pauza qilmoq, to\'xtab turmoq"],
        ["priest", "/prist/", "rohib, ruhoniy"],
        ["profession", "/prəˈfɛʃən/", "kasb, kor"],
      ]),
      unit(19, [
        ["adopt", "/əˈdɑpt/", "asrab olmoq, qabul qilmoq"],
        ["beg", "/bɛg/", "yalinmoq, yolvormoq"],
        ["beyond", "/bɪɔnd/", "narida, narigi tomonda"],
        ["costume", "/ˈkɑstum/", "kostyum, libos"],
        ["exclaim", "/ɪkˈskleɪm/", "hayqirmoq, baqirib yubormoq"],
        ["extend", "/ɪkˈstɛnd/", "uzaytirmoq, cho\'zmoq"],
        ["fool", "/ful/", "ahmoq, tentak"],
        ["forbid", "/fərˈbɪd/", "taqiqlamoq"],
        ["illustrate", "/ˈɪləˌstreɪt/", "rasm bilan tasvirlamoq, tushuntirmoq"],
        ["indeed", "/ˌɪnˈdid/", "haqiqatan ham"],
        ["interpret", "/ˌɪnˈtərprət/", "talqin qilmoq, tarjima qilmoq"],
        ["kindly", "/ˈkaɪndli/", "mehribonlik bilan"],
        ["motive", "/ˈmoʊtɪv/", "motive, sabab, niyat"],
        ["nest", "/nɛst/", "uya, in"],
        ["origin", "/ˈɔrəʤən/", "kelib chiqish, manba"],
        ["reception", "/rɪˈsɛpʃən/", "qabul marosimi, bazm"],
        ["reject", "/ˈriʤɛkt/", "rad etmoq"],
        ["silence", "/ˈsaɪləns/", "sukunat, tinchlik"],
        ["stream", "/strim/", "soylik, kichik daryo"],
        ["tone", "/toʊn/", "ovoz ohangi, ton"],
      ]),
      unit(20, [
        ["accomplish", "/əˈkɑmplɪʃ/", "bajarmoq, erishmoq"],
        ["approve", "/əˈpruv/", "ma\'qullamoq, tasdiqlamoq"],
        ["approximate", "/əˈprɑksəˌmeɪt/", "taxminiy, yaqin"],
        ["barrier", "/ˈbɛriər/", "g\'ov, to\'siq"],
        ["detect", "/dɪˈtɛkt/", "aniqlamoq, sezib qolmoq"],
        ["duty", "/ˈduti/", "burch, vazifa"],
        ["elementary", "/ˌɛləˈmɛnʧri/", "boshlang\'ich, oddiy"],
        ["failure", "/ˈfeɪljər/", "omadsizlik, muvaffaqiyatsizlik"],
        ["gradual", "/ˈgræʤuəl/", "bosqichma-bosqich, sekin-asta"],
        ["immigrant", "/ˈɪməgrənt/", "immigrant, ko\'chib kelgan kishi"],
        ["insert", "/ˌɪnˈsərt/", "joylashtirmoq, kiritmoq"],
        ["instant", "/ˈɪnstənt/", "lahza, bir zum"],
        ["poverty", "/ˈpɑvərti/", "kambag\'allik, muhtojlik"],
        ["pretend", "/priˈtɛnd/", "o\'zini ...dek ko\'rsatmoq"],
        ["rank", "/ræŋk/", "unvon, daraja"],
        ["recognition", "/ˌrɛkɪgˈnɪʃən/", "tan olinish, e\'tirof"],
        ["refrigerate", "/rɪˈfrɪʤərˌeɪt/", "sovitmoq (muzlatkichda)"],
        ["rent", "/rɛnt/", "ijara to\'lovi, ijara"],
        ["retire", "/ˌriˈtaɪər/", "nafaqaga chiqmoq"],
        ["statistic", "/stəˈtɪstɪk/", "statistik ma\'lumot"],
      ]),
      unit(21, [
        ["astronaut", "/ˈæstrəˌnɑt/", "kosmonavt, astronavt"],
        ["awake", "/əˈweɪk/", "uyg\'oq"],
        ["courage", "/kərɪʤ/", "jasorat, dovyuraklik"],
        ["float", "/floʊt/", "suv betida qalqmoq, muallaq turmoq"],
        ["grant", "/grænt/", "bermoq, ruxsat bermoq"],
        ["gravity", "/ˈgrævɪti/", "tortishish kuchi, tortilish"],
        ["jewel", "/ʤuəl/", "qimmatbaho tosh, javohir"],
        ["miner", "/ˈmaɪnər/", "konchi"],
        ["mineral", "/ˈmɪnərəl/", "mineral, ma\'dan"],
        ["participate", "/pɑrˈtɪsəˌpeɪt/", "qatnashmoq, ishtirok etmoq"],
        ["permission", "/pərˈmɪʃən/", "ruxsat, ruxsatnoma"],
        ["pour", "/pɔr/", "quymoq"],
        ["presence", "/ˈprɛzəns/", "borlik, hozir bo\'lish"],
        ["raw", "/rɑ/", "xom, ishlov berilmagan"],
        ["satellite", "/ˈsætəˌlaɪt/", "yo\'ldosh, sun\'iy yo\'ldosh"],
        ["scale", "/skeɪl/", "ko\'lam, miqyosi"],
        ["skip", "/skɪp/", "qoldirib ketmoq, o\'tkazib yubormoq"],
        ["stretch", "/strɛʧ/", "cho\'zilmoq, kerishmoq"],
        ["telescope", "/ˈtɛləˌskoʊp/", "teleskop"],
        ["underground", "/ˈəndərˌgraʊnd/", "yer ostida, yer osti"],
      ]),
      unit(22, [
        ["alarm", "/əˈlɑrm/", "xavf signalizatsiyasi, budilnik"],
        ["apart", "/əˈpɑrt/", "alohida, ajralgan"],
        ["arrest", "/ərˈɛst/", "hibsga olmoq"],
        ["award", "/əˈwɔrd/", "mukofot, sovrin"],
        ["breed", "/brid/", "zot, zotli hayvon"],
        ["bucket", "/ˈbəkɪt/", "chelak"],
        ["contest", "/ˈkɑntɛst/", "musobaqa, bellashuv"],
        ["convict", "/ˈkɑnvɪkt/", "aybdor deb topmoq"],
        ["garage", "/gərɑʒ/", "garaj"],
        ["journalist", "/ˈʤərnəlɪst/", "jurnalist"],
        ["pup", "/pəp/", "kuchukcha"],
        ["qualify", "/kˈwɑləˌfaɪ/", "saralanmoq, mos kelmoq"],
        ["repair", "/rɪˈpɛr/", "tuzatmoq, ta\'mirlamoq"],
        ["resume", "/ˈrɛzəˌmeɪ/", "qayta boshlamoq (tanaffusdan so\'ng)"],
        ["rob", "/rɑb/", "shilmoq, o\'g\'rilamoq"],
        ["slip", "/slɪp/", "toyib ketmoq"],
        ["somewhat", "/ˈsəmˈwət/", "biroz, bir oz bo\'lsada"],
        ["stable", "/ˈsteɪbəl/", "barqaror, mustahkam"],
        ["tissue", "/ˈtɪʃu/", "qog\'oz ro\'molcha"],
        ["yard", "/jɑrd/", "hovli"],
      ]),
      unit(23, [
        ["alike", "/əˈlaɪk/", "o\'xshash, bir xil"],
        ["annoy", "/əˈnɔɪ/", "g\'ashiga tegmoq, joniga tegmoq"],
        ["architecture", "/ˈɑrkəˌtɛkʧər/", "arxitektura, me\'morchilik"],
        ["artificial", "/ˌɑrtəˈfɪʃəl/", "sun\'iy"],
        ["chain", "/ʧeɪn/", "zanjir"],
        ["distinct", "/dɪˈstɪŋkt/", "aniq, ajralib turadigan"],
        ["distinguish", "/dɪˈstɪŋgwɪʃ/", "farqlamoq, ajratmoq"],
        ["dust", "/dəst/", "chang, g\'ubor"],
        ["excitement", "/ɪkˈsaɪtmənt/", "hayajon, quvonch"],
        ["heal", "/hil/", "tuzalmoq, davolanmoq"],
        ["inherit", "/ˌɪnˈhɛrət/", "meros qilib olmoq"],
        ["manner", "/ˈmænər/", "uslub, xulq-atvor"],
        ["mount", "/maʊnt/", "ortmoq, kuchaymoq"],
        ["roof", "/rʊf/", "tom, tom qismi"],
        ["shortage", "/ˈʃɔrtɪʤ/", "kamchillik, tanqislik"],
        ["solid", "/ˈsɑləd/", "qattiq, mustahkam"],
        ["stock", "/stɑk/", "zaxira, g\'amlangan zaxira"],
        ["substance", "/ˈsəbstəns/", "modda, moddiy asyo"],
        ["tomb", "/tum/", "maqbara, xilxona"],
        ["wound", "/wund/", "jarohat, jarohatlamoq"],
      ]),
      unit(24, [
        ["bath", "/bæθ/", "vanna, cho\'milish"],
        ["bend", "/bɛnd/", "egilmoq, buqmoq"],
        ["chew", "/ʧu/", "chaynamoq"],
        ["disabled", "/dɪˈseɪbəld/", "nogiron, imkoniyati cheklangan"],
        ["fantastic", "/fænˈtæstɪk/", "fantastik, juda ajoyib"],
        ["fiction", "/ˈfɪkʃən/", "badiiy adabiyot, uydirma"],
        ["flag", "/flæg/", "bayroq"],
        ["inspect", "/ˌɪnˈspɛkt/", "tekshirmoq, ko\'zdan kechirmoq"],
        ["journal", "/ˈʤərnəl/", "jurnal (ilmiy/akademik)"],
        ["liquid", "/ˈlɪkwɪd/", "suyuqlik"],
        ["marvel", "/ˈmɑrvəl/", "hayratlanmoq"],
        ["nutrient", "/ˈnutriənt/", "oziq modda"],
        ["overcome", "/ˈoʊvərˌkəm/", "engmoq, yengib o\'tmoq"],
        ["recall", "/ˈriˌkɔl/", "eslamoq, xotirlamoq"],
        ["regret", "/rɪˈgrɛt/", "afsuslanmoq, afsus qilmoq"],
        ["soul", "/soʊl/", "ruh, qalbi"],
        ["sufficient", "/səˈfɪʃənt/", "yetarli"],
        ["surgery", "/ˈsərʤəri/", "jarrohlik amaliyoti"],
        ["tough", "/təf/", "qiyin, og\'ir, qattiq"],
        ["tube", "/tub/", "mushuk, quvur, truba"],
      ]),
      unit(25, [
        ["admit", "/ədˈmɪt/", "tan olmoq"],
        ["bin", "/bɪn/", "chiqindi idishi, quti"],
        ["bowl", "/boʊl/", "kosa, kosacha"],
        ["cabin", "/ˈkæbən/", "kulba, yog\'och uy"],
        ["cash", "/kæʃ/", "naqd pul"],
        ["criminal", "/ˈkrɪmənəl/", "jinoyatchi"],
        ["dozen", "/ˈdəzən/", "o\'n ikkita, dyujina"],
        ["elder", "/ˈɛldər/", "kattaroq, yoshi ulug\'"],
        ["facial", "/ˈfeɪʃəl/", "yuzga oid"],
        ["fence", "/fɛns/", "devor, panjara"],
        ["inspire", "/ˌɪnˈspaɪr/", "ruhlantirmoq, ilhomlantirmoq"],
        ["mere", "/mɪr/", "xolos, arzimagan"],
        ["neat", "/nit/", "sartarosh, ozoda, tartibli"],
        ["occasion", "/əˈkeɪʒən/", "voqea, imkoniyat, ayyom"],
        ["penalty", "/ˈpɛnəlti/", "jazo, jarima"],
        ["rude", "/rud/", "qo\'pol, odobsiz"],
        ["settle", "/ˈsɛtəl/", "hal qilmoq, joylashmoq"],
        ["vehicle", "/ˈviɪkəl/", "transport vositasi"],
        ["wallet", "/ˈwɔlət/", "hamyon"],
        ["yell", "/jɛl/", "baqirmoq, baqirib aytmoq"],
      ]),
      unit(26, [
        ["accuse", "/əˈkjuz/", "ayblamoq"],
        ["adjust", "/əˈʤəst/", "moslashtirmoq, to\'g\'rilamoq"],
        ["amuse", "/əmˈjuz/", "kulgdurmoq, xushnud etmoq"],
        ["coral", "/ˈkɔrəl/", "marjon, korall"],
        ["cotton", "/ˈkɔtən/", "paxta, paxta matosi"],
        ["crash", "/kræʃ/", "to\'qnashmoq, urilib ketmoq"],
        ["deck", "/dɛk/", "palaubalar, kemaning palubasi"],
        ["engage", "/ɪnˈgeɪʤ/", "shug\'ullanmoq, jalb qilmoq"],
        ["firm", "/fərm/", "qattiq, mustahkam"],
        ["fuel", "/fjuəl/", "yoqilg\'i"],
        ["grand", "/grænd/", "xushbichim, muhtasham, ulkan"],
        ["hurricane", "/ˈhərəˌkeɪnz/", "to\'fon, dovul"],
        ["loss", "/lɔs/", "yo\'qotish, zarar"],
        ["plain", "/pleɪn/", "sodda, oddiy"],
        ["reef", "/rif/", "rif, suv osti qoyasi"],
        ["shut", "/ʃət/", "yopmoq, berkitmoq"],
        ["strict", "/strɪkt/", "talabchan, qattiqqo\'l"],
        ["surf", "/sərf/", "serfing qilmoq"],
        ["task", "/tæsk/", "vazifa, topshiriq"],
        ["zone", "/zoʊn/", "hudud, zona"],
      ]),
      unit(27, [
        ["apology", "/əˈpɑləˌʤi/", "uzr, kechirim"],
        ["bold", "/boʊld/", "dovyurak, botir"],
        ["capture", "/ˈkæpʧər/", "tutib olmoq, qo\'lga olmoq"],
        ["cardinal", "/ˈkɑrdɪnəl/", "asosiy, eng muhim"],
        ["duke", "/duk/", "gersog"],
        ["expose", "/ɪkˈspoʊz/", "fosh qilmoq, ochib tashlamoq"],
        ["guilty", "/ˈgɪlti/", "aybdor, aybdor his qilgan"],
        ["hire", "/haɪər/", "ishga olmoq, yollamoq"],
        ["innocent", "/ˈɪnəsənt/", "beayb, aybsiz"],
        ["jail", "/ʤeɪl/", "turma, qamoqxona"],
        ["minister", "/ˈmɪnɪstər/", "vazir, vazirlik xodimi"],
        ["ordinary", "/ˈɔrdəˌnɛri/", "oddiy, har doimgi"],
        ["permanent", "/ˈpərmɑˌnɛnt/", "doimiy"],
        ["preserve", "/prɪˈzərv/", "saqlamoq, asramoq"],
        ["pronounce", "/prəˈnaʊns/", "talaffuz qilmoq"],
        ["resemble", "/rɪˈzɛmbəl/", "o\'xshamoq"],
        ["symptom", "/ˈsɪmptəm/", "simptom, alomat"],
        ["tobacco", "/təˈbæˌkoʊ/", "tamaki"],
        ["twin", "/twɪn/", "egizak"],
        ["witch", "/wɪʧ/", "jodugar"],
      ]),
      unit(28, [
        ["accompany", "/əˈkəmpəni/", "hamrohlik qilmoq"],
        ["bare", "/bɛr/", "yalang\'och, ochiq"],
        ["branch", "/brænʧ/", "shox, daraxt shoxi"],
        ["breath", "/brɛθ/", "nafas, nafas olish"],
        ["bridge", "/brɪʤ/", "ko\'prik"],
        ["cast", "/kæst/", "otmoq, tashlamoq"],
        ["dare", "/dɛr/", "botir bo\'lmoq, jur\'at etmoq"],
        ["electronic", "/ˌɪˌlɛkˈtrɑnɪk/", "elektron"],
        ["inn", "/ɪn/", "mehmonxona, karvonsaroy"],
        ["net", "/nɛt/", "to\'r"],
        ["philosophy", "/fəˈlɑsəfi/", "falsafa"],
        ["pot", "/pɑt/", "qozon, idish"],
        ["seed", "/sid/", "urug\'"],
        ["sharp", "/ʃɑrp/", "o\'tkir, o\'tkir tig\'li"],
        ["sort", "/sɔrt/", "tur, xil"],
        ["subtract", "/səbˈtrækt/", "ayirmoq (matematik)"],
        ["tight", "/taɪt/", "mahkam, mahkam bog\'langan"],
        ["virtual", "/ˈvərʧuəl/", "amalda, deyarli haqiqiy"],
        ["weigh", "/weɪ/", "vaznga ega bo\'lmoq, tortmoq"],
        ["whisper", "/ˈwɪspər/", "shivirlamoq"],
      ]),
      unit(29, [
        ["abstract", "/ˈæbˌstrækt/", "mavhum, abstraktsion"],
        ["annual", "/ˈænjuəl/", "har yilgi, yillik"],
        ["clay", "/kleɪ/", "loy, loy moddasi"],
        ["cloth", "/klɔθ/", "molar, mato"],
        ["curtain", "/ˈkərtən/", "parda"],
        ["deserve", "/dɪˈzərv/", "loyiq bo\'lmoq, munosib bo\'lmoq"],
        ["feather", "/ˈfɛðər/", "pat"],
        ["fertile", "/ˈfərtəl/", "unumdor, hosildor"],
        ["flood", "/fləd/", "toqin, suv bosishi"],
        ["furniture", "/ˈfərnɪʧər/", "mebel, mebel jihozlari"],
        ["grave", "/greɪv/", "qabr"],
        ["ideal", "/aɪˈdil/", "ideal, eng yaxshi"],
        ["intelligence", "/ˌɪnˈtɛləʤəns/", "idrok, aql-zakovat"],
        ["nowadays", "/ˈnaʊəˌdeɪz/", "hozirgi kunlarda"],
        ["obtain", "/əbˈteɪn/", "qo\'lga kiritmoq, olmoq"],
        ["religious", "/rɪˈlɪʤəs/", "diniy"],
        ["romantic", "/roʊˈmæntɪk/", "romantik"],
        ["shell", "/ʃɛl/", "chig\'anoq, po\'stloq"],
        ["shore", "/ʃɔr/", "qirg\'oq, sohil"],
        ["wheel", "/wil/", "g\'ildirak, g\'ildirakcha"],
      ]),
      unit(30, [
        ["appeal", "/əˈpil/", "o\'ziga jalb etmoq, qiziqtirmoq"],
        ["assume", "/əˈsum/", "taxmin qilmoq, deb o\'ylamoq"],
        ["borrow", "/ˈbɑˌroʊ/", "qarzga olmoq"],
        ["client", "/klaɪənt/", "mijoz"],
        ["downtown", "/ˈdaʊnˈtaʊn/", "shahar markazi"],
        ["dull", "/dəl/", "zerikarli, xira"],
        ["embarrass", "/ɪmˈbɛrəs/", "xijolat qilmoq, uyaltirmoq"],
        ["fare", "/fɛr/", "yo\'l haqi (yo\'lovchi to\'lovi)"],
        ["former", "/ˈfɔrmər/", "sobiq, ilgarigi"],
        ["formula", "/ˈfɔrmjələ/", "formula, usul"],
        ["found", "/faʊnd/", "tashkil etmoq, asos solmoq"],
        ["invest", "/ˌɪnˈvɛst/", "sarmoya kiritmoq"],
        ["loan", "/loʊn/", "qarz, kredit"],
        ["practical", "/ˈpræktɪkəl/", "amaliy, foydali"],
        ["quarter", "/kˈwɔrtər/", "chorak (25 tsent)"],
        ["salary", "/ˈsæləri/", "ish haqi, maosh"],
        ["scholarship", "/ˈskɑlərˌʃɪp/", "stipendiya"],
        ["temporary", "/ˈtɛmpərˌɛri/", "vaqtinchalik"],
        ["treasure", "/ˈtrɛʒər/", "xazina"],
        ["urge", "/ərʤ/", "undamoq, undash"],
      ]),
    ],

};
