import { Book, createUnit as unit } from "../book-types";

export const essential1: Book = {
    id: "4eew1",
    title: "4000 Essential English Words 1",
    subtitle: "Book 1",
    totalUnits: 30,
    units: [
      unit(1, [
        ["afraid", "/əˈfreɪd/", "qo'rqqan, cho'chigan"],
        ["agree", "/əˈgri/", "fikriga qo'shilmoq, rozi bo'lmoq"],
        ["angry", "/ˈæŋgri/", "jahli chiqqan, badjahl"],
        ["arrive", "/əraɪv/", "yetib kelmoq, kelmoq"],
        ["attack", "/əˈtæk/", "hujum qilmoq, hujum uyushtirmoq"],
        ["bottom", "/ˈbɑtəm/", "tag, pastki qism"],
        ["clever", "/ˈklɛvər/", "aqlli, ziyrak"],
        ["cruel", "/kruəl/", "shafqatsiz, berahm"],
        ["finally", "/ˈfaɪnəli/", "axiyri, vanihoyat"],
        ["hide", "/haɪd/", "yashirinmoq, bekinmoq"],
        ["hunt", "/hənt/", "ov qilmoq, ovlamoq"],
        ["lot", "/lɔt/", "juda ko'p"],
        ["middle", "/ˈmɪdəl/", "o'rta"],
        ["moment", "/ˈmoʊmənt/", "sekund; on, zum"],
        ["pleased", "/plizd/", "hursand, mamnun"],
        ["promise", "/ˈprɑməs/", "va'da bermoq"],
        ["reply", "/rɪˈplaɪ/", "javob bermoq"],
        ["safe", "/seɪf/", "xavfsiz, bexatar"],
        ["trick", "/trɪk/", "xiyla, nayrang; fokus"],
        ["well", "/wɛl/", "yaxshi"],
      ]),
      unit(2, [
        ["adventure", "/ədˈvɛnʧər/", "sarguzasht"],
        ["approach", "/əˈproʊʧ/", "yaqinlashmoq, yaqin kelmoq"],
        ["carefully", "/ˈkɛrfəli/", "e'tibor bilan, ehtiyotkorlik bilan"],
        ["chemical", "/ˈkɛmɪkəl/", "kimyoviy modda"],
        ["create", "/kriˈeɪt/", "yaratmoq, yasamoq"],
        ["evil", "/ˈivəl/", "yomon, yovuz"],
        ["experiment", "/ɪkˈspɛrəmənt/", "tajriba, sinov"],
        ["kill", "/kɪl/", "o'ldirmoq"],
        ["laboratory", "/ˈlæbrəˌtɔri/", "laboratoriya"],
        ["laugh", "/læf/", "kulgi"],
        ["loud", "/laʊd/", "shovqinli, baland"],
        ["nervous", "/ˈnərvəs/", "xavotirlangan, xavotirga tushgan"],
        ["noise", "/nɔɪz/", "shovqin, yoqimsiz ovoz"],
        ["project", "/ˈprɑʤɛkt/", "yumush, mahsus topshiriq"],
        ["scare", "/skɛr/", "qo'rqitmoq, daxshatga solmoq"],
        ["secret", "/ˈsikrɪt/", "sir"],
        ["shout", "/ʃaʊt/", "baqirmoq, qichqirmoq"],
        ["smell", "/smɛl/", "hidlamoq, hidlab ko'rmoq"],
        ["terrible", "/ˈtɛrəbəl/", "juda yomon"],
        ["worse", "/wərs/", "yomonroq"],
      ]),
      unit(3, [
        ["alien", "/ˈeɪliən/", "o'zga sayyoralik"],
        ["among", "/əˈməŋ/", "orasida, ichida"],
        ["chart", "/ʧɑrt/", "diagramma"],
        ["cloud", "/klaʊd/", "bulut"],
        ["comprehend", "/ˌkɑmpriˈhɛnd/", "tushunmoq, anglamoq"],
        ["describe", "/dɪˈskraɪb/", "tasvirlamoq"],
        ["ever", "/ˈɛvər/", "qachon bo'lmasin; ilgari"],
        ["fail", "/feɪl/", "muvaffaqiyatsizlikka uchramoq"],
        ["friendly", "/ˈfrɛndli/", "mehribon, g'amxo'r, do'stona"],
        ["grade", "/greɪd/", "baho"],
        ["instead", "/ˌɪnˈstɛd/", "o'rniga"],
        ["library", "/ˈlaɪbrɛˌri/", "kutubxona"],
        ["planet", "/ˈplænət/", "planeta, sayyora"],
        ["report", "/rɪˈpɔrt/", "hisobot; o'quvchi tabeli"],
        ["several", "/ˈsɛvərəl/", "bir talay, bir nechta"],
        ["solve", "/sɑlv/", "yechmoq, javob topmoq"],
        ["suddenly", "/ˈsədənli/", "to'satdan, kutilmaganda, birdaniga"],
        ["suppose", "/səˈpoʊz/", "deb o'ylamoq, taxmin qilmoq"],
        ["universe", "/ˈjunəˌvərs/", "koinot"],
        ["view", "/vju/", "qaramoq, ko'rmoq"],
      ]),
      unit(4, [
        ["appropriate", "/əˈproʊpriˌeɪt/", "mos, to'g'ri, muvofiq"],
        ["avoid", "/əˈvɔɪd/", "yaqinlashmaslik, chetda turmoq"],
        ["behave", "/bɪˈheɪv/", "o'zini tutmoq, odob saqlamoq"],
        ["calm", "/kɑm/", "xotirjam"],
        ["concern", "/kənˈsərn/", "tashvish, g'am"],
        ["content", "/ˈkɑntɛnt/", "xursand, shod"],
        ["expect", "/ɪkˈspɛkt/", "umid qilmoq, ishonmoq, kutmoq"],
        ["frequently", "/ˈfrikwɛntli/", "tez-tez"],
        ["habit", "/ˈhæbət/", "odat"],
        ["instruct", "/ˌɪnˈstrəkt/", "ta'lim bermoq; ko'rsatma bermoq"],
        ["issue", "/ˈɪʃu/", "masala, muammo"],
        ["none", "/nən/", "hech qancha"],
        ["patient", "/ˈpeɪʃənt/", "sabrli, toqatli"],
        ["positive", "/ˈpɑzətɪv/", "ijobiy, porloq"],
        ["punish", "/ˈpənɪʃ/", "jazolamoq"],
        ["represent", "/ˌrɛprɪˈzɛnt/", "vakil bo'lmoq, vakillik qilmoq"],
        ["shake", "/ʃeɪk/", "silkitmoq, siltamoq; silkinmoq"],
        ["spread", "/sprɛd/", "tarqalmoq; surkamoq, surtmoq"],
        ["stroll", "/stroʊl/", "sayr qilmoq, aylanib kelmoq"],
        ["village", "/ˈvɪlɪʤ/", "qishloq, ovul"],
      ]),
      unit(5, [
        ["aware", "/əˈwɛr/", "xabardor, ogoh"],
        ["badly", "/ˈbædli/", "yomon; jiddiy"],
        ["belong", "/bɪˈlɔŋ/", "tegishli bo'lmoq"],
        ["continue", "/kənˈtɪnju/", "davom etmoq/ettirmoq"],
        ["error", "/ˈɛrər/", "xato"],
        ["experience", "/ɪkˈspɪriəns/", "taassurot, kechinma"],
        ["field", "/fild/", "keng maydon, dala"],
        ["hurt", "/hərt/", "jarohatlamoq, jarohat yetkazmoq"],
        ["judgment", "/ˈʤəʤmənt/", "qaror qabul qilish; fikr"],
        ["likely", "/ˈlaɪkli/", "ehtimol, balki, mumkin"],
        ["normal", "/ˈnɔrməl/", "odatiy, har doimgi"],
        ["rare", "/rɛr/", "kamdan-kam; noyob, kamyob"],
        ["relax", "/rɪˈlæks/", "dam olmoq, hordiq chiqarmoq"],
        ["request", "/rɪkˈwɛst/", "so'ramoq"],
        ["reside", "/rɪˈzaɪd/", "muayyan yashamoq, istiqomat qilmoq"],
        ["result", "/rɪˈzəlt/", "natija, oqibat"],
        ["roll", "/roʊl/", "yumalatmoq, dumalatmoq"],
        ["since", "/sɪns/", "-dan beri/buyon"],
        ["visible", "/ˈvɪzəbəl/", "ko'zga ko'rinarli, ko'rinib turgan"],
        ["wild", "/waɪld/", "yovvoyi"],
      ]),
      unit(6, [
        ["advantage", "/ædˈvæntɪʤ/", "ustun jihat, foyda"],
        ["cause", "/kɔz/", "sabab bo'lmoq"],
        ["choice", "/ʧɔɪs/", "tanlash imkoniyati"],
        ["community", "/kəmˈjunɪti/", "jamiyat, jamoa"],
        ["dead", "/dɛd/", "o'lgan, o'lik"],
        ["distance", "/ˈdɪstəns/", "masofa"],
        ["escape", "/ɪˈskeɪp/", "qochib qutulmoq"],
        ["face", "/feɪs/", "duch kelmoq, yuzlanmoq"],
        ["follow", "/ˈfɑloʊ/", "ortidan bormoq, ergashmoq"],
        ["fright", "/fraɪt/", "qo'rquv, vahima"],
        ["ghost", "/goʊst/", "rux, arvoh"],
        ["individual", "/ˌɪndəˈvɪʤəwəl/", "individ, kishi"],
        ["pet", "/pɛt/", "uy hayvoni"],
        ["reach", "/riʧ/", "yetib bormoq, yetib kelmoq"],
        ["return", "/rɪˈtərn/", "qaytib kelmoq"],
        ["survive", "/sərˈvaɪv/", "tirik qolmoq; saqlab qolmoq"],
        ["upset", "/ˈəpˌsɛt/", "xafa, tushkun"],
        ["voice", "/vɔɪs/", "ovoz, tovush"],
        ["weather", "/ˈwɛðər/", "ob-havo"],
        ["wise", "/waɪz/", "aqlli, dono"],
      ]),
      unit(7, [
        ["allow", "/əˈlaʊ/", "ruxsat bermoq; imkoniyat bermoq"],
        ["announce", "/əˈnaʊns/", "e'lon qilmoq, ma'lum qilmoq"],
        ["beside", "/ˌbiˈsaɪd/", "yonma-yon, yonida"],
        ["challenge", "/ˈʧælənʤ/", "qiyinchilik, mushkul ish"],
        ["claim", "/kleɪm/", "tasdiqlamoq, ma'qullamoq"],
        ["condition", "/kənˈdɪʃən/", "ahvol, holat"],
        ["contribute", "/kənˈtrɪbjut/", "xayr qilmoq; hissa qo'shmoq"],
        ["difference", "/ˈdɪfərəns/", "farq, tafovut"],
        ["divide", "/dɪˈvaɪd/", "taqsimlamoq, bo'lmoq"],
        ["expert", "/ˈɛkspərt/", "ekspert, mutaxassis, usta"],
        ["famous", "/ˈfeɪməs/", "mashhur, taniqli"],
        ["force", "/fɔrs/", "kuch, qudrat"],
        ["harm", "/hɑrm/", "jabr, jarohat"],
        ["lay", "/leɪ/", "qo'ymoq"],
        ["peace", "/pis/", "tinchlik"],
        ["prince", "/prɪns/", "shahzoda"],
        ["protect", "/prəˈtɛkt/", "himoya qilmoq, asramoq"],
        ["sense", "/sɛns/", "sezmoq, his qilmoq"],
        ["sudden", "/ˈsədən/", "kutilmagan, tasodifiy"],
        ["therefore", "/ˈðɛrˌfɔr/", "shu sababli, shuning uchun"],
      ]),
      unit(8, [
        ["accept", "/əkˈsɛpt/", "qabul qilmoq"],
        ["arrange", "/əreɪnʤ/", "joy-joyiga qo'ymoq, tartibga keltirmoq"],
        ["attend", "/əˈtɛnd/", "bormoq"],
        ["balance", "/ˈbæləns/", "muvozanat saqlamoq"],
        ["contrast", "/ˈkɑntræst/", "katta farq"],
        ["encourage", "/ɪnˈkərəʤ/", "ruhlantirmoq, ruhini ko'tarmoq"],
        ["familiar", "/fəˈmɪljər/", "tanish, qadrdon"],
        ["grab", "/græb/", "uzmoq; olmoq"],
        ["hang", "/hæŋ/", "osmoq, ilmoq"],
        ["huge", "/juʤ/", "katta, ulkan"],
        ["necessary", "/ˈnɛsəˌsɛri/", "shart, zarur"],
        ["pattern", "/ˈpætərn/", "uslub, yo'nalish, yo'l"],
        ["propose", "/prəˈpoʊz/", "taklif qilmoq"],
        ["purpose", "/ˈpərpəs/", "maqsad"],
        ["release", "/riˈlis/", "qo'yib yubormoq, ozod qilmoq"],
        ["require", "/ˌrikˈwaɪər/", "talab qilinmoq, talab qilmoq"],
        ["single", "/ˈsɪŋgəl/", "bitta, bir dona"],
        ["success", "/səkˈsɛs/", "muvaffaqiyat, yutuq"],
        ["tear", "/tɪr/", "yirtmoq"],
        ["theory", "/ˈθɪri/", "nazariya"],
      ]),
      unit(9, [
        ["against", "/əˈgɛnst/", "ro'baro, qarama-qarshi yo'nalishda"],
        ["beach", "/biʧ/", "sohil, plyaj"],
        ["damage", "/ˈdæmɪʤ/", "shikastlamoq"],
        ["discover", "/dɪˈskəvər/", "topmoq, kashf qilmoq"],
        ["emotion", "/ˈiˌmoʊʃən/", "emotsiya, ruhiy kechinma"],
        ["fix", "/fɪks/", "tuzatmoq, ta'mirlamoq; hal etmoq"],
        ["frank", "/fræŋk/", "ochiq, samimiy"],
        ["identify", "/aɪˈdɛntəˌfaɪ/", "tanib bilmoq"],
        ["island", "/ˈaɪlənd/", "orol"],
        ["ocean", "/ˈoʊʃən/", "okean, ummon"],
        ["perhaps", "/pərˈhæps/", "ehtimol, balki"],
        ["pleasant", "/ˈplɛzənt/", "yoqimli"],
        ["prevent", "/prɪˈvɛnt/", "to'sqinlik qilmoq"],
        ["rock", "/rɑk/", "tosh"],
        ["save", "/seɪv/", "asramoq, saqlamoq"],
        ["step", "/stɛp/", "yurmoq, qadam tashlamoq"],
        ["still", "/stɪl/", "hali ham, haligacha"],
        ["taste", "/teɪst/", "ta'm, maza"],
        ["throw", "/θroʊ/", "irg'itmoq, uloqtirmoq"],
        ["wave", "/weɪv/", "to'lqin, mavj"],
      ]),
      unit(10, [
        ["benefit", "/ˈbɛnəfɪt/", "foyda, ustun jihat"],
        ["certain", "/ˈsərtən/", "ishonchi komil"],
        ["chance", "/ʧæns/", "imkoniyat, shans"],
        ["effect", "/ˈifɛkt/", "ta'sir, samara"],
        ["essential", "/ɛˈsɛnʃəl/", "juda muhim, zarur(iy)"],
        ["far", "/fɑr/", "uzoq, olis"],
        ["focus", "/ˈfoʊkɪs/", "diqqatini qaratmoq"],
        ["function", "/ˈfəŋkʃən/", "funksiya, vazifa"],
        ["grass", "/græs/", "maysa, o't"],
        ["guard", "/gɑrd/", "qo'riqlamoq"],
        ["image", "/ˈɪmɪʤ/", "rasm, ko'rinish"],
        ["immediate", "/ˌɪˈmiˌdiət/", "tezkor"],
        ["primary", "/ˈpraɪˌmɛri/", "asosiy, birinchi darajali"],
        ["proud", "/praʊd/", "fahrlangan"],
        ["remain", "/rɪˈmeɪn/", "qolmoq"],
        ["rest", "/rɛst/", "dam olmoq"],
        ["separate", "/ˈsɛpərˌeɪt/", "alohida, ajralgan, bo'lak"],
        ["site", "/saɪt/", "joy"],
        ["tail", "/teɪl/", "dum"],
        ["trouble", "/ˈtrəbəl/", "muammo; qiyinchilik"],
      ]),
      unit(11, [
        ["anymore", "/ˌɛniˈmɔr/", "ortiq, boshqa"],
        ["asleep", "/əsˈlip/", "uxlayotgan, uyquda"],
        ["berry", "/ˈbɛri/", "malina, rezavor"],
        ["collect", "/kəˈlɛkt/", "to'plamoq, yig'moq"],
        ["compete", "/kəmˈpit/", "musobaqalashmoq"],
        ["conversation", "/ˌkɑnvərˈseɪʃən/", "suhbat, muloqot"],
        ["creature", "/ˈkriʧər/", "jonivor, tirik mavjudot"],
        ["decision", "/dɪˈsɪʒən/", "qaror"],
        ["either", "/ˈiðər/", "ikkisidan biri"],
        ["forest", "/ˈfɔrɪst/", "o'rmon"],
        ["ground", "/graʊnd/", "yer"],
        ["introduce", "/ˌɪntrəˈdus/", "tanishtirmoq"],
        ["marry", "/ˈmɛri/", "turmush qurmoq"],
        ["prepare", "/priˈpɛr/", "tayyorlanmoq, tayyorlamoq"],
        ["sail", "/seɪl/", "qayiqda suzmoq; suzib ketmoq"],
        ["serious", "/ˈsɪriəs/", "jiddiy, og'ir"],
        ["spend", "/spɛnd/", "o'tkazmoq (vaqt)"],
        ["strange", "/streɪnʤ/", "noodatiy, g'alati"],
        ["truth", "/truθ/", "haqiqat"],
        ["wake", "/weɪk/", "uyg'onmoq"],
      ]),
      unit(12, [
        ["alone", "/əˈloʊn/", "yolg'iz"],
        ["apartment", "/əˈpɑrtmənt/", "kvartira"],
        ["article", "/ˈɑrtɪkəl/", "maqola"],
        ["artist", "/ˈɑrtɪst/", "rassom"],
        ["attitude", "/ˈætəˌtud/", "munosabat, muomala"],
        ["compare", "/kəmˈpɛr/", "taqqoslamoq, solishtirmoq"],
        ["judge", "/ʤəʤ/", "baho bermoq"],
        ["magazine", "/ˈmægəˌzin/", "jurnal"],
        ["material", "/məˈtɪriəl/", "material, xom-ashyo"],
        ["meal", "/mil/", "ovqatlanish payti; taom"],
        ["method", "/ˈmɛθəd/", "metod, usul"],
        ["neighbor", "/ˈneɪbər/", "qo'shni"],
        ["professional", "/prəˈfɛʃənəl/", "kasbiy; professional"],
        ["profit", "/ˈprɑfɪt/", "foyda"],
        ["quality", "/kˈwɑləti/", "sifat"],
        ["shape", "/ʃeɪp/", "shakl"],
        ["space", "/speɪs/", "bo'sh joy"],
        ["stair", "/stɛr/", "zina, pillapoya"],
        ["symbol", "/ˈsɪmbəl/", "ramz, belgi"],
        ["thin", "/θɪn/", "oriq, ozg'in"],
      ]),
      unit(13, [
        ["blood", "/bləd/", "qon"],
        ["burn", "/bərn/", "olovda yoqmoq"],
        ["cell", "/sɛl/", "kamera (turmada)"],
        ["contain", "/kənˈteɪn/", "o'z ichiga olmoq"],
        ["correct", "/kərˈɛkt/", "to'g'ri, bexato"],
        ["crop", "/krɑp/", "hosil, o'rim"],
        ["demand", "/dɪˈmænd/", "talab qilmoq"],
        ["equal", "/ˈikwəl/", "teng, barobar"],
        ["feed", "/fid/", "ovqatlantirmoq, ovqat bermoq"],
        ["hole", "/hoʊl/", "teshik; chuqurcha"],
        ["increase", "/ˌɪnˈkris/", "oshirmoq, ko'tarmoq"],
        ["lord", "/lɔrd/", "lord"],
        ["owe", "/oʊ/", "qarz bo'lmoq"],
        ["position", "/pəˈzɪʃən/", "pozitsiya, holat"],
        ["raise", "/reɪz/", "ko'tarmoq"],
        ["responsible", "/riˈspɑnsəbəl/", "mas'uliyatli"],
        ["sight", "/saɪt/", "manzara"],
        ["spot", "/spɑt/", "joy, makon"],
        ["structure", "/ˈstrəkʧər/", "imorat, bino"],
        ["whole", "/hoʊl/", "barcha, butun"],
      ]),
      unit(14, [
        ["coach", "/koʊʧ/", "murabbiy, trener"],
        ["control", "/kənˈtroʊl/", "nazorat qilmoq, boshqarmoq"],
        ["description", "/dɪˈskrɪpʃən/", "tavsif, ta'rif"],
        ["direct", "/dɪˈrɛkt/", "to'g'ridan-to'g'ri"],
        ["exam", "/ɪgˈzæm/", "imtihon"],
        ["example", "/ɪgˈzæmpəl/", "misol, namuna"],
        ["limit", "/ˈlɪmət/", "me'yor, cheklov"],
        ["local", "/ˈloʊkəl/", "mahalliy"],
        ["magical", "/ˈmæʤɪkəl/", "sirli; ajoyib"],
        ["mail", "/meɪl/", "xat, maktub; pochta"],
        ["novel", "/ˈnɑvəl/", "roman"],
        ["outline", "/ˈaʊˌtlaɪn/", "reja, rejamutolaa"],
        ["poet", "/poʊət/", "shoir"],
        ["print", "/prɪnt/", "qog'ozga tushirmoq, chop etmoq"],
        ["scene", "/sin/", "epizod, sahna"],
        ["sheet", "/ʃit/", "varoq"],
        ["silly", "/ˈsɪli/", "ahmoqona, be'mani"],
        ["store", "/stɔr/", "do'kon, univermag"],
        ["suffer", "/ˈsəfər/", "azoblanmoq, dard chekmoq"],
        ["technology", "/tɛkˈnɑləʤi/", "texnika vositasi, texnologiya"],
      ]),
      unit(15, [
        ["across", "/əˈkrɔs/", "narigi tomoniga/-da"],
        ["breathe", "/brið/", "nafas olmoq"],
        ["characteristic", "/ˌkɛrɪktərˈɪstɪk/", "fazilat, xususiyat"],
        ["consume", "/kənˈsum/", "iste'mol qilmoq, yemoq"],
        ["excite", "/ɪkˈsaɪt/", "hayajonlantirmoq"],
        ["extreme", "/ɪkˈstrim/", "keskin, shiddatli"],
        ["fear", "/fɪr/", "qo'rquv, vahima"],
        ["fortunate", "/ˈfɔrʧənət/", "omadli"],
        ["happen", "/ˈhæpən/", "yuz bermoq, nasib qilmoq"],
        ["length", "/lɛŋθ/", "uzunlik"],
        ["mistake", "/mɪˈsteɪk/", "xato"],
        ["observe", "/əbˈzərv/", "kuzatmoq, ko'rmoq"],
        ["opportunity", "/ˌɑpərˈtunəti/", "imkoniyat, imkon"],
        ["prize", "/praɪz/", "mukofot, sovrin"],
        ["race", "/reɪs/", "poyga"],
        ["realize", "/ˈriəˌlaɪz/", "fahmlamoq, anglamoq"],
        ["respond", "/rɪˈspɑnd/", "javob qaytarmoq"],
        ["risk", "/rɪsk/", "xavfli tavakkal"],
        ["wonder", "/ˈwəndər/", "bilishni xohlamoq"],
        ["yet", "/jɛt/", "hali ham, haligacha"],
      ]),
      unit(16, [
        ["academy", "/əˈkædəmi/", "akademiya"],
        ["ancient", "/ˈeɪnʧənt/", "qadimiy"],
        ["board", "/bɔrd/", "taxta"],
        ["century", "/ˈsɛnʧəri/", "asr (100 yil)"],
        ["clue", "/klu/", "ashyoviy dalil, kalit"],
        ["concert", "/ˈkɑnsərt/", "konsert"],
        ["county", "/ˈkaʊnti/", "okrug"],
        ["dictionary", "/ˈdɪkʃəˌnɛri/", "lug'at"],
        ["exist", "/ɪgˈzɪst/", "mavjud bo'lmoq"],
        ["flat", "/flæt/", "tekis, silliq"],
        ["gentleman", "/ˈʤɛnəlmən/", "jentlmen, muloyim kishi"],
        ["hidden", "/ˈhɪdən/", "yashirin"],
        ["maybe", "/ˈmeɪbi/", "balki, ehtimol"],
        ["officer", "/ˈɔfɪsər/", "ofitser"],
        ["original", "/ərˈɪʤənəl/", "asl nusxadagi"],
        ["pound", "/paʊnd/", "urmoq, qoqmoq"],
        ["process", "/ˈprɔˌsɛs/", "jarayon"],
        ["publish", "/ˈpəblɪʃ/", "chop etmoq, nashr qilmoq"],
        ["theater", "/ˈθieɪtər/", "teatr"],
        ["wealth", "/wɛlθ/", "boylik, mol-davlat"],
      ]),
      unit(17, [
        ["appreciate", "/əˈpriʃiˌeɪt/", "qadriga yetmoq, tushunmoq"],
        ["available", "/əˈveɪləbəl/", "mavjud, topish mumkin bo'lgan"],
        ["beat", "/bit/", "yengmoq, o'zib ketmoq"],
        ["bright", "/braɪt/", "yorqin, porloq"],
        ["celebrate", "/ˈsɛləˌbreɪt/", "nishonlamoq"],
        ["determine", "/dɪˈtərmən/", "qaror qilmoq, aniqlamoq"],
        ["disappear", "/ˌdɪsəˈpɪr/", "yo'qolmoq, ko'zdan g'oyib bo'lmoq"],
        ["else", "/ɛls/", "boshqa"],
        ["fair", "/fɛr/", "odil, adolatli"],
        ["flow", "/floʊ/", "oqmoq"],
        ["forward", "/ˈfɔrwərd/", "oldinga"],
        ["hill", "/hɪl/", "tepalik"],
        ["level", "/ˈlɛvəl/", "daraja, daraja ko'rsatkichi"],
        ["lone", "/loʊn/", "yolg'iz, bir o'zi"],
        ["puddle", "/ˈpədəl/", "ko'lmak"],
        ["response", "/rɪˈspɑns/", "javob"],
        ["season", "/ˈsizən/", "fasl, mavsum"],
        ["solution", "/səˈluʃən/", "yechim, javob"],
        ["waste", "/weɪst/", "isrof qilmoq, bexuda sarflamoq"],
        ["whether", "/ˈwɛðər/", "yo ... yoki ..., ...-mi"],
      ]),
      unit(18, [
        ["argue", "/ˈɑrgju/", "tortishmoq, bahslashmoq"],
        ["communicate", "/kəmˈjunəˌkeɪt/", "muloqot qilmoq, gaplashmoq"],
        ["crowd", "/kraʊd/", "omma, olomon"],
        ["depend", "/dɪˈpɛnd/", "bog'liq bo'lmoq, suyanmoq"],
        ["dish", "/dɪʃ/", "idish, tarelka"],
        ["empty", "/ˈɛmti/", "bo'sh"],
        ["exact", "/ɪgˈzækt/", "aniq, do'ppidek"],
        ["fresh", "/frɛʃ/", "yangi, yangi uzilgan"],
        ["gather", "/ˈgæðər/", "yig'moq, to'plamoq"],
        ["indicate", "/ˈɪndəˌkeɪt/", "ko'rsatmoq, bildirmoq"],
        ["item", "/ˈaɪtəm/", "narsa, buyum"],
        ["offer", "/ˈɔfər/", "taklif qilmoq"],
        ["price", "/praɪs/", "narx, narx-navo"],
        ["product", "/ˈprɑdəkt/", "mahsulot"],
        ["property", "/ˈprɑpərti/", "mulk, mol-mulk"],
        ["purchase", "/ˈpərʧəs/", "sotib olmoq"],
        ["recommend", "/ˌrɛkəˈmɛnd/", "tavsiya qilmoq"],
        ["select", "/səˈlɛkt/", "tanlamoq"],
        ["tool", "/tul/", "qurol, asbob"],
        ["treat", "/trit/", "munosabatda bo'lmoq, muomala qilmoq"],
      ]),
      unit(19, [
        ["alive", "/əˈlaɪv/", "tirik, barhayot"],
        ["bone", "/boʊn/", "suyak"],
        ["bother", "/ˈbɑðər/", "harakat qilmoq, urinmoq; tashvishlanmoq"],
        ["captain", "/ˈkæptən/", "kapitan"],
        ["conclusion", "/kənˈkluʒən/", "xulosa, yakun"],
        ["doubt", "/daʊt/", "shubha, gumon"],
        ["explore", "/ɪkˈsplɔr/", "tadqiq qilmoq, izlamoq"],
        ["foreign", "/ˈfɔrən/", "xorijiy, chet el"],
        ["glad", "/glæd/", "xursand, mamnun"],
        ["however", "/ˌhaʊˈɛvər/", "shunga qaramay, biroq"],
        ["injustice", "/ˌɪnˈʤəstɪs/", "adolatsizlik"],
        ["international", "/ˌɪnərˈnæʃənɑl/", "xalqaro"],
        ["lawyer", "/ˈlɔjər/", "huquqshunos, advokat"],
        ["mention", "/ˈmɛnʃən/", "eslatib o'tmoq, aytib o'tmoq"],
        ["policy", "/ˈpɑləsi/", "qoida, siyosat"],
        ["social", "/ˈsoʊʃəl/", "ijtimoiy"],
        ["speech", "/spiʧ/", "nutq, ma'ruza"],
        ["staff", "/stæf/", "xodimlar jamoasi, shtat"],
        ["toward", "/təˈwɔrd/", "tomon, sari"],
        ["wood", "/wʊd/", "yog'och, yog'och materiali"],
      ]),
      unit(20, [
        ["achieve", "/əˈʧiv/", "erishmoq, qo'lga kiritmoq"],
        ["advise", "/ədˈvaɪz/", "maslahat bermoq"],
        ["already", "/ɔˈrɛdi/", "allaqachon"],
        ["basic", "/ˈbeɪsɪk/", "oddiy, asosiy"],
        ["bit", "/bɪt/", "ozgina, biroz"],
        ["consider", "/kənˈsɪdər/", "o'ylab ko'rmoq, ko'rib chiqmoq"],
        ["destroy", "/dɪˈstrɔɪ/", "vayron qilmoq, yo'q qilmoq"],
        ["entertain", "/ˌɛnərˈteɪn/", "ko'nglini olmoq, xushnud etmoq"],
        ["extra", "/ˈɛkstrə/", "qo'shimcha"],
        ["goal", "/goʊl/", "maqsad"],
        ["lie", "/laɪ/", "yolg'on gapirmoq"],
        ["meat", "/mit/", "go'sht"],
        ["opinion", "/əˈpɪnjən/", "fikr, mulohaza"],
        ["real", "/ril/", "haqiqiy, real"],
        ["reflect", "/rɪˈflɛkt/", "aks ettirmoq"],
        ["regard", "/rɪˈgɑrd/", "deb bilmoq, hisoblamoq"],
        ["serve", "/sərv/", "xizmat ko'rsatmoq, tortmoq (taom)"],
        ["vegetable", "/ˈvɛʤtəbəl/", "sabzavot"],
        ["war", "/wɔr/", "urush"],
        ["worth", "/wərθ/", "qiymatga ega, arzimoq"],
      ]),
      unit(21, [
        ["appear", "/əˈpɪr/", "tuyulmoq, ko'rinmoq"],
        ["base", "/beɪs/", "asos, poydevor"],
        ["brain", "/breɪn/", "miya"],
        ["career", "/kərɪr/", "karyera, kasbiy yo'l"],
        ["clerk", "/klərk/", "xodim, sotuvchi-kassir"],
        ["effort", "/ˈɛfərt/", "harakat, urinish"],
        ["enter", "/ˈɛnər/", "kirmoq"],
        ["excellent", "/ˈɛksələnt/", "a'lo, juda yaxshi"],
        ["hero", "/ˈhɪroʊ/", "qahramon"],
        ["hurry", "/ˈhəri/", "shoshilmoq"],
        ["inform", "/ˌɪnˈfɔrm/", "xabar bermoq, ma'lum qilmoq"],
        ["later", "/ˈleɪtər/", "keyinroq"],
        ["leave", "/liv/", "tark etmoq, ketmoq"],
        ["locate", "/ˈloʊˌkeɪt/", "joyini aniqlamoq"],
        ["nurse", "/nərs/", "hamshira"],
        ["operation", "/ˌɑpərˈeɪʃən/", "operatsiya"],
        ["pain", "/peɪn/", "og'riq"],
        ["refuse", "/ˈrɛfˌjuz/", "rad etmoq, yo'q demoq"],
        ["though", "/ðoʊ/", "qaramasdan, garchi"],
        ["various", "/ˈvɛriəs/", "har xil, turli tuman"],
      ]),
      unit(22, [
        ["actual", "/ˈækʧəwəl/", "haqiqiy, asl"],
        ["amaze", "/əˈmeɪz/", "hayratda qoldirmoq"],
        ["charge", "/ʧɑrʤ/", "to'lov, narx"],
        ["comfort", "/ˈkəmfərt/", "tasalli bermoq, ovutmoq"],
        ["contact", "/ˈkɑnˌtækt/", "bog'lanmoq, aloqaga chiqmoq"],
        ["customer", "/ˈkəstəmər/", "xaridor, mijoz"],
        ["deliver", "/dɪˈlɪvər/", "yetkazib bermoq"],
        ["earn", "/ərn/", "ishlab topmoq"],
        ["gate", "/geɪt/", "darvoza"],
        ["include", "/ˌɪnˈklud/", "o'z ichiga olmoq"],
        ["manage", "/ˈmænɪʤ/", "boshqarmoq, eplay olmoq"],
        ["mystery", "/ˈmɪstəri/", "sir, jumboq"],
        ["occur", "/əˈkər/", "yuz bermoq, sodir bo'lmoq"],
        ["opposite", "/ˈɑpəzɪt/", "qarama-qarshi"],
        ["plate", "/pleɪt/", "tarelka, likopcha"],
        ["receive", "/rɪˈsiv/", "qabul qilib olmoq"],
        ["reward", "/rɪˈwɔrd/", "mukofot"],
        ["set", "/sɛt/", "qo'ymoq, joylashtirmoq"],
        ["steal", "/stil/", "o'g'irlamoq"],
        ["thief", "/θif/", "o'g'ri"],
      ]),
      unit(23, [
        ["advance", "/ədˈvæns/", "oldinga yurmoq"],
        ["athlete", "/ˈæθˌlit/", "sportchi"],
        ["average", "/ˈævərɪʤ/", "o'rtacha"],
        ["behavior", "/bɪˈheɪvjər/", "xulq-atvor, xatti-harakat"],
        ["behind", "/bɪˈhaɪnd/", "orqasida"],
        ["course", "/kɔrs/", "dars, kurs"],
        ["lower", "/loʊər/", "pasaytirmoq, tushirmoq"],
        ["match", "/mæʧ/", "mos kelmoq"],
        ["member", "/ˈmɛmbər/", "a'zo"],
        ["mental", "/ˈmɛntəl/", "aqlga oid, ruhiy"],
        ["passenger", "/ˈpæsənʤər/", "yo'lovchi"],
        ["personality", "/ˌpərsəˈnælɪti/", "shaxsiyat, xarakter"],
        ["poem", "/poʊəm/", "she'r"],
        ["pole", "/poʊl/", "ustun, ustuncha"],
        ["remove", "/riˈmuv/", "olib tashlamoq, yo'qotmoq"],
        ["safety", "/ˈseɪfti/", "xavfsizlik"],
        ["shoot", "/ʃut/", "otmoq (o'q/to'p)"],
        ["sound", "/saʊnd/", "ovoz chiqarmoq, eshitilmoq"],
        ["swim", "/swɪm/", "suzmoq"],
        ["web", "/wɛb/", "to'r (o'rgimchak to'ri)"],
      ]),
      unit(24, [
        ["block", "/blɑk/", "bo'lak, bo'lakcha (muz/tosh)"],
        ["cheer", "/ʧɪr/", "qichqirib qo'llab-quvvatlamoq"],
        ["complex", "/ˈkɑmplɛks/", "murakkab"],
        ["critic", "/ˈkrɪtɪk/", "tanqidchi"],
        ["event", "/ɪˈvɛnt/", "voqea, hodisa"],
        ["exercise", "/ˈɛksərˌsaɪz/", "mashq qilmoq"],
        ["fit", "/fɪt/", "sig'moq, mos kelmoq"],
        ["friendship", "/ˈfrɛndʃɪp/", "do'stlik"],
        ["guide", "/gaɪd/", "yo'lboshchi, gid"],
        ["lack", "/læk/", "yetishmovchilik, kamchilik"],
        ["passage", "/ˈpæsɪʤ/", "yo'lak, yo'l"],
        ["perform", "/pərˈfɔrm/", "ijro etmoq, namoyish etmoq"],
        ["pressure", "/ˈprɛʃər/", "bosim, tazyiq"],
        ["probable", "/ˈprɑbəbəl/", "ehtimolli, bo'lishi mumkin bo'lgan"],
        ["public", "/ˈpəblɪk/", "jamoat, ommaviy"],
        ["strike", "/straɪk/", "urmoq, zarba bermoq"],
        ["support", "/səˈpɔrt/", "qo'llab-quvvatlamoq"],
        ["task", "/tæsk/", "vazifa, topshiriq"],
        ["term", "/tərm/", "atama, termin"],
        ["unite", "/ˈjuˌnaɪt/", "birlashmoq"],
      ]),
      unit(25, [
        ["associate", "/əˈsoʊʃiˌeɪt/", "bog'lamoq, bog'liqlik ko'rmoq"],
        ["environment", "/ɪnˈvaɪrənmənt/", "atrof-muhit"],
        ["factory", "/ˈfæktəri/", "fabrika, zavod"],
        ["feature", "/ˈfiʧər/", "xususiyat, jihat"],
        ["instance", "/ˈɪnstəns/", "misol, holat"],
        ["involve", "/ˌɪnˈvɑlv/", "qamrab olmoq, jalb etmoq"],
        ["medicine", "/ˈmɛdəsən/", "dori, tibbiyot"],
        ["mix", "/mɪks/", "aralashma"],
        ["organize", "/ˈɔrgəˌnaɪz/", "tashkillashtirmoq"],
        ["period", "/ˈpɪriəd/", "davr, vaqt oralig'i"],
        ["populate", "/ˈpɑpjəˌleɪt/", "yashamoq, joylashmoq"],
        ["produce", "/ˈproʊdus/", "ishlab chiqarmoq"],
        ["range", "/reɪnʤ/", "diapazon, qator"],
        ["recognize", "/ˈrɛkəgˌnaɪz/", "tanimoq, bilib olmoq"],
        ["regular", "/ˈrɛgjələr/", "muntazam, doimiy"],
        ["sign", "/saɪn/", "belgi, ishora"],
        ["tip", "/tɪp/", "uch (uchki qismi)"],
        ["tradition", "/trəˈdɪʃən/", "an'ana, urf-odat"],
        ["trash", "/træʃ/", "chiqindi, axlat"],
        ["wide", "/waɪd/", "keng"],
      ]),
      unit(26, [
        ["advice", "/ədˈvaɪs/", "maslahat"],
        ["along", "/əˈlɔŋ/", "bo'ylab"],
        ["attention", "/əˈtɛnʃən/", "e'tibor"],
        ["attract", "/əˈtrækt/", "o'ziga jalb qilmoq"],
        ["climb", "/klaɪm/", "marmalamoq, chiqqan bo'lmoq"],
        ["drop", "/drɔp/", "tushirib yubormoq, tommoq"],
        ["final", "/ˈfaɪnəl/", "yakuniy, oxirgi"],
        ["further", "/ˈfərðər/", "yanada uzoqroq, keyingi"],
        ["imply", "/ˌɪmˈplaɪ/", "shama qilmoq, nazarda tutmoq"],
        ["maintain", "/meɪnˈteɪn/", "bir maromda saqlamoq"],
        ["neither", "/ˈniðər/", "hech qaysisi, na u va na bu"],
        ["otherwise", "/ˈəðərˌwaɪz/", "aks holda"],
        ["physical", "/ˈfɪzɪkəl/", "jismoniy"],
        ["prove", "/pruv/", "isbotlamoq"],
        ["react", "/riækt/", "munosabat bildirmoq, munosabat ko'rsatmoq"],
        ["ride", "/raɪd/", "minmoq (velosiped/ot)"],
        ["situated", "/ˈsɪʧuˌeɪtɪd/", "joylashgan"],
        ["society", "/soʊˈsaɪɪti/", "jamiyat"],
        ["standard", "/ˈstændərd/", "standart, me'yor"],
        ["suggest", "/səˈʤɛst/", "taklif qilmoq"],
      ]),
      unit(27, [
        ["actually", "/ˈæˌkʧuəli/", "amalda, aslida"],
        ["bite", "/baɪt/", "tishlash, tishlamoq"],
        ["coast", "/koʊst/", "sohil, dengiz bo'yi"],
        ["deal", "/dil/", "kelishuv, bitim"],
        ["desert", "/ˈdɛzərt/", "sahro, cho'l"],
        ["earthquake", "/ˈərθkˌweɪk/", "zilzila"],
        ["effective", "/ˈifɛktɪv/", "samarali"],
        ["examine", "/ɪgˈzæmɪn/", "tekshirmoq, ko'rib chiqmoq"],
        ["false", "/fɔls/", "yolg'on, noto'g'ri"],
        ["gift", "/gɪft/", "sovg'a"],
        ["hunger", "/ˈhəŋgər/", "ochlik"],
        ["imagine", "/ˌɪˈmæʤən/", "tasavvur qilmoq"],
        ["journey", "/ˈʤərni/", "sayohat, uzun yo'l"],
        ["puzzle", "/ˈpəzəl/", "jumboq, topishmoq"],
        ["quite", "/kwaɪt/", "anchagina, juda"],
        ["rather", "/ˈrəðər/", "afzal ko'rmoq, aksincha"],
        ["specific", "/spɪˈsɪfɪk/", "aniq, xususiy"],
        ["tour", "/tʊr/", "sayohat, tur"],
        ["trip", "/trɪp/", "sayohat, safar"],
        ["value", "/ˈvælju/", "qiymat, qadr-qimmat"],
      ]),
      unit(28, [
        ["band", "/bænd/", "guruh, musiqiy guruh"],
        ["barely", "/ˈbɛrli/", "araning arang, deyarli yo'q"],
        ["boring", "/ˈbɔrɪŋ/", "zerikarli"],
        ["cancel", "/ˈkænsəl/", "bekor qilmoq"],
        ["driveway", "/ˈdraɪvˌweɪ/", "xususiy yo'lak (uyga kirish yo'li)"],
        ["garbage", "/ˈgɑrbɪʤ/", "chiqindi, axlat"],
        ["instrument", "/ˈɪnstrəmənt/", "musiqa asbobi, qurol"],
        ["list", "/lɪst/", "ro'yxat"],
        ["magic", "/ˈmæʤɪk/", "sehr, sehr-jodu"],
        ["message", "/ˈmɛsɪʤ/", "xabar, xat"],
        ["notice", "/ˈnoʊtɪs/", "payqamoq, ko'rib qolmoq"],
        ["own", "/oʊn/", "egalik qilmoq"],
        ["predict", "/prɪˈdɪkt/", "bashorat qilmoq, oldindan aytmoq"],
        ["professor", "/prəˈfɛsər/", "professor"],
        ["rush", "/rəʃ/", "shoshilmoq"],
        ["schedule", "/ˈskɛʤʊl/", "jadval, reja"],
        ["share", "/ʃɛr/", "bo'lishmoq, baham ko'rmoq"],
        ["stage", "/steɪʤ/", "sahna"],
        ["storm", "/stɔrm/", "bo'ron, bag'ri shamol"],
        ["within", "/wɪˈθɪn/", "ichida, oralig'ida"],
      ]),
      unit(29, [
        ["advertise", "/ˈædvərˌtaɪz/", "reklama qilmoq"],
        ["assign", "/əˈsaɪn/", "topshirmoq, biriktirmoq"],
        ["audience", "/ˈɔdiəns/", "tomoshabinlar jamoasi"],
        ["breakfast", "/ˈbrɛkfəst/", "nonushta"],
        ["competition", "/ˌkɑmpəˈtɪʃən/", "musobaqa"],
        ["cool", "/kul/", "salqin"],
        ["gain", "/geɪn/", "orttirmoq, ko'paytirmoq"],
        ["importance", "/ˌɪmˈpɔrtəns/", "muhimlik, ahamiyat"],
        ["knowledge", "/ˈnɑlɪʤ/", "bilim"],
        ["major", "/ˈmeɪʤər/", "kattakon, asosiy"],
        ["mean", "/min/", "bag'ritosh, yomon"],
        ["prefer", "/prɪˈfər/", "afzal ko'rmoq"],
        ["president", "/ˈprɛzɪdənt/", "prezident"],
        ["progress", "/ˈprɑˌgrɛs/", "rivojlanish, ilgarilash"],
        ["respect", "/rɪˈspɛkt/", "hurmat, xurmat qilmoq"],
        ["rich", "/rɪʧ/", "boy, badavlat"],
        ["skill", "/skɪl/", "ko'nikma, mahorat"],
        ["somehow", "/ˈsəmˌhaʊ/", "qandaydir yo'l bilan"],
        ["strength", "/strɛŋθ/", "kuch-quvvat"],
        ["vote", "/voʊt/", "ovoz bermoq"],
      ]),
      unit(30, [
        ["above", "/əˈbəv/", "tepasida, yuqorida"],
        ["ahead", "/əˈhɛd/", "oldinda"],
        ["amount", "/əˈmaʊnt/", "miqdor, hajm"],
        ["belief", "/bɪˈlif/", "ishonch, e'tiqod"],
        ["center", "/ˈsɛnər/", "markaz"],
        ["common", "/ˈkɑmən/", "umumiy, tez-tez uchraydigan"],
        ["cost", "/kɔst/", "turmoq (narxda)"],
        ["demonstrate", "/ˈdɛmənˌstreɪt/", "ko'rsatib bermoq, namoyish qilmoq"],
        ["different", "/ˈdɪfərənt/", "turli xil, boshqacha"],
        ["evidence", "/ˈɛvədəns/", "dalil, isbot"],
        ["honesty", "/ˈɑnəsti/", "halollik, rostg'uylik"],
        ["idiom", "/ˈɪdiəm/", "ibora, idiom"],
        ["independent", "/ˌɪndɪˈpɛndənt/", "mustaqil"],
        ["inside", "/ˌɪnˈsaɪd/", "ichida, ichki qismi"],
        ["master", "/ˈmæstər/", "usta, mohir kishi"],
        ["memory", "/ˈmɛməri/", "xotira"],
        ["proper", "/ˈprɑpər/", "to'g'ri, me'yoriy, mos"],
        ["scan", "/skæn/", "diqqat bilan ko'zdan kechirmoq"],
        ["section", "/ˈsɛkʃən/", "bo'lim, qism"],
        ["surface", "/ˈsərfəs/", "sirt, ustki qism"],
      ]),
    ],

};
