import { Book, createUnit as unit } from "../book-types";

export const essential4: Book = {

    id: "4eew4",
    title: "4000 Essential English Words 4",
    subtitle: "Book 4",
    totalUnits: 30,
    units: [
      unit(1, [
        ["aroma", "/ərˈoʊmə/", "xushbo\'y hid, is"],
        ["beverage", "/ˈbɛvərɪʤ/", "ichimlik"],
        ["cluster", "/ˈkləstər/", "bog'"],
        ["combine", "/ˈkɑmbaɪn/", "birlashtirmoq, aralashtirmoq"],
        ["condensed", "/kənˈdɛnst/", "quyuq, quyultirilgan"],
        ["contemporary", "/kənˈtɛmpərˌɛri/", "zamonaviy, hozirgi"],
        ["cultivate", "/ˈkəltəˌveɪt/", "o\'stirmoq, yetishtirmoq"],
        ["divine", "/dɪˈvaɪn/", "ilohiy"],
        ["humid", "/ˈjumɪd/", "nam, dim"],
        ["odor", "/ˈoʊdər/", "hid, is"],
        ["palate", "/ˈpælɪt/", "tanglay, ta\'m bilish qobiliyati"],
        ["paradise", "/ˈpɛrəˌdaɪs/", "jannat, jannatmakon joy"],
        ["plantation", "/ˌplænˈteɪʃən/", "plantatsiya, katta ferma"],
        ["rapid", "/ˈræpɪd/", "tez, jadal"],
        ["rate", "/reɪt/", "tezlik, sur\'at"],
        ["soothing", "/ˈsuðɪŋ/", "tinchlantiruvchi, ovuntiruvchi"],
        ["subtle", "/ˈsətəl/", "ko\'z ilg\'amas, bilinar-bilinmas"],
        ["texture", "/ˈtɛksʧər/", "tekstura, sirt tuzilishi"],
        ["toxic", "/ˈtɑksɪk/", "zaharli"],
        ["vary", "/ˈvɛri/", "farq qilmoq, o\'zgarib turmoq"],
      ]),
      unit(2, [
        ["accident", "/ˈæksədənt/", "falokat, baxtsiz hodisa"],
        ["admiral", "/ˈædmərəl/", "admiral"],
        ["arc", "/ɑrk/", "ark, yoy shakli"],
        ["character", "/ˈkɛrɪktər/", "xarakter, fe\'l-atvor"],
        ["conscience", "/ˈkɑnʃəns/", "vijdon"],
        ["fiery", "/ˈfaɪəri/", "olovli, alangali"],
        ["flesh", "/flɛʃ/", "tana, badan, go\'sht"],
        ["grapefruit", "/ˈgreɪpˌfrut/", "greypfrut"],
        ["hay", "/heɪ/", "somon, pichan"],
        ["horrified", "/ˈhɔrəˌfaɪd/", "daxshatga tushgan, qo\'rqqan"],
        ["kerosene", "/ˈkɛrəˌsin/", "kerosin"],
        ["loop", "/lup/", "sirtmoq, halqa"],
        ["paddle", "/ˈpædəl/", "eshkak"],
        ["raft", "/ræft/", "sol (yog\'och kema)"],
        ["sour", "/saʊər/", "nordon"],
        ["stake", "/steɪk/", "tirgak, ustun"],
        ["steward", "/stuərd/", "styuard, xizmatchi"],
        ["string", "/strɪŋ/", "kanop ip, iplar"],
        ["thorn", "/θɔrn/", "tikan"],
        ["wreck", "/rɛk/", "vayron qilmoq, buzmoq"],
      ]),
      unit(3, [
        ["admonish", "/ædˈmɑnɪʃ/", "ogohlantirmoq, dakka bermoq"],
        ["audible", "/ˈɑdəbəl/", "eshitiladigan"],
        ["awesome", "/ˈɔsəm/", "hayratlanarli, ajoyib"],
        ["beware", "/bɪˈwɛr/", "ehtiyot bo\'lmoq"],
        ["brag", "/bræg/", "maqtanmoq"],
        ["conscious", "/ˈkɑnʃəs/", "sezadigan, xabardor"],
        ["disagree", "/dɪsəˈgri/", "norozi bo\'lmoq, rozi bo\'lmaslik"],
        ["echo", "/ˈɛkoʊ/", "aks-sado bermoq"],
        ["eventual", "/əˈvɛnʧuəl/", "oxirgi, yakuniy"],
        ["hint", "/hɪnt/", "ishora, shama"],
        ["idiot", "/ˈɪˌdiət/", "ovsar, tentak"],
        ["immense", "/ˌɪˈmɛns/", "juda katta, ulkan"],
        ["indirect", "/ˌɪndərˈɛkt/", "aylanma, to\'g\'ri bo\'lmagan"],
        ["option", "/ˈɔpʃən/", "tanlov, imkoniyat"],
        ["pastime", "/ˈpæˌstaɪm/", "ermak, ovunchoq"],
        ["perfect", "/ˈpərˌfɪkt/", "mukammal, ideal"],
        ["pinpoint", "/ˈpɪnˌpɔɪnt/", "aniq joyini ko\'rsatmoq"],
        ["switch", "/swɪʧ/", "alishtirmoq, o\'zgartirmoq"],
        ["thorough", "/θəroʊ/", "to\'liq, batafsil"],
        ["torment", "/ˈtɔrˌmɛnt/", "azob bermoq, qiynamoq"],
      ]),
      unit(4, [
        ["beak", "/bik/", "tumshuq"],
        ["damp", "/dæmp/", "nam, xo\'l"],
        ["disapprove", "/ˌdɪsəˈpruv/", "ma\'qullamaslik, norozi bo\'lmoq"],
        ["except", "/ɪkˈsɛpt/", "...dan tashqari"],
        ["flight", "/flaɪt/", "parvoz, reys"],
        ["fond", "/fɑnd/", "ishqiboz, yaxshi ko\'radigan"],
        ["immoral", "/ˌɪˈmɔrəl/", "axloqsiz, yomon"],
        ["ivy", "/ˈaɪvi/", "pechak o\'simligi"],
        ["moan", "/moʊn/", "ingramoq, nola qilmoq"],
        ["oblivious", "/əˈblɪviəs/", "xabarsiz, bexabar"],
        ["perish", "/ˈpɛrɪʃ/", "halok bo\'lmoq, o\'lmoq"],
        ["pit", "/pɪt/", "o\'ra, chuqurlik"],
        ["rim", "/rɪm/", "chegarasi, to\'g\'in"],
        ["roost", "/rust/", "qo\'noq, qo\'nish joyi"],
        ["slippery", "/sˈlɪpəri/", "sirg\'anchiq, sirpanchiq"],
        ["soar", "/sɔr/", "baland uchmoq"],
        ["trivial", "/ˈtrɪviəl/", "arzimas, ahamiyatsiz"],
        ["typical", "/ˈtɪpɪkəl/", "odatiy, xarakterli"],
        ["utterly", "/ˈətərli/", "butkul, mutlaqo"],
        ["weep", "/wip/", "yig\'lamoq"],
      ]),
      unit(5, [
        ["awhile", "/əˈwaɪl/", "biroz vaqtga"],
        ["cyberspace", "/ˈsaɪbərˌspeɪs/", "kiberbo\'shliq, internet"],
        ["edit", "/ˈɛdət/", "tahrir qilmoq, tuzatmoq"],
        ["essay", "/ˈɛˌseɪ/", "insho, ocherk"],
        ["evaluate", "/ɪˈvæljuˌeɪt/", "baholamoq, o\'rganmoq"],
        ["faint", "/feɪnt/", "xushidan ketmoq"],
        ["global", "/ˈgloʊbəl/", "global, dunyoviy"],
        ["gymnasium", "/ʤɪmˈneɪziəm/", "gimnastika zali, sport zal"],
        ["highlight", "/ˈhaɪˌlaɪt/", "ajratib ko\'rsatmoq, markerlamoq"],
        ["ignorant", "/ˈɪgnərənt/", "bexabar, bilimdon bo\'lmagan"],
        ["index", "/ˈɪndɛks/", "mundarija, ilova"],
        ["lecture", "/ˈlɛkʧər/", "ma\'ruza, lektsiya"],
        ["moral", "/ˈmɔrəl/", "xulosa, axloqiy saboq"],
        ["operate", "/ˈɔpərˌeɪt/", "ishlamoq, boshqarmoq"],
        ["private", "/ˈpraɪvət/", "shaxsiy, xususiy"],
        ["recent", "/ˈrisənt/", "yaqindagi, so\'nggi"],
        ["resolution", "/ˌrɛzəˈluʃən/", "qat\'iy qaror, ahd"],
        ["semester", "/səˈmɛstər/", "semestr"],
        ["typewritten", "/ˈtaɪˌprɪtən/", "terilgan, kompyuterda yozilgan"],
        ["weird", "/wɪrd/", "g\'ayrioddiy, g\'alati"],
      ]),
      unit(6, [
        ["absolute", "/ˈæbsəˌlut/", "mutlaq, to\'liq"],
        ["alas", "/əˈlæs/", "afsuski, attang"],
        ["attentive", "/əˈtɛntɪv/", "diqqatli, e\'tiborli"],
        ["cape", "/keɪp/", "nakidka, yoping\'ich"],
        ["envision", "/ɛnˈvɪʒən/", "tasavvur qilmoq, ko\'z oldiga keltirmoq"],
        ["evenly", "/ˈivənli/", "teng, bir xilda"],
        ["folk", "/foʊk/", "odamlar, yaqinlar"],
        ["melt", "/mɛlt/", "erimoq"],
        ["patch", "/pæʧ/", "yamoq, parcha hudud"],
        ["pleasure", "/ˈplɛʒər/", "rohat, mamnuniyat"],
        ["pop", "/pɑp/", "paqillagan ovoz"],
        ["pudding", "/ˈpʊdɪŋ/", "pudding, shirin desert"],
        ["rail", "/reɪl/", "panjara, tutqich"],
        ["recipe", "/ˈrɛsəpi/", "retsept"],
        ["role", "/roʊl/", "vazifa, rol"],
        ["shrink", "/ʃrɪŋk/", "kichraymoq, qisqarmoq"],
        ["soak", "/soʊk/", "ivitmoq, ho\'llamamoq"],
        ["spark", "/spɑrk/", "uchqun"],
        ["spirit", "/ˈspɪrɪt/", "ruhiyat, kayfiyat"],
        ["suit", "/sut/", "kostyum-shim"],
      ]),
      unit(7, [
        ["account", "/əˈkaʊnt/", "hisob raqami"],
        ["architect", "/ˈɑrkəˌtɛkt/", "arxitektor, me\'mor"],
        ["conceal", "/kənˈsil/", "yashirmoq, berkitmoq"],
        ["crime", "/kraɪm/", "jinoyat"],
        ["deed", "/did/", "dalolatnoma, hujjat"],
        ["gratitude", "/ˈgrætəˌtud/", "minnatdorchilik, tashakkur"],
        ["habitat", "/ˈhæbəˌtæt/", "yashash muhiti, makon"],
        ["intervene", "/ˌɪntərˈvin/", "aralashmoq, o\'rtaga tushmoq"],
        ["landmark", "/ˈlændˌmɑrk/", "mo\'ljal, orientir"],
        ["legal", "/ˈligəl/", "qonuniy"],
        ["memorable", "/ˈmɛmərəbəl/", "esda qolarli, unutilmas"],
        ["oblige", "/əˈblaɪʤ/", "majbur qilmoq"],
        ["offense", "/əˈfɛns/", "jinoyat, huquqbuzarlik"],
        ["proclaim", "/proʊˈkleɪm/", "tantanali e\'lon qilmoq"],
        ["rally", "/ˈræli/", "yig\'ilish, ralli"],
        ["resolve", "/riˈzɑlv/", "hal qilmoq, yechim topmoq"],
        ["resource", "/ˈrisɔrs/", "resurs, manba"],
        ["sentence", "/ˈsɛntəns/", "hukm, jazo"],
        ["volunteer", "/ˌvɑlənˈtɪr/", "ko\'ngilli bo\'lmoq"],
        ["witness", "/ˈwɪtnəs/", "guvoh, shohid"],
      ]),
      unit(8, [
        ["access", "/ˈækˌsɛs/", "ruxsat, kirish imkoniyati"],
        ["conduct", "/ˈkɑndəkt/", "xulq-atvor, xulq"],
        ["constant", "/ˈkɑnstənt/", "doimiy, muttasil"],
        ["crack", "/kræk/", "yoriq, darz"],
        ["device", "/dɪˈvaɪs/", "qurilma, asbob"],
        ["enclose", "/ɪnˈkloʊz/", "o\'rab olmoq, ichiga qo\'ymoq"],
        ["grip", "/grɪp/", "mahkam ushlab olmoq"],
        ["halt", "/hɔlt/", "to\'xtamoq, to\'xtatmoq"],
        ["impending", "/ˌɪmˈpɛndɪŋ/", "yaqinlashayotgan, muqarrar"],
        ["influence", "/ˈɪnfluəns/", "ta\'sir ko\'rsatmoq"],
        ["law", "/lɔ/", "qonun"],
        ["mode", "/moʊd/", "rejim, holat"],
        ["perspire", "/pərˈspaɪr/", "terlamoq"],
        ["replace", "/ˌriˈpleɪs/", "almashtirmoq, joyiga qo\'ymoq"],
        ["snap", "/snæp/", "qarsillatib sindirmoq"],
        ["sly", "/slaɪ/", "ayyor, makkor"],
        ["tend", "/tɛnd/", "moyil bo\'lmoq"],
        ["valid", "/ˈvælɪd/", "haqiqiy, asosli, yaroqli"],
        ["version", "/ˈvərʒən/", "talqin, versiya"],
        ["whatsoever", "/ˌwətsoʊˈɛvər/", "mutlaqo, umuman"],
      ]),
      unit(9, [
        ["alongside", "/əˈlɔŋˈsaɪd/", "yonma-yon, birgalikda"],
        ["appetite", "/ˈæpəˌtaɪt/", "ishtaha"],
        ["assist", "/əˈsɪst/", "yordam bermoq"],
        ["breeze", "/briz/", "shabada, salqin shamol"],
        ["defy", "/dɪˈfaɪ/", "bo\'ysunmaslik, qarshi chiqmoq"],
        ["display", "/dɪˈspleɪ/", "namoyish qilmoq, ko\'rsatmoq"],
        ["efficient", "/ɪˈfɪʃənt/", "samarali, epchil"],
        ["feeble", "/ˈfibəl/", "kuchsiz, nimjon"],
        ["forgive", "/fərˈgɪv/", "kechirmoq"],
        ["lively", "/ˈlaɪvli/", "quvnoq, jonli"],
        ["majestic", "/məˈʤɛstɪk/", "hashamatli, muhtasham"],
        ["nor", "/nɔr/", "na ... na ..."],
        ["outraged", "/ˈaʊˌtreɪʤd/", "g\'azablangan, darg\'azab"],
        ["pessimistic", "/ˌpɛsəˈmɪstɪk/", "pessimistik, tushkun"],
        ["rumor", "/ˈrumər/", "mish-mish"],
        ["slap", "/slæp/", "tarsaki tushirmoq"],
        ["smash", "/smæʃ/", "sindirmoq, parchalab tashlamoq"],
        ["subject", "/ˈsəbʤɪkt/", "fan, mavzu"],
        ["wage", "/weɪʤ/", "ish haqi, maosh"],
        ["whereas", "/wɛˈræz/", "holdatki, vaholanki"],
      ]),
      unit(10, [
        ["animate", "/ˈænəˌmeɪt/", "jonli, tirik"],
        ["classify", "/ˈklæsəˌfaɪ/", "tasniflamoq, guruhlamoq"],
        ["concede", "/kənˈsid/", "tan olmoq, yon bermoq"],
        ["concept", "/ˈkɑnsɛpt/", "tushuncha, g\'oya"],
        ["construct", "/ˈkɑnstrəkt/", "qurmoq, barpo etmoq"],
        ["decade", "/ˈdɛkeɪd/", "o\'n yillik"],
        ["diagram", "/ˈdaɪəˌgræm/", "diagramma, chizma"],
        ["ferry", "/ˈfɛri/", "parom (kema)"],
        ["handy", "/ˈhændi/", "qulay, foydali"],
        ["isolate", "/ˈaɪsəˌleɪt/", "ajratmoq, izolyatsiya qilmoq"],
        ["longing", "/ˈlɔŋɪŋ/", "kuchli xohish, mshtiyoq"],
        ["numerous", "/ˈnumərəs/", "ko\'plab, ko me\'yordagidan ko\'p"],
        ["particle", "/ˈpɑrtɪkəl/", "zarra, zarracha"],
        ["plea", "/pli/", "o\'tinch, iltijo"],
        ["refrain", "/rɪˈfreɪn/", "o\'zini tiymoq, saqlanmoq"],
        ["review", "/ˌrivˈju/", "sharh, qayta ko\'rib chiqish"],
        ["sophisticated", "/səˈfɪstɪˌkeɪtəd/", "zamonaviy, ko\'pni ko\'rgan"],
        ["surrender", "/sərˈɛndər/", "taslim bo\'lmoq, topshirmoq"],
        ["upright", "/ˈəˌpraɪt/", "tikka, tik turgan"],
        ["worthwhile", "/ˈwərθˈwaɪl/", "foydali, arzirli"],
      ]),
      unit(11, [
        ["alliance", "/əˈlaɪəns/", "ittifoq, birlashma"],
        ["applause", "/əˈplɔz/", "olqish, qarsaklar"],
        ["armed", "/ɑrmd/", "qurollangan"],
        ["authoritative", "/əˈθɔrəˌteɪtɪv/", "nufuzli, ishonchli"],
        ["ceremony", "/ˈsɛrəˌmoʊni/", "marosim, tantana"],
        ["culture", "/ˈkəlʧər/", "madaniyat"],
        ["defense", "/dɪˈfɛns/", "mudofaa, himoya"],
        ["detail", "/ˈditeɪl/", "tafsilot, detallar"],
        ["diverse", "/dɪˈvərs/", "turli xil, xilma-xil"],
        ["enchant", "/ɛnˈʧænt/", "maftun qilmoq, rom etmoq"],
        ["equip", "/ɪkˈwɪp/", "jihozlamoq, ta\'minlamoq"],
        ["exception", "/ɪkˈsɛpʃən/", "istisno"],
        ["genre", "/ˈʒɑnrə/", "janr"],
        ["impact", "/ˌɪmˈpækt/", "ta\'sir, zarba"],
        ["lure", "/lʊr/", "yo\'ldan urmoq, jalb qilmoq"],
        ["obstacle", "/ˈɑbstəkəl/", "to\'siq, g\'ov"],
        ["shelter", "/ˈʃɛltər/", "boshpana, pana joy"],
        ["sort", "/sɔrt/", "saralamoq, ajratmoq"],
        ["supply", "/səˈplaɪ/", "ta\'minlamoq, yetkazmoq"],
        ["vain", "/veɪn/", "kekkaygan, manman"],
      ]),
      unit(12, [
        ["alternative", "/ɔlˈtərnətɪv/", "muqobil, boshqa yo\'l"],
        ["avenue", "/ˈævəˌnu/", "shoh ko\'cha, prospekt"],
        ["belly", "/ˈbɛli/", "qorin"],
        ["bid", "/bɪd/", "harakat, urinish, taklif"],
        ["blow", "/bloʊ/", "esmoq (shamol)"],
        ["conflict", "/ˈkɑnflɪkt/", "nizo, mojaro"],
        ["continent", "/ˈkɑntənənt/", "qit\'a, materik"],
        ["current", "/ˈkɑrənt/", "oqim (suv/havo)"],
        ["disrespect", "/ˌdɪsrɪˈspɛkt/", "hurmatsizlik"],
        ["enthusiasm", "/ɪnˈθuziˌæzəm/", "ishtiyoq, g\'ayrat"],
        ["harsh", "/hɑrʃ/", "yoqimsiz, qattiq, shafqatsiz"],
        ["lean", "/lin/", "suyanmoq, egilmoq"],
        ["meantime", "/ˈminˌtaɪm/", "shu orada, orada"],
        ["mischief", "/ˈmɪsʧəf/", "sho\'xlik, sho\'xlik qilmoq"],
        ["muscle", "/ˈməsəl/", "mushak, muskul"],
        ["rescue", "/ˈrɛskju/", "qutqarmoq"],
        ["succession", "/səkˈsɛʃən/", "ketma-ketlik, ketma-ketlikda"],
        ["terrain", "/təreɪn/", "relef, yer maydoni"],
        ["timid", "/ˈtɪmɪd/", "qo\'rqoq, tortinchoq"],
        ["violence", "/ˈvaɪələns/", "zo\'ravonlik"],
      ]),
      unit(13, [
        ["affect", "/əˈfɛkt/", "ta\'sir qilmoq"],
        ["autograph", "/ˈɔtəˌgræf/", "dastxat, imzo"],
        ["bead", "/bid/", "tomchi, munchoq"],
        ["brew", "/bru/", "damlamoq (choy/kofe)"],
        ["charm", "/ʧɑrm/", "rom etmoq, maftun qilmoq"],
        ["destiny", "/ˈdɛstəni/", "taqdir, qismat"],
        ["horn", "/hɔrn/", "signal, muguz"],
        ["irritable", "/ˈɪrətəbəl/", "jizzaki, jahli tez"],
        ["lag", "/læg/", "orqada qolmoq"],
        ["maximize", "/ˈmæksəˌmaɪz/", "maksimallashtirmoq"],
        ["nightmare", "/ˈnaɪtˌmɛr/", "yomon tush, daxshatli tush"],
        ["nutritious", "/nuˈtrɪʃəs/", "to me\'yorli, oziqli"],
        ["protein", "/ˈproʊˌtin/", "oqsil, belok"],
        ["signature", "/ˈsɪgnəʧər/", "imzo"],
        ["stuff", "/stəf/", "narsa-buyumlar"],
        ["subconscious", "/səbˈkɑnʃəs/", "beixtiyor, ostki shuuriy"],
        ["van", "/væn/", "furgon avtomobil"],
        ["warn", "/wɔrn/", "ogohlantirmoq"],
        ["workout", "/ˈwərˌkaʊt/", "jismoniy mashg\'ulot"],
        ["zoom", "/zum/", "tez harakatlanmoq, uchmoq"],
      ]),
      unit(14, [
        ["brick", "/brɪk/", "g\'isht"],
        ["crumble", "/ˈkrəmbəl/", "maydalanmoq, uvalanmoq"],
        ["dough", "/doʊ/", "xamir"],
        ["express", "/ɪkˈsprɛs/", "ifodalamoq, izhor qilmoq"],
        ["fist", "/fɪst/", "musht"],
        ["flexible", "/ˈflɛksəbəl/", "egiluvchan, moslashuvchan"],
        ["flush", "/fləʃ/", "yuzi qizarmoq"],
        ["injure", "/ˈɪnʤər/", "jarohatlamoq, zararlamoq"],
        ["lump", "/ləmp/", "bo\'lak, guvala"],
        ["mixture", "/ˈmɪksʧər/", "qorishma, aralashma"],
        ["reconcile", "/ˈrɛkənˌsaɪl/", "yarashmoq, kelishmoq"],
        ["ruin", "/ruɪn/", "rasvo qilmoq, buzmoq"],
        ["shatter", "/ˈʃætər/", "chilparchin qilmoq"],
        ["shutter", "/ˈʃətər/", "deraza panjarasi/eshikchasi"],
        ["sift", "/sɪft/", "elamoq"],
        ["slight", "/slaɪt/", "ozgina, kichik"],
        ["sparkle", "/ˈspɑrkəl/", "porlamoq, porillamoq"],
        ["sprinkle", "/ˈsprɪŋkəl/", "sepmoq, purkamoq"],
        ["stale", "/steɪl/", "aynigan, qotgan (non)"],
        ["utter", "/ˈətər/", "aytmoq, demoq"],
      ]),
      unit(15, [
        ["although", "/ˌɔlˈðoʊ/", "garchi, ...sa ham"],
        ["apply", "/əˈplaɪ/", "surtmoq, qo\'llamoq"],
        ["await", "/əˈweɪt/", "kutmoq"],
        ["beloved", "/bɪˈləvəd/", "sevimli, suyukli"],
        ["bury", "/ˈbɛri/", "ko\'mmoq, dafn etmoq"],
        ["climate", "/ˈklaɪmɪt/", "iqlim"],
        ["complain", "/kəmˈpleɪn/", "shikoyat qilmoq"],
        ["confuse", "/kənfˈjuz/", "adashtirmoq, chalg\'itmoq"],
        ["due", "/du/", "kutilayotgan, bajarilishi kerak"],
        ["entire", "/ɪnˈtaɪər/", "butun, to\'liq"],
        ["establish", "/ɪˈstæblɪʃ/", "tashkil etmoq, asos solmoq"],
        ["furnace", "/ˈfərnəs/", "pech, gorn"],
        ["leash", "/liʃ/", "jilov, ip (it uchun)"],
        ["mature", "/məˈʧʊr/", "ulg\'aymoq, yetilmoq"],
        ["measure", "/ˈmɛʒər/", "o\'lchamoq"],
        ["midst", "/mɪst/", "o\'rtasi, markazi"],
        ["misery", "/ˈmɪzəri/", "baxtsizlik, azob"],
        ["prior", "/praɪər/", "avvalgi, oldingi"],
        ["research", "/ˈrisərʧ/", "tadqiqot, izlanish"],
        ["variety", "/vərˈaɪəti/", "xilma-xillik, turli xillik"],
      ]),
      unit(16, [
        ["altogether", "/ˌɔltəˈgɛðər/", "butunlay, to\'liq"],
        ["bind", "/baɪnd/", "bog\'lamoq, birlashtirmoq"],
        ["bruise", "/bruz/", "ko\'kargan joy, jarohat"],
        ["custom", "/ˈkəstəm/", "urf-odat, an\'ana"],
        ["disobedient", "/ˌdɪsəˈbidiənt/", "bo\'ysunmas, qaysar"],
        ["foresee", "/fɔrˈsi/", "oldindan ko\'ra bilmoq"],
        ["glimpse", "/glɪmps/", "ko\'zi tushib qolmoq"],
        ["hoop", "/hup/", "halqa, halqacha"],
        ["misfortune", "/mɪsˈfɔrʧən/", "omadsizlik, baxtsizlik"],
        ["negative", "/ˈnɛgətɪv/", "salbiy, salbiy bo\'lgan"],
        ["per", "/pər/", "har biriga"],
        ["plead", "/plid/", "o\'tinib so\'ramoq, yolvormoq"],
        ["rip", "/rɪp/", "yirtmoq"],
        ["sake", "/seɪk/", "haqida, hurmati uchun"],
        ["scrape", "/skreɪp/", "shilinmoq, qirmoq"],
        ["source", "/sɔrs/", "manba, kelib chiqish joyi"],
        ["stern", "/stərn/", "qattiqqo\'l, jiddiy"],
        ["stitch", "/stɪʧ/", "tikmoq, chok tushirmoq"],
        ["thump", "/θəmp/", "duppillagan ovoz"],
        ["vehement", "/ˈviəmənt/", "darg\'azab, jo\'shqin"],
      ]),
      unit(17, [
        ["civilization", "/ˌsɪvəlɪˈzeɪʃən/", "sivilizatsiya, madaniyat"],
        ["convenient", "/kənˈvinjənt/", "qulay, oson"],
        ["den", "/dɛn/", "in, uy (hayvonlar uchun)"],
        ["dew", "/du/", "shabnam"],
        ["drastic", "/ˈdræstɪk/", "keskin, jiddiy"],
        ["exit", "/ˈɛksət/", "chiqib ketmoq"],
        ["flock", "/flɑk/", "poda, gala"],
        ["fold", "/foʊld/", "taxlamoq, buklamoq"],
        ["lid", "/lɪd/", "qopqoq"],
        ["loom", "/lum/", "xavf solmoq, ko\'rinmoq"],
        ["mighty", "/ˈmaɪti/", "qudratli, ulkan"],
        ["mushroom", "/ˈməʃrum/", "qo\'ziqorin"],
        ["native", "/ˈneɪtɪv/", "mahalliy, tub"],
        ["poison", "/ˈpɔɪzən/", "zahar"],
        ["reed", "/rid/", "qamish"],
        ["shield", "/ʃild/", "himoya qilmoq, qalqon bo\'lmoq"],
        ["stormy", "/ˈstɔrmi/", "bo\'ronli, dovulli"],
        ["sway", "/sweɪ/", "tebranmoq, chayqalmoq"],
        ["urban", "/ˈərbən/", "shahar, shaharga oid"],
        ["wade", "/weɪd/", "suv kechib yurmoq"],
      ]),
      unit(18, [
        ["accent", "/ˈækˌsɛnt/", "aktsent, sheva"],
        ["barber", "/ˈbɑrbər/", "sartarosh"],
        ["basement", "/ˈbeɪsmənt/", "to\'la, zirzamida"],
        ["blank", "/blæŋk/", "bo\'sh, yozilmagan"],
        ["blink", "/blɪŋk/", "ko\'z qirpmog\'"],
        ["choir", "/kwaɪər/", "xor (ashula guruhi)"],
        ["comic", "/ˈkɑmɪk/", "kulgili, komik"],
        ["complicate", "/ˈkɑmpləˌkeɪt/", "murakkablashtirmoq"],
        ["decline", "/dɪˈklaɪn/", "rad etmoq, yo\'q demoq"],
        ["errand", "/ˈɛrənd/", "mayda topshiriq, yumush"],
        ["glove", "/gləv/", "qo\'lqop"],
        ["hermit", "/ˈhərmət/", "tarki dunyo qilgan kishi"],
        ["justly", "/ˈʤəstli/", "odoban, adolat bilan"],
        ["leather", "/ˈlɛðər/", "charm, teri"],
        ["ponder", "/ˈpɑndər/", "o\'ylab ko\'rmoq, fikr yuritmoq"],
        ["reserve", "/rɪˈzərv/", "olib qo\'ymoq, band qilmoq"],
        ["script", "/skrɪpt/", "stsennariy, matn"],
        ["search", "/sərʧ/", "qidirmoq, izlamoq"],
        ["slam", "/slæm/", "qarsillatib yopmoq"],
        ["staircase", "/ˈstɛrˌkeɪs/", "zinapoya"],
      ]),
      unit(19, [
        ["afflicted", "/əˈflɪktɪd/", "qiynalgan, azoblangan"],
        ["aisle", "/aɪəl/", "yo\'lak (o\'rindiqlar orasi)"],
        ["atmosphere", "/ˈætməsˌfɪr/", "atmosfera, havo"],
        ["author", "/ˈɔθər/", "muallif, yozuvchi"],
        ["breakdown", "/ˈbreɪkˌdaʊn/", "buzuqlik, ishdan chiqish"],
        ["cargo", "/ˈkɑrˌgoʊ/", "yuk (kema/samolyot)"],
        ["chapter", "/ˈʧæptər/", "bob, qism"],
        ["connect", "/kəˈnɛkt/", "ulamoq, bog\'lamoq"],
        ["etc.", "/ˌɛtˈsɛtərə./", "va hokazo"],
        ["flip", "/flɪp/", "chertmoq, tugmani bosmoq"],
        ["idle", "/ˈaɪdəl/", "bekorchi, ish qilmayotgan"],
        ["notify", "/ˈnoʊtəˌfaɪ/", "xabar qilmoq, bildirmoq"],
        ["pea", "/pi/", "no\'xat"],
        ["raisin", "/ˈreɪzɪn/", "mayiz"],
        ["retain", "/rɪˈteɪn/", "saqlab qolmoq"],
        ["state", "/steɪt/", "ta\'kidlamoq, aytmoq"],
        ["tray", "/treɪ/", "patnis"],
        ["unfortunate", "/ənˈfɔrʧənət/", "omadsiz, ko\'ngilsiz"],
        ["vivid", "/ˈvɪvɪd/", "yorqin, aniq"],
        ["vomit", "/ˈvɑmət/", "qusmoq"],
      ]),
      unit(20, [
        ["betray", "/bɪˈtreɪ/", "xiyonat qilmoq"],
        ["blast", "/blæst/", "portlash, shiddatli ovoz"],
        ["bracelet", "/ˈbreɪslət/", "bilaguzuk"],
        ["cease", "/sis/", "to\'xtamoq"],
        ["choke", "/ʧoʊk/", "bo\'g\'ilmoq, tiqilmoq"],
        ["civil", "/ˈsɪvəl/", "fuqarolik, ichki"],
        ["comment", "/ˈkɑmɛnt/", "fikr bildirmoq"],
        ["cross", "/krɔs/", "kesib o\'tmoq"],
        ["dent", "/dɛnt/", "pachoqlangan joy, pachoqlik"],
        ["distrust", "/dɪˈstrəst/", "ishonmaslik"],
        ["fort", "/fɔrt/", "qal\'a, fort"],
        ["found", "/faʊnd/", "tashkil etmoq, asos solmoq"],
        ["lining", "/ˈlaɪnɪŋ/", "ichki astar (kiim)"],
        ["mass", "/mæs/", "ko\'pchilik, omma"],
        ["pray", "/preɪ/", "duo qilmoq, ibodat qilmoq"],
        ["rife", "/raɪf/", "keng tarqalgan, ko\'p"],
        ["sole", "/soʊl/", "yagona, yolg\'iz"],
        ["sweep", "/swip/", "supurmoq"],
        ["treachery", "/ˈtrɛʧəri/", "xiyonat, sotqinlik"],
        ["tuck", "/tək/", "tqib qo\'ymoq, kirgizib qo\'ymoq"],
      ]),
      unit(21, [
        ["background", "/ˈbækˌgraʊnd/", "ma\'lumot, kelib chiqish"],
        ["bait", "/beɪt/", "xo\'rak, masal"],
        ["chronicle", "/ˈkrɑnɪkəl/", "xronika qilmoq, yozib bormoq"],
        ["copper", "/ˈkɑpər/", "mis (metall)"],
        ["disease", "/dɪˈziz/", "kasaIlik, xastalik"],
        ["folklore", "/ˈfoʊˌklɔr/", "folklor, xalq og\'zaki ijodi"],
        ["infect", "/ˌɪnˈfɛkt/", "yuqtirmoq, yuqmoq"],
        ["itch", "/ɪʧ/", "qichimoq"],
        ["literature", "/ˈlɪtərəʧər/", "adabiyot"],
        ["millennium", "/məˈlɛniəm/", "ming yillik"],
        ["myth", "/mɪθ/", "afsona, mif"],
        ["promote", "/prəˈmoʊt/", "lavozimini oshirmoq, targ\'ib qilmoq"],
        ["relate", "/rɪˈleɪt/", "bog me\'yorida bo\'lmoq, aloqador bo\'lmoq"],
        ["religion", "/rɪˈlɪʤən/", "din, e\'tiqod"],
        ["sum", "/səm/", "summa, jami miqdor"],
        ["teller", "/ˈtɛlər/", "kassir (bankda)"],
        ["trustworthy", "/ˈtrəstˌwərði/", "ishonchli"],
        ["update", "/ˈəpˌdeɪt/", "yangilamoq"],
        ["vein", "/veɪn/", "vena, qon tomiri"],
        ["venom", "/ˈvɛnəm/", "zahar (hayvonlar)"],
      ]),
      unit(22, [
        ["charity", "/ˈʧɛrɪti/", "xayriya, ehson"],
        ["commerce", "/ˈkɑmərs/", "tijorat, savdo"],
        ["condemn", "/kənˈdɛm/", "hukm qilmoq, ayblamoq"],
        ["cozy", "/ˈkoʊzi/", "shinam, issiq"],
        ["deplete", "/dɪˈplit/", "tugatmoq, tugatib qo\'ymoq"],
        ["economy", "/ɪˈkɑnəmi/", "iqtisodiyot"],
        ["empire", "/ˈɛmpaɪər/", "imperiya"],
        ["goods", "/gʊdz/", "tovar, mahsulotlar"],
        ["heed", "/hid/", "quloq solmoq, bo\'ysunmoq"],
        ["hitchhike", "/ˈhɪˌʧhaɪk/", "yo\'lovchi mashinada tekinga yurmoq"],
        ["mock", "/mɑk/", "masxara qilmoq"],
        ["neutral", "/ˈnutrəl/", "betaraf"],
        ["persecute", "/ˈpərsəˌkjut/", "ta\'qib qilmoq, qiynamoq"],
        ["pity", "/ˈpɪti/", "rahmdillik, achinish"],
        ["reduce", "/rɪˈdus/", "kamaytirmoq"],
        ["scribe", "/skraɪb/", "xatitib, mirza"],
        ["temper", "/ˈtɛmpər/", "jahldorlik, kayfiyat"],
        ["throne", "/θroʊn/", "taxt"],
        ["unity", "/ˈjunɪti/", "birlik, hamjihatlik"],
        ["victor", "/ˈvɪktər/", "g\'olib"],
      ]),
      unit(23, [
        ["accurate", "/ˈækjərət/", "aniq, to\'g\'ri"],
        ["analyze", "/ˈænəˌlaɪz/", "tahlil qilmoq"],
        ["asteroid", "/ˈæstərˌɔɪd/", "asteroid"],
        ["controversy", "/ˈkɑntrəˌvərsi/", "bahs-munozara, nizo"],
        ["evolve", "/ɪˈvɑlv/", "rivojlanmoq, o\'smoq"],
        ["factor", "/ˈfæktər/", "omil, faktor"],
        ["genetic", "/ʤəˈnɛtɪk/", "genetik"],
        ["genome", "/ˈʤiˌnoʊm/", "genom"],
        ["identical", "/aɪˈdɛntɪkəl/", "bir xil, birday"],
        ["intellectual", "/ˌɪnəˈlɛkʧuəl/", "ziyoli, aqlli kishi"],
        ["majority", "/məˈʤɔrəti/", "ko\'pchilik, ko\'p qismi"],
        ["mammal", "/ˈmæməl/", "sutemizuvchi hayvon"],
        ["multiply", "/ˈməltəˌplaɪ/", "ko\'paymoq"],
        ["offspring", "/ˈɔfˌsprɪŋ/", "nasl, farzand, hayvon bolasi"],
        ["pesticide", "/ˈpɛstəˌsaɪd/", "pesticid, zaharli dori"],
        ["regulate", "/ˈrɛgjəˌleɪt/", "tartibga solmoq, boshqarmoq"],
        ["reinforce", "/ˌriɪnˈfɔrs/", "mustahkamlamoq, kuchaytirmoq"],
        ["stricken", "/ˈstrɪkən/", "qattiq ta\'sirlangan, kasallikka uchragan"],
        ["vast", "/væst/", "juda keng, ulkan"],
        ["vegetarian", "/ˌvɛʤəˈtɛˌriən/", "vegetariyan, go\'sht yemaydigan"],
      ]),
      unit(24, [
        ["cherish", "/ˈʧɛrɪʃ/", "qadrlamoq, ezozlamoq"],
        ["compassion", "/kəmˈpæʃən/", "hamdardlik, achinish"],
        ["consent", "/kənˈsɛnt/", "rozilik, ruxsat"],
        ["core", "/kɔr/", "o\'zak, markaz"],
        ["cunning", "/ˈkənɪŋ/", "makkor, ayyor"],
        ["dizzy", "/ˈdɪzi/", "boshi aylanayotgan"],
        ["equilibrium", "/ˌikwəˈlɪbriəm/", "muvozanat"],
        ["foster", "/ˈfɑstər/", "rivojlantirmoq, tarbiyalamoq"],
        ["grind", "/graɪnd/", "maydalamoq, uvalamoq"],
        ["growl", "/graʊl/", "irillamoq (hayvon)"],
        ["moderation", "/ˌmɑdərˈeɪʃən/", "me\'yor, mo\'tadillik"],
        ["predator", "/ˈprɛdətər/", "yirtqich hayvon"],
        ["sane", "/seɪn/", "sog\'lom fikrli"],
        ["saucer", "/ˈsɔsər/", "likopcha (finjon ostidagi)"],
        ["snatch", "/snæʧ/", "tortib olmoq, yulqib olmoq"],
        ["stagger", "/ˈstægər/", "gandiraklamoq"],
        ["stumble", "/ˈstəmbəl/", "qoqilib ketmoq"],
        ["tense", "/tɛns/", "tarang, xavotirlangan"],
        ["tumble", "/ˈtəmbəl/", "dumalab tushmoq"],
        ["withhold", "/wɪθˈhoʊld/", "bermay turmoq, ushlab turmoq"],
      ]),
      unit(25, [
        ["aircraft", "/ˈɛrˌkræft/", "samolyot, uchish apparati"],
        ["celebrity", "/səˈlɛbrɪti/", "mashhur shaxs"],
        ["concrete", "/ˈkɑnkrit/", "beton"],
        ["decisive", "/dɪˈsaɪsɪv/", "qat\'iyatli, keskin"],
        ["esteemed", "/ɛˈstimd/", "hurmatli, e\'tiborli"],
        ["ethical", "/ˈɛθɪkəl/", "axloqiy, to\'g\'ri"],
        ["extinct", "/ɪkˈstɪŋkt/", "yo\'qolib ketgan (tur)"],
        ["hardy", "/ˈhɑrdi/", "chidamli, chidamkor"],
        ["institute", "/ˈɪnstɪˌtut/", "institut, tashkilot"],
        ["jealousy", "/ˈʤɛləsi/", "hasad, rashk"],
        ["migrate", "/ˈmaɪˌgreɪt/", "ko\'chib o\'tmoq (qushlar/odamlar)"],
        ["nurture", "/ˈnərʧər/", "parvarish qilmoq, o\'stirmoq"],
        ["overhead", "/ˈoʊvərˈhɛd/", "tepada, tepadan"],
        ["principle", "/ˈprɪnsəpəl/", "tamoyil, qoida"],
        ["rural", "/ˈrʊrəl/", "qishloq, qishloqqa oid"],
        ["secluded", "/sɪˈkludɪd/", "kimsasiz, xoli"],
        ["species", "/ˈspiʃiz/", "turlar, tur"],
        ["swamp", "/swɔmp/", "botqoqlik"],
        ["traverse", "/ˈtrævərs/", "kesib o\'tmoq, bosib o\'tmoq"],
        ["zoology", "/zoʊˈɑləʤi/", "zoologiya"],
      ]),
      unit(26, [
        ["assumption", "/əˈsəmpʃən/", "faraz, taxmin"],
        ["barley", "/ˈbɑrli/", "arpa"],
        ["beast", "/bist/", "yirtqich, ulkan hayvon"],
        ["colonel", "/ˈkərnəl/", "polkovnik"],
        ["contagious", "/kənˈteɪʤəs/", "yuqumli (kasallik)"],
        ["corpse", "/kɔrps/", "murdani, jasadi"],
        ["crisis", "/ˈkraɪsəs/", "krizis, inqiroz"],
        ["cure", "/kjʊr/", "davolamoq"],
        ["deformed", "/dɪˈfɔrmd/", "xunuk shaklli, nogiron"],
        ["discriminate", "/dɪˈskrɪməˌneɪt/", "kamsitmoq, ajratmoq"],
        ["embassy", "/ˈɛmbəsi/", "elchixona"],
        ["extinguish", "/ɪkˈstɪŋgwɪʃ/", "o\'chirmoq (olovni)"],
        ["flint", "/flɪnt/", "chaqmoqtosh"],
        ["harass", "/həræs/", "g\'ashiga tegmoq, bezovta qilmoq"],
        ["integrate", "/ˈɪnəˌgreɪt/", "qo me\'yorlashmoq, aralashmoq"],
        ["miniature", "/ˈmɪnɪˌʧʊr/", "juda kichik, miniatyura"],
        ["nutrition", "/nuˈtrɪʃən/", "ovqatlanish, oziqlanish"],
        ["promptly", "/ˈprɑmptli/", "zudlik bilan, vaqtida"],
        ["technician", "/tɛkˈnɪʃən/", "texnik, usta"],
        ["tropics", "/ˈtrɑpɪks/", "tropik hududlar"],
      ]),
      unit(27, [
        ["beneficial", "/ˌbɛnəˈfɪʃəl/", "foydali"],
        ["birthplace", "/ˈbərθˌpleɪs/", "tug\'ilgan joy"],
        ["capacity", "/kəˈpæsɪti/", "sig\'im, hajm"],
        ["comparative", "/kəmˈpærətɪv/", "qiyosiy"],
        ["comprehensive", "/ˌkɑmpriˈhɛnsɪv/", "har tomonlama, batafsil"],
        ["conserve", "/kənˈsərv/", "asrash, saqlash"],
        ["crucial", "/ˈkruʃəl/", "juda muhim, hal qiluvchi"],
        ["cumulative", "/ˈkjumjələtɪv/", "yig\'ilib boruvchi"],
        ["deposit", "/dɪˈpɑzət/", "qo\'ymoq, joylashtirmoq"],
        ["distribute", "/dɪˈstrɪbjut/", "tarqatmoq"],
        ["equator", "/ɪkˈweɪtər/", "ekvator"],
        ["exotic", "/ɪgˈzɑtɪk/", "ekzotik, g\'ayrioddiy"],
        ["federal", "/ˈfɛdərəl/", "federal, davlatga oid"],
        ["formation", "/fɔrˈmeɪʃən/", "shakllanish, hosil bo\'lish"],
        ["frequency", "/ˈfrikwənsi/", "chastota, takrorlanish"],
        ["objective", "/əˈbʤɛktɪv/", "maqsad, vazifa"],
        ["oxygen", "/ˈɑksɪʤən/", "kislorod"],
        ["rainforest", "/ˈraɪnˌfɔrəst/", "tropik o\'rmon"],
        ["strategy", "/ˈstrætəʤi/", "strategiya, reja"],
        ["wooded", "/ˈwʊdɪd/", "daraxtzor, o\'rmonli"],
      ]),
      unit(28, [
        ["avail", "/əˈveɪl/", "yordam, foyda (to no avail)"],
        ["expand", "/ɪkˈspænd/", "kengaymoq, kattalashmoq"],
        ["define", "/dɪˈfaɪn/", "ta\'riflamoq, tushuntirmoq"],
        ["dread", "/drɛd/", "qo\'rqmoq, daxshatga tushmoq"],
        ["fundamental", "/ˌfəndəˈmɛnəl/", "asosiy, fundamental"],
        ["horrifying", "/ˈhɔrəˌfaɪɪŋ/", "dahshatli, qo\'rqinchli"],
        ["incredulous", "/ˌɪnˈkrɛʤələs/", "ishonmaydigan, shubhalanuvchi"],
        ["linger", "/ˈlɪŋər/", "uzoqlashmay turmoq, qolib ketmoq"],
        ["organism", "/ˈɔrgəˌnɪzəm/", "organizm, tirik mavjudot"],
        ["paraphrase", "/ˈpɛrəˌfreɪz/", "qisqacha qayta ifodalamoq"],
        ["plague", "/pleɪg/", "o\'lat, yuqumli kasallik"],
        ["presently", "/ˈprɛzəntli/", "hozirgi vaqtda"],
        ["random", "/ˈrændəm/", "tasodifiy"],
        ["riot", "/raɪət/", "g\'alayon, to\'polon"],
        ["scribble", "/ˈskrɪbəl/", "shoshilib yozib qo\'ymoq"],
        ["shrine", "/ʃraɪn/", "ziyoratgoh, ibodatxona"],
        ["solitude", "/ˈsɑləˌtud/", "yolg\'izlik"],
        ["stark", "/stɑrk/", "yaqqol, keskin"],
        ["summon", "/ˈsəmən/", "chaqirmoq"],
        ["worsen", "/ˈwərsən/", "yomonlashmoq"],
      ]),
      unit(29, [
        ["automobile", "/ˌɔtəmoʊˈbil/", "avtomobil, mashina"],
        ["candidate", "/ˈkænədɪt/", "nomzod"],
        ["confidential", "/ˌkɑnfəˈdɛnʃəl/", "maxfiy, sirli"],
        ["corporate", "/ˈkɔrpərət/", "korporativ, kompaniyaning"],
        ["enhance", "/ɛnˈhæns/", "yaxshilamoq, oshirmoq"],
        ["era", "/ˈɪrə/", "era, davr"],
        ["guideline", "/ˈgaɪˌdlaɪn/", "yo\'riqnoma, qoida"],
        ["incorporate", "/ˌɪnˈkɔrpərˌeɪt/", "qo\'shmoq, kiritmoq"],
        ["interact", "/ˌɪnərˈækt/", "muloqot qilmoq, o\'zaro ta\'sirlashmoq"],
        ["interval", "/ˈɪntərvəl/", "oraliq vaqt, tanaffus"],
        ["mobile", "/ˈmoʊbəl/", "harakatlanuvchi, ko\'chma"],
        ["modify", "/ˈmɑdəˌfaɪ/", "o\'zgartirmoq, tuzatmoq"],
        ["parallel", "/ˈpɛrəˌlɛl/", "parallel"],
        ["phenomenon", "/fəˈnɑməˌnɑn/", "hodisa, fenomen"],
        ["pollute", "/pəˈlut/", "ifloslantirmoq"],
        ["ridicule", "/ˈrɪdəˌkjul/", "ustidan kulmoq, masxara qilmoq"],
        ["solar", "/ˈsoʊlər/", "quyoshga oid"],
        ["territory", "/ˈtɛrɪˌtɔri/", "hudud, hududlar"],
        ["tournament", "/ˈtʊrnəmənt/", "turnir, musobaqa"],
        ["transportation", "/ˌtrænspərˈteɪʃən/", "transport, tashish"],
      ]),
      unit(30, [
        ["bill", "/bɪl/", "hisob-kitob qog\'ozi, chek"],
        ["boundary", "/ˈbaʊndəri/", "chegara, cheklanish yo\'li"],
        ["chaos", "/keɪɑs/", "tartibsizlik, tartibsiz holat"],
        ["consistent", "/kənˈsɪstənt/", "barqaror, bir xil"],
        ["cyclone", "/sɪˈkloʊn/", "siklon, kuchli bo\'ron"],
        ["doomed", "/dumd/", "muqarrar mag\'lubiyatga uchragan"],
        ["heir", "/ɛr/", "merosxo\'r"],
        ["martial", "/ˈmɑrʃəl/", "harbiy, jangovar"],
        ["organic", "/ɔrˈgænɪk/", "organik, tabiiy"],
        ["poultry", "/ˈpoʊltri/", "parrandachilik, parranda go\'shti"],
        ["scramble", "/ˈskræmbəl/", "shoshilinch harakat qilmoq"],
        ["sergeant", "/ˈsɑrʤənt/", "serjant"],
        ["sheer", "/ʃɪr/", "mutlaq, ulkan"],
        ["stance", "/stæns/", "pozitsiya, nuqtayi nazar"],
        ["telegraph", "/ˈtɛləˌgræf/", "telegraf"],
        ["textile", "/ˈtɛkˌstaɪl/", "to\'qimachilik, mato"],
        ["tornado", "/tɔrˈneɪˌdoʊ/", "tornado, quyun"],
        ["typhoon", "/ˌtaɪˈfun/", "tayfun, bo\'ron"],
        ["wail", "/weɪl/", "faryod chekmoq, yig\'lamoq"],
        ["wardrobe", "/ˈwɔrˌdroʊb/", "garderob, kiyimlar jamlanmasi"],
      ]),
    ],

};
