import { Book, createUnit as unit } from "../book-types";

export const essential5: Book = {

    id: "4eew5",
    title: "4000 Essential English Words 5",
    subtitle: "Book 5",
    totalUnits: 30,
    units: [
      unit(1, [
        ["allot", "/əˈlɑt/", "bermoq, ajratmoq"],
        ["appall", "/əˈpɔl/", "qo\'rqitmoq, daxshatga solmoq"],
        ["cache", "/kæˈʃeɪ/", "maxfiy joy, xazina joyi"],
        ["convenience", "/kənˈvinjəns/", "qulaylik"],
        ["dearth", "/dərθ/", "tanqislik, yetishmovchilik"],
        ["deliberate", "/dɪˈlɪbərˌeɪt/", "rejalashtirilgan, rejali"],
        ["dire", "/daɪər/", "qo\'rqinchli, daxshatli"],
        ["elapse", "/ɪˈlæps/", "o\'tmoq, o\'tib ketmoq (vaqt)"],
        ["empathy", "/ˈɛmpəθi/", "hamdardlik, his-tuyg\'uni tushunish"],
        ["fanciful", "/ˈfænsɪfəl/", "g\'alati, antiqa, xayoliy"],
        ["gripe", "/graɪp/", "tinmay nolimoq, shikoyat qilmoq"],
        ["grueling", "/ˈgruɪlɪŋ/", "sermashaqqat, juda og\'ir"],
        ["mundane", "/mənˈdeɪn/", "zerikarli, maroqsiz, oddiy"],
        ["opt", "/ɑpt/", "tanlamoq, qaror qilmoq"],
        ["outrage", "/ˈaʊˌtreɪʤ/", "darg\'azablik, g\'azab"],
        ["paltry", "/ˈpɔltri/", "arzimagan, cuxat"],
        ["rectify", "/ˈrɛktəˌfaɪ/", "xatoni to\'g\'rilamoq, tuzatmoq"],
        ["resourceful", "/riˈsɔrsfəl/", "ijodkor, uddaburon"],
        ["sustenance", "/ˈsəstənəns/", "oziq, yemish"],
        ["tedious", "/ˈtidiəs/", "zerikarli, joniga tegadigan"],
      ]),
      unit(2, [
        ["abbey", "/ˈæbi/", "abbatlik, monastir"],
        ["abundant", "/əˈbəndənt/", "mo\'l, serob"],
        ["adjoin", "/əˈʤɔɪn/", "yonma-yon bo\'lmoq, tutashmoq"],
        ["ample", "/ˈæmpəl/", "yetarli, ko\'p"],
        ["arid", "/ˈɛrəd/", "juda quruq, kam yog\'in"],
        ["cathedral", "/kəˈθidrəl/", "bosh cherkov, sobor"],
        ["deprive", "/dɪˈpraɪv/", "mahrum etmoq"],
        ["drought", "/draʊt/", "qurg\'oqchilik"],
        ["eligible", "/ˈɛlɪʤəbəl/", "haqli, huquqli, munosib"],
        ["fast", "/fæst/", "ro\'za tutmoq"],
        ["grumble", "/ˈgrəmbəl/", "javramoq, vaysamoq"],
        ["inland", "/ˈɪnˌlænd/", "mamlakat ichkarisiga/markaziga"],
        ["moisture", "/ˈmɔɪsʧər/", "namlik"],
        ["nonetheless", "/ˌnənðəˈlɛs/", "shunga qaramay, shunday bo\'lsa ham"],
        ["oath", "/oʊθ/", "qasam, ont"],
        ["prairie", "/ˈprɛri/", "dash, yovon"],
        ["ragged", "/ˈrægəd/", "eski, juldurvaqa"],
        ["rugged", "/ˈrəgəd/", "g\'adir-budur, dag\'al, qoya sifat"],
        ["scarce", "/skɛrs/", "tanqis, taqchil"],
        ["speculate", "/ˈspɛkjəˌleɪt/", "taxmin qilmoq, o\'ylab ko\'rmoq"],
      ]),
      unit(3, [
        ["analytic", "/ˌænəˈlɪtɪk/", "tahliliy, mantiqiy"],
        ["assert", "/əˈsərt/", "tasdiqlamoq, kat\'iy aytmoq"],
        ["bachelor", "/ˈbæʧələr/", "bo\'ydoq"],
        ["calculus", "/ˈkælkjələs/", "hisob-kitob, kalkulyus"],
        ["celestial", "/səˈlɛsʧəl/", "osmoniy, koinotga oid"],
        ["cognitive", "/ˈkɑgnɪtɪv/", "bilish, anglashga oid"],
        ["collision", "/kəˈlɪʒən/", "to\'qnashuv, urilish"],
        ["competent", "/ˈkɑmpətɪnt/", "puxta bilimli, malakali"],
        ["diploma", "/dɪˈploʊmɑ/", "diplom"],
        ["excel", "/ɪkˈsɛl/", "zo\'r bo\'lmoq, ustun bo\'lmoq"],
        ["geology", "/ʤiˈɑləʤi/", "geologiya"],
        ["harness", "/ˈhɑrnɪs/", "jilovlamoq, energiyadan foydalanmoq"],
        ["intellect", "/ˈɪnəˌlɛkt/", "intellekt, idrok"],
        ["keen", "/kin/", "aqlli, o\'tkir, zukkog\'"],
        ["mythology", "/məˈθɑləˌʤi/", "mifologiya"],
        ["physiology", "/ˌfɪziˈɑləʤi/", "fiziologiya"],
        ["radioactive", "/ˌreɪdioʊˈæktɪv/", "radioaktiv"],
        ["relativity", "/ˌrɛləˈtɪvəti/", "nisbiylik nazariyasi"],
        ["sociology", "/ˌsoʊsiˈɑləʤi/", "sotsiologiya, jamiyatshunoslik"],
        ["theoretical", "/ˌθiərˈɛtɪkəl/", "nazariy"],
      ]),
      unit(4, [
        ["administrator", "/ədˈmɪnɪˌstreɪtər/", "administrator, rahbar"],
        ["affluent", "/ˈæfluənt/", "boy, badavlat"],
        ["audit", "/ˈɔdɪt/", "tekshirmoq, taftish qilmoq"],
        ["automate", "/ˈɔtəˌmeɪt/", "avtomatlashtirmoq"],
        ["bribe", "/braɪb/", "pora bermoq"],
        ["corrupt", "/kərəpt/", "poraxo\'r, buzuq"],
        ["dispose", "/dɪˈspoʊz/", "qutulmoq, xalos bo\'lmoq"],
        ["headquarters", "/ˈhɛdˌkɔrtərz/", "bosh ofis, shtab-kvartira"],
        ["incentive", "/ˌɪnˈsɛnɪv/", "stimul, undovchi omil"],
        ["infrastructure", "/ˌɪnfrəˈstrəkʧər/", "infrastruktura"],
        ["legislate", "/ˈlɛʤɪsˌleɪt/", "qonun chiqarmoq"],
        ["legitimate", "/ləˈʤɪtəmət/", "qonuniy, qonunga muvofiq"],
        ["manipulate", "/məˈnɪpjəˌleɪt/", "mohirona boshqarmoq, ta\'sir o\'tkazmoq"],
        ["merchandise", "/ˈmərʧənˌdaɪz/", "to\'plam tovarlar, mahsulot"],
        ["retail", "/ˈriˌteɪl/", "chakana savdo"],
        ["revenue", "/ˈrɛvəˌnu/", "daromad, tushum"],
        ["rubbish", "/ˈrəbɪʃ/", "axlat, chiqindi"],
        ["subsidy", "/ˈsəbsɪdi/", "subsidiya, yordam puli"],
        ["transaction", "/trænˈzækʃən/", "kelishuv, bitim"],
        ["violate", "/ˈvaɪəleɪt/", "qonunni buzmoq"],
      ]),
      unit(5, [
        ["assess", "/əˈsɛs/", "baholamoq, tekshirmoq"],
        ["astonish", "/əˈstɑnɪʃ/", "hayratda qoldirmoq"],
        ["commence", "/kəˈmɛns/", "boshlamoq"],
        ["essence", "/ˈɛsəns/", "mohiyat, ma\'no"],
        ["extract", "/ˈɛkˌstrækt/", "sug\'urib olmoq, ajratib olmoq"],
        ["fabulous", "/ˈfæbjələs/", "juda yaxshi, ajoyib"],
        ["haste", "/heɪst/", "shoshilish, shoshilinchlik"],
        ["impulse", "/ˌɪmˈpəls/", "impuls, ruhiy turtki"],
        ["latter", "/ˈlætər/", "oxirgi, so\'nggi (tanlov)"],
        ["molecule", "/ˈmɑləˌkjul/", "molekula"],
        ["ongoing", "/ˈɔnˌgoʊɪŋ/", "davom etayotgan"],
        ["pharmaceutical", "/ˌfɑrməˈsutɪkəl/", "farmatsevtik, doriga oid"],
        ["precise", "/prɪˈsaɪs/", "sinchkov, aniq"],
        ["proximity", "/prɑkˈsɪməti/", "yaqinlik (masofa/vaqt)"],
        ["publicity", "/pəˈblɪsɪti/", "jamoatchilik e\'tibori, reklama"],
        ["remedy", "/ˈrɛmədi/", "malham, davo, chora"],
        ["significance", "/sɪgˈnɪfɪkəns/", "ahamiyat, muhimlik"],
        ["subsequent", "/ˈsəbsəkwənt/", "keyingi, kelgusi"],
        ["synthetic", "/sɪnˈθɛtɪk/", "sintetik, sun\'iy"],
        ["terminal", "/ˈtərmənəl/", "o\'limga olib keluvchi, oxirgi"],
      ]),
      unit(6, [
        ["altitude", "/ˈæltəˌtud/", "balandlik (dengiz sathidan)"],
        ["coastline", "/ˈkoʊˌstlaɪn/", "sohil liniyasi"],
        ["deter", "/dɪˈtər/", "yo\'lidan qaytarmoq, to\'xtatmoq"],
        ["devise", "/dɪˈvaɪz/", "o\'ylab topmoq, reja tuzmoq"],
        ["expertise", "/ˌɛkspərˈtiz/", "bilim va tajriba, mahorat"],
        ["fracture", "/ˈfrækʧər/", "singan joy, yoriq"],
        ["impair", "/ˌɪmˈpɛr/", "zarar yetkazmoq, yomonlashtirmoq"],
        ["implement", "/ˈɪmpləmənt/", "amalga oshirmoq, joriy qilmoq"],
        ["indigenous", "/ˌɪnˈdɪʤənəs/", "mahalliy, tub (yerli)"],
        ["insight", "/ˈɪnˌsaɪt/", "chuqur tushuncha, anglash"],
        ["limb", "/lɪm/", "katta shox, tana a\'zosi"],
        ["migraine", "/ˈmaɪˌgreɪn/", "migren, kuchli bosh og\'rig\'i"],
        ["optimism", "/ˈɑptɪˌmɪzəm/", "optimizm, xushbinlik"],
        ["peculiar", "/pɪˈkjuljər/", "g\'ayrioddiy, g\'alati"],
        ["proficient", "/prɑˈfɪʃənt/", "malakali, tajribali"],
        ["quest", "/kwɛst/", "qidiruv, izlash safari"],
        ["ridge", "/rɪʤ/", "qirra, tog\' tizmisi"],
        ["spouse", "/spaʊs/", "turmush o\'rtoq"],
        ["thrust", "/θrəst/", "zarba bermoq, itarmoq"],
        ["tolerate", "/ˈtɑlərˌeɪt/", "chidamoq, bardosh bermoq"],
      ]),
      unit(7, [
        ["aquatic", "/əkˈwɑtɪk/", "suvda yashaydigan, suvga oid"],
        ["biosphere", "/ˈbaɪoʊsˌfɪr/", "biosfera, hayot qobig\'i"],
        ["bizarre", "/bɪˈzɑr/", "g\'ayritabiiy, juda g\'alati"],
        ["Celsius", "/ˈsɛlsiəs/", "Selsiy shkalasi"],
        ["coarse", "/kɔrs/", "dag\'al, g\'adir-budur"],
        ["companion", "/kəmˈpænjən/", "hamroh, sherik"],
        ["digest", "/ˈdaɪʤɛst/", "hazm qilmoq"],
        ["duration", "/ˈdʊˈreɪʃən/", "davom etish miqdori/vaqti"],
        ["ecology", "/ɪˈkɑləʤi/", "ekologiya"],
        ["feat", "/fit/", "mahorat, jasorat, erishilgan yutuq"],
        ["infinite", "/ˈɪnfənət/", "cheksiz, adog\'i yo\'q"],
        ["nucleus", "/ˈnukliəs/", "yadro (hujayra/atom)"],
        ["parasite", "/ˈpɛrəˌsaɪt/", "parazit"],
        ["prominent", "/ˈprɑmənənt/", "mashhur, taniqli, ko\'zga tashlanadigan"],
        ["repetitive", "/rɪˈpɛtɪtɪv/", "takrorlanuvchi, zerikarli"],
        ["reproductive", "/ˌriprəˈdəktɪv/", "reproduktiv, ko\'payishga oid"],
        ["temperate", "/ˈtɛmpərət/", "mo\'tadil (iqlim)"],
        ["tolerance", "/ˈtɑlərəns/", "chidam, bardosh"],
        ["undergo", "/ˌəndərˈgoʊ/", "boshdan kechirmoq"],
        ["vulnerable", "/ˈvəlnərəbəl/", "zaif, himoyasiz"],
      ]),
      unit(8, [
        ["adept", "/əˈdɛpt/", "bilimdon, mutaxassis"],
        ["barren", "/ˈbɛrən/", "unumsiz, hosilsiz"],
        ["ceramic", "/sərˈæmɪk/", "keramik, sopoldan qilingan"],
        ["culinary", "/ˈkjulɪˌnɛri/", "oshpazlik, pazandachilik"],
        ["dense", "/dɛns/", "zich, qalin"],
        ["dignity", "/ˈdɪgnəti/", "salobat, savlat, qadr-qimmat"],
        ["dominate", "/ˈdɑməˌneɪt/", "ustunlik qilmoq, boshqarmoq"],
        ["edible", "/ˈɛdəbəl/", "yesa bo\'ladigan, yemishli"],
        ["hostile", "/ˈhɑstəl/", "adovatli, dushmanona"],
        ["intake", "/ˈɪnˌteɪk/", "iste\'mol qilish miqdori"],
        ["likewise", "/ˈlaɪkˌwaɪz/", "xuddi shunday, shuningdek"],
        ["malnutrition", "/ˌmælnuˈtrɪʃən/", "to\'yib ovqatlanmaslik, oziq yetishmasligi"],
        ["medication", "/ˌmɛdəˈkeɪʃən/", "dori-darmon"],
        ["misconception", "/mɪskənˈsɛpʃən/", "noto\'g\'ri tasavvur/tushuncha"],
        ["obscure", "/əbˈskjʊr/", "notanish, noma\'lum"],
        ["oppress", "/əˈprɛs/", "jabr-zulm qilmoq, ezmoq"],
        ["peel", "/pil/", "archmoq (po\'stini)"],
        ["prescription", "/prəˈskrɪpʃən/", "shifokor retsepti"],
        ["respirator", "/ˈrɛspərˌeɪtər/", "respirator, sun\'iy nafas apparati"],
        ["strive", "/straɪv/", "intilmoq, tirishmoq"],
      ]),
      unit(9, [
        ["archaic", "/ɑrˈkeɪɪk/", "arxaik, eskirgan"],
        ["benevolent", "/bəˈnɛvələnt/", "mehribon, saxiy"],
        ["brass", "/bræs/", "sariq mis, guruch metall"],
        ["capitalism", "/ˈkæpɪtəˌlɪzəm/", "kapitalizm"],
        ["component", "/kəmˈpoʊnənt/", "tarkibiy qism, komponent"],
        ["dependence", "/dɪˈpɛndəns/", "qaramlik, tobelik"],
        ["diminish", "/dɪˈmɪnɪʃ/", "kamaymoq, qisqarmoq"],
        ["drawback", "/ˈdrɔˌbæk/", "kamchilik, salbiy jihat"],
        ["fad", "/fæd/", "o\'tkinchi hoyu-havas, urf"],
        ["impose", "/ˌɪmˈpoʊz/", "yuklamoq, majburlab hukm o\'tkazmoq"],
        ["managerial", "/ˌmænɪˈʤɪriəl/", "boshqaruvga oid, menejerlik"],
        ["medieval", "/mɪˈdjivəl/", "o\'rta asrlarga oid"],
        ["obsolete", "/ˌɑbsəˈlit/", "urfdan qolgan, eskirgan"],
        ["peninsula", "/pəˈnɪnsələ/", "yarim orol"],
        ["prestige", "/prɛˈstiʒ/", "obro'"],
        ["proportion", "/prəˈpɔrʃən/", "nisbat, qism, bo\'lak"],
        ["radical", "/ˈrædɪkəl/", "tupdan o\'zgaruvchi, keskin"],
        ["refute", "/rɪfˈjut/", "rad etmoq, isbotlab inkor qilmoq"],
        ["spectacular", "/spɛkˈtækjələr/", "ta\'sirchan, ajoyib"],
        ["weave", "/wiv/", "to\'qimoq"],
      ]),
      unit(10, [
        ["accountant", "/əˈkaʊntənt/", "buxgalter, hisobchi"],
        ["capitalist", "/ˈkæpətəlɪst/", "kapitalist, sarmoyador"],
        ["contempt", "/kənˈtɛmpt/", "mensimaslik, nafrat"],
        ["dedicate", "/ˈdɛdəˌkeɪt/", "bag\'ishlamoq (vaqt/kuch)"],
        ["ditch", "/dɪʧ/", "ariq, zovur"],
        ["enterprise", "/ˈɛnərˌpraɪz/", "korxona, biznes"],
        ["exquisite", "/ˈɛkskwəzət/", "go\'zal, nafis, latofatli"],
        ["finance", "/ˈfaɪˌnæns/", "mablag\' bilan ta\'minlamoq"],
        ["indifferent", "/ˌɪnˈdɪfərənt/", "beparvo, loqayd"],
        ["irrigate", "/ˈɪrəˌgeɪt/", "sug\'ormoq (yerlarni)"],
        ["maximize", "/ˈmæksəˌmaɪz/", "maksimallashtirmoq"],
        ["monetary", "/ˈmɑnəˌtɛri/", "pulg\'a oid, monetar"],
        ["precaution", "/priˈkɔʃən/", "ehtiyot chorasi"],
        ["preliminary", "/prɪˈlɪməˌnɛri/", "dastlabki, tayyorgarlik"],
        ["saturate", "/ˈsæʧərˌeɪt/", "ho\'llamoq, bo\'ktirib ivitmoq"],
        ["simplicity", "/sɪmˈplɪsɪti/", "soddalik, osonlik"],
        ["sow", "/soʊ/", "urug\' sepmoq, ekmoq"],
        ["soy", "/sɔɪ/", "soya sousi/loviyasi"],
        ["spade", "/speɪd/", "belkurak, lapotka"],
        ["upcoming", "/ˈəpˌkəmɪŋ/", "yaqinlashayotgan, kelgusi"],
      ]),
      unit(11, [
        ["acute", "/əˈkjut/", "qattiq, o\'tkir, og\'ir"],
        ["aggression", "/əˈgrɛʃən/", "tajovuzkorlik, agressiya"],
        ["banquet", "/ˈbæŋkwət/", "banket, rasmiy ziyofat"],
        ["biography", "/baɪˈɑgrəfi/", "tarjimai hol, biografiya"],
        ["boost", "/bust/", "oshirmoq, ko\'tarmoq"],
        ["clap", "/klæp/", "qarsak chalmoq"],
        ["compel", "/kəmˈpɛl/", "majbur qilmoq"],
        ["dominance", "/ˈdɑmənəns/", "hukmronlik, ustunlik"],
        ["gorgeous", "/ˈgɔrʤəs/", "juda go\'zal, ko\'rkam"],
        ["inevitable", "/ˌɪˈnɛvətəbəl/", "muqarrar, qutulib bo\'lmaydigan"],
        ["legacy", "/ˈlɛgəsi/", "meros, qolgan iz"],
        ["masterpiece", "/ˈmæstərˌpis/", "shoh asar, durdona"],
        ["multiple", "/ˈməltəpəl/", "ko\'p sonli, bir nechta"],
        ["narrate", "/ˈnɛˌreɪt/", "hikoya qilib bermoq"],
        ["notorious", "/noʊˈtɔriəs/", "yomon nom chiqargan"],
        ["outdated", "/ˈaʊtˌdeɪtɪd/", "eski, urfdan qolgan"],
        ["overall", "/ˈoʊvərˌɔl/", "umuman olganda, umumiy"],
        ["partiality", "/ˌpɑrʃiˈæləti/", "yon bosish, moyillik"],
        ["spontaneous", "/spɑnˈteɪniəs/", "kutilmagan, spontan"],
        ["virtue", "/ˈvərʧu/", "yaxshi xislat, fazilat"],
      ]),
      unit(12, [
        ["anthropology", "/ˌænθrəˈpɑləʤi/", "antropologiya"],
        ["applaud", "/əˈplɔd/", "olqishlamoq, qarsak chalmoq"],
        ["appoint", "/əˈpɔɪnt/", "ta\'yinlamoq (lavozimga)"],
        ["compatible", "/kəmˈpætəbəl/", "bir-biriga mos, kirishimli"],
        ["competence", "/ˈkɑmpətɪns/", "mahorat, kompetensiya"],
        ["confer", "/kənˈfər/", "maslahatlashmoq"],
        ["consecutive", "/kənˈsɛkjətɪv/", "ketma-ket, izchil"],
        ["crude", "/krud/", "qo\'pol, ishlov berilmagan"],
        ["cube", "/kjub/", "kubik, kub"],
        ["feedback", "/ˈfidˌbæk/", "fikr-mulohaza, qayta aloqa"],
        ["ignorance", "/ˈɪgnərəns/", "bilimsizlik, savodsizlik"],
        ["masculine", "/ˈmæskjələn/", "erkaklarcha, erkakka xos"],
        ["monument", "/ˈmɑnjəmənt/", "haykal, yodgorlik"],
        ["muscular", "/ˈməskjələr/", "mushakdor, baquvvat"],
        ["posture", "/ˈpɑsʧər/", "qomat, gavda holati"],
        ["situate", "/ˈsɪʧuˌeɪt/", "joylashtirmoq"],
        ["supervise", "/ˈsupərˌvaɪz/", "nazorat qilmoq"],
        ["symmetry", "/ˈsɪmətri/", "simmetriya"],
        ["tattoo", "/ˌtæˈtu/", "tatuirovka"],
        ["undergraduate", "/ˌəndərˈgræʤəwət/", "bakalavr talabasi"],
      ]),
      unit(13, [
        ["brook", "/brʊk/", "kichik soy, anhor"],
        ["cater", "/ˈkeɪtər/", "ta\'minlamoq, ehtiyojini qondirmoq"],
        ["considerate", "/kənˈsɪdərət/", "o\'zgalarga e\'tiborli, g\'amxo\'r"],
        ["consumption", "/kənˈsəmʃən/", "iste\'mol qilish"],
        ["criteria", "/kraɪˈtɪriə/", "kriteriy, mezonlar"],
        ["crust", "/krəst/", "non po\'stlog\'i/sirti"],
        ["degrade", "/dɪˈgreɪd/", "obro\'yini tushirmoq, kamsitmoq"],
        ["entitle", "/ɪnˈtaɪtəl/", "huquq bermoq"],
        ["escort", "/ˈɛskɔrt/", "kuzatib bormoq, qo\'riqlamoq"],
        ["external", "/ɪkˈstərnəl/", "tashqi, tashqaridagi"],
        ["facility", "/fəˈsɪlɪti/", "bino, inshoot, imkoniyat"],
        ["faculty", "/ˈfækəlti/", "qobiliyat, iqtidor"],
        ["heap", "/hip/", "uyum, g\'aram"],
        ["hemisphere", "/ˈhɛmɪsˌfɪr/", "yarimshar (yer)"],
        ["hound", "/haʊnd/", "tozi it, ov iti"],
        ["impersonal", "/ˌɪmˈpərsənəl/", "jozibasiz, sovuq, rasmiy"],
        ["ornament", "/ˈɔrnəmənt/", "bezak, naqsh"],
        ["pedestrian", "/pəˈdɛstriən/", "piyoda kishi"],
        ["sanctuary", "/ˈsæŋkʧuˌɛri/", "boshpana, qo\'riqxona"],
        ["spectator", "/ˈspɛkteɪtər/", "tomoshabin"],
      ]),
      unit(14, [
        ["asset", "/ˈæˌsɛt/", "foydali qobiliyat, aktiv, boylik"],
        ["aspect", "/ˈæˌspɛkt/", "tomon, jihat"],
        ["Braille", "/breɪl/", "Brayl yozuvi (ko\'rlar uchun)"],
        ["bud", "/bəd/", "g\'uncha, kurtak"],
        ["coordinate", "/koʊˈɔrdəˌneɪt/", "o\'zaro moslamoq, muvofiqlashtirmoq"],
        ["disprove", "/dɪˈspruv/", "noto\'g\'riligini isbotlamoq, rad etmoq"],
        ["humanitarian", "/ˌjuˌmænəˈtɛriən/", "gumanitar, insonparvarlikka oid"],
        ["hypothesis", "/haɪˈpɑθəsəs/", "gipoteza, faraz"],
        ["imprint", "/ˌɪmˈprɪnt/", "o\'chmas iz, unutilmas ta\'sir"],
        ["informative", "/ˌɪnˈfɔrmətɪv/", "axborotga boy, ma\'lumotli"],
        ["optic", "/ˈɑptɪk/", "ko\'zga/ko\'rishga oid, optik"],
        ["premise", "/ˈprɛmɪs/", "asosiy g\'oya, poydevor fikr"],
        ["rack", "/ræk/", "tokcha, javon"],
        ["Renaissance", "/ˌrɛnəˈsɑns/", "Uyg\'onish davri, Renessans"],
        ["revere", "/rɪˈvɪr/", "e\'zozlamoq, qadrlamoq"],
        ["simultaneous", "/ˌsaɪməlˈteɪniəs/", "bir vaqtda yuz beradigan"],
        ["skeptic", "/ˈskɛptɪk/", "skeptik, shubhalanuvchi"],
        ["spatial", "/ˈspeɪʃəl/", "fazoviy, makonga oid"],
        ["specify", "/ˈspɛsəˌfaɪ/", "aniq ko\'rsatmoq, ifodalamoq"],
        ["wax", "/wæks/", "mum, parafin"],
      ]),
      unit(15, [
        ["accessory", "/ækˈsɛsəri/", "aksessuar, qo\'shimcha buyum"],
        ["acquisition", "/ˌækwəˈzɪʃən/", "sotib olingan narsa, xarid"],
        ["adequate", "/ˈædəkˌweɪt/", "talabga javob beradigan, yetarli"],
        ["cardboard", "/ˈkɑrdˌbɔrd/", "karton"],
        ["dilemma", "/dɪˈlɛmə/", "dilemma, qiyin tanlov"],
        ["elaborate", "/ɪˈlæbərˌeɪt/", "mufassal, batafsil ishlangan"],
        ["facilitate", "/fəˈsɪləˌteɪt/", "yengillashtirmoq, osonlashtirmoq"],
        ["fleet", "/flit/", "flot, kemalar to\'plami"],
        ["grid", "/grɪd/", "katakcha, koordinata to\'ri"],
        ["import", "/ˌɪmˈpɔrt/", "import qilmoq"],
        ["infer", "/ˌɪnˈfər/", "xulosa chiqarmoq"],
        ["inflate", "/ɪnˈfleɪt/", "shishirmoq (havo bilan)"],
        ["innate", "/ˌɪˈneɪt/", "tug\'ma"],
        ["marble", "/ˈmɑrbəl/", "marmar"],
        ["mast", "/mæst/", "machta, ustun"],
        ["nausea", "/ˈnɔziə/", "ko\'ngil aynishi"],
        ["naval", "/ˈneɪvəl/", "harbiy-dengiz flotiga oid"],
        ["pouch", "/paʊʧ/", "xalta, kissacha"],
        ["saturated", "/ˈsæʧərˌeɪtɪd/", "shalabbo, ho\'l bo\'lgan"],
        ["update", "/ˈəpˌdeɪt/", "yangilanish, zamonaviylashtirish"],
      ]),
      unit(16, [
        ["addict", "/ˈæˌdɪkt/", "ishqiboz, mukkasidan ketgan kishi"],
        ["archeological", "/ˌɑrkiəˈlɑʤɪkəl/", "arxeologik"],
        ["archeology", "/ˌɑrkiˈɑləʤi/", "arxeologiya"],
        ["brainstorm", "/ˈbreɪnˌstɔrm/", "fikrlashmoq, miya xujumi qilmoq"],
        ["budget", "/ˈbəʤɪt/", "byudjet, xarajat rejasi"],
        ["chaotic", "/keɪˈɑtɪk/", "tartibsiz, chalkash"],
        ["cite", "/saɪt/", "misol qilib keltirmoq"],
        ["correspond", "/ˌkɔrəˈspɑnd/", "mos kelmoq, muvofiq bo\'lmoq"],
        ["courtyard", "/ˈkɔrˌtjɑrd/", "hovli, ichki hovli"],
        ["estate", "/ɛˈsteɪt/", "katta yer-mulk, hovli"],
        ["fraud", "/frɔd/", "firibgarlik"],
        ["hydrogen", "/ˈhaɪdrəʤən/", "vodorod gazi"],
        ["integrity", "/ˌɪnˈtɛgrəti/", "halollik, to\'g\'rilik"],
        ["knit", "/nɪt/", "to\'qimoq (ipdan)"],
        ["outlook", "/ˈaʊˌtlʊk/", "dunyoqarash, fikr"],
        ["parachute", "/ˈpɛrəˌʃut/", "parashyut"],
        ["prehistoric", "/ˌprihɪˈstɔrɪk/", "tarixdan avvalgi"],
        ["proponent", "/prəˈpoʊnənt/", "targ\'ibotchi, tarafdor"],
        ["refine", "/rɪˈfaɪn/", "yaxshilamoq, mukammallashtirmoq"],
        ["restrict", "/riˈstrɪkt/", "cheklamoq"],
      ]),
      unit(17, [
        ["attorney", "/əˈtərni/", "advokat, huquqshunos"],
        ["chronic", "/ˈkrɑnɪk/", "surunkali, doimiy"],
        ["discipline", "/ˈdɪsəplən/", "intizom, tartib-intizom"],
        ["donor", "/ˈdoʊnər/", "donar, ehson qiluvchi"],
        ["fellow", "/ˈfɛloʊ/", "hamkasb, tengdosh, o\'rtoq"],
        ["gossip", "/ˈgɑsəp/", "mish-mish, g\'ibat"],
        ["graduate", "/ˈgræʤəˌweɪt/", "bitirmoq (o\'quv yurtini)"],
        ["graffiti", "/grəˈfiti/", "graffiti, devoriy yozuvlar"],
        ["guardian", "/ˈgɑrdiən/", "himoyachi, vasiy"],
        ["implicate", "/ˈɪmplɪˌkeɪt/", "aybdor deb ko\'rsatmoq"],
        ["kin", "/kɪn/", "qarindoshlar, qarindosh-urug\'"],
        ["referee", "/ˌrɛfərˈi/", "sudya (sportda)"],
        ["sever", "/ˈsɛvər/", "uzib tashlamoq, kesmoq"],
        ["shaft", "/ʃæft/", "dasta, sop (qurol/asbob)"],
        ["stab", "/stæb/", "pichoq urmoq, sanchmoq"],
        ["stimulus", "/ˈstɪmjələs/", "rag\'bat, turtki"],
        ["suspicion", "/səˈspɪʃən/", "shubha, gumon"],
        ["terminate", "/ˈtərməˌneɪt/", "to\'xtatmoq, tugatmoq"],
        ["theme", "/θim/", "mavzu, asosiy g\'oya"],
        ["tuition", "/tjuˈɪʃən/", "o\'qish haqi, kontrakt to\'lovi"],
      ]),
      unit(18, [
        ["aggressive", "/əˈgrɛsɪv/", "tajovuzkor, urishqoq"],
        ["amnesty", "/ˈæmnəsti/", "amnistiya, afv etish"],
        ["arena", "/ərˈinə/", "arena, maydon"],
        ["auditorium", "/ˌɔdəˈtɔriəm/", "tomoshabinlar zali, auditoriya"],
        ["captive", "/ˈkæptɪv/", "tutqun, asir"],
        ["combat", "/ˈkɑmbæt/", "jang, olishuv"],
        ["commonplace", "/ˈkɑmənˌpleɪs/", "odatiy, oddiy"],
        ["compound", "/ˈkɑmpaʊnd/", "o\'rab olingan hudud/maydon"],
        ["corps", "/kɔrz/", "korpus, harbiy bo\'linma"],
        ["distract", "/dɪˈstrækt/", "chalg\'itmoq"],
        ["dumb", "/dəm/", "soqov, gapira olmaydigan"],
        ["foe", "/foʊ/", "dushman, raqib"],
        ["hack", "/hæk/", "chopmoq, uvalamoq"],
        ["meditate", "/ˈmɛdəˌteɪt/", "meditatsiya qilmoq, o\'yga tolmoq"],
        ["nick", "/nɪk/", "ozgina kesib yubormoq"],
        ["provoke", "/prəˈvoʊk/", "g\'azabini keltirmoq, gij-gijlamoq"],
        ["realm", "/rɛlm/", "soha, soha/qirollik"],
        ["reign", "/reɪn/", "hukmronlik davri"],
        ["rust", "/rəst/", "zang, zanglash"],
        ["sacred", "/ˈseɪkrɪd/", "muqaddas, tabarruk"],
      ]),
      unit(19, [
        ["accordingly", "/əˈkɔrdɪŋli/", "shunga muvofiq, mos ravishda"],
        ["anchor", "/ˈæŋkər/", "yakor, zanjirli yakor"],
        ["buoy", "/bui/", "buyak, suvdagi ishora"],
        ["catastrophe", "/kəˈtæstrəfi/", "katastrofa, katta falokat"],
        ["context", "/ˈkɑntɛkst/", "kontekst, vaziyat"],
        ["designate", "/ˈdɛzɪgˌneɪt/", "belgilamoq, nomlamoq"],
        ["distort", "/dɪˈstɔrt/", "buzuq ko\'rsatmoq, yolg\'on gapirmoq"],
        ["dock", "/dɑk/", "dok, kema to\'xtash joyi"],
        ["fore", "/fɔr/", "old qismi (kema/bino)"],
        ["frequent", "/ˈfrikˌwɛnt/", "tez-tez yuz beradigan"],
        ["genuine", "/ˈʤɛnjuˌaɪn/", "haqiqiy, asl"],
        ["grease", "/gris/", "moy, yog\'lama"],
        ["intricate", "/ˈɪntrəkət/", "murakkab, ko\'p detallarga ega"],
        ["offset", "/ˈɔfˌsɛt/", "yo\'qqa chiqarmoq, tenglashtirmoq"],
        ["overlap", "/ˈoʊvərˌlæp/", "ustma-ust tushmoq"],
        ["precipitate", "/prɪˈsɪpɪˌteɪt/", "tezlashtirmoq, sabab bo\'lmoq"],
        ["secondhand", "/ˈsɛkənˌdhænd/", "ishlatilgan, ikkinchi qo\'l"],
        ["slot", "/slɑt/", "tor teshik, tirqish"],
        ["submerge", "/səbˈmərʤ/", "suvga sho\'ng\'itmoq, cho\'ktirmoq"],
        ["tactic", "/ˈtæktɪk/", "taktika, usul"],
      ]),
      unit(20, [
        ["aggregate", "/ˈægrəgət/", "umumiy, jami"],
        ["antibiotic", "/ˌæntibaɪˈɑtɪk/", "antibiotik dori"],
        ["circuit", "/ˈsərkət/", "elektr zanjiri, sxema"],
        ["complement", "/ˈkɑmpləmənt/", "to\'ldirmoq, yaxshilamoq"],
        ["compress", "/ˈkɑmprɛs/", "siqmoq, ziqlamoq"],
        ["database", "/ˈdætəˌbeɪs/", "ma\'lumotlar bazasi"],
        ["equivalent", "/ɪkˈwɪvələnt/", "teng qiymatli, ekvivalent"],
        ["immune", "/ˌɪmˈjun/", "immunitetga ega, ta\'sir qilmaydigan"],
        ["input", "/ˈɪnˌpʊt/", "kiritilgan ma\'lumot"],
        ["intimate", "/ˈɪnɪmət/", "yaqin, jips"],
        ["magnet", "/ˈmægnət/", "magnit"],
        ["metabolism", "/məˈtæbəˌlɪzəm/", "moddalar almashinuvi"],
        ["microchip", "/ˈmaɪˌkroʊˈʧɪp/", "mikrosxema, mikrochip"],
        ["phase", "/feɪz/", "bosqich, faza"],
        ["pinch", "/pɪnʧ/", "chimchilamoq, siqib ushlamoq"],
        ["prevalent", "/ˈprɛvələnt/", "keng tarqalgan, odatiy"],
        ["quantum", "/kˈwɑntəm/", "kvant..."],
        ["ratio", "/ˈreɪʃiˌoʊ/", "proportsiya, nisbat"],
        ["spiral", "/ˈspaɪrəl/", "spiral shakldagi"],
        ["viral", "/ˈvaɪrəl/", "virusli"],
      ]),
      unit(21, [
        ["astounded", "/əˈstaʊndɪd/", "juda hayratlangan"],
        ["attribute", "/əˈtrɪˌbjut/", "xususiyat, sifat"],
        ["bilingual", "/baɪˈlɪŋgwəl/", "ikki tilli"],
        ["clone", "/kloʊn/", "klon, nusxa"],
        ["colloquial", "/kəˈloʊkwiəl/", "so\'zlashuvga oid, norasmiy"],
        ["cosmetics", "/kɑzˈmɛtɪks/", "pardoz vositalari"],
        ["dash", "/dæʃ/", "shoshilib yugurmoq"],
        ["disgust", "/dɪsˈgəst/", "jirkanish, nafrat"],
        ["fluorescent", "/ˌflʊˈrɛsənt/", "lyuminestsent, juda yorqin"],
        ["furious", "/fˈjʊriəs/", "darg\'azab, juda jahldor"],
        ["gulf", "/gəlf/", "tushunmovchilik, jarlik"],
        ["humanities", "/juˈmænɪtiz/", "gumanitar fanlar"],
        ["knot", "/nɑt/", "tugun"],
        ["linguist", "/ˈlɪŋgwɪst/", "tilshunos"],
        ["participant", "/pɑrˈtɪsəpənt/", "ishtirokchi"],
        ["plausible", "/ˈplɔzəbəl/", "mantiqiy, bo\'lishi mumkin bo\'lgan"],
        ["ritual", "/ˈrɪʧuəl/", "diniy marosim, uzoq davom etgan odat"],
        ["sibling", "/ˈsɪblɪŋ/", "tug\'ishgan aka-uka/opa-singil"],
        ["skinny", "/ˈskɪni/", "juda oriq, ozg\'in"],
        ["vague", "/veɪg/", "nohaq, gumonli, noaniq"],
      ]),
      unit(22, [
        ["acid", "/ˈæsəd/", "kislota"],
        ["administration", "/ædˌmɪnɪˈstreɪʃən/", "ma\'muriyat, rahbarlik"],
        ["administrative", "/ədˈmɪnɪˌstreɪtɪv/", "ma\'muriy"],
        ["biotechnology", "/ˌbaɪoʊˌtɛkˈnɑləʤi/", "biotexnologiya"],
        ["cholesterol", "/kəˈlɛstərˌɔl/", "xolesterin"],
        ["coalition", "/ˌkoʊəˈlɪʃən/", "koalitsiya, birlashma"],
        ["deceptive", "/dɪˈsɛptɪv/", "chalg\'ituvchi, yolg\'on"],
        ["diabetes", "/ˌdaɪəˈbitiz/", "diabet, qand kasalligi"],
        ["eliminate", "/ɪˈlɪməˌneɪt/", "yo\'qotmoq, bartaraf etmoq"],
        ["erosion", "/ɪˈroʊʒən/", "eroziya, yemirilish"],
        ["ethics", "/ˈɛθɪks/", "etika, axloq qoidalari"],
        ["explicit", "/ɪkˈsplɪsət/", "ochiq-oydin, aniq"],
        ["framework", "/ˈfreɪmˌwərk/", "tuzilma, qoidalar majmui"],
        ["manufacture", "/ˌmænjəˈfækʧər/", "ishlab chiqarmoq (fabrikada)"],
        ["mechanism", "/ˈmɛkəˌnɪzəm/", "mexanizm"],
        ["minimize", "/ˈmɪnəˌmaɪz/", "kamaytirmoq"],
        ["nectar", "/ˈnɛktər/", "nektar (gul sharbati)"],
        ["notion", "/ˈnoʊʃən/", "tushuncha, fikr"],
        ["prone", "/proʊn/", "moyil, beriluvchan"],
        ["straightforward", "/ˈstreɪtˈfɔrwərd/", "tushunarli, oddiy"],
      ]),
      unit(23, [
        ["astronomical", "/ˌæstrəˈnɑmɪkəl/", "astronomik, juda katta"],
        ["atom", "/ˈætəm/", "atom"],
        ["breadth", "/brɛdθ/", "kenglik (bir chetdan boshqasiga)"],
        ["circumference", "/ˌsərˈkəmfrəns/", "aylana uzunligi"],
        ["comet", "/ˈkɑmət/", "kometa"],
        ["crater", "/ˈkreɪtər/", "krater, chuqurlik"],
        ["crescent", "/ˈkrɛsənt/", "yarim oy shakli"],
        ["debris", "/dəˈbri/", "bo\'laklar, qoldiqlar"],
        ["despair", "/dɪˈspɛr/", "umidsizlik"],
        ["embed", "/ɪmˈbɛd/", "joylashtirmoq, kirgizib qo\'ymoq"],
        ["fragment", "/ˈfrægmənt/", "bo\'lak, parchalar"],
        ["galaxy", "/ˈgæləksi/", "galaktika"],
        ["gigantic", "/ʤaɪˈgænɪk/", "juda katta, gigant"],
        ["gloom", "/glum/", "g\'amginlik, nim qorong\'ulik"],
        ["radiate", "/ˈreɪdiˌeɪt/", "nur sochmoq, issiqlik taratmoq"],
        ["roam", "/roʊm/", "maqsadiz kezib yurmoq"],
        ["solitary", "/ˈsɑləˌtɛri/", "yolg\'iz, bir o\'zi"],
        ["spectrum", "/ˈspɛktrəm/", "spektr, ranglar majmui"],
        ["sphere", "/sfɪr/", "sfera, shar shaklidagi narsa"],
        ["status", "/ˈstætəs/", "status, mavqe"],
      ]),
      unit(24, [
        ["bankrupt", "/ˈbæŋkrəpt/", "bankrot bo\'lgan"],
        ["conform", "/kənˈfɔrm/", "qoidaga bo\'ysunmoq"],
        ["employ", "/ɪmˈplɔɪ/", "ishga olmoq"],
        ["expel", "/ɪkˈspɛl/", "haydab chiqarmoq, chetlatmoq"],
        ["extension", "/ɪkˈstɛnʃən/", "uzaytirish, qo\'shimcha vaqt"],
        ["forthcoming", "/ˈfɔrθˈkəmɪŋ/", "bo\'ladigan, kutilayotgan"],
        ["furnish", "/ˈfərnɪʃ/", "mebel jihozlari bilan ta\'minlamoq"],
        ["hygiene", "/ˈhaɪˌʤin/", "gigiyena"],
        ["hygienic", "/hygienic*/", "gigiyenik, ozoda"],
        ["landlord", "/ˈlænˌdlɔrd/", "uy egasi (ijaraga beruvchi)"],
        ["lease", "/lis/", "ijaraga olmoq/bermoq"],
        ["mandatory", "/ˈmændəˌtɔri/", "majburiy"],
        ["mend", "/mɛnd/", "tuzatmoq, tuzatib qo\'ymoq"],
        ["mortgage", "/ˈmɔrgɪʤ/", "ipoteka krediti"],
        ["personnel", "/ˌpərsəˈnɛl/", "xodimlar jamoasi"],
        ["plumbing", "/ˈpləmɪŋ/", "santexnika, quvurlar tizimi"],
        ["tenant", "/ˈtɛnənt/", "ijarachi"],
        ["trendy", "/ˈtrɛndi/", "zamonaviy, ommabop"],
        ["utility", "/juˈtɪləti/", "kommunal xizmatlar"],
        ["whereby", "/wɛrˈbaɪ/", "shu orqali, yordamida"],
      ]),
      unit(25, [
        ["aesthetic", "/ɛsˈθɛtɪk/", "estetik, go\'zallikka oid"],
        ["arrogant", "/ˈɛrəgənt/", "kattasimon, manman"],
        ["bias", "/baɪəs/", "xolis bo\'lmaslik, tarafkashlik"],
        ["canyon", "/ˈkænjən/", "kanon, chuqur darag\'"],
        ["creek", "/krik/", "kichik soy, daryocha"],
        ["drill", "/drɪl/", "drel, parma uskunasi"],
        ["executive", "/ɪgˈzɛkjətɪv/", "ijrochi rahbar, menejer"],
        ["fatigue", "/fəˈtig/", "juda qattiq charchash"],
        ["incline", "/ˌɪnˈklaɪn/", "tik qiyalik"],
        ["nasty", "/ˈnæsti/", "juda yomon, yoqimsiz"],
        ["perceive", "/pərˈsiv/", "his qilmoq, payqamoq"],
        ["primate", "/ˈpraɪˌmeɪt/", "primat (maymun/odam)"],
        ["primitive", "/ˈprɪmɪtɪv/", "sodda, ibtidoiy"],
        ["stereotype", "/ˈstɛrioʊˌtaɪp/", "stereotip, noto\'g\'ri qolip fikr"],
        ["sticky", "/ˈstɪki/", "yopishqoq"],
        ["termite", "/ˈtərmaɪt/", "termit (hasharot)"],
        ["thereby", "/ˈðɛrˈbaɪ/", "shu sababli, natijada"],
        ["trail", "/treɪl/", "o\'rmon yo\'lagi, so\'qmoq"],
        ["twig", "/twɪg/", "shoxcha, kichik shox"],
        ["welfare", "/ˈwɛlˌfɛr/", "farovonlik, salomatlik"],
      ]),
      unit(26, [
        ["behalf", "/bɪˈhæf/", "nomidan (on behalf of)"],
        ["flap", "/flæp/", "qanot qoqmoq"],
        ["glacier", "/ˈgleɪʃər/", "muzlik"],
        ["globe", "/gloʊb/", "yer shari, globus"],
        ["horizontal", "/ˌhɔrəˈzɑntəl/", "gorizontal, tekis"],
        ["hum", "/həm/", "g\'uldiramoq, ashula aytmoq"],
        ["inventory", "/ˌɪnvənˈtɔri/", "zaxira, tovarlar ro\'yxati"],
        ["inward", "/ˈɪnwərd/", "ichki, oshkor etilmagan"],
        ["loaf", "/loʊf/", "bo\'lak (non)"],
        ["oracle", "/ˈɔrəkəl/", "folbin, kohin"],
        ["orbit", "/ˈɔrbət/", "orbiitasi bo\'ylab aylanmoq"],
        ["overview", "/ˈoʊvərvˌju/", "umumiy sharh"],
        ["preview", "/ˈprivˌju/", "dastlabki ko\'rish"],
        ["previous", "/ˈpriviəs/", "oldingi, avvalgi"],
        ["provide", "/prəˈvaɪd/", "ta\'minlamoq, bermoq"],
        ["recur", "/rɪˈkər/", "qayta yuz bermoq"],
        ["relevant", "/ˈrɛləvənt/", "tegishli, muhim"],
        ["rite", "/raɪt/", "marosim, udum"],
        ["stall", "/stɔl/", "to\'xtab qolmoq, ushlanib qolmoq"],
        ["supernatural", "/ˌsupərˈnæʧərəl/", "g\'ayritabiiy, mo\'jizaviy"],
      ]),
      unit(27, [
        ["adapt", "/əˈdæpt/", "moslashmoq"],
        ["biological", "/ˌbaɪəˈlɑʤɪkəl/", "biologik"],
        ["cellular", "/ˈsɛljələr/", "hujayraviy, hujayraga oid"],
        ["dynamic", "/daɪˈnæmɪk/", "dinamik, harakatchan"],
        ["fantasy", "/ˈfænəsi/", "xayol, fantastika"],
        ["heredity", "/hərˈɛdəti/", "irsiyat"],
        ["internal", "/ˌɪnˈtərnəl/", "ichki, ichkaridagi"],
        ["minimal", "/ˈmɪnəməl/", "juda kichik, minimal"],
        ["pioneer", "/ˌpaɪəˈnɪr/", "kashshof, birinchi bo\'lib boshlagan kishi"],
        ["prescribe", "/prəˈskraɪb/", "retsept yozib bermoq"],
        ["respective", "/rɪˈspɛktɪv/", "har birining o\'ziga tegishli"],
        ["revive", "/rɪˈvaɪv/", "qayta jonlantirmoq, quvvatini tiklamoq"],
        ["rigid", "/ˈrɪʤɪd/", "qattiq, o\'zgarmas (qoida)"],
        ["sequence", "/ˈsikwəns/", "ketma-ketlik, izchillik"],
        ["substitute", "/ˈsəbstəˌtut/", "almashtirmoq, o\'rniga qo\'ymoq"],
        ["surgeon", "/ˈsərʤɪn/", "jarroh"],
        ["therapy", "/ˈθɛrəpi/", "terapiya, davolash"],
        ["transfer", "/ˈtrænsfər/", "ko\'chirmoq, o\'tkazmoq"],
        ["transition", "/trænˈzɪʃən/", "o\'tish bosqichi, o\'zgarish"],
        ["transplant", "/trænˈsplænt/", "a\'zoni ko\'chirib o\'tkazish"],
      ]),
      unit(28, [
        ["aquarium", "/əkˈwɛriəm/", "akvarium"],
        ["arbitrary", "/ˈɑrbɪˌtrɛri/", "ixtiyoriy, tasodifiy"],
        ["autobiography", "/ˌɔtəbaɪˈɑgrəfi/", "avtobiofrafiya"],
        ["convention", "/kənˈvɛnʃən/", "odob qoidasi, konvensiya"],
        ["gracious", "/ˈgreɪʃəs/", "saxiy, iltifotli"],
        ["improve", "/ˌɪmˈpruv/", "yaxshilamoq"],
        ["insulate", "/ˈɪnsəˌleɪt/", "himoyalamoq, izolyatsiya qilmoq"],
        ["intrigue", "/ˌɪnˈtrig/", "qiziqtirmoq, maftun etmoq"],
        ["longevity", "/lɔnˈʤɛvəti/", "uzoq umr ko\'rish"],
        ["misplace", "/mɪˈspleɪs/", "yo\'qotib qo\'ymoq"],
        ["naughty", "/ˈnɔti/", "sho\'x, gapga kirmaydigan"],
        ["norm", "/nɔrm/", "norma, odatiy holat"],
        ["orangutan", "/ɔˈræŋətɑn/", "orangutan (maymun)"],
        ["overload", "/ˈoʊvərˌloʊd/", "ortiqcha yuklamoq"],
        ["philanthropy", "/fɪˈlænθrəpi/", "xayriya, ehsonsevarlik"],
        ["probe", "/proʊb/", "savol-javob qilib o\'rganmoq"],
        ["recipient", "/rɪˈsɪpiənt/", "qabul qilib oluvchi"],
        ["reptile", "/ˈrɛptaɪl/", "surnib yuruvchi hayvon"],
        ["thrive", "/θraɪv/", "gullab-yashnamoq, o\'smoq"],
        ["ultimate", "/ˈəltəmət/", "yakuniy, oxirgi"],
      ]),
      unit(29, [
        ["antique", "/ænˈtik/", "qadimiy, antikvar"],
        ["applicant", "/ˈæplɪkənt/", "nomzod, ariza beruvchi"],
        ["artifact", "/ˈɑrtəˌfækt/", "qadimiy osori-atika"],
        ["authentic", "/əˈθɛnɪk/", "haqiqiy, asl"],
        ["chronology", "/krəˈnɑləʤi/", "xronologiya, voqealar tartibi"],
        ["diplomat", "/ˈdɪpləˌmæt/", "diplomat"],
        ["epic", "/ˈɛpɪk/", "doston, epik asar"],
        ["excerpt", "/ˈɛksərpt/", "parcha, ko\'chirma (matndan)"],
        ["fossil", "/ˈfɑsəl/", "toshga aylangan qoldiq"],
        ["humiliate", "/hjuˈmɪliˌeɪt/", "sharmanda qilmoq, uyaltirmoq"],
        ["lyric", "/ˈlɪrɪk/", "lirik"],
        ["majesty", "/ˈmæʤəsti/", "oliyjanoblik, martaba"],
        ["monarch", "/ˈmɑˌnɑrk/", "monarx, qirol"],
        ["precede", "/prɪˈsid/", "oldin kelmoq"],
        ["punctual", "/ˈpəŋkʧuəl/", "vaqtiga rioya qiluvchi, punktual"],
        ["recruit", "/rɪˈkrut/", "ishga tanlamoq, yollamoq"],
        ["refund", "/ˈriˌfənd/", "pulni qaytarish"],
        ["register", "/ˈrɛʤɪstər/", "ro\'yxat, jurnal"],
        ["renown", "/rɪˈnaʊn/", "mashhurlik, shon-shuhrat"],
        ["tusk", "/təsk/", "qoziq tish, fil suyagi"],
      ]),
      unit(30, [
        ["burden", "/ˈbərdən/", "og\'ir yuk, tashvish"],
        ["compromise", "/ˈkɑmprəˌmaɪz/", "murosa qilmoq, kelishmoq"],
        ["craft", "/kræft/", "hunarmandchilik, mahorat"],
        ["crook", "/krʊk/", "g\'irrom kishi, jinoyatchi"],
        ["currency", "/ˈkərənsi/", "valyuta, pul birligi"],
        ["enigma", "/ɪˈnɪgmə/", "mumboq, sir"],
        ["fragile", "/ˈfræʤəl/", "nozik, tez sinadigan"],
        ["hybrid", "/ˈhaɪbrɪd/", "gibrid, aralash"],
        ["innocence", "/ˈɪnəsəns/", "beayblik, ma\'sumlik"],
        ["merge", "/mərʤ/", "birlashmoq, qo\'shilmoq"],
        ["moderate", "/ˈmɑdərˌeɪt/", "mo\'tadil, o\'rtacha"],
        ["overwhelm", "/ˌoʊvərˈwɛlm/", "lol qoldirmoq, bosib ketmoq"],
        ["perception", "/pərˈsɛpʃən/", "qabul qilish, tushunish"],
        ["reunion", "/riˈunjən/", "qayta uchrashuv, yig\'ilish"],
        ["rig", "/rɪg/", "g\'irromlik bilan to\'g\'rilamoq"],
        ["shiver", "/ˈʃɪvər/", "titramoq (sovuqdan/qo\'rquvdan)"],
        ["sociable", "/ˈsoʊʃəbəl/", "kirishimli, muloqotsevar"],
        ["talkative", "/ˈtɔkətɪv/", "sergap, ko\'p gapiradigan"],
        ["tow", "/toʊ/", "shatakka olmoq (avtomobilni)"],
        ["tramp", "/træmp/", "daydi kishi, daydib yuruvchi"],
      ]),
    ],

};
