import { Book, createUnit as unit } from "../book-types";

export const essential6: Book = {

    id: "4eew6",
    title: "4000 Essential English Words 6",
    subtitle: "Book 6",
    totalUnits: 30,
    units: [
      unit(1, [
        ["alleviate", "/əˈliviˌeɪt/", "yengillashtirmoq, kamaytirmoq"],
        ["astrology", "/əˈstrɑləʤi/", "astrologiya"],
        ["differentiate", "/ˌdɪfərˈɛnʧiˌeɪt/", "farqlamoq, ajratmoq"],
        ["disrupt", "/dɪsˈrəpt/", "putur yetkazmoq, buzmoq"],
        ["equation", "/ɪkˈweɪʒən/", "tenglama"],
        ["err", "/ɛr/", "xato qilmoq"],
        ["erroneous", "/ɛˈroʊniəs/", "xato, xatoli"],
        ["frantic", "/ˈfræntɪk/", "jazavaga tushgan, shoshinch"],
        ["hull", "/həl/", "kema korpusi"],
        ["inadvertent", "/ˌɪnədˈvərtənt/", "e\'tiborsiz, bexosdan qilingan"],
        ["improvise", "/ˌɪmprəˈvaɪz/", "tayyorgarliksiz bajarmoq"],
        ["latitude", "/ˈlætəˌtud/", "kenglik (geografik)"],
        ["mariner", "/ˈmɛrənər/", "dengizchi, matros"],
        ["multitude", "/ˈməltəˌtud/", "juda ko\'p, omma"],
        ["nuisance", "/ˈnusəns/", "ko\'ngilsizlik, g\'ashga tegadigan narsa"],
        ["permanence", "/ˈpərmənəns/", "doimiylik"],
        ["revolve", "/riˈvɑlv/", "aylanmoq, markazida tutmoq"],
        ["soothe", "/suð/", "tinchlantirmoq, ovutmoq"],
        ["stranded", "/ˈstrændɪd/", "qiyinchilikda qolgan, qarovsiz"],
        ["volatile", "/ˈvɑlətəl/", "o\'zgaruvchan, beqaror"],
      ]),
      unit(2, [
        ["arduous", "/ˈɑrʤuəs/", "qiyin, mashaqqatli"],
        ["attain", "/əˈteɪn/", "erishmoq, qo\'lga kiritmoq"],
        ["coexist", "/ˌkoʊəgˈzɪst/", "birga yashamoq"],
        ["conceive", "/kənˈsiv/", "tasavvur qilmoq, o\'ylab topmoq"],
        ["dubious", "/ˈdubiəs/", "shubhali, gumonli"],
        ["ego", "/ˈigoʊ/", "xudbinlik, kibr, ego"],
        ["elastic", "/ɪˈlæstɪk/", "elastik, cho\'ziluvchan"],
        ["endeavor", "/ɪnˈdɛvər/", "sa\'y-harakat, urinish"],
        ["engrave", "/ɪnˈgreɪv/", "o\'yib yozmoq/solmoq"],
        ["excavate", "/ˈɛkskəˌveɪt/", "qazimoq, kovlamoq"],
        ["jagged", "/ʤægd/", "o\'tkir, qirrali, g\'adir-budur"],
        ["locale", "/loʊˈkæl/", "voqea joyi, hudud"],
        ["mold", "/moʊld/", "qolip, qolipga solmoq"],
        ["outright", "/ˈaʊˈtraɪt/", "shak-shubhasiz, mutlaqo"],
        ["periphery", "/pərˈɪfəri/", "chet, chekka qismi"],
        ["plaster", "/ˈplæstər/", "ganch, gips, alebastr"],
        ["shovel", "/ˈʃəvəl/", "belkurak"],
        ["skeletal", "/ˈskɛlətəl/", "skeletga oid"],
        ["terrestrial", "/tərˈɛstriəl/", "yerga oid, quruqlikdagi"],
        ["vicious", "/ˈvɪʃəs/", "shafqatsiz, yovuz"],
      ]),
      unit(3, [
        ["absurd", "/əbˈsərd/", "mantiqsiz, be\'mani"],
        ["anemia", "/əˈnimiə/", "anemiya, kamqonlik"],
        ["aristocracy", "/ˌɛrəˈstɑkrəsi/", "aristokratiya, aslzodalar"],
        ["aristocrat", "/ərˈɪstəˌkræt/", "aristokrat, aslzoda"],
        ["attire", "/əˈtaɪər/", "hashamatli kiyim, libos"],
        ["craze", "/kreɪz/", "o\'tkinchi moda, hoyu-havas"],
        ["enlarge", "/ˌɛnˈlɑrʤ/", "kattalashtirmoq"],
        ["excess", "/ˈɛkˌsɛs/", "ortiqchalik, ortiqcha miqdor"],
        ["feminine", "/ˈfɛmənən/", "ayollarga xos"],
        ["hallmark", "/ˈhɑlˌmɑrk/", "asosiy belgi, hususiyat"],
        ["pad", "/pæd/", "yumshoq yostiqcha/to\'shakcha"],
        ["predominant", "/prɪˈdɑmənənt/", "ustun, hukmron"],
        ["reputable", "/ˈrɛpjətəbəl/", "obro\'li, nufuzli"],
        ["rouge", "/ruʒ/", "qizil yog\'upa (roja)"],
        ["signify", "/ˈsɪgnəˌfaɪ/", "anglatmoq, bildirmoq"],
        ["strap", "/stræp/", "tasma, qayish"],
        ["tangle", "/ˈtæŋgəl/", "chigal, tugun"],
        ["vanity", "/ˈvænɪti/", "manmanlik, kibr"],
        ["vie", "/vaɪ/", "raqobatlashmoq, bellashmoq"],
        ["vulgar", "/ˈvəlgər/", "beodob, qo\'pol, madaniyatsiz"],
      ]),
      unit(4, [
        ["attic", "/ˈætɪk/", "chordoq"],
        ["chunk", "/ʧəŋk/", "yirik bo\'lak"],
        ["civic", "/ˈsɪvɪk/", "shaharga oid, fuqarolik"],
        ["descent", "/dɪˈsɛnt/", "pastga tushish, pasayish"],
        ["din", "/dɪn/", "shovqin-suron, g\'ala-g\'ovur"],
        ["dissatisfy", "/dɪˈsætəsˌfaɪ/", "qoniqtirmaslik"],
        ["fuss", "/fəs/", "ovora bo\'lish, ortiqcha tashvish"],
        ["gourmet", "/ˈgʊrˌmeɪ/", "shirin/qimmatbaho taom"],
        ["hence", "/hɛns/", "shu sababli, shuning uchun"],
        ["intrinsic", "/ˌɪnˈtrɪnsɪk/", "ichki, negizdagi"],
        ["kettle", "/ˈkɛtəl/", "chovgun, choynak"],
        ["ministry", "/ˈmɪnɪstri/", "vazirlik"],
        ["ordeal", "/ɔrˈdil/", "og\'ir sinov, achchiq kechinma"],
        ["outspoken", "/ˈaʊtˈspoʊkən/", "samimiy, ochiqko\'ngil"],
        ["overwork", "/ˌoʊvərˈwərk/", "ortiqcha ishlatmoq/ishlamoq"],
        ["particular", "/ˌpɑˈtɪkjələr/", "maxsus, o\'ziga xos"],
        ["pungent", "/ˈpənʤənt/", "o\'tkir, achchiq (hid/tam)"],
        ["snore", "/snɔr/", "xurrak otmoq"],
        ["soundly", "/ˈsaʊndli/", "mahkam, qattiq, to\'liq"],
        ["superintendent", "/ˌsupərɪnˈtɛndənt/", "boshqaruvchi, nazoratchi"],
      ]),
      unit(5, [
        ["alternate", "/ˈɔltərˌneɪt/", "navbatlashmoq, almashtirmoq"],
        ["apologetic", "/əˌpɑləˈʤɛtɪk/", "uzr so\'ragan, xijolatli"],
        ["benign", "/bɪˈnaɪn/", "zararsiz, muloyim"],
        ["char", "/ʧɑr/", "kuydirmoq, qoraytirmoq"],
        ["clarify", "/ˈklɛrəˌfaɪ/", "oydinlashtirmoq, tushuntirmoq"],
        ["distress", "/dɪˈstrɛs/", "g\'am, tashvish, azob"],
        ["dogged", "/dɔgd/", "qat\'iyatli, o\'jar"],
        ["ensue", "/ɪnˈsu/", "orqasidan kelmoq, sodir bo\'lmoq"],
        ["gasp", "/gæsp/", "hansiramoq, havo yutmoq"],
        ["negotiate", "/nɪˈgoʊʃiˌeɪt/", "muzokara olib bormoq"],
        ["overdose", "/ˈoʊvərˌdoʊs/", "ortiqcha doza"],
        ["persuasion", "/pərsˈweɪʒən/", "ishontirish, ko\'ndirish"],
        ["relay", "/ˈriˌleɪ/", "estafeta musobaqasi"],
        ["reluctance", "/rɪˈləktəns/", "xohlamaslik, ikkilanish"],
        ["restate", "/riˈsteɪt/", "qayta ta\'kidlamoq"],
        ["sesame", "/ˈsɛsəmi/", "kunjut"],
        ["sip", "/sɪp/", "ho\'plamoq"],
        ["verge", "/vərʤ/", "bo\'sag\'a, arafasida bo\'lmoq"],
        ["wary", "/ˈwɛri/", "ehtiyotkor, hushyor"],
        ["waver", "/ˈweɪvər/", "ikkilanmoq, tebranmoq"],
      ]),
      unit(6, [
        ["ashore", "/əˈʃɔr/", "qirg\'oqqa, qirg\'oqda"],
        ["contradict", "/ˌkɑntrəˈdɪkt/", "inkor qilmoq, qarshi chiqmoq"],
        ["counterpart", "/ˈkaʊntərˌpɑrt/", "o\'xshash taraf, hamkasb, lavozimdoshi"],
        ["devoid", "/dɪˈvɔɪd/", "xoli, mavjud bo\'lmagan"],
        ["diverge", "/dɪˈvərʤ/", "bo\'linmoq, boshqa yo\'ldan ketmoq"],
        ["elude", "/ɪˈlud/", "chap bermoq, qochib qutilmoq"],
        ["embryo", "/ˈɛmbriˌoʊ/", "murtak, embrion"],
        ["fend", "/fɛnd/", "o\'zini himoya qilmoq, qaytarmoq"],
        ["fictitious", "/fɪkˈtɪʃəs/", "uydirma, soxta"],
        ["gazette", "/gəˈzɛt/", "gazeta, ro\'znoma"],
        ["homogeneous", "/ˌhoʊməˈʤiniəs/", "bir jinsli, bir xil"],
        ["obstruct", "/əbˈstrəkt/", "to\'smoq, g\'ov bo\'lmoq"],
        ["plunge", "/plənʤ/", "sho\'ng\'imoq, o\'zini tashlamoq"],
        ["prolong", "/prəˈlɔŋ/", "cho\'zmoq, uzaytirmoq"],
        ["publicize", "/ˈpəblɪˌsaɪz/", "reklama qilmoq, e\'lon qilmoq"],
        ["sparse", "/spɑrs/", "siyrak, oz"],
        ["surplus", "/ˈsərpləs/", "ortiqcha miqdor, zaxira"],
        ["theorize", "/θiəraɪz/", "nazariya yaratmoq"],
        ["verify", "/ˈvɛrəˌfaɪ/", "tasdiqlamoq, tekshirib ko\'rmoq"],
        ["vigorous", "/ˈvɪgərəs/", "g\'ayratli, kuchli"],
      ]),
      unit(7, [
        ["altar", "/ˈɔltər/", "mehrob, altar"],
        ["arthritis", "/ɑrθˈraɪtɪs/", "bo\'g\'im kasalligi, artrit"],
        ["botany", "/ˈbɑtəni/", "botanika"],
        ["credible", "/ˈkrɛdəbəl/", "ishonchli, ishonarli"],
        ["deceased", "/dɪˈsist/", "marhum, vafot etgan"],
        ["deception", "/dɪˈsɛpʃən/", "aldov, hiyla"],
        ["decipher", "/dɪˈsaɪfər/", "shifrni yechmoq, anglamoq"],
        ["dung", "/dəŋ/", "go\'ng, tezak"],
        ["dusk", "/dəsk/", "shom vaqti, g\'ira-shira"],
        ["gratify", "/ˈgrætəˌfaɪ/", "mamnun qilmoq, xursand qilmoq"],
        ["hone", "/hoʊn/", "charxlamoq, oshirmoq"],
        ["mash", "/mæʃ/", "mizg\'imoq, ezib tashlamoq"],
        ["ornate", "/ɔrˈneɪt/", "naqshinkor, bezatilgan"],
        ["pneumonia", "/nəˈmoʊnjə/", "pnevmoniya, zotiljam"],
        ["psychic", "/ˈsaɪkɪk/", "ekstrasensor, ruhiy"],
        ["psychotic", "/ˌsaɪˈkɑtɪk/", "ruhiy kasal"],
        ["scope", "/skoʊp/", "miqyos, ko\'lam"],
        ["sinister", "/ˈsɪnɪstər/", "vahimali, me\'yorsiz, mash\'um"],
        ["strife", "/straɪf/", "nizo, nizolashuv"],
        ["therapeutic", "/ˌθɛrəˈpjutɪk/", "davolovchi, terapevtik"],
      ]),
      unit(8, [
        ["congested", "/kənˈʤɛstɪd/", "tiqilinch, gavjum"],
        ["courier", "/ˈkəriər/", "kuryer, xat tashuvchi"],
        ["deform", "/ˌdiˈfɔrm/", "shaklini buzmoq"],
        ["etiquette", "/ˈɛtəkət/", "etiket, odob qoidalari"],
        ["exclusive", "/ɪkˈsklusɪv/", "eksklyuziv, maxsus"],
        ["freight", "/freɪt/", "yuk, yuk tashish"],
        ["garment", "/ˈgɑrmənt/", "kiyim-kechak"],
        ["insomnia", "/ˌɪnˈsɑmniə/", "uyqusizlik"],
        ["intuitive", "/ˌɪnˈtuətɪv/", "intuitiv, ichki hisga oid"],
        ["liable", "/ˈlaɪəbəl/", "ma\'sul, ehtimoli bor"],
        ["obsess", "/əbˈsɛs/", "xayolini egallab olmoq"],
        ["overboard", "/ˈoʊvərˌbɔrd/", "bort tashqarisiga"],
        ["premium", "/ˈprimiəm/", "qo\'shimcha haq, ustama"],
        ["privilege", "/ˈprɪvɪlɪʤ/", "imtiyoz, huquq"],
        ["propel", "/prəˈpɛl/", "harakatlantirmoq, itarmoq"],
        ["socialize", "/ˈsoʊʃəˌlaɪz/", "muloqotda bo\'lmoq"],
        ["suppress", "/səˈprɛs/", "bostirmoq, tiyib turmoq"],
        ["tram", "/træm/", "tramvay"],
        ["unsettle", "/ənˈsɛtəl/", "tashvishlantirmoq"],
        ["warp", "/wɔrp/", "qayrilmoq, qishaymoq"],
      ]),
      unit(9, [
        ["artery", "/ˈɑrtəri/", "arteriya qon tomiri"],
        ["deterioration", "/dɪˈtɪriərˌeɪʃən/", "yomonlashuv, yemirilish"],
        ["elusive", "/ɪˈlusɪv/", "tutqich bermas, qiyin topiladigan"],
        ["forage", "/ˈfɔrɪʤ/", "ozuqa izlamoq"],
        ["impede", "/ˌɪmˈpid/", "xalaqit bermoq, to\'sqinlik qilmoq"],
        ["induce", "/ˌɪnˈdus/", "keltirib chiqarmoq, sabab bo\'lmoq"],
        ["inseparable", "/ˌɪnˈsɛpərəbəl/", "ajralmas"],
        ["invalid", "/ˌɪnˈvæləd/", "yaroqsiz, noto\'g\'ri"],
        ["magnify", "/ˈmægnəˌfaɪ/", "kattalashtirmoq"],
        ["mainstream", "/ˈmeɪnˌstrim/", "ommaviy yo\'nalish"],
        ["microbe", "/ˈmaɪˌkroʊb/", "mikrob"],
        ["negligible", "/ˈnɛglɪʤəbəl/", "arzimas, juda oz"],
        ["paralysis", "/pərˈælɪsɪs/", "falajlik, shol bo\'lish"],
        ["pest", "/pɛst/", "zararkuranda"],
        ["prevail", "/prɪˈveɪl/", "ustun kelmoq, keng tarqalmoq"],
        ["respiration", "/ˌrɛspərˈeɪʃən/", "nafas olish"],
        ["rupture", "/ˈrəpʧər/", "yorilmoq, uzilmoq"],
        ["savage", "/ˈsævɪʤ/", "shafqatsiz, vahshiy"],
        ["stun", "/stən/", "karaxt qilmoq, hayratda qoldirmoq"],
        ["susceptible", "/səˈsɛptəbəl/", "beriluvchan, moyil"],
      ]),
      unit(10, [
        ["accumulate", "/əˈkjumjəˌleɪt/", "yig\'ilmoq, to\'planmoq"],
        ["aerial", "/ˈɛriəl/", "havodagi, havoga oid"],
        ["apparatus", "/ˌæpərˈætəs/", "apparat, qurilma"],
        ["avalanche", "/ˈævəˌlænʧ/", "qor ko\'chkisi"],
        ["consistency", "/kənˈsɪstənsi/", "barqarorlik, izchillik"],
        ["convection", "/kənˈvɛkʃən/", "konvektsiya (issiq havo oqimi)"],
        ["discharge", "/ˈdɪsˌʧɑrʤ/", "bo\'shatmoq (kasalxonadan)"],
        ["intact", "/ˌɪnˈtækt/", "shikastlanmagan, butun"],
        ["mortal", "/ˈmɔrtəl/", "o\'ladigan, faniymon"],
        ["omen", "/ˈoʊmən/", "alomat, belgi"],
        ["overcast", "/ˈoʊvərˌkæst/", "bulutli, qorong\'u"],
        ["poignant", "/ˈpɔɪnjənt/", "ta\'sirli, g\'amgin"],
        ["ranger", "/ˈreɪnʤər/", "o\'rmonchi, qo\'riqchi"],
        ["rubble", "/ˈrəbəl/", "vayronagarchilik chiqindisi, toshlar"],
        ["seclude", "/səˈklud/", "ajratmoq, yolg\'izlatmoq"],
        ["sideways", "/ˈsaɪdˌweɪz/", "yon tomonga"],
        ["sob", "/sɑb/", "hiqillab yig\'lamoq"],
        ["sober", "/ˈsoʊbər/", "bosiq, jiddiy, hushyor"],
        ["speck", "/spɛk/", "zarracha, dog\'cha"],
        ["upbringing", "/ˈəpˌbrɪŋɪŋ/", "tarbiya"],
      ]),
      unit(11, [
        ["advocate", "/ˈædvəˌkeɪt/", "qo\'llab-quvvatlamoq"],
        ["authorize", "/ˈɔθərˌaɪz/", "ruxsat bermoq, huquq bermoq"],
        ["civilian", "/səˈvɪljən/", "fuqaro (harbiy emas)"],
        ["commodity", "/kəˈmɑdəti/", "tovar, mahsulot"],
        ["conquest", "/ˈkɑŋkwɛst/", "fath etish, bosib olish"],
        ["disclose", "/dɪˈskloʊz/", "oshkor qilmoq"],
        ["dynamics", "/daɪˈnæmɪks/", "dinamika, o\'zaro ta\'sir"],
        ["enroll", "/ɪnˈroʊl/", "a\'zo bo\'lmoq, ro\'yxatdan o\'tmoq"],
        ["envious", "/ˈɛnviəs/", "hasadgo\'y"],
        ["euphoria", "/juˈfɔriə/", "eyforiya, juda katta quvonch"],
        ["festive", "/ˈfɛstɪv/", "bayramona"],
        ["jolly", "/ˈʤɑli/", "quvnoq, xushchaqchaq"],
        ["lentil", "/ˈlɛntəl/", "yasmiq"],
        ["marshal", "/ˈmɑrʃəl/", "to\'plamoq, safga tizmoq"],
        ["morale", "/məræl/", "ruhiyat, jangovar ruh"],
        ["prophecy", "/ˈprɑfəsi/", "bashorat"],
        ["sage", "/seɪʤ/", "donishmand"],
        ["senate", "/ˈsɛnɪt/", "senat"],
        ["sentiment", "/ˈsɛnəmənt/", "fikr, tuyg\'u"],
        ["unrest", "/ənˈrɛst/", "notinchlik, g\'alayon"],
      ]),
      unit(12, [
        ["adorn", "/əˈdɔrn/", "bezatmoq"],
        ["bliss", "/blɪs/", "rohat, baxtiyorlik"],
        ["butler", "/ˈbətlər/", "bosh xizmatkor"],
        ["cramp", "/kræmp/", "tomir tortishishi, spazm"],
        ["dilapidated", "/dɪˈlæpəˌdeɪtɪd/", "xarob bo\'lgan, eski"],
        ["evoke", "/ɪˈvoʊk/", "uyg\'otmoq (xotira/tuyg\'u)"],
        ["farewell", "/ˌfɛrˈwɛl/", "xayrlashuv"],
        ["faucet", "/ˈfɔsət/", "suv jo\'mragi"],
        ["filth", "/fɪlθ/", "kir, ifloslik"],
        ["flaw", "/flɔ/", "kamchilik, nuqson"],
        ["grin", "/grɪn/", "tirjaymoq, iljaymoq"],
        ["housekeeping", "/ˈhaʊˌskipɪŋ/", "uy-ro\'zg\'or tutish"],
        ["mound", "/maʊnd/", "uyum, do\'nglik"],
        ["numb", "/nəm/", "uvishgan, qotgan"],
        ["reckless", "/ˈrɛkləs/", "e\'tiborsiz, beparvo"],
        ["slate", "/sleɪt/", "shifer, tog\' jinsi"],
        ["stool", "/stul/", "taburetka"],
        ["testament", "/ˈtɛstəmənt/", "isbot, dalil"],
        ["timber", "/ˈtɪmbər/", "yog\'och, taxta"],
        ["valve", "/vælv/", "klapan, jo\'mrak valvi"],
      ]),
      unit(13, [
        ["certify", "/ˈsərtəˌfaɪ/", "tasdiqlamoq, guvohnoma bermoq"],
        ["collaborate", "/kəˈlæbərˌeɪt/", "hamkorlik qilmoq"],
        ["compile", "/kəmˈpaɪl/", "to\'plamoq, jamlamoq"],
        ["counteract", "/ˈkaʊntərˌækt/", "qarshi ta\'sir ko\'rsatmoq"],
        ["curb", "/kərb/", "jilovlamoq, cheklamoq"],
        ["diagnose", "/ˌdaɪəgˈnoʊs/", "tashxis qo\'ymoq"],
        ["enact", "/ɪˈnækt/", "qonun qabul qilmoq"],
        ["federation", "/ˌfɛdərˈeɪʃən/", "federatsiya, birlashma"],
        ["gross", "/groʊs/", "jirkanch, qo\'pol"],
        ["humane", "/hjuˈmeɪn/", "insonparvar, rahmdil"],
        ["intolerable", "/ˌɪnˈtɑlərəbəl/", "chidab bo\'lmas"],
        ["needy", "/ˈnidi/", "muhtoj, kambag\'al"],
        ["onset", "/ˈɔnˌsɛt/", "boshlanishi, xuruj"],
        ["pledge", "/plɛʤ/", "va\'da bermoq"],
        ["prohibit", "/proʊˈhɪbət/", "taqiqlamoq"],
        ["rash", "/ræʃ/", "toshma (terida)"],
        ["render", "/ˈrɛndər/", "holatga keltirmoq"],
        ["smallpox", "/sˈmɔlˌpɑks/", "chechak kasalligi"],
        ["transmit", "/trænzˈmɪt/", "yuqtirmoq, uzatmoq"],
        ["vow", "/vaʊ/", "qasam ichmoq"],
      ]),
      unit(14, [
        ["camouflage", "/ˈkæməˌflɑʒ/", "kamuflyaj, maskirovka"],
        ["contemplate", "/ˈkɑntəmˌpleɪt/", "o\'ylab ko\'rmoq, mushohada qilmoq"],
        ["contend", "/kənˈtɛnd/", "kurashmoq, olishmoq"],
        ["cot", "/kɑt/", "yig\'ma karavot, krovat"],
        ["enlist", "/ˌɛnˈlɪst/", "harbiy xizmatga kirmoq"],
        ["frontier", "/frənˈtɪr/", "chegara hududi"],
        ["handbook", "/ˈhændˌbʊk/", "qo\'llanma, yo\'riqnoma"],
        ["hesitant", "/ˈhɛzɪtənt/", "ikkilanayotgan"],
        ["lush", "/ləʃ/", "sertashvish, qalin o\'sadigan"],
        ["marrow", "/ˈmɛroʊ/", "ilik (suyakda)"],
        ["outfit", "/ˈaʊtˌfɪt/", "kiyim-kechak to\'plami"],
        ["paw", "/pɔ/", "panja"],
        ["quiver", "/kˈwɪvər/", "qaltiramoq, titramoq"],
        ["splendid", "/ˈsplɛndɪd/", "juda zo\'r, ajoyib"],
        ["stray", "/streɪ/", "adashib ketmoq"],
        ["substantial", "/səbˈstænʃəl/", "katta, sezilarli"],
        ["torch", "/tɔrʧ/", "mash\'ala, fonar"],
        ["tract", "/trækt/", "keng maydon, hudud"],
        ["vigil", "/ˈvɪʤəl/", "tungi poyloqchilik"],
        ["weary", "/ˈwɪri/", "charchagan, xorigan"],
      ]),
      unit(15, [
        ["adhere", "/əˈdhɪr/", "amal qilmoq, bo\'ysunmoq"],
        ["administer", "/ədˈmɪnɪstər/", "boshqarmoq, bermoq (dori)"],
        ["compassionate", "/kəmˈpæʃənət/", "rahmdil, hamdard"],
        ["contaminate", "/kənˈtæməˌneɪt/", "ifloslantirmoq"],
        ["deficiency", "/dɪˈfɪʃənsi/", "yetishmovchilik, tanqislik"],
        ["epidemic", "/ˌɛpɪˈdɛmɪk/", "epidemiya"],
        ["hazard", "/ˈhæzərd/", "xavf-xatar"],
        ["imperative", "/ˌɪmˈpɛrətɪv/", "o\'ta muhim, shart bo\'lgan"],
        ["intestines", "/ˌɪnˈtɛstənz/", "ichaklar"],
        ["manifest", "/ˈmænəˌfɛst/", "namoyon bo\'lmoq, ko\'rinmoq"],
        ["metabolic", "/ˌmɛtəˈbɑlɪk/", "metabolik, moddalar almashinuviga oid"],
        ["overcrowded", "/ˈoʊvərˌkraʊdɪd/", "gavjum, odam to\'la"],
        ["paramount", "/ˈpɛrəˌmaʊnt/", "eng muhim, birinchi darajali"],
        ["practitioner", "/prækˈtɪʃənər/", "shifokor"],
        ["provision", "/prəˈvɪʒən/", "ta\'minot, yetkazib berish"],
        ["replenish", "/riˈplɛnɪʃ/", "to me\'yorig\'a keltirmoq, to\'ldirmoq"],
        ["sterile", "/ˈstɛrəl/", "sterillangan, toza"],
        ["upgrade", "/ˈəpˈgreɪd/", "yaxshilamoq, darajasini oshirmoq"],
        ["viable", "/ˈvaɪəbəl/", "hayotiy, amalga oshirsa bo\'ladigan"],
        ["voluntary", "/ˈvɑləntɛri/", "ko\'ngilli, ixtiyoriy"],
      ]),
      unit(16, [
        ["amid", "/əˈmɪd/", "orasida, o\'rtasida"],
        ["backstage", "/ˈbækˈsteɪʤ/", "sahna ortida"],
        ["billionaire", "/ˌbɪljəˈnɛr/", "milliarder"],
        ["brute", "/brut/", "qo\'pol/vahshiy odam"],
        ["clumsy", "/ˈkləmzi/", "e\'tiborsiz, noaniq harakat qiluvchi"],
        ["collide", "/kəˈlaɪd/", "to\'qnashmoq"],
        ["culprit", "/ˈkəlprɪt/", "aybdor, jinoyatchi"],
        ["evacuate", "/ɪˈvækjəˌeɪt/", "evakuatsiya qilmoq"],
        ["flammable", "/ˈflæməbəl/", "tez yonuvchan"],
        ["mob", "/mɑb/", "olomon, to\'da"],
        ["premature", "/ˌpriməˈʧʊr/", "vaqtidan ilgari"],
        ["resent", "/rɪˈzɛnt/", "g\'azablanmoq, xafa bo\'lmoq"],
        ["satire", "/ˈsæˌtaɪər/", "satira, kulgili asar"],
        ["scrutiny", "/ˈskrutəni/", "sinchkovlik bilan tekshirish"],
        ["segregate", "/ˈsɛgrəˌgeɪt/", "ajratmoq, guruhlamoq"],
        ["subject", "/ˈsəbʤɪkt/", "duchor qilmoq, bo\'ysundirmoq"],
        ["testify", "/ˈtɛstɪˌfaɪ/", "guvohlik bermoq"],
        ["tumult", "/ˈtuməlt/", "shovqin-suron, to\'polon"],
        ["underestimate", "/ˈəndərˈɛstəˌmeɪt/", "past baholamoq"],
        ["uproar", "/ˈəˌprɔr/", "g\'alayon, baqir-chaqir"],
      ]),
      unit(17, [
        ["accelerate", "/ækˈsɛlərˌeɪt/", "tezlashmoq"],
        ["anew", "/əˈnu/", "qaytadan, yangitdan"],
        ["defect", "/ˈdifɛkt/", "nuqson, nuqsonli joy"],
        ["dreary", "/ˈdrɪri/", "g\'amgin, zerikarli"],
        ["duplicate", "/ˈdupləˌkeɪt/", "nusxasini olmoq"],
        ["electromagnetic", "/ˌɪˌlɛktroʊmægˈnɛtɪk/", "elektromagnit..."],
        ["electron", "/ˌɪˈlɛktrɑn/", "elektron"],
        ["glide", "/glaɪd/", "sirpanmoq, parvoz qilmoq"],
        ["ingenious", "/ˌɪnˈʤinjəs/", "juda aqlli, dohiyoniy"],
        ["innovation", "/ˌɪnəˈveɪʃən/", "innovatsiya, yangilik"],
        ["innovative", "/ˈɪnəˌveɪtɪv/", "innovatsion, yangicha"],
        ["launch", "/lɔnʧ/", "uchirmoq, yo\'lga qo\'ymoq"],
        ["meteorological", "/ˌmitiˌɔrəˈlɑʤɪkəl/", "meteorologik, ob-havoga oid"],
        ["meteorology", "/ˌmitiərˈɑləʤi/", "meteorologiya"],
        ["penetrate", "/ˈpɛnəˌtreɪt/", "yorib kirmoq, ichiga kirmoq"],
        ["propulsion", "/prəˈpəlʃən/", "harakatlantiruvchi kuch"],
        ["simulate", "/ˈsɪmjəˌleɪt/", "xuddi shunday taqlid qilmoq"],
        ["spur", "/spər/", "rag\'batlantirmoq, turtki bermoq"],
        ["stimulate", "/ˈstɪmjəˌleɪt/", "faollashtirmoq, qo\'zg\'atmoq"],
        ["tenacious", "/təˈneɪʃəs/", "qat\'iyatli, bo\'sh kelmaydigan"],
      ]),
      unit(18, [
        ["beforehand", "/bɪˈfɔˌrhænd/", "oldindan, avvaldan"],
        ["centigrade", "/ˈsɛntəˌgreɪd/", "Selsiy darajasi"],
        ["chatter", "/ˈʧætər/", "valdiramoq, ko\'p gapirmoq"],
        ["concerto", "/kənˈʧɛrtoʊ/", "kontsert (musiqiy asar)"],
        ["condense", "/kənˈdɛns/", "quyuqlashmoq, suvga aylanmoq"],
        ["cove", "/koʊv/", "kichik ko\'rfaz"],
        ["deteriorate", "/dɪˈtɪriərˌeɪt/", "yomonlashmoq"],
        ["exterior", "/ɪkˈstɪriər/", "tashqi ko\'rinish/sirt"],
        ["freeway", "/ˈfriˌweɪ/", "katta magistral yo\'l"],
        ["hearty", "/ˈhɑrti/", "samimiy, quvnoq"],
        ["hospitable", "/ˈhɑˈspɪtəbəl/", "mehmondo\'st"],
        ["manor", "/ˈmænər/", "katta hovli, yer-mulk"],
        ["monastery", "/ˈmɑnəˌstɛri/", "monastir"],
        ["nursery", "/ˈnərsəri/", "bolalar xonasi/bog\'chasi"],
        ["outstretched", "/aʊtˈstrɛʧt/", "uzatilgan, yozilgan"],
        ["parcel", "/ˈpɑrsəl/", "posylka, tugun"],
        ["profile", "/ˈproʊˌfaɪl/", "yon tomondan ko\'rinish, profil"],
        ["vivacious", "/vəˈveɪʃəs/", "quvnoq, kirishimli"],
        ["winding", "/ˈwaɪndɪŋ/", "egri-bugri yo\'l"],
        ["zip", "/zɪp/", "zamokni yopmoq"],
      ]),
      unit(19, [
        ["airway", "/ˈɛrˌweɪ/", "nafas yo\'li"],
        ["Almighty", "/ɔlˈmaɪti/", "Egamiz, Xudo"],
        ["advent", "/ˈædˌvɛnt/", "kelish, paydo bo\'lish"],
        ["constellation", "/ˌkɑnstəˈleɪʃən/", "yulduzlar turkumi"],
        ["definitive", "/dɪˈfɪnɪtɪv/", "yakuniy, aniq"],
        ["equate", "/ɪkˈweɪt/", "tenglashtirmoq, solishtirmoq"],
        ["inhale", "/ˌɪnˈheɪl/", "nafas olmoq, ichga tortmoq"],
        ["invoke", "/ˌɪnˈvoʊk/", "yordamga chaqirmoq, tilga olmoq"],
        ["lunar", "/ˈlunər/", "oyga oid"],
        ["novelty", "/ˈnɑvəlti/", "yangilik, g\'ayrioddiylik"],
        ["outmoded", "/ˌaʊtˈmoʊdɪd/", "urfdan qolgan, eski"],
        ["personalize", "/ˈpərsənəˌlaɪz/", "shaxsiylashtirmoq"],
        ["pertain", "/pərˈteɪn/", "tegishli bo\'lmoq"],
        ["primal", "/ˈpraɪməl/", "azaliy, ibtidoiy"],
        ["psychiatric", "/ˌsaɪkiˈætrɪk/", "psixiatrik"],
        ["psychiatry", "/sɪˈkaɪətri/", "psixiatriya"],
        ["reflex", "/ˈriflɛks/", "refleks, beixtiyor harakat"],
        ["seizure", "/ˈsiʒər/", "tutqanoq, xuruj"],
        ["session", "/ˈsɛʃən/", "seans, uchrashuv"],
        ["utensil", "/juˈtɛnsəl/", "idish-tovoq, qurol"],
      ]),
      unit(20, [
        ["adhesive", "/əˈdhisɪv/", "yopishqoq modda, yelim"],
        ["adverse", "/ˌædˈvərs/", "salbiy, zararli"],
        ["dependency", "/dɪˈpɛndənsi/", "qaramlik, ehtiyoj"],
        ["dump", "/dəmp/", "tashlab yubormoq"],
        ["eternal", "/ɪˈtərnəl/", "abadiy, me\'yorsiz"],
        ["fluctuate", "/ˈfləkʧəˌweɪt/", "o\'zgarib turmoq, beqaror bo\'lmoq"],
        ["fro", "/froʊ/", "orqaga (to and fro)"],
        ["inclusion", "/ˌɪnˈkluʒən/", "qo\'shish, kiritish"],
        ["intermediate", "/ˌɪnərˈmidiɪt/", "o\'rta darajadagi"],
        ["intermittent", "/ˌɪntərˈmɪtənt/", "vaqti-vaqti bilan bo\'ladigan"],
        ["mentor", "/ˈmɛnˌtɔr/", "ustoz, maslahatchi"],
        ["phoenix", "/ˈfinɪks/", "Samandar qushi, Feniks"],
        ["photosynthesis", "/ˌfoʊtoʊˈsɪnθəsɪs/", "fotosintez"],
        ["pollen", "/ˈpɑlən/", "chang (guldagi)"],
        ["regain", "/rɪˈgeɪn/", "qayta tiklamoq"],
        ["reverse", "/rɪˈvərs/", "teskari tomonga o\'zgartirmoq"],
        ["swarm", "/swɔrm/", "gala, to\'da (hasharotlar)"],
        ["texture", "/ˈtɛksʧər/", "faktura, sirt tuzilishi"],
        ["tickle", "/ˈtɪkəl/", "qitiqlamoq"],
        ["vibrant", "/ˈvaɪbrənt/", "yorqin, jonli"],
      ]),
      unit(21, [
        ["abolish", "/əˈbɑlɪʃ/", "bekor qilmoq (qonunni)"],
        ["amend", "/əˈmɛnd/", "o\'zgartirish kiritmoq, tuzatmoq"],
        ["aspire", "/əˈspaɪr/", "intilmoq, orzu qilmoq"],
        ["censor", "/ˈsɛnsər/", "tsenzura qilmoq"],
        ["charter", "/ˈʧɑrtər/", "nizom, xartiya"],
        ["constitution", "/ˌkɑnstəˈtuʃən/", "konstitutsiya"],
        ["cosmopolitan", "/ˌkɑzməˈpɑlətən/", "kosmopolit, turli millatli"],
        ["disseminate", "/dɪˈsɛməˌneɪt/", "tarqatmoq (axborotni)"],
        ["flatter", "/ˈflætər/", "xushomad qilmoq"],
        ["infamous", "/ˈɪnfəməs/", "yomon nom chiqargan"],
        ["lame", "/leɪm/", "oqsog\'lanadigan, cho\'loq"],
        ["limp", "/lɪmp/", "oqsamoq"],
        ["outburst", "/ˈaʊtˌbərst/", "birdaniga portlash (xissiyot)"],
        ["pathological", "/ˌpæθəˈlɑʤɪkəl/", "patologik, kasallikka oid"],
        ["phenomenal", "/fəˈnɑmənəl/", "favqulodda, ajoyib"],
        ["poll", "/poʊl/", "so\'rovnoma"],
        ["remorse", "/rɪˈmɔrs/", "afsuslanish, pushaymonlik"],
        ["secrecy", "/ˈsikrəsi/", "maxfiylik"],
        ["tackle", "/ˈtækəl/", "hal qilmoq, kirishmoq"],
        ["trance", "/træns/", "trans, gipnoz holati"],
      ]),
      unit(22, [
        ["coward", "/kaʊərd/", "qo\'rqoq kishi"],
        ["delete", "/dɪˈlit/", "o\'chirib tashlamoq"],
        ["firsthand", "/ˈfərsthænd/", "bevosita, birinchi qo\'ldan"],
        ["earnest", "/ˈərnɪst/", "samimiy, jiddiy"],
        ["ethnic", "/ˈɛθnɪk/", "etnik, milliy"],
        ["exclude", "/ɪkˈsklud/", "chiqartirib tashlamoq, qo\'shmaslik"],
        ["fluent", "/fluənt/", "ravon gapiradigan"],
        ["imperial", "/ˌɪmˈpɪriəl/", "imperiyaga oid"],
        ["inclusive", "/ˌɪnˈklusɪv/", "qamrab oluvchi, hamma uchun"],
        ["legislature", "/ˈlɛʤəsˌleɪʧər/", "qonun chiqaruvchi organ"],
        ["linguistic", "/lɪŋgˈwɪstɪk/", "lingvistik, tilga oid"],
        ["monolingual", "/ˌmɑnəˈlɪŋgwəl/", "bir tilli"],
        ["nationality", "/ˌnæʃəˈnælɪti/", "millat, fuqarolik"],
        ["patriot", "/ˈpeɪtriət/", "vatanparvar"],
        ["prosecute", "/ˈprɑsəˌkjut/", "sudga bermoq"],
        ["racial", "/ˈreɪʃəl/", "irqiy"],
        ["solemn", "/ˈsɑləm/", "jiddiy, rasmiy"],
        ["solidarity", "/ˌsɑləˈdɛrəti/", "hamjihatlik, birlik"],
        ["tact", "/tækt/", "muomala odobi, takt"],
        ["undermining", "/ˈəndərˌmaɪnɪŋ/", "zaiflashtirmoq, obro\'sizlantirmoq"],
      ]),
      unit(23, [
        ["allocate", "/ˈæləˌkeɪt/", "ajratmoq (mablag\'/resurs)"],
        ["appetizing", "/ˈæpɪˌtaɪzɪŋ/", "ishtahani ochadigan"],
        ["blizzard", "/ˈblɪzərd/", "kuchli qor bo\'roni"],
        ["cavity", "/ˈkævəti/", "bo\'shliq, g\'ovak"],
        ["clockwise", "/ˈklɑkˌwaɪz/", "soat mili bo\'ylab"],
        ["concentric", "/kənˈsɛntrɪk/", "markazdash (aylanalar)"],
        ["courtesy", "/ˈkərtəsi/", "xushmuomalalik, iltifot"],
        ["crisp", "/krɪsp/", "qarsillaydigan, yangi"],
        ["discord", "/ˈdɪskɔrd/", "nizo, kelishmovchilik"],
        ["frigid", "/ˈfrɪʤəd/", "juda sovuq, muzdek"],
        ["generate", "/ˈʤɛnərˌeɪt/", "yaratmoq, hosil qilmoq"],
        ["glacial", "/ˈgleɪʃəl/", "muzlikka oid"],
        ["interchange", "/ˌɪnərˈʧeɪnʤ/", "fikr almashinuvi"],
        ["locker", "/ˈlɑkər/", "shkafcha (qulflanadigan)"],
        ["multicultural", "/ˌməltiˈkəlʧərəl/", "ko\'p madaniyatli"],
        ["omission", "/oʊˈmɪʃən/", "qolib ketish, tushirib qoldirish"],
        ["oversee", "/ˈoʊvərˌsi/", "nazorat qilmoq"],
        ["pierce", "/pɪrs/", "teshmoq, sanchmoq"],
        ["replicate", "/ˈrɛplɪˌkeɪt/", "aynan nusxa ko\'chirmoq"],
        ["wavy", "/ˈweɪvi/", "to\'lqinsimon"],
      ]),
      unit(24, [
        ["abide", "/əˈbaɪd/", "bo\'ysunmoq, amal qilmoq"],
        ["conversion", "/kənˈvərʒən/", "o\'zgarish, boshqa shaklga o\'tish"],
        ["cram", "/kræm/", "tiqishtirmoq, tiqib qo\'ymoq"],
        ["defer", "/dɪˈfər/", "kechiktirmoq"],
        ["export", "/ˈɛkspɔrt/", "eksport qilmoq"],
        ["fume", "/fjum/", "tutun, zaharli gaz"],
        ["habitual", "/həˈbɪʧuəl/", "odatiy"],
        ["justify", "/ˈʤəstəˌfaɪ/", "oqlamoq, asoslab bermoq"],
        ["output", "/ˈaʊtˌpʊt/", "mahsulot hajmi, unumdorlik"],
        ["overpopulation", "/ˌoʊvərˌpɑpjəˈleɪʃən/", "aholi oshib ketishi"],
        ["patent", "/ˈpætənt/", "patent, mualliflik huquqi"],
        ["penalize", "/ˈpɛnəˌlaɪz/", "jazolamoq"],
        ["petroleum", "/pəˈtroʊliəm/", "neft"],
        ["prototype", "/ˈproʊtoʊˌtaɪp/", "prototip, dastlabki nusxa"],
        ["scrap", "/skræp/", "parcha, bo\'lak, temir-tersak"],
        ["sector", "/ˈsɛktər/", "soha, sektor"],
        ["subscribe", "/səbˈskraɪb/", "qo\'shilmoq (fikrga), obuna bo\'lmoq"],
        ["subsist", "/səbˈsɪst/", "kun kechirmoq"],
        ["suspend", "/səˈspɛnd/", "vaqtincha to\'xtatmoq"],
        ["synthesis", "/ˈsɪnθəsəs/", "sintez, birlashma"],
      ]),
      unit(25, [
        ["acrobat", "/ˈækrəˌbæt/", "akrobat"],
        ["advocacy", "/ˈædvəkəsi/", "qo\'llab-quvvatlash, targ\'ibot"],
        ["communal", "/kəmˈjunəl/", "jamoat, umumiy"],
        ["fluid", "/fluɪd/", "ravon, silliq harakatlanuvchi"],
        ["harmonize", "/ˈhɑrməˌnaɪz/", "uyg\'unlashmoq"],
        ["industrious", "/ˌɪnˈdəstriəs/", "mehnatsevar, tirishqoq"],
        ["inventive", "/ˌɪnˈvɛntɪv/", "ijodkor, kashfiyotchi"],
        ["judicial", "/ʤuˈdɪʃəl/", "sudga oid"],
        ["Mandarin", "/ˈmændərən/", "Xitoy tili (Mandarinchaga oid)"],
        ["metropolitan", "/ˌmɛtrəˈpɑlətən/", "katta shaharga oid"],
        ["mimic", "/ˈmɪmɪk/", "taqlid qilmoq"],
        ["misguided", "/mɪsˈgaɪdɪd/", "xato fikrdagi, adashgan"],
        ["rehearse", "/riˈhərs/", "repetitsiya qilmoq"],
        ["scorn", "/skɔrn/", "mensimaslik, nafrat bilan qaramoq"],
        ["sensory", "/ˈsɛnsəri/", "sezgi organlariga oid"],
        ["staple", "/ˈsteɪpəl/", "asosiy, standart"],
        ["statute", "/ˈstæʧut/", "rasmiy qonun, statut"],
        ["veteran", "/ˈvɛtərən/", "faxriy, tajribali kishi"],
        ["villain", "/ˈvɪlən/", "yovuz personaj, jinoyatchi"],
        ["vine", "/vaɪn/", "chirmashuvchi o\'simlik, pechak"],
      ]),
      unit(26, [
        ["constrain", "/kənˈstreɪn/", "cheklamoq, cheklab qo\'ymoq"],
        ["depot", "/ˈdipoʊ/", "vokzal, depo"],
        ["emulate", "/ˈɛmjəˌleɪt/", "taqlid qilmoq, havas qilmoq"],
        ["forefinger", "/ˈfɔrˌfɪŋgər/", "ko\'rsatkich barmoq"],
        ["guts", "/gəts/", "ichki a\'zolar, jasorat"],
        ["inherent", "/ˌɪnˈhɛrənt/", "xos, ajralmas qism"],
        ["intimidate", "/ˌɪnˈtɪmɪˌdeɪt/", "qo\'rqitmoq, do\'q qilmoq"],
        ["janitor", "/ˈʤænətər/", "farrosh, koridor nazoratchisi"],
        ["moist", "/mɔɪst/", "nam, xo\'l"],
        ["nope", "/noʊp/", "yo\'q (norasmiy)"],
        ["prod", "/prɑd/", "turtmoq, itarmoq"],
        ["ransom", "/ˈrænsəm/", "tovon puli"],
        ["restrain", "/riˈstreɪn/", "bostirmoq, ushlab turmoq"],
        ["saliva", "/səˈlaɪvə/", "soley, tuproq"],
        ["spit", "/spɪt/", "tupurmoq"],
        ["sprint", "/sprɪnt/", "tez chopmoq"],
        ["stunt", "/stənt/", "tryuk, diqqat tortuvchi harakat"],
        ["tolerant", "/ˈtɑlərənt/", "bag\'rikeng, chidamli"],
        ["vampire", "/ˈvæmpaɪr/", "vampir"],
        ["yawn", "/jɔn/", "esnamoq"],
      ]),
      unit(27, [
        ["analogy", "/əˈnæləʤi/", "o\'xshatish, analogiya"],
        ["ancestry", "/ˈænsɛstri/", "nasl-nasab, ajdodlar"],
        ["archer", "/ˈɑrʧər/", "kamondan otuvchi"],
        ["conspiracy", "/kənˈspɪrəsi/", "fitna, til biriktirish"],
        ["deputy", "/ˈdɛpjəti/", "o\'rinbosar, o\'rinbosari"],
        ["earl", "/ərl/", "graf (unvon)"],
        ["fragrant", "/ˈfreɪgrənt/", "xushbo\'y"],
        ["funnel", "/ˈfənəl/", "voronka, quyg\'ich"],
        ["hereditary", "/hərˈɛdəˌtɛri/", "nasliy, irsiy"],
        ["hymn", "/hɪm/", "madhiya, diniy qo\'shiq"],
        ["invert", "/ˌɪnˈvərt/", "ag\'darib qo\'ymoq"],
        ["prey", "/preɪ/", "o\'lja"],
        ["procession", "/prəˈsɛʃən/", "yurish, tantanali saf"],
        ["prophet", "/ˈprɑfət/", "payg\'ambar"],
        ["sarcastic", "/sɑrˈkæstɪk/", "kesatikli, pichingli"],
        ["seasoning", "/ˈsizənɪŋ/", "ziravorlar"],
        ["sodium", "/ˈsoʊdiəm/", "natriy"],
        ["tyranny", "/ˈtɪrəni/", "tiraniya, zolimlik"],
        ["tyrant", "/ˈtaɪrənt/", "zolim, tiran"],
        ["vinegar", "/ˈvɪnəgər/", "sirka"],
      ]),
      unit(28, [
        ["adjoining", "/əˈʤɔɪnɪŋ/", "qo\'shni, tutash"],
        ["allege", "/əˈlɛʤ/", "asossiz ayblamoq/ta\'kidlamoq"],
        ["arch", "/ɑrʧ/", "rawoq, arka"],
        ["assemble", "/əˈsɛmbəl/", "to\'planmoq, yig\'ilmoq"],
        ["casualty", "/ˈkæʒəwəlti/", "qurbon, talafot ko\'rgan kishi"],
        ["erect", "/ɪˈrɛkt/", "qurmoq, tiklamoq"],
        ["foul", "/faʊl/", "juda yoqimsiz, sassiq"],
        ["hectare", "/ˈhɛkˌtɑr/", "gektar"],
        ["heighten", "/ˈhaɪtən/", "kuchaytirmoq, oshirmoq"],
        ["hospitality", "/ˌhɑspəˈtæləti/", "mehmondo\'stlik"],
        ["mansion", "/ˈmænʃən/", "hashamatli hovli/saroy"],
        ["outnumber", "/aʊtˈnəmbər/", "son jihatdan ko\'p bo\'lmoq"],
        ["overjoyed", "/ˌoʊvərˈʤɔɪd/", "juda xursand"],
        ["pasture", "/ˈpæsʧər/", "o\'tloq, yaylov"],
        ["petition", "/pəˈtɪʃən/", "petitsiya, yozma murojaat"],
        ["renovate", "/ˈrɛnəˌveɪt/", "ta\'mirlamoq, yangilamoq"],
        ["revise", "/rɪˈvaɪz/", "qayta ko\'rib chiqmoq"],
        ["slab", "/slæb/", "plita, qalin bo\'lak"],
        ["terrace", "/ˈtɛrəs/", "terrasa, ayvon"],
        ["turf", "/tərf/", "maysazor, maysa qatlami"],
      ]),
      unit(29, [
        ["analogous", "/əˈnæləgəs/", "o\'xshash, o\'xshash bo\'lgan"],
        ["binoculars", "/bəˈnɑkjələrz/", "durbin"],
        ["bulk", "/bəlk/", "katta qismi, ulkan hajm"],
        ["comprise", "/kəmˈpraɪz/", "tashkil topmoq, iborat bo\'lmoq"],
        ["depict", "/dɪˈpɪkt/", "tasvirlamoq"],
        ["dual", "/duəl/", "ikki yo\'nalishli, ikki hissali"],
        ["Fahrenheit", "/ˈfɛrənˌhaɪt/", "Farengeyt shkalasi"],
        ["fulfill", "/fʊlˈfɪl/", "bajarmoq, amalga oshirmoq"],
        ["grove", "/groʊv/", "daraxtzor, kichik o\'rmon"],
        ["ore", "/ɔr/", "ma\'dan, ruda"],
        ["outback", "/ˈaʊtˌbæk/", "cho\'l hududi (Avstraliya)"],
        ["outweigh", "/ˈaʊtˌweɪ/", "ustun kelmoq (muhimlikda)"],
        ["paradox", "/ˈpɛrəˌdɑks/", "paradoks, mantiqsiz kabi ko\'ringan haqiqat"],
        ["pier", "/pɪr/", "pirs, kema to\'xtash joyi"],
        ["shortcut", "/ˈʃɔrtˌkət/", "qisqa yo\'l"],
        ["tariff", "/ˈtɛrəf/", "tarif, bojxona to\'lovi"],
        ["thermometer", "/θərˈmɑmətər/", "termometr"],
        ["tilt", "/tɪlt/", "egmoq, qiyshaytirmoq"],
        ["vice versa", "/vaɪs ˈvərsə/", "aksincha, aks holda"],
        ["whereabouts", "/ˈwɛrəˌbaʊts/", "turgan joyi, manzili"],
      ]),
      unit(30, [
        ["amber", "/ˈæmbər/", "qahrabo, kahrabo"],
        ["charcoal", "/ˈʧɑrˌkoʊl/", "yog\'och ko\'miri"],
        ["columnist", "/ˈkɑləmnəst/", "kolumnist, maqolachi"],
        ["courteous", "/ˈkərtiəs/", "xushmuomala, xushfe\'l"],
        ["credentials", "/krəˈdɛnʃəlz/", "hujjatlar, malaka isboti"],
        ["cricket", "/ˈkrɪkɪt/", "chigirtka"],
        ["delta", "/ˈdɛltə/", "delta (daryo quyilish joyi)"],
        ["detergent", "/dɪˈtərʤənt/", "kir yuvish kukuni"],
        ["euphemism", "/ˈjufəˌmɪzəm/", "yuvoshroq so\'z (evfemizm)"],
        ["expire", "/ɪkˈspaɪr/", "muddati tugamoq"],
        ["granite", "/ˈgrænɪt/", "granit toshi"],
        ["gravel", "/ˈgrævəl/", "shag\'al"],
        ["haunt", "/hɔnt/", "tinchlik bermaslik, tez-tez kelmoq"],
        ["liberal", "/ˈlɪˌbərəl/", "liberal, keng fikrlaydigan"],
        ["maze", "/meɪz/", "labirint"],
        ["moss", "/mɔs/", "mox, yo\'sin"],
        ["pebble", "/ˈpɛbəl/", "mayda tosh, shag\'al toshi"],
        ["peck", "/pɛk/", "cho\'qimoq (qush)"],
        ["reservoir", "/ˈrɛzəvˌwɑr/", "suv ombori"],
        ["streak", "/strik/", "yo\'l-yo\'l chiziq, iz"],
      ]),
    ],
 
};
