import { Book, createUnit as unit } from "../book-types";

export const oxfordAdvanced: Book = {
  id: "ows_advanced",
  title: "Oxford Word Skills Advanced",
  subtitle: "Advanced",
  totalUnits: 80,
  units: [
    unit(1, [
      ["synonymous", "/səˈnɑnəməs/", "sinonim, ma\'nodosh"],
      ["sense", "/sɛns/", "ma\'no, tushuncha"],
      ["interchangeable", "/ˌɪnərˈʧeɪnʤəbəl/", "o\'rnini almashtirib bo\'ladigan"],
      ["ambiguous", "/æmˈbɪgjuəs/", "ikki ma\'noli, tushunarsiz"],
      ["interpret", "/ˌɪnˈtərprət/", "talqin qilmoq, tushunmoq"],
      ["transparent", "/trænˈspɛrənt/", "tiniq, tushunarli"],
      ["self-explanatory", "/self-explanatory*/", "o\'z-o\'zidan tushunarli"],
      ["precise", "/prɪˈsaɪs/", "aniq, aniq-tiniq"],
      ["virtually", "/ˈvərʧuəli/", "amalda, deyarli"],
      ["irony", "/ˈaɪrəni/", "istehzo, kinoya"],
      ["sarcasm", "/ˈsɑrˌkæzəm/", "zaharxanda, kesatiq"],
      ["figurative", "/ˈfɪgjərətɪv/", "ko\'chma ma\'noli"],
      ["literal", "/ˈlɪtərəl/", "to\'g\'ridan-to\'g\'ri (asl) ma\'noli"],
      ["pejorative", "/pəˈʤɔrətɪv/", "salbiy ma\'no beruvchi"],
      ["insulting", "/ˌɪnˈsəltɪŋ/", "haqoratli"],
    ], 'I can talk about meaning and style', 'Expanding your vocabulary'),
    unit(2, [
      ["crawl", "/krɔl/", "sekin harakatlanmoq, sudralmoq"],
      ["have second thoughts", "/hæv ˈsɛkənd θɔts/", "ikkilanib qolmoq, fikridan qaytmoq"],
      ["be in two minds", "/bi ɪn tu maɪndz/", "ikki o\'rtada ikkilanib turmoq"],
      ["sweet", "/swit/", "yoqimli, mehribon"],
      ["be tied up", "/bi taɪd əp/", "band bo\'lmoq"],
      ["dawn on", "/dɔn ɔn/", "anglab yetmoq, tushuna boshlamoq"],
      ["ulterior motive", "/əlˈtɪriər ˈmoʊtɪv/", "yashirin maqsad"],
      ["thick", "/θɪk/", "kaltafahm, ahmoq (norasmiy)"],
      ["get out of", "/gɪt aʊt əv/", "qutulmoq, chetlab o\'tmoq"],
      ["get", "/gɪt/", "majburlamoq, ko\'ndirmoq"],
      ["keep", "/kip/", "saqlanmoq, yangi holatda qolmoq"],
      ["put", "/pʊt/", "ifodalamoq, so\'z bilan aytmoq"],
      ["push", "/pʊʃ/", "majburlamoq, qattiq harakat qildirmoq"],
    ], 'I can use familiar words in a new way', 'Expanding your vocabulary'),
    unit(3, [
      ["driving licence", "/ˈdraɪvɪŋ ˈlaɪsəns/", "haydovchilik guvohnomasi"],
      ["birth certificate", "/bərθ sərˈtɪfɪkət/", "tug\'ilganlik haqida guvohnoma"],
      ["spare part", "/spɛr pɑrt/", "ehtiyot qism"],
      ["passer-by", "/passer-by*/", "yo\'lovchi (o\'tib ketayotgan odam)"],
      ["long weekend", "/lɔŋ ˈwiˌkɪnd/", "uzaytirilgan dam olish kunlari"],
      ["life expectancy", "/laɪf ɪkˈspɛktənsi/", "umr ko\'rish davomiyligi"],
      ["short cut", "/ʃɔrt kət/", "qisqa yo\'l"],
      ["fancy dress", "/ˈfænsi drɛs/", "maskarad libosi"],
      ["nursery rhyme", "/ˈnərsəri raɪm/", "bolalar qo\'shig\'i/qofiyasi"],
      ["slot machine", "/slɑt məˈʃin/", "o\'yin avtomati"],
      ["next of kin", "/nɛkst əv kɪn/", "eng yaqin qarindosh"],
      ["last-minute", "/ˌlæsˈmɪnət/", "oxirgi daqiqadagi"],
      ["built-up", "/built-up*/", "binolar bilan qoplangan (hudud)"],
      ["panic-stricken", "/panic-stricken*/", "sarosimaga tushgan"],
      ["thick-skinned", "/thick-skinned*/", "tanqidga chidamli, yuzsiz"],
      ["off-putting", "/off-putting*/", "yoqimsiz, bezor qiluvchi"],
      ["tongue-tied", "/tongue-tied*/", "tili aylanmay qolgan, dovdirab qolgan"],
      ["worn out", "/wɔrn aʊt/", "eskirgan / o\'ta charchagan"],
      ["hard-wearing", "/hard-wearing*/", "chidamli, pishiq"],
      ["never-ending", "/ˌnɛvərˈɛndɪŋ/", "bitmas-tuganmas"],
      ["bad-tempered", "/bad-tempered*/", "jahldor, asabiy"],
      ["let-down", "/let-down*/", "hafsalani pir qiluvchi holat"],
      ["drop-out", "/drop-out*/", "o\'qishni tashlab ketgan odam"],
      ["turnout", "/ˈtərˌnaʊt/", "ishtirokchilar soni, kelganlar"],
      ["shake-up", "/shake-up*/", "tub o\'zgarish, yangilanish"],
      ["tailback", "/tailback*/", "uzoq tirbandlik (mashinalar qatori)"],
      ["write-off", "/write-off*/", "butunlay yaroqsiz holga kelgan mashina"],
    ], 'I can use compounds', 'Expanding your vocabulary'),
    unit(4, [
      ["set fire to", "/sɛt faɪər tɪ/", "o\'t qo\'ymoq"],
      ["catch fire", "/kæʧ faɪər/", "yonib ketmoq, o\'t olmoq"],
      ["break out", "/breɪk aʊt/", "boshlanib ketmoq (yong\'in, urush)"],
      ["on fire", "/ɔn faɪər/", "yonmoqda"],
      ["spread", "/sprɛd/", "tarqalmoq"],
      ["burst into flames", "/bərst ˈɪntu fleɪmz/", "birdan alanga olmoq"],
      ["go up in flames", "/goʊ əp ɪn fleɪmz/", "kulga aylanib yonib ketmoq"],
      ["die down", "/daɪ daʊn/", "pasaymoq, susaymoq (alanga/ovoz)"],
      ["put out", "/pʊt aʊt/", "o\'chirmoq (yong\'inni)"],
      ["torrential rain", "/tɔˈrɛnʃəl reɪn/", "jala, jadal yomg\'ir"],
      ["gale-force wind", "/gale-force* wɪnd/", "bo\'ronli kuchli shamol"],
      ["considerable difficulty", "/kənˈsɪdərəbəl ˈdɪfɪˌkəlti/", "sezilarli qiyinchilik"],
      ["extensive damage", "/ɪkˈstɛnsɪv ˈdæmɪʤ/", "katta miqyosdagi zarar"],
      ["strong accent", "/strɔŋ ˈækˌsɛnt/", "kuchli talaffuz aksenti"],
      ["utter chaos", "/ˈətər keɪɑs/", "mutlaq tartibsizlik"],
      ["narrow escape", "/ˈnɛroʊ ɪˈskeɪp/", "zo\'rg\'a qochib qutilish"],
      ["take offence", "/teɪk offence*/", "hafa bo\'lmoq, ranjimoq"],
      ["settle a dispute", "/ˈsɛtəl ə dɪˈspjut/", "nizoni hal qilmoq"],
      ["hold responsible", "/hoʊld riˈspɑnsəbəl/", "javobgar deb bilmoq"],
      ["take the blame", "/teɪk ðə bleɪm/", "aybni o\'z zimmasiga olmoq"],
    ], 'I can use a range of collocations', 'Expanding your vocabulary'),
    unit(5, [
      ["reflect", "/rɪˈflɛkt/", "aks ettirmoq / o\'ylab ko\'rmoq"],
      ["count", "/kaʊnt/", "sanamoq / hisobga olmoq"],
      ["absorb", "/əbˈzɔrb/", "o\'ziga singdirmoq / o\'zlashtirmoq"],
      ["favour", "/ˈfeɪvər/", "yaxshilik, yordam"],
      ["propose", "/prəˈpoʊz/", "taklif qilmoq"],
      ["circumstance", "/ˈsərkəmˌstæns/", "shart-sharoit, vaziyat"],
      ["nod", "/nɑd/", "bosh irg\'amoq"],
      ["shrug", "/ʃrəg/", "elka qisib qo\'ymoq"],
      ["lick", "/lɪk/", "lamba qilmoq, yalamoq"],
    ], 'I can use a dictionary productively', 'Expanding your vocabulary'),
    unit(6, [
      ["mistake", "/mɪˈsteɪk/", "xato"],
      ["excel", "/ɪkˈsɛl/", "ustun turmoq, zo\'r bajarmoq"],
      ["final", "/ˈfaɪnəl/", "yakuniy"],
      ["pointless", "/ˈpɔɪntləs/", "ma\'nosiz, bekorchi"],
      ["following", "/ˈfɑloʊɪŋ/", "muxlislar guruhi, ergashuvchilar"],
      ["heartless", "/ˈhɑrtləs/", "bag\'ritosh, shafqatsiz"],
      ["emotive", "/ˈiˌmoʊtɪv/", "hissiyot qo\'zg\'atuvchi"],
      ["apologetic", "/əˌpɑləˈʤɛtɪk/", "uzr so\'rovchi"],
      ["unforgivable", "/ˌənfɔrˈgɪvəbəl/", "kechirib bo\'lmas"],
      ["indescribable", "/ˌɪndɪˈskraɪbəbəl/", "ta\'riflab bo\'lmaydigan"],
      ["reputable", "/ˈrɛpjətəbəl/", "obro\'li, nufuzli"],
      ["occupy", "/ˈɑkjəˌpaɪ/", "band qilmoq"],
      ["confess", "/kənˈfɛs/", "tan olmoq"],
      ["commit", "/kəˈmɪt/", "va\'da bermoq, o\'z zimmasiga olmoq"],
      ["origin", "/ˈɔrəʤən/", "kelib chiqish manbai"],
      ["simplify", "/ˈsɪmpləˌfaɪ/", "soddalashtirmoq"],
      ["abuse", "/əˈbjuz/", "zo\'ravonlik qilmoq, suiiste\'mol qilmoq"],
      ["defend", "/dɪˈfɛnd/", "himoya qilmoq"],
    ], 'I can build word families', 'Expanding your vocabulary'),
    unit(7, [
      ["chubby", "/ˈʧəbi/", "to\'ladigan, dumaloq (chaqaloq yuzi kabi)"],
      ["freckles", "/ˈfrɛkəlz/", "sepkillar"],
      ["brace", "/breɪs/", "tish breketi"],
      ["gorgeous", "/ˈgɔrʤəs/", "juda go\'zal, ko\'rkam"],
      ["paunch", "/paunch*/", "qorin (erkaklardagi kattaroq qorin)"],
      ["stick out", "/stɪk aʊt/", "chiqib turmoq, bo\'rtib turmoq"],
      ["frail", "/freɪl/", "holsiz, nozik (keksa odam haqida)"],
      ["doddery", "/doddery*/", "qari, qaltiroq bosib qolgan"],
      ["enhance", "/ɛnˈhæns/", "sifatini yaxshilamoq, oshirmoq"],
      ["discreetly", "/dɪˈskritli/", "bilintirmasdan, ehtiyotkorona"],
      ["conceal", "/kənˈsil/", "yashirmoq"],
      ["flattering", "/ˈflætərɪŋ/", "odamni chiroyli ko\'rsatadigan"],
      ["exaggerate", "/ɪgˈzæʤərˌeɪt/", "bo\'rttirib yubormoq"],
    ], 'I can describe the human body', 'The body'),
    unit(8, [
      ["jump to conclusions", "/ʤəmp tɪ kənˈkluʒənz/", "shoshma-shoshar xulosa chiqarmoq"],
      ["gesture", "/ˈʤɛsʧər/", "jest, imo-ishora"],
      ["misinterpret", "/mɪsɪnˈtərprət/", "noto\'g\'ri tushunmoq"],
      ["eye contact", "/aɪ ˈkɑnˌtækt/", "ko\'z solishish, nigoh almashish"],
      ["observe", "/əbˈzərv/", "kuzatmoq"],
      ["display", "/dɪˈspleɪ/", "namoyish etmoq, ko\'rsatmoq"],
      ["go red", "/goʊ rɛd/", "qizarib ketmoq"],
      ["sweat", "/swɛt/", "terlamoq"],
      ["excessive", "/ɪkˈsɛsɪv/", "haddan tashqari ko\'p"],
      ["clench", "/klɛnʧ/", "qisib olmoq (mushtni)"],
      ["fold arms", "/foʊld ɑrmz/", "qo\'lni ko\'krakka chalishtirib olmoq"],
      ["lean", "/lin/", "engashmoq, intilmoq"],
      ["fiddle with", "/ˈfɪdəl wɪθ/", "nimandir bilan ovora bo\'lib o\'ynamoq"],
      ["stroke", "/stroʊk/", "sypamoq, silamoq"],
      ["flirt", "/flərt/", "flirt qilmoq"],
    ], 'I can talk about body language', 'The body'),
    unit(9, [
      ["creep", "/krip/", "sekin va jimgina yurmoq"],
      ["stroll", "/stroʊl/", "sayr qilmoq, erkin yurmoq"],
      ["limp", "/lɪmp/", "oqsoqlanmoq"],
      ["stagger", "/ˈstægər/", "dovdirab, tebranib yurmoq"],
      ["hike", "/haɪk/", "piyoda uzoq yo\'l yurmoq (sayohat)"],
      ["march", "/mɑrʧ/", "saf tortib yurmoq"],
      ["chase", "/ʧeɪs/", "quvib yetmoq, ta\'qib qilmoq"],
      ["dash", "/dæʃ/", "otilib yugurmoq"],
      ["gallop", "/ˈgæləp/", "chopmoq (ot haqida)"],
      ["charge", "/ʧɑrʤ/", "hujumga o\'tib yugurmoq"],
      ["supple", "/ˈsəpəl/", "egiluvchan, elastik"],
      ["agile", "/ˈæʤəl/", "chaqqon, tezkor"],
      ["stiff", "/stɪf/", "qotib qolgan (mushaklar)"],
      ["sluggish", "/sˈləgɪʃ/", "holsiz, sust"],
      ["devise", "/dɪˈvaɪz/", "o\'ylab topmoq, reja tuzmoq"],
      ["loosen up", "/ˈlusən əp/", "qizishib olmoq (mashq oldidan)"],
      ["bend", "/bɛnd/", "bukilmoq, egilmoq"],
      ["strenuous", "/ˈstrɛnjuəs/", "kuch talab qiladigan, mashaqqatli"],
      ["relentless", "/rɪˈlɛntlɪs/", "tinimsiz, to\'xtovsiz"],
      ["recurrent", "/rɪˈkərənt/", "takrorlanib turuvchi"],
      ["sprint", "/sprɪnt/", "qisqa masofaga tez yugurmoq"],
    ], 'I can describe physical movement', 'The body'),
    unit(10, [
      ["rattle", "/ˈrætəl/", "taqillamoq, jaranglamoq"],
      ["rumble", "/ˈrəmbəl/", "g\'uvillamoq, gulduramoq"],
      ["rustle", "/ˈrəsəl/", "shildiramoq, g\'ichirlamoq"],
      ["splash", "/splæʃ/", "sakratib suv sachratmoq"],
      ["beep", "/bip/", "signal bermoq (signalizatsiya/klakson)"],
      ["screech", "/skriʧ/", "chiyillamoq, g\'ichirlatib to\'xtamoq"],
      ["slam", "/slæm/", "arsillatib yopmoq"],
      ["squelch", "/skwɛlʧ/", "chuvillagan tovush chiqarmoq (loyda)"],
      ["creak", "/krik/", "g\'ichirlamoq (taxta va eshik)"],
      ["high-pitched", "/high-pitched*/", "baland va ingichka ovozli"],
      ["bark", "/bɑrk/", "vovullamoq"],
      ["howl", "/haʊl/", "uvlamoq"],
      ["growl", "/graʊl/", "g\'urillamoq, g\'azab bilan ingramoq"],
      ["buzz", "/bəz/", "g\'izillamoq, g\'uvillamoq"],
      ["roar", "/rɔr/", "g\'urrillamoq, o\'qish"],
      ["squeak", "/skwik/", "qiyqirmoq, g\'ichirlamoq"],
      ["crow", "/kroʊ/", "qichqirmoq (xo\'roz)"],
      ["hoot", "/hut/", "signal bermoq (mashina)"],
    ], 'I can describe sounds', 'The body'),
    unit(11, [
      ["eyesight", "/ˈaɪˌsaɪt/", "ko\'rish qobiliyati"],
      ["eye strain", "/aɪ streɪn/", "ko\'z zo\'riqishi"],
      ["blurred vision", "/blərd ˈvɪʒən/", "xira ko\'rish"],
      ["blink", "/blɪŋk/", "ko\'z qisib-ochmoq (pildiratmoq)"],
      ["tear", "/tɪr/", "ko\'z yoshi"],
      ["irritated", "/ˈɪrəˌteɪtəd/", "achishgan, qizarib qolgan"],
      ["ease", "/iz/", "yengillashtirmoq, og\'riqni bosmoq"],
      ["adjust", "/əˈʤəst/", "moslashtirmoq, to\'g\'rilamoq"],
      ["eliminate", "/ɪˈlɪməˌneɪt/", "yo\'q qilmoq, bartaraf etmoq"],
      ["glare", "/glɛr/", "ko\'zni qamashtiruvchi yorug\'lik"],
      ["moist", "/mɔɪst/", "namlangan, nam"],
      ["gaze", "/geɪz/", "tikilib qaramoq"],
      ["breathtaking", "/ˈbrɛθˌteɪkɪŋ/", "nafasni oladigan darajada go\'zal"],
      ["barely", "/ˈbɛrli/", "zo\'rg\'a"],
      ["visible", "/ˈvɪzəbəl/", "ko\'rinib turgan"],
      ["haze", "/heɪz/", "tuman, chang-g\'ubor"],
      ["make out", "/meɪk aʊt/", "aniq ko\'ra olmoq, farqlamoq"],
      ["spot", "/spɑt/", "payqamoq, ko\'rib qolmoq"],
      ["warily", "/ˈwɛrəli/", "ehtiyotkorlik bilan"],
    ], 'I can describe sight', 'The body'),
    unit(12, [
      ["massage", "/məˈsɑʒ/", "uqalash, massaj qilmoq"],
      ["stroke", "/stroʊk/", "silamoq"],
      ["slide", "/slaɪd/", "sirpanib harakatlanmoq"],
      ["apply pressure", "/əˈplaɪ ˈprɛʃər/", "bosim o\'tkazmoq"],
      ["stimulate", "/ˈstɪmjəˌleɪt/", "faollashtirmoq, qo\'zg\'atmoq"],
      ["pat", "/pæt/", "sekin urib qo\'ymoq (ftat)"],
      ["pinch", "/pɪnʧ/", "chimchilab qo\'ymoq"],
      ["tension", "/ˈtɛnʃən/", "taranglik, zo\'riqish"],
      ["squeeze", "/skwiz/", "siqmoq"],
      ["delicate", "/ˈdɛləkət/", "mayin, nozik"],
      ["fragrance", "/ˈfreɪgrəns/", "xushbo\'y hid"],
      ["faint", "/feɪnt/", "zaif, sezilar-sezilmas"],
      ["appetizing", "/ˈæpɪˌtaɪzɪŋ/", "ishtaha ochar"],
      ["aroma", "/ərˈoʊmə/", "idish/taom xushbo\'yligi"],
      ["insipid", "/ˌɪnˈsɪpəd/", "mazasiz, totli bo\'lmagan"],
      ["pungent", "/ˈpənʤənt/", "o\'tkir hidli"],
      ["musty", "/ˈməsti/", "namxush, eski hidli"],
      ["odour", "/ˈoʊdər/", "badbo\'y yoki o\'ziga xos hid"],
      ["revolting", "/riˈvoʊltɪŋ/", "juda yoqimsiz, jirkanch"],
      ["go off", "/goʊ ɔf/", "aynib qolmoq (ovqat)"],
      ["nauseating", "/ˈnɔʒiˌeɪtɪŋ/", "ko\'ngil aynituvchi"],
      ["stench", "/stɛnʧ/", "sasigan qo\'lansa hid"],
    ], 'I can describe touch, smell, and taste', 'The body'),
    unit(13, [
      ["scalp", "/skælp/", "bosh terisi"],
      ["splitting headache", "/ˈsplɪtɪŋ ˈhɛˌdeɪk/", "kalla yorilguldek qattiq bosh og\'rig\'i"],
      ["hay fever", "/heɪ ˈfivər/", "gulli o\'simliklar allergiyasi"],
      ["mouth ulcer", "/maʊθ ˈəlsər/", "og\'iz bo\'shlig\'idagi yaracha"],
      ["dislocate", "/ˈdɪsloʊkeɪt/", "chiqib ketmoq (suyak)"],
      ["rash", "/ræʃ/", "toshma (terida)"],
      ["upset stomach", "/ˈəpˌsɛt ˈstəmək/", "oshqozon buzilishi"],
      ["constipated", "/ˈkɑnstəˌpeɪtəd/", "ich qotishi"],
      ["high blood pressure", "/haɪ bləd ˈprɛʃər/", "yuqori qon bosimi"],
      ["sprain", "/spreɪn/", "payni cho\'zib yubormoq"],
      ["pull a muscle", "/pʊl ə ˈməsəl/", "mushakni cho\'zib yubormoq"],
      ["blister", "/ˈblɪstər/", "qadoq, suvli pufakcha"],
      ["dissolve", "/dɪˈzɑlv/", "eriytirmoq, erib ketmoq"],
      ["lethargy", "/ˈlɛθərʤi/", "holsizlik, loqaydlik"],
      ["drowsiness", "/ˈdraʊzinəs/", "uyqusirash, esankirash"],
      ["short-term", "/ˌʃɔrtˈtərm/", "qisqa muddatli"],
      ["dose", "/doʊs/", "doza (dori miqdori)"],
      ["enclosed", "/ɪnˈkloʊzd/", "ichiga solingan, ilova qilingan"],
      ["leaflet", "/ˈliflət/", "ma\'lumotnoma varaqasi"],
      ["side effect", "/saɪd ˈifɛkt/", "nojo\'ya ta\'sir"],
      ["disorder", "/dɪˈsɔrdər/", "funksional buzilish, kasallik"],
      ["discard", "/dɪˈskɑrd/", "tashlab yubormoq"],
      ["persist", "/pərˈsɪst/", "davom etmoq (alomat)"],
      ["expiry date", "/ˌɛkˈspaɪri deɪt/", "amal qilish muddati"],
    ], 'I can describe illness and injuries', 'The body'),
    unit(14, [
      ["spontaneous", "/spɑnˈteɪniəs/", "o\'z-o\'zidan, erkin harakat qiluvchi"],
      ["happy-go-lucky", "/happy-go-lucky*/", "g\'am-tashvishsiz yashovchi"],
      ["down-to-earth", "/down-to-earth*/", "sodda, real hayotga yaqin"],
      ["chatterbox", "/chatterbox*/", "val-val, ko\'p gapiruvchi"],
      ["passionate", "/ˈpæʃənət/", "ehtirosli, qiziqqon"],
      ["considerate", "/kənˈsɪdərət/", "boshqalarni o\'ylaydigan, e\'tiborli"],
      ["affection", "/əˈfɛkʃən/", "mehr-muhabbat"],
      ["integrity", "/ˌɪnˈtɛgrəti/", "halollik, qat\'iy tamoyillar"],
      ["pretentious", "/priˈtɛnʃəs/", "manman, o\'zini yuqori tutuvchi"],
      ["quick-witted", "/quick-witted*/", "zukko, tez fikrlaydigan"],
      ["shrewd", "/ʃrud/", "ayyor, ishbilarmon, fahmli"],
      ["ruthless", "/ˈruθləs/", "shafqatsiz, rahmsiz"],
      ["pushy", "/ˈpʊʃi/", "o\'ta o\'jarlik bilan maqsadiga intiluvchi"],
      ["conceited", "/kənˈsitəd/", "o\'zidan kegirgan, dimog\'dor"],
      ["conscientious", "/ˌkɑnʃiˈɛnʃəs/", "vijdonli, ishiga mas\'uliyatli"],
      ["trustworthy", "/ˈtrəstˌwərði/", "ishonchli"],
      ["charisma", "/kərˈɪzmə/", "xarizma, joziba"],
      ["assertive", "/əˈsərtɪv/", "o\'z fikrini qat\'iy himoya qiluvchi"],
      ["aloof", "/əˈluf/", "o\'zini chetga oluvchi, sovuqqon"],
      ["diffident", "/diffident*/", "tortinchoq, o\'ziga ishonqiramaydigan"],
      ["trait", "/treɪt/", "xarakter belgisi"],
      ["misleading", "/mɪsˈlidɪŋ/", "chalg\'ituvchi"],
      ["virtue", "/ˈvərʧu/", "fazilat, yaxshi xislat"],
      ["cunning", "/ˈkənɪŋ/", "makkor, hiylagar"],
      ["impulsive", "/ˌɪmˈpəlsɪv/", "hissiyotga berilib ish tutuvchi"],
      ["naive", "/naɪiv/", "sodda, g\'o\'r"],
    ], 'I can discuss aspects of character', 'You and other people'),
    unit(15, [
      ["ecstatic", "/ɛkˈstætɪk/", "cheksiz quvonchdagi, mast-alast"],
      ["jubilant", "/ˈʤubələnt/", "g\'alabadan g\'ururlangan, xursand"],
      ["devastated", "/ˈdɛvəˌsteɪtɪd/", "qattiq tushkunlikka tushgan, vayron bo\'lgan"],
      ["hysterical", "/hɪˈstɛrɪkəl/", "isterikaga tushgan"],
      ["stunned", "/stənd/", "esankirab qolgan, shokda"],
      ["appalled", "/əˈpɔld/", "daxshatga tushgan, norozi"],
      ["desperate", "/ˈdɛspərɪt/", "umidsiz, o\'ta xavotirli"],
      ["bottle up", "/ˈbɑtəl əp/", "hissiyotni ichga yutmoq"],
      ["disclose", "/dɪˈskloʊz/", "fosh qilmoq, sirni ochmoq"],
      ["vulnerable", "/ˈvəlnərəbəl/", "himoyasiz, jarohatlanuvchan"],
      ["uneasy", "/əˈnizi/", "bezovta, noqulay sezuvchi"],
      ["pour out", "/pɔr aʊt/", "dildan to\'kilib gapirmoq"],
      ["instinct", "/ˈɪnstɪŋkt/", "instinkt, tabiat"],
    ], 'I can talk about feelings', 'You and other people'),
    unit(16, [
      ["resent", "/rɪˈzɛnt/", "ich ichidan g\'azablanmoq, ranjimoq"],
      ["hostile", "/ˈhɑstəl/", "dushmanona"],
      ["complimentary", "/ˌkɑmpləˈmɛntəri/", "maqtovli, lutf ko\'rsatuvchi"],
      ["inevitably", "/ˌɪˈnɛvətəbli/", "muqarrar ravishda"],
      ["strain", "/streɪn/", "zajim, ruhiy bosim"],
      ["stick up for", "/stɪk əp fər/", "himoya qilmoq"],
      ["settle down", "/ˈsɛtəl daʊn/", "tinchib qolmoq, o\'rnashmoq"],
      ["reluctant", "/rɪˈləktənt/", "istamaydigan, xohishsiz"],
      ["bond", "/bɑnd/", "rishta, bog\'liqlik"],
      ["confide", "/kənˈfaɪd/", "sirini aytib to\'kilib solmoq"],
      ["appreciate", "/əˈpriʃiˌeɪt/", "qadrlamoq"],
      ["sacrifice", "/ˈsækrəˌfaɪs/", "qurbonlik qilmoq"],
    ], 'I can talk about relationships', 'You and other people'),
    unit(17, [
      ["heroine", "/ˈhɛroʊən/", "qahramon ayol"],
      ["courage", "/kərɪʤ/", "jasorat"],
      ["dignity", "/ˈdɪgnəti/", "viqor, g\'urur"],
      ["humility", "/hjuˈmɪlɪti/", "kamtarlik"],
      ["inspire", "/ˌɪnˈspaɪr/", "ilhomlantirmoq"],
      ["idolize", "/ˈaɪdəˌlaɪz/", "butunlay e\'tiqod qilmoq, sig\'inmoq"],
      ["dedication", "/ˌdɛdəˈkeɪʃən/", "fidoiylik, sadoqat"],
      ["rebel", "/ˈrɛbəl/", "isyonchi, isyon ko\'taruvchi"],
      ["idealist", "/aɪˈdilɪst/", "idealist"],
      ["hypocrite", "/ˈhɪpəˌkrɪt/", "ikkiyuzlamachi"],
      ["snob", "/snɑb/", "snob (o\'zini hammadan ustun qo\'yuvchi)"],
      ["vulgar", "/ˈvəlgər/", "qo\'pol, madaniyatsiz"],
      ["despise", "/dɪˈspaɪz/", "nafratlanmoq, mensimaslik"],
      ["malicious", "/məˈlɪʃəs/", "badniyat, g\'arazli"],
    ], 'I can talk about people I admire and loathe', 'You and other people'),
    unit(18, [
      ["nature", "/ˈneɪʧər/", "tabiat (tug\'ma xarakter)"],
      ["nurture", "/ˈnərʧər/", "tarbiya, voyaga yetkazish"],
      ["impact", "/ˌɪmˈpækt/", "ta\'sir"],
      ["role model", "/roʊl ˈmɑdəl/", "namuna ola oladigan shaxs"],
      ["peer pressure", "/pɪr ˈprɛʃər/", "tengqurlar bosimi"],
      ["incentive", "/ˌɪnˈsɛnɪv/", "rag\'bat, rag\'batlantiruvchi omil"],
      ["deterrent", "/dɪˈtərrənt/", "to\'xtatib turuvchi omil"],
      ["deprived", "/dɪˈpraɪvd/", "imkoniyatdan mahrum bo\'lgan"],
      ["messy", "/ˈmɛsi/", "tartibsiz, kir"],
      ["pull your weight", "/pʊl jʊr weɪt/", "o\'z ulushini bajarmoq (mehnatda)"],
      ["nag", "/næg/", "tinimsiz koyib berib turg\'uvchi"],
      ["fuss", "/fəs/", "ortiqcha vahima, g\'ovg\'o"],
    ], 'I can talk about behaviour', 'You and other people'),
    unit(19, [
      ["etiquette", "/ˈɛtəkət/", "etiket, odob-axloq qoidalari"],
      ["manners", "/ˈmænərz/", "muomala odobi"],
      ["frown on", "/fraʊn ɔn/", "ma\'qullamaslik, yomon ko\'rmoq"],
      ["discourteous", "/discourteous*/", "odob-axloqsiz, qo\'pol"],
      ["customary", "/ˈkəstəˌmɛri/", "odat tusiga kirgan"],
      ["respectful", "/rɪˈspɛktfəl/", "hurmatli"],
      ["offensive", "/əˈfɛnsɪv/", "haqoratli, dilni og\'rituvchi"],
      ["impeccable", "/ˌɪmˈpɛkəbəl/", "mukammal, benuqson"],
      ["exemplary", "/ɪgˈzɛmpləri/", "namunali"],
      ["cheeky", "/ˈʧiki/", "betgachoparlarcha, erkin (erkalovchi ma\'noda)"],
      ["insolent", "/ˈɪnsələnt/", "o\'ta qo\'pol, xadsiz"],
      ["downright", "/ˈdaʊnˌraɪt/", "mutlaq, ochiq-oydin"],
      ["disgraceful", "/dɪsˈgreɪsfəl/", "sharmandali"],
    ], 'I can talk about manners', 'You and other people'),
    unit(20, [
      ["pomegranate", "/ˌpɑməˈgrænət/", "anor"],
      ["passion fruit", "/ˈpæʃən frut/", "marakuya"],
      ["beetroot", "/beetroot*/", "lavlagi"],
      ["almonds", "/ˈɑlməndz/", "bodom"],
      ["lentils", "/ˈlɛntəlz/", "yasmiq"],
      ["cinnamon", "/ˈsɪnəmən/", "dolchin"],
      ["wok", "/wɑk/", "vok tovasi"],
      ["steamer", "/ˈstimər/", "bug\'da pishirgich"],
      ["colander", "/ˈkɑləndər/", "objuvoz, suzgich"],
      ["grater", "/ˈgreɪtər/", "qirg\'ich"],
      ["go pear-shaped", "/goʊ pear-shaped*/", "rejalar buzilib ketmoq"],
      ["eat your words", "/it jʊr wərdz/", "aytgan gapidan qaytmoq"],
      ["sour grapes", "/saʊər greɪps/", "hasaddan kelib chiqqan tanqid"],
      ["breadwinner", "/ˈbrɛdˌwɪnər/", "oilani boquvchi"],
    ], 'I can talk about food', 'Leisure and lifestyle'),
    unit(21, [
      ["stunning", "/ˈstənɪŋ/", "hayratlanarli darajada go\'zal"],
      ["thriving", "/θˈraɪvɪŋ/", "gullab-yashnayotgan, rivojlanayotgan"],
      ["vibrant", "/ˈvaɪbrənt/", "jonli, jo\'shqin"],
      ["cobbled streets", "/ˈkɑbəld strits/", "tosh yotqizilgan ko\'chalar"],
      ["diverse", "/dɪˈvərs/", "xilma-xil, turfa xil"],
      ["unwind", "/ənˈwaɪnd/", "hordiq chiqarmoq, bo\'shashmoq"],
      ["laze around", "/laze* əraʊnd/", "bekor o\'tirib dam olmoq"],
      ["soak up", "/soʊk əp/", "singdirmoq, muhitdan rohatlanmoq"],
      ["off the beaten track", "/ɔf ðə ˈbitən træk/", "odam kam yradigan,olis joy"],
      ["trek", "/trɛk/", "piyoda uzoq yo\'l yurish, safar"],
      ["remote", "/rɪˈmoʊt/", "olis, olisdagi, chekka"],
      ["unspoilt", "/unspoilt*/", "o\'z holicha saqlanib qolgan tabiat"],
    ], 'I can talk about holidays', 'Leisure and lifestyle'),
    unit(22, [
      ["spine-tingling", "/spine-tingling*/", "etni jimirlatuvchi, dahshatli-qiziqarli"],
      ["ghost story", "/goʊst ˈstɔri/", "arvohlar haqidagi hikoya"],
      ["set", "/sɛt/", "sahna bezagi, dekoratsiya"],
      ["sound effects", "/saʊnd ˈifɛkts/", "ovoz effektlari"],
      ["nail-biting", "/nail-biting*/", "hayajonli, yurakni hovuchlatadigan"],
      ["adaptation", "/ˌædəpˈteɪʃən/", "moslashtirilgan asar/film"],
      ["twist", "/twɪst/", "kutilmagan burilish (syujetda)"],
      ["cast", "/kæst/", "aktyorlar jamoasi"],
      ["applause", "/əˈplɔz/", "qarsaklar, olqish"],
      ["acclaimed", "/əˈkleɪmd/", "e\'tirof etilgan"],
      ["atrocious", "/əˈtroʊʃəs/", "juda yomon, daxshatli darajada yomon"],
      ["sentimental", "/ˌsɛnəˈmɛnəl/", "hissiyotlarga beriluvchan, ta\'sirchan"],
      ["cliché", "/cliché*é/", "takrorlanaverib yod bo\'lib ketgan fikr/holat"],
      ["shallow", "/ˈʃæloʊ/", "yuzaki, sayoz (fikr/qahramon)"],
      ["mediocre", "/ˌmidiˈoʊkər/", "o\'rtamiyonasi, past sifatli"],
    ], 'I can talk about plays and films', 'Leisure and lifestyle'),
    unit(23, [
      ["qualify", "/kˈwɑləˌfaɪ/", "saralashdan o\'tmoq, yo\'llanma olmoq"],
      ["knockout", "/ˈnɑˌkaʊt/", "mag\'lubiyatga uchratib keyingi bosqichga chiqish"],
      ["runner-up", "/ˈrənərˌəp/", "ikkinchi o\'rin egasi, finalchi"],
      ["eliminate", "/ɪˈlɪməˌneɪt/", "musobaqadan chiqarib yubormoq"],
      ["draw", "/drɔ/", "qur\'a tashlash / durang"],
      ["venue", "/ˈvɛnju/", "musobaqa o\'tkaziladigan joy"],
      ["form", "/fɔrm/", "sportchining joriy holati/tayyorgarligi"],
      ["unbeaten", "/ənˈbitən/", "mag\'lubiyatga uchramagan"],
      ["promotion", "/pərˈmoʊʃən/", "yuqori ligaga chiqish"],
      ["let down", "/lɛt daʊn/", "hafsalasini pir qilmoq, ishonchni oqlamaslik"],
      ["dominate", "/ˈdɑməˌneɪt/", "ustunlik qilmoq"],
      ["give away", "/gɪv əˈweɪ/", "boy berib qo\'ymoq (xato tufayli)"],
    ], 'I can talk about competitive sport', 'Leisure and lifestyle'),
    unit(24, [
      ["imitate", "/ˈɪməˌteɪt/", "taqlid qilmoq"],
      ["acquire", "/əkˈwaɪər/", "qo\'lga kiritmoq, sotib olmoq"],
      ["cottage", "/ˈkɑtɪʤ/", "qishloq uyi, kottej"],
      ["wildlife", "/ˈwaɪlˌdlaɪf/", "yovvoyi tabiat"],
      ["slope", "/sloʊp/", "niqab, qiyalik, nishablik"],
      ["shed", "/ʃɛd/", "omborxona, molxona, xontaxta"],
      ["scatter", "/ˈskætər/", "sochib yubormoq, sepmoq"],
      ["seed", "/sid/", "urug\'"],
      ["meadow", "/ˈmɛˌdoʊ/", "o\'tloq, dasht"],
      ["nest", "/nɛst/", "uya (qush uyasi)"],
      ["compost", "/ˈkɑmpoʊst/", "kompost (o\'g\'it)"],
      ["prune", "/prun/", "butamoq (daraxt/butani)"],
      ["lawnmower", "/ˈlɔnmoʊər/", "maysazor o\'radigan mashina"],
    ], 'I can talk about gardens and nature', 'Leisure and lifestyle'),
    unit(25, [
      ["impulse", "/ˌɪmˈpəls/", "birdan kelgan xohish/istak"],
      ["price tag", "/praɪs tæg/", "narx yorlig\'i"],
      ["browse", "/braʊz/", "tamosha qilib chiqmoq, ko\'z yugurtirmoq"],
      ["shop around", "/ʃɑp əraʊnd/", "narxini surishtirib, solishtirib sotib olmoq"],
      ["focused", "/ˈfoʊkɪst/", "diqqatini jamlagan, aniq maqsadli"],
      ["distract", "/dɪˈstrækt/", "chalg\'itmoq"],
      ["pursuit", "/pərˈsut/", "mashg\'ulot, intilish"],
      ["spree", "/spri/", "to\'satdan ko\'p pul sarflab xarid qilish"],
      ["gadget", "/ˈgæʤət/", "qurilma, gadjet"],
      ["shopaholic", "/shopaholic*/", "shopogolik (xaridga berilib ketgan odam)"],
      ["compulsive", "/kəmˈpəlsɪv/", "o\'zini to\'xtata olmaydigan (odat)"],
      ["addicted", "/əˈdɪktɪd/", "bog\'lanib qolgan, qaram bo\'lgan"],
    ], 'I can talk about shopping habits', 'Leisure and lifestyle'),
    unit(26, [
      ["socialize", "/ˈsoʊʃəˌlaɪz/", "odamlar bilan muloqot qilmoq"],
      ["host", "/hoʊst/", "mezbon"],
      ["lay on", "/leɪ ɔn/", "ta\'minlamoq, muhayyo qilmoq (ziyofat)"],
      ["time-consuming", "/time-consuming*/", "ko\'p vaqt oladigan"],
      ["contribution", "/ˌkɑntrəˈbjuʃən/", "hissa"],
      ["disposable", "/dɪˈspoʊzəbəl/", "bir martalik (idish va h.k.)"],
      ["gatecrasher", "/gatecrasher*/", "taklif qilinmagan mezbon"],
      ["deafening", "/ˈdɛfənɪŋ/", "quloqni qomatga keltiradigan darajada baland"],
      ["pop round", "/pɑp raʊnd/", "qisqa vaqtga kirib o\'tmoq"],
      ["loner", "/ˈloʊnər/", "yakka yashaydigan, yolg\'izlanuvchi"],
      ["cliquey", "/cliquey*/", "guruhboz, o\'rtasiga odam qo\'ymaydigan"],
    ], 'I can talk about socializing', 'Leisure and lifestyle'),
    unit(27, [
      ["transform", "/ˈtrænsfɔrm/", "tubdan o\'zgartirmoq"],
      ["amend", "/əˈmɛnd/", "o\'zgartirish kiritmoq (qonun/hujjatga)"],
      ["adapt", "/əˈdæpt/", "moslashmoq"],
      ["assimilate", "/əˈsɪməˌleɪt/", "o\'zlashtirmoq, singdirmoq"],
      ["evolve", "/ɪˈvɑlv/", "evolyutsiya qilmoq, asta-sekin rivojlanmoq"],
      ["transition", "/trænˈzɪʃən/", "o\'tish davri"],
      ["revert", "/rɪˈvərt/", "oldingi holatga qaytmoq"],
      ["restore", "/rɪˈstɔr/", "tiklamoq, asl holiga keltirmoq"],
      ["reverse", "/rɪˈvərs/", "ortga qaytarmoq, qarama-qarshi qilmoq"],
      ["reform", "/rɪˈfɔrm/", "isloh qilmoq"],
      ["resist", "/rɪˈzɪst/", "qarshilik ko\'rsatmoq"],
      ["enforce", "/ɛnˈfɔrs/", "majburan ijro ettirmoq"],
      ["impose", "/ˌɪmˈpoʊz/", "majburan tiqishtirmoq, yuklamoq"],
      ["pursue", "/pərˈsu/", "ortidan quvmoq, amalga oshirmoq"],
      ["facilitate", "/fəˈsɪləˌteɪt/", "yengillashtirmoq, ko\'maklashmoq"],
      ["implement", "/ˈɪmpləmənt/", "hayotga tatbiq etmoq, bajarmoq"],
    ], 'I can talk about change', 'A changing world'),
    unit(28, [
      ["conserve", "/kənˈsərv/", "asramoq, tejab ishlatmoq"],
      ["switch to", "/swɪʧ tɪ/", "boshqasiga o\'tib olmoq"],
      ["emit", "/ɪˈmɪt/", "chiqarmoq (gaz, issiqlik, nur)"],
      ["consumption", "/kənˈsəmʃən/", "iste\'mol"],
      ["appliance", "/əˈplaɪəns/", "maishiy texnika vositasi"],
      ["standby", "/ˈstændˈbaɪ/", "kutish rejimi"],
      ["charge", "/ʧɑrʤ/", "quvvatlamoq (akkumulyatorni)"],
      ["landfill", "/ˈlændˌfɪl/", "chiqindi poligoni"],
      ["toxic", "/ˈtɑksɪk/", "zaharli, toksik"],
      ["green", "/grin/", "ekologik toza"],
      ["groundbreaking", "/ˈgraʊnˌbreɪkɪŋ/", "yangilik ochuvchi, ilg\'or"],
      ["sustainable", "/səˈsteɪnəbəl/", "barqaror, tabiatga zararsiz"],
      ["carbon footprint", "/ˈkɑrbən ˈfʊtˌprɪnt/", "uglerod izi"],
    ], 'I can talk about energy conservation', 'A changing world'),
    unit(29, [
      ["habitat", "/ˈhæbəˌtæt/", "yashash muhiti"],
      ["deforestation", "/dɪˌfɔrɪˈsteɪʃən/", "o\'rmonlarni kesib yo\'q qilish"],
      ["endangered", "/ɪnˈdeɪnʤərd/", "xavf ostidagi (turlar)"],
      ["species", "/ˈspiʃiz/", "biologik tur"],
      ["reserve", "/rɪˈzərv/", "qo\'riqxona"],
      ["in decline", "/ɪn dɪˈklaɪn/", "kamayib borayotgan"],
      ["breed", "/brid/", "ko\'paymoq, zot ko\'paytirmoq"],
      ["wipe out", "/waɪp aʊt/", "butunlay yo\'q qilib yubormoq"],
      ["die out", "/daɪ aʊt/", "qirilib ketmoq, yo\'qolib ketmoq"],
      ["poaching", "/ˈpoʊʧɪŋ/", "brakonerlik (noqonuniy ov)"],
      ["sought after", "/sɔt ˈæftər/", "talab yuqori bo\'lgan, izlangan"],
      ["poverty", "/ˈpɑvərti/", "kambag\'allik"],
      ["encroach", "/ɪnˈkroʊʧ/", "chegaradan o\'tib bostirib bormoq"],
    ], 'I can discuss wildlife under threat', 'A changing world'),
    unit(30, [
      ["conventional", "/kənˈvɛnʃənəl/", "an\'anaviy, odatiy"],
      ["diagnostic", "/ˌdaɪəgˈnɑstɪk/", "tashxis qo\'yishga oid"],
      ["restrict", "/riˈstrɪkt/", "cheklamoq"],
      ["prone to", "/proʊn tɪ/", "moyil bo\'lgan (kasallikka)"],
      ["cure", "/kjʊr/", "davolash, shifo"],
      ["vaccine", "/ˌvækˈsin/", "vaksina"],
      ["eradicate", "/ɪˈrædəˌkeɪt/", "ildizi bilan yo\'q qilmoq"],
      ["invasive", "/ˌɪnˈveɪsɪv/", "aralashuvni talab qiluvchi (operatsiya)"],
      ["procedure", "/prəˈsiʤər/", "tibbiy muolaja, operatsiya"],
      ["organ", "/ˈɔrgən/", "a\'zo (tana a\'zosi)"],
      ["transplant", "/trænˈsplænt/", "ko\'chirib o\'tkazish (a\'zoni)"],
      ["chemotherapy", "/ˌkimoʊˈθɛrəpi/", "kimyoterapiya"],
    ], 'I can describe medical advances', 'A changing world'),
    unit(31, [
      ["jargon", "/ˈʤɑrgən/", "professional atamalar, jargon"],
      ["password", "/ˈpæsˌwərd/", "parol"],
      ["username", "/username*/", "foydalanuvchi nomi"],
      ["log on", "/lɔg ɔn/", "tizimga kirmoq"],
      ["scroll", "/skroʊl/", "sahifani pastga/yuqoriga surmoq"],
      ["google", "/ˈgugəl/", "internetdan qidirmoq"],
      ["link", "/lɪŋk/", "havola, silka"],
      ["spam", "/spæm/", "keraksiz reklama xatlari"],
      ["virus", "/ˈvaɪrəs/", "kompyuter virusi"],
      ["hack into", "/hæk ˈɪntu/", "tarmoqqa noqonuniy kirmoq (buzib)"],
      ["format", "/ˈfɔrˌmæt/", "format"],
      ["browser", "/ˈbraʊzər/", "brauzer"],
      ["virtual", "/ˈvərʧuəl/", "virtual"],
      ["upload", "/ˈəˌploʊd/", "internetga yuklamoq"],
      ["camcorder", "/ˈkæmˌkɔrdər/", "videokamera"],
    ], 'I can talk about communication technology', 'A changing world'),
    unit(32, [
      ["flee", "/fli/", "qochib ketmoq (xavfli joydan)"],
      ["refugee", "/ˈrɛfjuʤi/", "qochqin"],
      ["refuge", "/ˈrɛfjuʤ/", "panohgoh, boshpana"],
      ["asylum", "/əˈsaɪləm/", "siyosiy boshpana"],
      ["ethnic minority", "/ˈɛθnɪk məˈnɔrəti/", "etnik ozchilik"],
      ["uproot", "/əˈprut/", "yashab turgan joyidan ko\'chishga majbur bo\'lmoq"],
      ["discrimination", "/dɪˌskrɪməˈneɪʃən/", "kamsitish"],
      ["deport", "/dɪˈpɔrt/", "mamlakatdan chiqarib yubormoq"],
      ["prejudice", "/ˈprɛʤədɪs/", "xolis bo\'lmagan qarash, xurofot"],
      ["culture shock", "/ˈkəlʧər ʃɑk/", "madaniy shok"],
      ["animosity", "/ˌænəˈmɑsəti/", "adovat, dushmanlik"],
      ["stereotype", "/ˈstɛrioʊˌtaɪp/", "stereotip"],
      ["integration", "/ˌɪnəˈgreɪʃən/", "integratsiya, qo\'shilib ketish"],
      ["nostalgia", "/nɔˈstælʤə/", "nostalgiya, sog\'inch"],
    ], 'I can talk about migration', 'A changing world'),
    unit(33, [
      ["register", "/ˈrɛʤɪstər/", "ro\'yxatdan o\'tmoq (shifokor huzurida)"],
      ["referral", "/rɪˈfərəl/", "mutaxassis huzuriga yo\'naltirish"],
      ["second opinion", "/ˈsɛkənd əˈpɪnjən/", "boshqa shifokor maslahati"],
      ["confidential", "/ˌkɑnfəˈdɛnʃəl/", "sir saqlanadigan, maxfiy"],
      ["negligence", "/ˈnɛglɪʤəns/", "e\'tiborsizlik, loqaydlik (tibbiy)"],
      ["access", "/ˈækˌsɛs/", "foydalana olish imkoniyati"],
      ["cosmetic surgery", "/kɑzˈmɛtɪk ˈsərʤəri/", "plastik jarrohlik"],
      ["clinical trial", "/ˈklɪnɪkəl traɪəl/", "klinik sinov"],
      ["complementary medicine", "/ˌkɑmpləˈmɛnʧi ˈmɛdəsən/", "noan\'anaviy tibbiyot"],
      ["spotless", "/ˈspɑtləs/", "dog\'siz, o\'ta toza"],
      ["meticulous", "/məˈtɪkjələs/", "o\'ta sinchkov, puxta"],
      ["keyhole surgery", "/ˈkiˌhoʊl ˈsərʤəri/", "laparoskopiya (kichik kesma bilan operatsiya)"],
    ], 'I can discuss health services', 'Institutions'),
    unit(34, [
      ["manifesto", "/ˌmænɪˈfɛˌstoʊ/", "manifest, dastur"],
      ["council", "/ˈkaʊnsəl/", "shahar kengashi"],
      ["stand up for", "/stænd əp fər/", "himoya qilmoq"],
      ["resident", "/ˈrɛzɪdənt/", "doimiy yashovchi aholi"],
      ["allocate", "/ˈæləˌkeɪt/", "ajratmoq (mablag\'/resurs)"],
      ["grant", "/grænt/", "subsidiya, grant puli"],
      ["voluntary", "/ˈvɑləntɛri/", "ko\'ngilli"],
      ["mayor", "/meɪər/", "mer"],
      ["eligible", "/ˈɛlɪʤəbəl/", "huquqli, nomzodlikka loyiq"],
      ["spokesperson", "/ˈspoʊkspərsən/", "matbuot kotibi, vakil"],
      ["budget", "/ˈbəʤɪt/", "byudjet"],
    ], 'I can talk about local government', 'Institutions'),
    unit(35, [
      ["drug-trafficking", "/drug-trafficking*/", "giyohvand moddalar savdosi"],
      ["smuggling", "/sˈməgəlɪŋ/", "kontrabanda"],
      ["exploitation", "/ˌɛkˌsplɔɪˈteɪʃən/", "ekspluatatsiya qilish"],
      ["fraud", "/frɔd/", "firibgarlik"],
      ["forgery", "/ˈfɔrʤəri/", "soxtalashtirish (hujjat/pul)"],
      ["firearm", "/ˈfaɪˌrɑrm/", "o\'qotar qurol"],
      ["detain", "/dɪˈteɪn/", "ushlab turmoq (qamoqda)"],
      ["warrant", "/ˈwɔrənt/", "order (sud ruxsatnomasi)"],
      ["caution", "/ˈkɔʃən/", "ogohlantirmoq (huquqni buzuvchini)"],
      ["custody", "/ˈkəstədi/", "hibsxona, qamoq"],
      ["solicitor", "/səˈlɪsətər/", "advokat, huquqshunos"],
      ["bail", "/beɪl/", "garov evaziga ozod qilish"],
    ], 'I can talk about crime and the police', 'Institutions'),
    unit(36, [
      ["abolition", "/ˌæbəˈlɪʃən/", "bekor qilish, tugatish"],
      ["capital punishment", "/ˈkæpɪtəl ˈpənɪʃmənt/", "o\'lim jazosi"],
      ["retribution", "/ˌrɛtrəˈbjuʃən/", "qasos, jazo"],
      ["deterrent", "/dɪˈtərrənt/", "to\'xtatib qoluvchi omil"],
      ["rehabilitation", "/ˌriəˌbɪləˈteɪʃən/", "ijtimoiy moslashtirish, sog\'lomlashtirish"],
      ["reoffend", "/riɔˈfɛnd/", "qayta jinoyat sodir etmoq"],
      ["inmate", "/ˈɪnˌmeɪt/", "mahkum, qamoqdagi shaxs"],
      ["segregation", "/ˌsɛgrəˈgeɪʃən/", "ajratib qo\'yish"],
      ["consent", "/kənˈsɛnt/", "rozilik"],
    ], 'I can discuss prisons', 'Institutions'),
    unit(37, [
      ["military", "/ˈmɪlɪˌtɛri/", "harbiy, armiya"],
      ["branch", "/brænʧ/", "tarmoq, bo\'lim"],
      ["civilian", "/səˈvɪljən/", "fuqaro (harbiy bo\'lmagan)"],
      ["conscription", "/kənˈskrɪpʃən/", "harbiy majburiyat (prizyv)"],
      ["combat", "/ˈkɑmbæt/", "jang, to\'qnashuv"],
      ["nuclear reactor", "/ˈnukliər riˈæktər/", "yadroli reaktor"],
      ["peacekeeping", "/ˈpiˌskipɪŋ/", "tinchlikparvarlik"],
      ["mobilize", "/ˈmoʊbəˌlaɪz/", "safarbar qilmoq"],
      ["counter-productive", "/counter-productive*/", "teskari natija beruvchi"],
    ], 'I can talk about the armed forces', 'Institutions'),
    unit(38, [
      ["probe", "/proʊb/", "surishtiruv, tekshiruv"],
      ["plea", "/pli/", "iltimos, murojaat"],
      ["ordeal", "/ɔrˈdil/", "og\'ir sinov, musibat"],
      ["urge", "/ərʤ/", "qat\'iy tavsiya qilmoq"],
      ["bid", "/bɪd/", "urinish, harakat"],
      ["oust", "/aʊst/", "lavozimidan haydab chiqarmoq"],
      ["vow", "/vaʊ/", "va\'da bermoq, qasamyod qilmoq"],
      ["blast", "/blæst/", "portlash"],
      ["boost", "/bust/", "kuchaytirmoq, ko\'tarmoq"],
      ["curb", "/kərb/", "cheklamoq, jilovlamoq"],
      ["riddle", "/ˈrɪdəl/", "sir, jumboq"],
    ], 'I can understand news headlines', 'News and current affairs'),
    unit(39, [
      ["allegation", "/ˌæləˈgeɪʃən/", "ayblash, da\'vo"],
      ["cover-up", "/ˈkəvərˌəp/", "ishni yop-yop qilish, yashirish"],
      ["source", "/sɔrs/", "axborot manbai"],
      ["lapse", "/læps/", "xato, qo\'yilgan kamchilik"],
      ["scathing", "/ˈskeɪðɪŋ/", "keskin tanqidiy"],
      ["leak", "/lik/", "sirni sizdirib yubormoq"],
      ["quote", "/kwoʊt/", "iqtibos keltirmoq"],
      ["storm of protest", "/stɔrm əv ˈproʊˌtɛst/", "norozilik to\'lqini"],
      ["blazing row", "/ˈbleɪzɪŋ roʊ/", "qizg\'in janjal"],
      ["firing line", "/ˈfaɪərrɪŋ laɪn/", "tanqid ostida qolgan joy"],
    ], 'I can understand news journalism', 'News and current affairs'),
    unit(40, [
      ["pencil in", "/ˈpɛnsəl ɪn/", "vaqtincha rejalashtirib qo\'ymoq"],
      ["lodged", "/lɑʤd/", "tiqilib qolgan, o\'rnashib qolgan"],
      ["puncture", "/ˈpəŋkʧər/", "teshmoq (shina/terini)"],
      ["excruciating", "/ɪkˈskruʃiˌeɪtɪŋ/", "chidab bo\'lmas darajada og\'riqli"],
      ["chronic", "/ˈkrɑnɪk/", "surunkali"],
      ["shelter", "/ˈʃɛltər/", "boshpana topmoq"],
      ["infested", "/ˌɪnˈfɛstɪd/", "zararkunandalar bosgan"],
      ["swamp", "/swɔmp/", "botqoqlik"],
      ["drastic", "/ˈdræstɪk/", "keskin, keskin chorali"],
      ["dazed", "/deɪzd/", "esankiragan, gangigan"],
      ["disorientated", "/disorientated*/", "yo\'nalishni yo\'qotgan, adashgan"],
      ["gruelling", "/gruelling*/", "o\'ta og\'ir, charchatuvchi"],
    ], 'I can read human interest stories', 'News and current affairs'),
    unit(41, [
      ["celebrity", "/səˈlɛbrɪti/", "mashhur shaxs, yulduz"],
      ["deserve", "/dɪˈzərv/", "loyiq bo\'lmoq"],
      ["survey", "/ˈsərˌveɪ/", "so\'rovnoma"],
      ["privacy", "/ˈpraɪvəsi/", "shaxsiy hayot daxlsizligi"],
      ["coverage", "/ˈkəvərɪʤ/", "axborot yoritilishi (OAVda)"],
      ["in the public eye", "/ɪn ðə ˈpəblɪk aɪ/", "doimiy e\'tibor markazida bo\'lgan"],
      ["findings", "/ˈfaɪndɪŋz/", "tadqiqot natijalari"],
      ["intrusion", "/ˌɪnˈtruʒən/", "aralashish (shaxsiy hayotga)"],
      ["tabloid", "/ˈtæblɔɪd/", "sariq matbuot (shov-shuvli gazeta)"],
      ["single out", "/ˈsɪŋgəl aʊt/", "ajratib ko\'rsatmoq, tanlab olmoq"],
      ["pry", "/praɪ/", "burun tiqmoq, kovushtirmoq"],
      ["allegedly", "/əˈlɛʤədli/", "go\'yoki, taxmin qilinishicha"],
      ["rehab", "/rihæb/", "reabilitatsiya markazi"],
      ["rock", "/rɑk/", "shokka solmoq, larzaga solmoq"],
      ["scandal", "/ˈskændəl/", "mojaro, shov-shuv"],
      ["newlyweds", "/ˈnuliˌwɛdz/", "yangi turmush qurganlar"],
      ["on the rocks", "/ɔn ðə rɑks/", "inqiroz yoqasida turgan (munosabat)"],
      ["custody", "/ˈkəstədi/", "farzand vasiyligi / qamoq"],
      ["dump", "/dəmp/", "tashlab ketmoq (sevishganini)"],
      ["give birth", "/gɪv bərθ/", "farzand dunyoga keltirmoq"],
      ["fellow", "/ˈfɛloʊ/", "sherik, bir xil toifadagi"],
      ["rally", "/ˈræli/", "qo\'llab-quvvatlash uchun yig\'ilmoq"],
    ], 'I can talk about celebrity', 'News and current affairs'),
    unit(42, [
      ["capitalism", "/ˈkæpɪtəˌlɪzəm/", "kapitalizm"],
      ["socialism", "/ˈsoʊʃəˌlɪzəm/", "sotsializm"],
      ["liberalism", "/ˈlɪˌbərəˌlɪzəm/", "liberalizm"],
      ["communism", "/ˈkɑmjəˌnɪzəm/", "kommunizm"],
      ["associated with", "/əˈsoʊʃiˌeɪtəd wɪθ/", "...- bilan bog\'liq bo\'lgan"],
      ["favour", "/ˈfeɪvər/", "qo\'llab-quvvatlamoq, tarafdor bo\'lmoq"],
      ["status quo", "/ˈstætəs kwoʊ/", "mavjud holat, o\'zgarmas holat"],
      ["opposed to", "/əˈpoʊzd tɪ/", "qarshi bo\'lgan"],
      ["radical", "/ˈrædɪkəl/", "tubdan o\'zgartiruvchi, radikal"],
      ["distribute", "/dɪˈstrɪbjut/", "taqsimlamoq"],
      ["equally", "/ˈikwəli/", "teng ravishda"],
      ["left-wing", "/left-wing*/", "so\'l qanot (siyosatda)"],
      ["right-wing", "/right-wing*/", "o\'ng qanot (siyosatda)"],
      ["extremist", "/ɪkˈstrimɪst/", "ekstremist"],
      ["centre party", "/ˈsɛntər ˈpɑrti/", "markaziy partiya"],
    ], 'I can discuss political beliefs', 'News and current affairs'),
    unit(43, [
      ["zone", "/zoʊn/", "zona, hudud"],
      ["rubble", "/ˈrəbəl/", "vayrona, g\'isht parchalari"],
      ["scarce", "/skɛrs/", "taqchil, yetishmaydigan"],
      ["overwhelm", "/ˌoʊvərˈwɛlm/", "bosib ketmoq, gangitib qo\'ymoq"],
      ["shell", "/ʃɛl/", "snaryad, qobiq"],
      ["sniper", "/sˈnaɪpər/", "snayper"],
      ["random", "/ˈrændəm/", "tasodifiy, tartibsiz"],
      ["breaking point", "/ˈbreɪkɪŋ pɔɪnt/", "oxirgi chigal chegara, sinish nuqtasi"],
      ["desert", "/ˈdɛzərt/", "tashlab ketmoq, tark etmoq"],
      ["adrenalin", "/əˈdrɛnəlɪn/", "adrenalin"],
      ["grim", "/grɪm/", "xunuk, og\'ir, ayanchli"],
      ["siege", "/siʤ/", "qamal qilish"],
    ], 'I can talk about areas of conflict', 'News and current affairs'),
    unit(44, [
      ["benefits", "/ˈbɛnəfɪts/", "imtiyozlar, bonuslar"],
      ["perks", "/pərks/", "qo\'shimcha imtiyozlar"],
      ["benefits package", "/ˈbɛnəfɪts ˈpækɪʤ/", "taqdim etiladigan imtiyozlar to\'plami"],
      ["relocation allowance", "/ˌriˈloʊˈkeɪʃən əˈlaʊəns/", "ko\'chib o\'tish uchun nafaqa/pul"],
      ["performance-related bonus", "/performance-related* ˈboʊnəs/", "ish natijasiga qarab beriladigan mukofot"],
      ["company pension scheme", "/ˈkəmpəˌni ˈpɛnʃən skim/", "kompaniyaning pensiya jamg\'armasi"],
      ["maternity leave", "/məˈtərnɪti liv/", "homiladorlik va tug\'ish ta\'tili"],
      ["paternity leave", "/pəˈtərnɪti liv/", "otalik ta\'tili"],
      ["expenses", "/ɪkˈspɛnsɪz/", "xarajatlarni qoplash"],
      ["holiday entitlement", "/ˈhɑlɪˌdeɪ ɛnˈtaɪtəlmənt/", "ta\'til olish huquqi"],
      ["healthcare provision", "/ˈhɛlθˌkɛr prəˈvɪʒən/", "tibbiy sug\'urta ta\'minoti"],
      ["subsidized canteen", "/ˈsəbsɪˌdaɪzd kænˈtin/", "arzonlashtirilgan korxona oshxonasi"],
    ], 'I can explain job benefits', 'Work and finance'),
    unit(45, [
      ["accountable", "/əˈkaʊntəbəl/", "javobgar, hisobot beruvchi"],
      ["insight", "/ˈɪnˌsaɪt/", "tushuncha, chuqur anglash"],
      ["lucrative", "/ˈlukrətɪv/", "daromadli, foydali"],
      ["solely", "/ˈsoʊəli/", "faqatgina, yolg\'iz o\'zi"],
      ["juggle", "/ˈʤəgəl/", "bir nechta ishni bir vaqtda bajarishga urinmoq"],
      ["guarantee", "/ˌgɛrənˈti/", "kafolatlamoq"],
      ["additional", "/əˈdɪʃənəl/", "qo\'shimcha"],
      ["encounter", "/ɪnˈkaʊnər/", "duch kelmoq"],
      ["encroach upon", "/ɪnˈkroʊʧ əˈpɑn/", "chegarasidan o\'tib bezovta qilmoq"],
      ["morale", "/məræl/", "ruhiy holat, kayfiyat"],
      ["foster", "/ˈfɑstər/", "rivojlantirmoq, ko\'maklashmoq"],
      ["mutual", "/mˈjuʧuəl/", "o\'zaro"],
      ["fulfilling", "/fʊlˈfɪlɪŋ/", "qoniqish keltiradigan"],
      ["pool", "/pul/", "umumiy havza/resursga birlashtirmoq"],
      ["disruptive", "/dɪsˈrəptɪv/", "buzg\'unchi, tartibni buzuvchi"],
      ["undermine", "/ˈəndərˌmaɪn/", "obro\'siga putur yetkazmoq, zaiflashtirmoq"],
      ["stifle", "/ˈstaɪfəl/", "bo\'g\'ib qo\'ymoq, rivojlanishiga yo\'l qo\'ymaslik"],
      ["enterprise", "/ˈɛnərˌpraɪz/", "tashabbuskorlik, korxona"],
      ["initiative", "/ˌɪˈnɪʃətɪv/", "tashabbus"],
    ], 'I can describe ways of working', 'Work and finance'),
    unit(46, [
      ["imminent", "/ˈɪmənənt/", "yaqin orada sodir bo\'ladigan"],
      ["former", "/ˈfɔrmər/", "sobiq"],
      ["mount", "/maʊnt/", "tashkil qilmoq, boshlamoq (aksiya/hujum)"],
      ["joint venture", "/ʤɔɪnt ˈvɛnʧər/", "qo\'shma korxona"],
      ["bid", "/bɪd/", "taklif qilingan narx / tender taklifi"],
      ["backing", "/ˈbækɪŋ/", "qo\'llab-quvvatlash, homiylik"],
      ["reject", "/ˈriʤɛkt/", "rad etmoq"],
      ["shareholder", "/ˈʃɛˌrhoʊldər/", "aktsiyador"],
      ["dividend", "/ˈdɪvɪˌdɛnd/", "divident (foydadan ulush)"],
      ["clinch", "/klɪnʧ/", "kelishuvga erishmoq, bitim tuzmoq"],
      ["set off", "/sɛt ɔf/", "boshlab yubormoq, harakatga keltirmoq"],
      ["go under", "/goʊ ˈəndər/", "kasatga uchramoq, bankrot bo\'lmoq"],
      ["wind up", "/wɪnd əp/", "tugatmoq, yopmoq (kompaniyani)"],
      ["step down", "/stɛp daʊn/", "lavozimidan iste\'foga chiqmoq"],
      ["tighten your belt", "/ˈtaɪtən jʊr bɛlt/", "xarajatlarni qisqartirmoq"],
      ["lure", "/lʊr/", "aldab o\'z tomoniga og\'dirmoq"],
      ["tip the balance", "/tɪp ðə ˈbæləns/", "hal qiluvchi ta\'sir ko\'rsatmoq"],
    ], 'I can talk about the business world', 'Work and finance'),
    unit(47, [
      ["soar", "/sɔr/", "keskin o\'smoq, yuqoriga otilib chiqmoq"],
      ["surge", "/sərʤ/", "keskin o\'sish, ko\'tarilish"],
      ["gain", "/geɪn/", "foyda, o\'sish"],
      ["hike", "/haɪk/", "keskin oshish (narx/stavka)"],
      ["strengthen", "/ˈstrɛŋθən/", "mustahkamlanmoq (valyuta)"],
      ["rally", "/ˈræli/", "tiklanib olmoq, o\'sishni boshlamoq"],
      ["buoyant", "/bɔɪənt/", "barqaror o\'suvchi, ijobiy"],
      ["snap up", "/snæp əp/", "tezda sotib olmoq, ilib ketmoq"],
      ["plummet", "/ˈpləmət/", "tuban tushib ketmoq, qulamoq"],
      ["slump", "/sləmp/", "kuchli pasayish, tushkunlik"],
      ["slash", "/slæʃ/", "keskin kamaytirmoq (narxni)"],
      ["turmoil", "/ˈtərˌmɔɪl/", "sarosima, tartibsizlik"],
      ["volatile", "/ˈvɑlətəl/", "o\'zgaruvchan, turg\'un bo\'lmagan"],
      ["turbulence", "/ˈtərbjələns/", "beqarorlik, notinchlik"],
      ["investor", "/ˌɪnˈvɛstər/", "investor, sarmoyador"],
      ["equities", "/ˈɛkwətiz/", "aktsiyalar"],
      ["underpin", "/ˈəndərˌpɪn/", "qo\'llab-quvvatlamoq, asos bo\'lmoq"],
      ["corporate", "/ˈkɔrpərət/", "korporativ"],
      ["debt burden", "/dɛt ˈbərdən/", "qarz yuki"],
      ["yield", "/jild/", "daromad, foyda foizi"],
      ["bubble", "/ˈbəbəl/", "sun\'iy qabariq (moliyaviy pufak)"],
      ["dry up", "/draɪ əp/", "qurib qolmoq, tugab qolmoq"],
    ], 'I can talk about money markets', 'Work and finance'),
    unit(48, [
      ["outgoings", "/outgoings*/", "chiqimlar, xarajatlar"],
      ["debit card", "/ˈdɛbɪt kɑrd/", "debet karta"],
      ["lose track", "/luz træk/", "hisobini yo\'qotib qo\'ymoq"],
      ["credit", "/ˈkrɛdɪt/", "kredit / mablag\' mavjudligi"],
      ["mount up", "/maʊnt əp/", "ko\'payib bormoq, yig\'ilib bormoq"],
      ["transaction", "/trænˈzækʃən/", "tranzaksiya, pul o\'tkazmasi"],
      ["bank statement", "/bæŋk ˈsteɪtmənt/", "bank ko\'chirmasi"],
      ["thrifty", "/θˈrɪfti/", "tejovchi, iqtisodli"],
      ["squander", "/skˈwɑndər/", "isrof qilmoq, sovurmoq"],
      ["budget", "/ˈbəʤɪt/", "byudjet tuzmoq"],
      ["calculate", "/ˈkælkjəˌleɪt/", "hisoblamoq"],
      ["subtract", "/səbˈtrækt/", "ayirib tashlamoq"],
      ["surplus", "/ˈsərpləs/", "ortiqcha mablag'"],
      ["shortfall", "/ˈʃɔrtˌfɔl/", "mablag\' yetishmasligi, taqchillik"],
      ["economize", "/ɪˈkɑnəˌmaɪz/", "tejamkorlik qilmoq"],
      ["subsidize", "/ˈsəbsɪˌdaɪz/", "subsidiya bermoq, moliyalashtirmoq"],
      ["bail out", "/beɪl aʊt/", "qiyin ahvondan qutqarib qolmoq (pul bilan)"],
    ], 'I can talk about personal finance', 'Work and finance'),
    unit(49, [
      ["jot down", "/ʤɑt daʊn/", "shoshilinch yozib qo\'ymoq"],
      ["prioritize", "/praɪˈɔrəˌtaɪz/", "ustuvor vazifalarni belgilamoq"],
      ["ruthlessly", "/ˈruθləsli/", "shafqatsizlarcha, qat\'iy tarzda"],
      ["accomplish", "/əˈkɑmplɪʃ/", "bajarib chiqmoq, erishmoq"],
      ["anticipate", "/ænˈtɪsəˌpeɪt/", "oldindan ko\'rmoq, kutmoq"],
      ["delegate", "/ˈdɛləˌgeɪt/", "vazifani boshqasiga yuklamoq"],
      ["rigorous", "/ˈrɪgərəs/", "qattiqqo\'l, talabchan"],
      ["inundated", "/ˈɪnənˌdeɪtɪd/", "ko\'mib tashlangan (ish bilan)"],
      ["stressed out", "/strɛst aʊt/", "stressga tushgan"],
      ["promptly", "/ˈprɑmptli/", "zudlik bilan, kechiktirmasdan"],
      ["unproductive", "/ˌənprəˈdəktɪv/", "samarasiz"],
      ["get out of hand", "/gɪt aʊt əv hænd/", "nazoratdan chiqib ketmoq"],
      ["break off", "/breɪk ɔf/", "to\'xtatib turmoq (ishni)"],
      ["train of thought", "/treɪn əv θɔt/", "fikrlash zanjiri"],
      ["set aside", "/sɛt əˈsaɪd/", "ajratib qo\'ymoq (vaqt yoki pul)"],
    ], 'I can discuss time management', 'Work and finance'),
    unit(50, [
      ["deadlock", "/ˈdɛˌdlɑk/", "shaxmatdagi pat holati, berk ko\'cha (nizo)"],
      ["ballot", "/ˈbælət/", "ovoz berish, saylov (tashrif)"],
      ["dispute", "/dɪˈspjut/", "nizo, mojaro"],
      ["halt", "/hɔlt/", "to\'xtatmoq"],
      ["closure", "/ˈkloʊʒər/", "yopilish, tugatilish"],
      ["privatization", "/ˈpraɪvətəˈzeɪʃən/", "xususiylashtirish"],
      ["at stake", "/æt steɪk/", "xavf ostida turgan"],
      ["precedent", "/ˈprɛsɪdənt/", "pretsedent, o\'rnak bo\'ladigan holat"],
      ["step up", "/stɛp əp/", "faollashtirmoq, oshirmoq"],
      ["intervene", "/ˌɪntərˈvin/", "aralashmoq (nizoga)"],
      ["resolve", "/riˈzɑlv/", "hal qilmoq"],
      ["proactive", "/ˌproʊˈæktɪv/", "faol, oldindan harakat qiluvchi"],
      ["tackle", "/ˈtækəl/", "hal qilishga kirishmoq (muammoni)"],
      ["sort out", "/sɔrt aʊt/", "tartibga keltirmoq, hal qilmoq"],
      ["pass the buck", "/pæs ðə bək/", "javobgarlikni boshqasiga ag\'darmoq"],
      ["procrastinate", "/prəˈkræstəˌneɪt/", "ishni cho\'zmoq, kechiktirmoq"],
    ], 'I can discuss workplace disputes', 'Work and finance'),
    unit(51, [
      ["pet hate", "/pɛt heɪt/", "odamning asabiga tegadigan eng yomon ko\'rgan narsasi"],
      ["jam", "/ʤæm/", "tiqilib qolish, ishlamay qolish (printer/fotokopir)"],
      ["put right", "/pʊt raɪt/", "to\'g\'rilab qo\'ymoq, xatoni tuzatmoq"],
      ["absent", "/ˈæbsənt/", "yo\'q, ishda bo\'lmagan"],
      ["pile up", "/paɪl əp/", "to\'planib qolmoq, ko\'payib ketmoq"],
      ["hectic", "/ˈhɛktɪk/", "o\'ta gavjum, shoshilinch va qizg\'in"],
      ["neglect", "/nɪˈglɛkt/", "e\'tiborsiz qoldirmoq"],
      ["poke your nose in", "/poʊk jʊr noʊz ɪn/", "burnini tiqmoq (boshqaning ishiga)"],
      ["handover", "/ˈhændoʊvər/", "ishni topshirish (boshqasiga o\'tkazish)"],
      ["hum", "/həm/", "past ovozda g\'ing\'illab kuylamoq"],
      ["giggle", "/ˈgɪgəl/", "yarim ovozda kulib yubormoq"],
      ["sniff", "/snɪf/", "tortib olmoq (burunni tortmoq)"],
    ], 'I can talk about office problems', 'Work and finance'),
    unit(52, [
      ["cause", "/kɔz/", "sabab bo\'lmoq"],
      ["effect", "/ˈifɛkt/", "ta\'sir, oqibat"],
      ["consequence", "/ˈkɑnsəkwəns/", "oqibat, natija"],
      ["result in", "/rɪˈzəlt ɪn/", "bilan yakunlanmoq"],
      ["lead to", "/lɛd tɪ/", "olib kelmoq"],
      ["trigger", "/ˈtrɪgər/", "harakatga keltirmoq, turtki bo\'lmoq"],
      ["contribute to", "/kənˈtrɪbjut tɪ/", "hissa qo\'shmoq"],
      ["spark off", "/spɑrk ɔf/", "birdan keltirib chiqarmoq"],
      ["bring about", "/brɪŋ əˈbaʊt/", "sodir etmoq, amalga oshirmoq"],
    ], 'I can describe cause and effect', 'Concepts'),
    unit(53, [
      ["truth", "/truθ/", "haqiqat"],
      ["lie", "/laɪ/", "yolg\'on"],
      ["deceive", "/dɪˈsiv/", "aldamoq"],
      ["mislead", "/mɪsˈlid/", "chalg\'itmoq, adashtirmoq"],
      ["honest", "/ˈɑnəst/", "halol"],
      ["dishonest", "/dɪˈsɑnəst/", "nohalol, firibgar"],
      ["fabricate", "/ˈfæbrəˌkeɪt/", "to\'qib chiqarmoq, soxtalashtirmoq"],
      ["verify", "/ˈvɛrəˌfaɪ/", "tekshirib tasdiqlamoq"],
      ["genuine", "/ˈʤɛnjuˌaɪn/", "asl, haqiqiy"],
    ], 'I can talk about truth and lies', 'Concepts'),
    unit(54, [
      ["problem", "/ˈprɑbləm/", "muammo"],
      ["solution", "/səˈluʃən/", "yechim"],
      ["dilemma", "/dɪˈlɛmə/", "dilemma, qiyin tanlov"],
      ["resolve", "/riˈzɑlv/", "hal qilmoq"],
      ["address", "/ˈæˌdrɛs/", "shug\'ullanib hal etishga kirishmoq"],
      ["cope with", "/koʊp wɪθ/", "bardosh bermoq, uddalamoq"],
      ["tackle", "/ˈtækəl/", "kurashmoq, hal qilmoq"],
      ["obstacle", "/ˈɑbstəkəl/", "to\'siq"],
      ["hurdle", "/ˈhərdəl/", "g\'ov, to\'siq"],
    ], 'I can discuss problems and solutions', 'Concepts'),
    unit(55, [
      ["ancient", "/ˈeɪnʧənt/", "qadimiy"],
      ["outdated", "/ˈaʊtˌdeɪtɪd/", "eskirgan, o\'z kuchini yo\'qotgan"],
      ["obsolete", "/ˌɑbsəˈlit/", "muomaladan chiqqan, ishlatilmaydigan"],
      ["innovative", "/ˈɪnəˌveɪtɪv/", "innovatsion, yangi"],
      ["cutting-edge", "/ˈkətɪˌŋɛʤ/", "eng ilg\'or, so\'nggi texnologik"],
      ["state-of-the-art", "/ˌsteɪtəvðɪˈɑrt/", "eng so\'nggi rusumdagi"],
      ["revive", "/rɪˈvaɪv/", "aylantirib tiklamoq, jonlantirmoq"],
      ["modernize", "/ˈmɑdərˌnaɪz/", "zamonaviylashtirmoq"],
    ], 'I can describe old and new', 'Concepts'),
    unit(56, [
      ["success", "/səkˈsɛs/", "muvaffaqiyat"],
      ["failure", "/ˈfeɪljər/", "muvaffaqiyatsizlik"],
      ["flourish", "/flərɪʃ/", "gullab-yashnamoq, rivojlanmoq"],
      ["thrive", "/θraɪv/", "muvaffaqiyat qozonmoq"],
      ["collapse", "/kəˈlæps/", "qulamoq, barbod bo\'lmoq"],
      ["backfire", "/ˈbækˌfaɪr/", "kutilmagan teskari natija bermoq"],
      ["breakthrough", "/ˈbreɪkθˌru/", "katta yutuq, ilmiy kashfiyot"],
      ["accomplish", "/əˈkɑmplɪʃ/", "oxiriga yetkazib muvaffaqiyat qozonmoq"],
    ], 'I can talk about success and failure', 'Concepts'),
    unit(57, [
      ["past", "/pæst/", "o\'tmish"],
      ["present", "/ˈprɛzənt/", "hozirgi payt"],
      ["future", "/fˈjuʧər/", "kelajak"],
      ["imminent", "/ˈɪmənənt/", "yaqin orada kutilayotgan"],
      ["foresee", "/fɔrˈsi/", "oldindan ko\'ra bilmoq"],
      ["retrospect", "/ˈrɛtrəˌspɛkt/", "o\'tmishga nazar tashlab"],
      ["subsequent", "/ˈsəbsəkwənt/", "keyingi, so\'nggi"],
      ["prior to", "/praɪər tɪ/", "...-dan oldin"],
    ], 'I can describe the past, present, and future', 'Concepts'),
    unit(58, [
      ["anyway", "/ˈɛniˌweɪ/", "har holda, xullas"],
      ["actually", "/ˈæˌkʧuəli/", "aslida"],
      ["basically", "/ˈbeɪsɪkli/", "asosan, qisqasi"],
      ["sort of", "/sɔrt əv/", "taxminan, ... kabi"],
      ["I mean", "/aɪ min/", "mening aytmoqchimizki"],
      ["mind you", "/maɪnd ju/", "garchi shunday bo\'lsa-da"],
      ["fair enough", "/fɛr ɪˈnəf/", "kelishdik, mayli, to\'g\'ri"],
    ], 'I can use everyday language', 'Spoken English'),
    unit(59, [
      ["drop in the ocean", "/drɔp ɪn ðə ˈoʊʃən/", "dengizdan tomchi (juda oz miqdor)"],
      ["nothing to lose", "/ˈnəθɪŋ tɪ luz/", "yo\'qotadigan hech narsasi yo\'q"],
      ["foregone conclusion", "/ˈfɔrˈgɔn kənˈkluʒən/", "oldindan aniq bo\'lgan natija"],
      ["first and foremost", "/fərst ənd ˈfɔrˌmoʊst/", "avvalambor, eng asosiysi"],
      ["bend the rules", "/bɛnd ðə rulz/", "qoidalarga ozgina yon bosmoq"],
    ], 'I can use idioms and set phrases (1)', 'Spoken English'),
    unit(60, [
      ["call it a day", "/kɔl ɪt ə deɪ/", "ishni yakunlamoq, bas qilmoq"],
      ["cut to the chase", "/kət tɪ ðə ʧeɪs/", "asosiy mavzuga o\'tmoq (laqillatmasdan)"],
      ["spill the beans", "/spɪl ðə binz/", "sirni fosh qilib yubormoq"],
      ["steal the show", "/stil ðə ʃoʊ/", "hamma e\'tiborni o\'ziga qaratib olmoq"],
      ["up in the air", "/əp ɪn ðə ɛr/", "noma\'lum, hal etilmagan (reja)"],
    ], 'I can use idioms and set phrases (2)', 'Spoken English'),
    unit(61, [
      ["pros and cons", "/proʊz ənd kɑnz/", "ijobiy va salbiy tomonlari"],
      ["safe and sound", "/seɪf ənd saʊnd/", "sog\'-salomat, eson-omon"],
      ["sick and tired", "/sɪk ənd taɪərd/", "joniga tekkan, bezor bo\'lgan"],
      ["touch and go", "/təʧ ənd goʊ/", "xavfli va xavotirli (natijasi noma\'lum)"],
      ["wait and see", "/weɪt ənd si/", "kuzatamiz va ko\'ramiz"],
    ], 'I can use set phrases with two key words', 'Spoken English'),
    unit(62, [
      ["as blind as a bat", "/ɛz blaɪnd ɛz ə bæt/", "ko\'zi yaxshi ko\'rmaydigan"],
      ["as dead as a doornail", "/ɛz dɛd ɛz ə ˈdɔrˌneɪl/", "butunlay ishdan chiqqan / o\'lik"],
      ["as good as gold", "/ɛz gʊd ɛz goʊld/", "juda itoatkor va yaxshi (bola)"],
      ["as light as a feather", "/ɛz laɪt ɛz ə ˈfɛðər/", "patdek yengil"],
      ["as red as a beet", "/ɛz rɛd ɛz ə bit/", "lavlagidek qizargan (uyalganda)"],
    ], 'I can use similes', 'Spoken English'),
    unit(63, [
      ["bring about", "/brɪŋ əˈbaʊt/", "vujudga keltirmoq"],
      ["carry out", "/ˈkɛri aʊt/", "bajarib chiqmoq (tajriba/vazifa)"],
      ["fall through", "/fɔl θru/", "amalga oshmay qolmoq (reja)"],
      ["live up to", "/lɪv əp tɪ/", "umidni oqlamoq"],
      ["opt out", "/ɑpt aʊt/", "ishtirok etishdan bosh tortmoq"],
    ], 'I can use a range of phrasal verbs', 'Spoken English'),
    unit(64, [
      ["actually", "/ˈæˌkʧuəli/", "haqiqatda,aslida"],
      ["anyway", "/ˈɛniˌweɪ/", "har holda, shundoq ham"],
      ["besides", "/ˌbiˈsaɪdz/", "boshqa tomondan, qolaversa"],
      ["furthermore", "/ˈfərðərˌmɔr/", "bundan tashqari"],
      ["meanwhile", "/ˈminˌwaɪl/", "shu asnoda, shu paytda"],
    ], 'I can use discourse markers', 'Spoken English'),
    unit(65, [
      ["or something", "/ər ˈsəmθɪŋ/", "... yoki shunga o\'xshash narsa"],
      ["and things like that", "/ənd θɪŋz laɪk ðət/", "va shunga o\'xshash narsalar"],
      ["stuff", "/stəf/", "narsalar, matohlar (norasmiy)"],
      ["roughly", "/ˈrəfli/", "taxminan"],
      ["or so", "/ər soʊ/", "atrofida, ... chamasida"],
    ], 'I can use vague language', 'Spoken English'),
    unit(66, [
      ["better late than never", "/ˈbɛtər leɪt ðən ˈnɛvər/", "hechdan ko\'ra kech"],
      ["every cloud has a silver lining", "/ˈɛvəri klaʊd həz ə ˈsɪlvər ˈlaɪnɪŋ/", "har bir yomon narsaning yaxshi tomoni bo\'ladi"],
      ["look before you leap", "/lʊk ˌbiˈfɔr ju lip/", "etti o\'lchab bir kes"],
      ["practice makes perfect", "/ˈpræktɪs meɪks ˈpərˌfɪkt/", "ko\'p mashq qilish mukammallikka olib keladi"],
      ["too many cooks spoil the broth", "/tu ˈmɛni kʊks spɔɪl ðə brɔθ/", "bosh ko\'p bo\'lsa osh bulg\'anar"],
    ], 'I can use sayings and proverbs', 'Spoken English'),
    unit(67, [
      ["Dear Sir/Madam", "/dɪr sir/madam*/", "Hurmatli Janob/Oliyalari (ism noma\'lum bo\'lsa)"],
      ["Yours faithfully", "/jʊrz ˈfeɪθfəli/", "Hurmat bilan (nomalum shaxsga)"],
      ["Yours sincerely", "/jʊrz sɪnˈsɪrli/", "Hurmat bilan (ismi yozilgan shaxsga)"],
      ["further to", "/ˈfərðər tɪ/", "... munosabati bilan, davomi sifatida"],
      ["regard", "/rɪˈgɑrd/", "hurmat bajo keltirmoq"],
    ], 'I can write a formal letter', 'Written English'),
    unit(68, [
      ["consequently", "/ˈkɑnsəkˌwɛntli/", "natijada"],
      ["furthermore", "/ˈfərðərˌmɔr/", "bundan tashqari"],
      ["hence", "/hɛns/", "shu sababli, shundan kelib chiqib"],
      ["in addition", "/ɪn əˈdɪʃən/", "bunga qo\'shimcha ravishda"],
      ["nevertheless", "/ˌnɛvərðəˈlɛs/", "shunga qaramasdan, baribir"],
    ], 'I can use formal link words', 'Written English'),
    unit(69, [
      ["analyse", "/analyse*/", "tahlil qilmoq"],
      ["approach", "/əˈproʊʧ/", "yondashuv"],
      ["concept", "/ˈkɑnsɛpt/", "konsepsiya, tushuncha"],
      ["data", "/ˈdætə/", "ma\'lumotlar, faktlar"],
      ["hypothesis", "/haɪˈpɑθəsəs/", "gipoteza, faraz"],
      ["methodology", "/ˌmɛθəˈdɑləʤi/", "metodologiya, uslubiyot"],
    ], 'I can use academic English', 'Written English'),
    unit(70, [
      ["genre", "/ˈʒɑnrə/", "janr"],
      ["plot", "/plɑt/", "syujet, voqealar tarmoqi"],
      ["protagonist", "/proʊˈtægənəst/", "bosh qahramon"],
      ["theme", "/θim/", "asosiy mavzu, g\'oya"],
      ["tragedy", "/ˈtræʤədi/", "fojia"],
      ["verse", "/vərs/", "she\'r misrasi, bandi"],
    ], 'I can talk about literature', 'Written English'),
    unit(71, [
      ["atom", "/ˈætəm/", "atom"],
      ["catalyst", "/ˈkætəˌlɪst/", "katalizator"],
      ["compound", "/ˈkɑmpaʊnd/", "kimyoviy birikma"],
      ["experiment", "/ɪkˈspɛrəmənt/", "tajriba"],
      ["formula", "/ˈfɔrmjələ/", "formula"],
      ["molecule", "/ˈmɑləˌkjul/", "molekula"],
    ], 'I can use scientific English', 'Written English'),
    unit(72, [
      ["component", "/kəmˈpoʊnənt/", "detal, qism, komponent"],
      ["function", "/ˈfəŋkʃən/", "vazifa, funksiya"],
      ["mechanism", "/ˈmɛkəˌnɪzəm/", "mexanizm"],
      ["prototype", "/ˈproʊtoʊˌtaɪp/", "dastlabki namuna, prototip"],
      ["specifications", "/ˌspɛsəfəˈkeɪʃənz/", "texnik tavsifnoma"],
    ], 'I can use technical English', 'Written English'),
    unit(73, [
      ["ASAP", "/ˈeɪˌsæp/", "imkon qadar tezroq (as soon as possible)"],
      ["DIY", "/diy*/", "o\'zi ta\'mirlash (do it yourself)"],
      ["FAQ", "/faq*/", "ko\'p beriladigan savollar"],
      ["Id", "/ˈaɪˈdi/", "shaxsni tasdiqlovchi hujjat (identification)"],
      ["PIN", "/pɪn/", "shaxsiy raqam kod"],
    ], 'I can use abbreviations', 'Written English'),
    unit(74, [
      ["anti-", "/ˈænˌti-/", "qarshi (...ga qarshi)"],
      ["ex-", "/ɛks-/", "sobiq"],
      ["inter-", "/ˌɪnˈtər-/", "aro, o\'zaro"],
      ["mis-", "/mɪs-/", "noto\'g\'ri (bajarmoq)"],
      ["over-", "/ˈoʊvər-/", "haddan tashqari ko\'p"],
      ["sub-", "/səb-/", "osti, quyi qism"],
    ], 'I can use prefixes', 'Aspects of language'),
    unit(75, [
      ["-able", "/-ˈeɪbəl/", "...-sa bo\'ladigan"],
      ["-ful", "/-ful*/", "ga boy, to\'la"],
      ["-less", "/-lɛs/", "...-siz (ma\'nosini beradi)"],
      ["-hood", "/-hʊd/", "davr, holat (childhood kabi)"],
      ["-ness", "/-nɛs/", "sifatdan ot yasovchi qo\'shimcha"],
    ], 'I can use suffixes', 'Aspects of language'),
    unit(76, [
      ["accuse of", "/əˈkjuz əv/", "ayblamoq (...-da)"],
      ["apologize for", "/əˈpɑləˌʤaɪz fər/", "uzr so\'ramoq"],
      ["belong to", "/bɪˈlɔŋ tɪ/", "tegishli bo\'lmoq"],
      ["consist of", "/kənˈsɪst əv/", "iborat bo\'lmoq"],
      ["prevent from", "/prɪˈvɛnt frəm/", "to\'sqinlik qilmoq"],
    ], 'I can use words with prepositions', 'Aspects of language'),
    unit(77, [
      ["by accident", "/baɪ ˈæksədənt/", "tasodifan"],
      ["in advance", "/ɪn ədˈvæns/", "oldindan"],
      ["on purpose", "/ɔn ˈpərpəs/", "atayin, qasddan"],
      ["under control", "/ˈəndər kənˈtroʊl/", "nazorat ostida"],
      ["in a hurry", "/ɪn ə ˈhəri/", "shoshilgan holatda"],
    ], 'I can use prepositional phrases', 'Aspects of language'),
    unit(78, [
      ["broad", "/brɔd/", "keng"],
      ["deep", "/dip/", "chuqur"],
      ["flat", "/flæt/", "tekis"],
      ["heavy", "/ˈhɛvi/", "og\'ir"],
      ["sharp", "/ʃɑrp/", "o\'tkir"],
      ["smooth", "/smuð/", "silliq"],
    ], 'I can use a range of adjectives', 'Aspects of language'),
    unit(79, [
      ["absolutely", "/ˌæbsəˈlutli/", "mutlaqo, so\'zsiz"],
      ["fairly", "/ˈfɛrli/", "ancha, o\'rtacha"],
      ["extremely", "/ɪkˈstrimli/", "haddan tashqari"],
      ["slightly", "/sˈlaɪtli/", "ozgina, sal"],
      ["totally", "/ˈtoʊtəli/", "butunlay"],
    ], 'I can use different types of adverb', 'Aspects of language'),
    unit(80, [
      ["pass away", "/pæs əˈweɪ/", "vafot etmoq (yumshoq ma\'noda)"],
      ["let go", "/lɛt goʊ/", "ishdan bo\'shatmoq (yumshoqroq shaklda)"],
      ["ethnic cleansing", "/ˈɛθnɪk ˈklɛnzɪŋ/", "etnik tozalash"],
      ["collateral damage", "/kəˈlætərəl ˈdæmɪʤ/", "tinch aholiga yetgan zarar (harbiy tilda)"],
      ["downsizing", "/ˈdaʊnˌsaɪzɪŋ/", "shtatni qisqartirish"],
    ], 'I can use euphemisms', 'Aspects of language'),
  ]
};
