import { Book, createUnit as unit } from "../book-types";

export const oxfordIntermediate: Book = {
  id: "ows_intermediate",
  title: "Oxford Word Skills Intermediate",
  subtitle: "Intermediate",
  totalUnits: 100,
  units: [
    unit(1, [
      ["foreign", "/ˈfɔrən/", "chet elga tegishli, xorijiy"],
      ["basic", "/ˈbeɪsɪk/", "asosiy, tub"],
      ["recognize", "/ˈrɛkəgˌnaɪz/", "tanimoq, farqlay olmoq"],
      ["identify", "/aɪˈdɛntəˌfaɪ/", "aniqlamoq, shaxsini yoki narsani topmoq"],
      ["guess", "/gɛs/", "taxmin qilmoq, topmoq"],
      ["context", "/ˈkɑntɛkst/", "kontekst, matn muhiti"],
      ["keep a record", "/kip ə ˈrɛkərd/", "yozib bormoq, qayd etib bormoq"],
      ["formal", "/ˈfɔrməl/", "rasmiy"],
      ["informal", "/ˌɪnˈfɔrməl/", "norasmiy"],
      ["translation", "/trænzˈleɪʃən/", "tarjima"],
    ], 'Vocabulary learning', 'Learning'),
    unit(2, [
      ["keen", "/kin/", "ishtiyoqi baland, xohishi kuchli"],
      ["motivated", "/ˈmoʊtəˌveɪtəd/", "rag\'batlantirilgan, o\'ziga maqsad qo\'ygan"],
      ["improve", "/ˌɪmˈpruv/", "tahsilni/darajani yaxshilamoq"],
      ["express", "/ɪkˈsprɛs/", "ifodalamoq (fikrni)"],
      ["effectively", "/ˈifɛktɪvli/", "samarali tarzda"],
      ["obvious", "/ˈɑbviəs/", "aniq, yaqqol ko\'rinib turgan"],
      ["encouraging", "/ɪnˈkərəʤɪŋ/", "ruhlantiruvchi, dalda beruvchi"],
      ["slow down", "/sloʊ daʊn/", "sekinlashmoq"],
      ["aware of", "/əˈwɛr əv/", "xabardor bo\'lmoq, sezmoq"],
      ["frustrating", "/ˈfrəˌstreɪtɪŋ/", "tushkunlikka soluvchi, jahlni chiqaruvchi"],
      ["goal", "/goʊl/", "maqsad"],
      ["native speaker", "/ˈneɪtɪv ˈspikər/", "ona tilida so\'zlashuvchi"],
      ["expand", "/ɪkˈspænd/", "kengaytirmoq (bilimni/lug\'atni)"],
      ["complex", "/ˈkɑmplɛks/", "murakkab, chalkash"],
      ["fluent", "/fluənt/", "ravon, erkin so\'zlashuvchi"],
    ], 'Progress and aims', 'Learning'),
    unit(3, [
      ["definition", "/ˌdɛfəˈnɪʃən/", "ta\'rif, ma\'no izohi"],
      ["provide", "/prəˈvaɪd/", "ta\'minlamoq, bermoq"],
      ["avoid", "/əˈvɔɪd/", "chetlab o\'tmoq, qochmoq"],
      ["idiom", "/ˈɪdiəm/", "idioma, ibora"],
      ["entry", "/ˈɛntri/", "lug\'atdagi so\'z maqolasi/qayd"],
      ["symbol", "/ˈsɪmbəl/", "belgi, ramz"],
      ["syllable", "/ˈsɪləbəl/", "bo\'g\'in"],
      ["related", "/rɪˈleɪtɪd/", "bog\'liq, o\'zaro aloqador"],
      ["build", "/bɪld/", "kengaytirmoq, qurmoq"],
      ["style", "/staɪl/", "uslub"],
      ["for instance", "/fər ˈɪnstəns/", "masalan"],
      ["slang", "/slæŋ/", "sleng, ko\'cha tili"],
    ], 'Using an English dictionary', 'Learning'),
    unit(4, [
      ["full stop", "/fʊl stɑp/", "nuqta"],
      ["comma", "/ˈkɑmə/", "vergul"],
      ["colon", "/ˈkoʊlən/", "ikki nuqta"],
      ["semicolon", "/semicolon*/", "nuqtali vergul"],
      ["apostrophe", "/əˈpɑstrəˌfi/", "apostrof"],
      ["question mark", "/kˈwɛʃən mɑrk/", "so\'roq belgisi"],
      ["exclamation mark", "/ˌɛkskləˈmeɪʃən mɑrk/", "undov belgisi"],
      ["brackets", "/ˈbrækɪts/", "qavslar"],
      ["hyphen", "/ˈhaɪfən/", "chiziqcha (defis)"],
      ["abbreviation", "/əˌbriviˈeɪʃən/", "qisqartma"],
      ["capital letter", "/ˈkæpɪtəl ˈlɛtər/", "bosh harf"],
      ["pause", "/pɔz/", "to\'xtalish, pauza"],
    ], 'English punctuation', 'Learning'),
    unit(5, [
      ["shoulder", "/ˈʃoʊldər/", "elka"],
      ["chest", "/ʧɛst/", "ko\'krak qafasi"],
      ["elbow", "/ˈɛlˌboʊ/", "tirsak"],
      ["stomach", "/ˈstəmək/", "qorin, oshqozon"],
      ["waist", "/weɪst/", "bel"],
      ["wrist", "/rɪst/", "bilak"],
      ["hip", "/hɪp/", "son, yonbosh"],
      ["thumb", "/θəm/", "bosh barmoq (qo\'l)"],
      ["fingernail", "/ˈfɪŋgərˌneɪl/", "tirnoq"],
      ["knee", "/ni/", "tizza"],
      ["toe", "/toʊ/", "oyoq barmog\'i"],
      ["heel", "/hil/", "tovon"],
      ["ankle", "/ˈæŋkəl/", "to\'piq"],
      ["eyebrow", "/ˈaɪˌbraʊ/", "qosh"],
      ["neck", "/nɛk/", "bo\'yin"],
    ], 'The body', 'People'),
    unit(6, [
      ["bald", "/bɔld/", "kal"],
      ["broad shoulders", "/brɔd ˈʃoʊldərz/", "keng elka"],
      ["tattoo", "/ˌtæˈtu/", "tatuirovka, nakoyka"],
      ["wavy hair", "/ˈweɪvi hɛr/", "to\'lqinli soch"],
      ["dark skin", "/dɑrk skɪn/", "qoramtir teri"],
      ["in good shape", "/ɪn gʊd ʃeɪp/", "sportchi holatida, tetik"],
      ["tan", "/tæn/", "quyoshda qorayish (tan olish)"],
      ["medium build", "/ˈmidiəm bɪld/", "o\'rta tana tuzilishi"],
      ["pregnant", "/ˈprɛgnənt/", "homilador"],
      ["smooth skin", "/smuð skɪn/", "silliq teri"],
      ["figure", "/ˈfɪgjər/", "qomat"],
      ["hairstyle", "/ˈhɛrˌstaɪl/", "soch turmagi"],
      ["neat", "/nit/", "ozoda, tartibli"],
      ["contact lenses", "/ˈkɑnˌtækt ˈlɛnzɪz/", "kontakt linzalar"],
    ], 'Appearance', 'People'),
    unit(7, [
      ["ambitious", "/æmˈbɪʃəs/", "maqsadiga intiluvchan"],
      ["organized", "/ˈɔrgəˌnaɪzd/", "tartibli, uyushgan"],
      ["hard-working", "/ˌhɑrdˈwərkɪŋ/", "mehnatsevar"],
      ["outgoing", "/ˈaʊtˌgoʊɪŋ/", "kirishuvchan, ochiqko\'ngil"],
      ["generous", "/ˈʤɛnərəs/", "saxiy"],
      ["confident", "/ˈkɑnfədənt/", "o\'ziga ishongan"],
      ["patient", "/ˈpeɪʃənt/", "sabrli, toqatli"],
      ["sensible", "/ˈsɛnsəbəl/", "aqlli, mulohazali"],
      ["shy", "/ʃaɪ/", "uyatchan, tortinchoq"],
      ["dull", "/dəl/", "zerikarli"],
      ["cheerful", "/ˈʧɪrfəl/", "quvnoq"],
      ["easy-going", "/easy-going*/", "og\'ir-bosiq, muloyim"],
      ["energetic", "/ˌɛnərˈʤɛtɪk/", "g\'ayratli, energiyaga to\'la"],
      ["practical", "/ˈpræktɪkəl/", "amaliy"],
      ["responsible", "/riˈspɑnsəbəl/", "mas\'uliyatli"],
    ], 'Character', 'People'),
    unit(8, [
      ["anxious", "/ˈæŋʃəs/", "xavotirli, tashvishli"],
      ["calm", "/kɑm/", "xotirjam"],
      ["delighted", "/dɪˈlaɪtɪd/", "mamnun, judayam xursand"],
      ["disappointed", "/ˌdɪsəˈpɔɪnɪd/", "hafsalasi pir bo\'lgan"],
      ["embarrassed", "/ɪmˈbɛrəst/", "xijolat bo\'lgan"],
      ["frightened", "/ˈfraɪtənd/", "qo\'rqqan"],
      ["furious", "/fˈjʊriəs/", "g\'azabnok, o\'ta g\'azablangan"],
      ["miserable", "/ˈmɪzərəbəl/", "baxtsiz, ma\'yus"],
      ["pleased", "/plizd/", "mamnun"],
      ["relaxed", "/rɪˈlækst/", "bo\'shashgan, xotirjam"],
      ["upset", "/ˈəpˌsɛt/", "xafa bo\'lgan"],
      ["stressed", "/strɛst/", "stressga tushgan"],
      ["guilty", "/ˈgɪlti/", "aybdor his qiluvchi"],
      ["jealous", "/ˈʤɛləs/", "hasadgo\'y"],
      ["annoyed", "/əˈnɔɪd/", "g\'ashiga tekkan"],
    ], 'Feelings and emotions', 'People'),
    unit(9, [
      ["talented", "/ˈtæləntɪd/", "istedodli, qobiliyatli"],
      ["champion", "/ˈʧæmpiən/", "chempion"],
      ["brave", "/breɪv/", "jasur, qo\'rqmas"],
      ["courage", "/kərɪʤ/", "jasorat"],
      ["dignity", "/ˈdɪgnəti/", "viqor, o\'zini tuta bilish"],
      ["humility", "/hjuˈmɪlɪti/", "kamtarlik"],
      ["inspire", "/ˌɪnˈspaɪr/", "ilhomlantirmoq"],
      ["idolize", "/ˈaɪdəˌlaɪz/", "sig\'inmoq, judayam yaxshi ko\'rmoq"],
      ["dedication", "/ˌdɛdəˈkeɪʃən/", "sadoqat, fidoyilik"],
      ["charity", "/ˈʧɛrɪti/", "xayriya tashkiloti"],
      ["proud", "/praʊd/", "faxrlanuvchi"],
      ["quality", "/kˈwɑləti/", "fazilat, sifat"],
      ["kind", "/kaɪnd/", "mehribon"],
      ["gentle", "/ˈʤɛnəl/", "muloyim, yumshoq tabiatli"],
      ["loving", "/ˈləvɪŋ/", "mehr-oqibatli"],
    ], 'Personal qualities', 'People'),
    unit(10, [
      ["friendship", "/ˈfrɛndʃɪp/", "do\'stlik"],
      ["get on well", "/gɪt ɔn wɛl/", "inoq bo\'lmoq, chiqishmoq"],
      ["trust", "/trəst/", "ishonmoq"],
      ["have things in common", "/hæv θɪŋz ɪn ˈkɑmən/", "umumiy qiziqishlarga ega bo\'lmoq"],
      ["keep in touch", "/kip ɪn təʧ/", "aloqada bo\'lib turmoq"],
      ["sense of humour", "/sɛns əv ˈhjumər/", "hazil-mutoyiba tuyg\'usi"],
      ["attitude", "/ˈætəˌtud/", "munosabat, qarash"],
      ["dislike", "/dɪsˈlaɪk/", "yoqtirmaslik"],
      ["rely on", "/rɪˈlaɪ ɔn/", "tayanmoq, ishonch bildirmoq"],
      ["support", "/səˈpɔrt/", "qo\'llab-quvvatlamoq"],
      ["tell the truth", "/tɛl ðə truθ/", "haqiqatni aytmoq"],
      ["honest", "/ˈɑnəst/", "halol, rostgo\'y"],
    ], 'Friendship', 'People'),
    unit(11, [
      ["relatives", "/ˈrɛlətɪvz/", "qarindoshlar"],
      ["nuclear family", "/ˈnukliər ˈfæməli/", "kichik oila (ota-ona va bolalar)"],
      ["extended family", "/ɪkˈstɛndɪd ˈfæməli/", "kengaytirilgan oila (bobo, buvi, amaki va h.k.)"],
      ["ancestor", "/ˈænˌsɛstər/", "ajdod"],
      ["descendant", "/dɪˈsɛndənt/", "avlod, voris"],
      ["only child", "/ˈoʊnli ʧaɪld/", "olg\'iz farzand"],
      ["bring up", "/brɪŋ əp/", "voyaga yetkazmoq, tarbiyalamoq"],
      ["raise", "/reɪz/", "tarbiyalamoq, voyaga yetkazmoq"],
      ["adopt", "/əˈdɑpt/", "farzandlikka olmoq"],
      ["foster", "/ˈfɑstər/", "vaqtincha o\'z qaramog\'iga olmoq"],
      ["generation", "/ˌʤɛnərˈeɪʃən/", "avlod"],
      ["upbringing", "/ˈəpˌbrɪŋɪŋ/", "tarbiya"],
    ], 'Families', 'People'),
    unit(12, [
      ["engage", "/ɪnˈgeɪʤ/", "unashtirmoq"],
      ["wedding", "/ˈwɛdɪŋ/", "to\'y"],
      ["ceremony", "/ˈsɛrəˌmoʊni/", "marosim"],
      ["bride", "/braɪd/", "kelin"],
      ["groom", "/grum/", "kuyov"],
      ["reception", "/rɪˈsɛpʃən/", "to\'y bazmi, ziyofat"],
      ["honeymoon", "/ˈhəniˌmun/", "asal oyi"],
      ["anniversary", "/ˌænəˈvərsəri/", "yilnoma, nishonlanadigan sana"],
      ["separate", "/ˈsɛpərˌeɪt/", "ajralib yashamoq"],
      ["divorce", "/dɪˈvɔrs/", "ajrashish"],
      ["affair", "/əˈfɛr/", "xiyonat, yashirin ishqiy munosabat"],
      ["argument", "/ˈɑrgjəmənt/", "janjal, tortishuv"],
    ], 'Marriage and divorce', 'People'),
    unit(13, [
      ["region", "/ˈriʤən/", "mintaqa, hudud"],
      ["border", "/ˈbɔrdər/", "chegara"],
      ["coast", "/koʊst/", "dengiz qirg\'og\'i"],
      ["inland", "/ˈɪnˌlænd/", "quruqlik ichkarisi, dengizdan uzoqda"],
      ["mountainous", "/ˈmaʊntənəs/", "tog\'li"],
      ["desert", "/ˈdɛzərt/", "sahro, cho\'l"],
      ["jungle", "/ˈʤəŋgəl/", "jungli, qalin o\'rmon"],
      ["waterfall", "/ˈwɔtərˌfɔl/", "sharshara"],
      ["cliff", "/klɪf/", "qoya, jarlik"],
      ["cave", "/keɪv/", "g\'or"],
      ["harbour", "/ˈhɑrbər/", "port, kema to\'xtaydigan joy"],
      ["horizon", "/hərˈaɪzən/", "ufq"],
    ], 'Geography', 'The world around us'),
    unit(14, [
      ["universe", "/ˈjunəˌvərs/", "koinot"],
      ["satellite", "/ˈsætəˌlaɪt/", "sun\'iy yo\'ldosh"],
      ["revolve", "/riˈvɑlv/", "aylanmoq (orbit bo\'ylab)"],
      ["solar system", "/ˈsoʊlər ˈsɪstəm/", "quyosh sistemasi"],
      ["rocket", "/ˈrɑkət/", "raketa"],
      ["spacecraft", "/ˈspeɪˌskræft/", "kosmik kema"],
      ["explore", "/ɪkˈsplɔr/", "tadqiq qilmoq, o\'rganmoq"],
      ["experiment", "/ɪkˈspɛrəmənt/", "tajriba, eksperiment"],
      ["discover", "/dɪˈskəvər/", "kashf qilmoq"],
      ["invent", "/ˌɪnˈvɛnt/", "ixtiro qilmoq"],
      ["scientist", "/ˈsaɪəntɪst/", "olim"],
      ["solid", "/ˈsɑləd/", "qattiq jism"],
    ], 'The universe and science', 'The world around us'),
    unit(15, [
      ["changeable", "/ˈʧeɪnʤəbəl/", "o\'zgaruvchan (ob-havo)"],
      ["shower", "/ʃaʊər/", "qisqa muddatli yomg\'ir"],
      ["humid", "/ˈjumɪd/", "namgarchilik, dim"],
      ["breeze", "/briz/", "mayin shabada"],
      ["thunder", "/ˈθəndər/", "momaqaldiroq"],
      ["lightning", "/ˈlaɪtnɪŋ/", "chaqmoq"],
      ["freezing", "/ˈfrizɪŋ/", "qahraton sovuq, muzlatuvchi"],
      ["damp", "/dæmp/", "nam, namgar"],
      ["frost", "/frɔst/", "qirov, ayoz"],
      ["heatwave", "/heatwave*/", "kuchli issiq to\'lqini"],
      ["forecast", "/ˈfɔrˌkæst/", "ob-havo ma\'lumoti"],
    ], 'Weather conditions', 'The world around us'),
    unit(16, [
      ["global warming", "/ˈgloʊbəl ˈwɔrmɪŋ/", "global isish"],
      ["atmosphere", "/ˈætməsˌfɪr/", "atmosfera"],
      ["melting", "/ˈmɛltɪŋ/", "erish (muzning)"],
      ["sea level", "/si ˈlɛvəl/", "dengiz sathi"],
      ["unpredictable", "/ˌənprɪˈdɪktəbəl/", "oldindan aytib bo\'lmaydigan"],
      ["famine", "/ˈfæmən/", "ocharchilik"],
      ["drought", "/draʊt/", "qurg\'oqchilik"],
      ["carbon footprint", "/ˈkɑrbən ˈfʊtˌprɪnt/", "uglerod izi"],
      ["emission", "/ɪˈmɪʃən/", "gaz chiqarish, tashlanma"],
      ["rainforest", "/ˈraɪnˌfɔrəst/", "tropik o\'rmon"],
    ], 'Climate change', 'The world around us'),
    unit(17, [
      ["conserve", "/kənˈsərv/", "asramoq, tejab ishlatmoq"],
      ["renewable energy", "/riˈnuəbəl ˈɛnərʤi/", "qayta tiklanuvchi energiya"],
      ["recycle", "/riˈsaɪkəl/", "qayta ishlamoq"],
      ["waste", "/weɪst/", "isrof qilmoq, chiqindi"],
      ["sustainable", "/səˈsteɪnəbəl/", "barqaror, tabiatga zarar keltirmaydigan"],
      ["organic", "/ɔrˈgænɪk/", "organik (tabiiy)"],
      ["pollution", "/pəˈluʃən/", "ifloslanish"],
      ["solar power", "/ˈsoʊlər paʊər/", "quyosh energiyasi"],
      ["wind turbine", "/wɪnd ˈtərbaɪn/", "shamol generatori"],
      ["environmentally friendly", "/ɪnˌvaɪrənˈmɛnəli ˈfrɛndli/", "ekologik toza"],
    ], 'Saving the environment', 'The world around us'),
    unit(18, [
      ["wildlife", "/ˈwaɪlˌdlaɪf/", "yovvoyi tabiat"],
      ["species", "/ˈspiʃiz/", "tur (biologik)"],
      ["endangered", "/ɪnˈdeɪnʤərd/", "xavf ostidagi (turlar)"],
      ["extinct", "/ɪkˈstɪŋkt/", "yo\'qolib ketgan, qirilib ketgan"],
      ["habitat", "/ˈhæbəˌtæt/", "yashash muhiti"],
      ["predator", "/ˈprɛdətər/", "yirtqich hayvon"],
      ["prey", "/preɪ/", "o\'lja"],
      ["migration", "/maɪˈgreɪʃən/", "migratsiya, ko\'chib yurish"],
      ["creature", "/ˈkriʧər/", "mavjudot, jonivor"],
      ["feather", "/ˈfɛðər/", "pat"],
    ], 'Animals, insects and birds', 'The world around us'),
    unit(19, [
      ["enormous", "/ɪˈnɔrmɪs/", "ulg\'am, judayam katta"],
      ["tiny", "/ˈtaɪni/", "juda kichkina, mitti"],
      ["exhausted", "/ɪgˈzɔstɪd/", "holsizlangan, o\'ta charchagan"],
      ["furious", "/fˈjʊriəs/", "g\'azabdan yorilayotgan"],
      ["terrified", "/ˈtɛrəˌfaɪd/", "dahshatga tushgan, o\'ta qo\'rqqan"],
      ["fascinating", "/ˈfæsəˌneɪtɪŋ/", "maftunkor, o\'ta qiziqarli"],
      ["essential", "/ɛˈsɛnʃəl/", "juda muhim, zaruriy"],
      ["brilliant", "/ˈbrɪljənt/", "ajoyib, daho"],
      ["awful", "/ˈɔfəl/", "daxshatli, yomon"],
      ["amazed", "/əˈmeɪzd/", "hayratda qolgan"],
    ], 'Adjectives (1)', 'Language focus: adjectives and adverbs'),
    unit(20, [
      ["artificial", "/ˌɑrtəˈfɪʃəl/", "sun\'iy"],
      ["temporary", "/ˈtɛmpərˌɛri/", "vaqtinchalik"],
      ["permanent", "/ˈpərmɑˌnɛnt/", "doimiy, abadiy"],
      ["public", "/ˈpəblɪk/", "jamoatga tegishli, ommaviy"],
      ["private", "/ˈpraɪvət/", "shaxsiy, xususiy"],
      ["convenient", "/kənˈvinjənt/", "qulay"],
      ["inconvenient", "/ˌɪnkənˈvinjənt/", "noqulay"],
      ["imaginary", "/ˌɪˈmæʤəˌnɛri/", "xayoliy, to\'qima"],
      ["baggy", "/ˈbægi/", "keng (kiyim haqida)"],
      ["tight", "/taɪt/", "tor, yopishib turadigan"],
      ["rare", "/rɛr/", "kamyob, noyob"],
      ["common", "/ˈkɑmən/", "keng tarqalgan, odatiy"],
    ], 'Adjectives (2): opposites', 'Language focus: adjectives and adverbs'),
    unit(21, [
      ["stunning", "/ˈstənɪŋ/", "ajoyib, lol qoldiradigan"],
      ["thriving", "/θˈraɪvɪŋ/", "rivojlanayotgan, gullab-yashnayotgan"],
      ["vibrant", "/ˈvaɪbrənt/", "jonli, g\'ayratga to\'la"],
      ["cobbled streets", "/ˈkɑbəld strits/", "tosh yotqizilgan ko\'chalar"],
      ["diverse", "/dɪˈvərs/", "turfa xil, xilma-xil"],
      ["unwind", "/ənˈwaɪnd/", "hordiq chiqarmoq, bo\'shashmoq"],
      ["laze around", "/laze* əraʊnd/", "bekor o\'tirmoq, dam olib yotmoq"],
      ["soak up", "/soʊk əp/", "singdirmoq, muhitdan lazzatlanmoq"],
      ["charm", "/ʧɑrm/", "joziba, jozibadorlik"],
      ["trek", "/trɛk/", "piyoda uzoq yo\'l yurish, sayohat"],
      ["remote", "/rɪˈmoʊt/", "olis, olisdagi"],
      ["unspoilt", "/unspoilt*/", "buzilmagan, o\'z holicha qolgan tabiat"],
    ], 'Holidays', 'Transport and travel'),
    unit(22, [
      ["spine-tingling", "/spine-tingling*/", "dahshatli, qiziqarli (etni jimirlatuvchi)"],
      ["ghost story", "/goʊst ˈstɔri/", "arvohlar haqidagi hikoya"],
      ["set", "/sɛt/", "sahna bezagi (dekoratsiya)"],
      ["sound effects", "/saʊnd ˈifɛkts/", "ovoz effektlari"],
      ["nail-biting", "/nail-biting*/", "hayajonli, yurakni hovuchlatadigan"],
      ["adaptation", "/ˌædəpˈteɪʃən/", "moslashtirilgan asar (film/pyesa)"],
      ["twist", "/twɪst/", "kutilmagan burilish (syujetda)"],
      ["cast", "/kæst/", "aktyorlar jamoasi"],
      ["sensational", "/sɛnˈseɪʃənəl/", "sensatsion, o\'ta ajoyib"],
      ["applause", "/əˈplɔz/", "qarsaklar, olqish"],
      ["acclaimed", "/əˈkleɪmd/", "e\'tirof etilgan, olqishga sazovor"],
    ], 'A fabulous play', 'Media and entertainment'),
    unit(23, [
      ["compete", "/kəmˈpit/", "musobaqalashmoq, bellashmoq"],
      ["competitor", "/kəmˈpɛtɪtər/", "ishtirokchi, raqobatchi"],
      ["tournament", "/ˈtʊrnəmənt/", "turnir"],
      ["champion", "/ˈʧæmpiən/", "chempion"],
      ["defeat", "/dɪˈfit/", "mag\'lub etmoq"],
      ["draw", "/drɔ/", "durang o\'ynamoq"],
      ["medal", "/ˈmɛdəl/", "medal"],
      ["trophy", "/ˈtroʊfi/", "kubok, sovrin"],
      ["referee", "/ˌrɛfərˈi/", "hakam (sportda)"],
      ["spectator", "/ˈspɛkteɪtər/", "tomoshabin"],
      ["stadium", "/ˈsteɪdiəm/", "stadion"],
      ["track", "/træk/", " yugurish yo\'lakchasi"],
    ], 'Sporting events', 'Media and entertainment'),
    unit(24, [
      ["pitch", "/pɪʧ/", "maydon (futbol, regbi uchun)"],
      ["court", "/kɔrt/", "kort (tennis, basketbol uchun)"],
      ["track", "/træk/", "trek (yugurish yoki poyga uchun)"],
      ["ring", "/rɪŋ/", "ring (boks uchun)"],
      ["course", "/kɔrs/", "maydon (golf uchun)"],
      ["pool", "/pul/", "basseyn (suzish uchun)"],
      ["captain", "/ˈkæptən/", "sardor"],
      ["coach", "/koʊʧ/", "murabbiy"],
      ["opponent", "/əˈpoʊnənt/", "raqib"],
      ["supporter", "/səˈpɔrtər/", "muxlis, tarafdor"],
      ["manager", "/ˈmænɪʤər/", "menejer, bosh murabbiy"],
    ], 'Sport: people and places', 'Media and entertainment'),
    unit(25, [
      ["festival", "/ˈfɛstɪvəl/", "festival"],
      ["celebrate", "/ˈsɛləˌbreɪt/", "nishonlamoq"],
      ["procession", "/prəˈsɛʃən/", "tantanali yurish, namoyish"],
      ["fireworks", "/ˈfaɪrˌwərks/", "feyerverk"],
      ["costume", "/ˈkɑstum/", "milliy yoki maskarad libosi"],
      ["tradition", "/trəˈdɪʃən/", "an\'ana"],
      ["custom", "/ˈkəstəm/", "odat, rasm-rusum"],
      ["atmosphere", "/ˈætməsˌfɪr/", " muhit, kayfiyat"],
      ["spectacular", "/spɛkˈtækjələr/", "tomoshabop, ko\'z qoraytiradigan"],
      ["gather", "/ˈgæðər/", "to\'planmoq, yig\'ilmoq"],
    ], 'Festivals', 'Media and entertainment'),
    unit(26, [
      ["website", "/ˈwɛbˌsaɪt/", "veb-sayt"],
      ["browser", "/ˈbraʊzər/", "brauzer"],
      ["search engine", "/sərʧ ˈɪnʤən/", "qidiruv tizimi"],
      ["download", "/ˈdaʊnˌloʊd/", "yuklab olmoq"],
      ["upload", "/ˈəˌploʊd/", "yuklamoq (internetga)"],
      ["link", "/lɪŋk/", "havola (silka)"],
      ["password", "/ˈpæsˌwərd/", "parol"],
      ["wireless", "/ˈwaɪrlɪs/", "simsiz (Wi-Fi)"],
      ["broadband", "/ˈbrɔdˌbænd/", "keng polosali internet"],
      ["network", "/ˈnɛtˌwərk/", "tarmoq"],
    ], 'The internet', 'Media and entertainment'),
    unit(27, [
      ["inbox", "/inbox*/", "kiruvchi xatlar qutisi"],
      ["attachment", "/əˈtæʧmənt/", "fayl ilovasi"],
      ["forward", "/ˈfɔrwərd/", "boshqasiga yo\'naltirmoq, ulashmoq"],
      ["reply", "/rɪˈplaɪ/", "javob yozmoq"],
      ["spam", "/spæm/", "keraksiz reklama xatlari"],
      ["social media", "/ˈsoʊʃəl ˈmidiə/", "ijtimoiy tarmoqlar"],
      ["profile", "/ˈproʊˌfaɪl/", "profil"],
      ["post", "/poʊst/", "post qoldirmoq, xabar joylamoq"],
      ["share", "/ʃɛr/", "ulashmoq"],
      ["comment", "/ˈkɑmɛnt/", "izoh yozmoq"],
    ], 'Email and social media', 'Media and entertainment'),
    unit(28, [
      ["prefix", "/ˈprifɪks/", "old qo\'shimcha (prefiks)"],
      ["unemployed", "/ˌənɛmˈplɔɪd/", "ishsiz"],
      ["disappear", "/ˌdɪsəˈpɪr/", "g\'oyib bo\'lmoq"],
      ["impossible", "/ˌɪmˈpɑsəbəl/", "imkonsiz"],
      ["illegal", "/ˌɪˈligəl/", "noqonuniy"],
      ["irregular", "/ˌɪˈrɛgjələr/", "notartib, noto\'g\'ri"],
      ["misunderstand", "/ˌmɪsəndərˈstænd/", "noto\'g\'ri tushunmoq"],
      ["rewrite", "/ˈriˌraɪt/", "qayta yozmoq"],
      ["overcook", "/ˌoʊvərˈkʊk/", "haddan tashqari pishirib yubormoq"],
      ["underpaid", "/ˈəndərˈpeɪd/", "kam haq to\'lanadigan"],
    ], 'Word building: prefixes', 'Language focus: word building'),
    unit(29, [
      ["suffix", "/ˈsəfɪks/", "ort qo\'shimcha (suffiks)"],
      ["happiness", "/ˈhæpinəs/", "baxt"],
      ["hood", "/hʊd/", "bolalik (childhood kabi)"],
      ["friendship", "/ˈfrɛndʃɪp/", "do\'stlik"],
      ["editable", "/editable*/", "tahrirlasa bo\'ladigan"],
      ["careless", "/ˈkɛrlɛs/", "e\'tiborsiz, loqayd"],
      ["useful", "/ˈjusfəl/", "foydali"],
      ["scientist", "/ˈsaɪəntɪst/", "olim"],
      ["dominate", "/ˈdɑməˌneɪt/", "ustunlik qilmoq"],
      ["industrialize", "/ˌɪnˈdəstriəˌlaɪz/", "sanoatlashtirmoq"],
    ], 'Word building: suffixes', 'Language focus: word building'),
    unit(30, [
      ["although", "/ˌɔlˈðoʊ/", "...-sa ham, garchi"],
      ["however", "/ˌhaʊˈɛvər/", "biroq, qolaversa"],
      ["despite", "/dɪˈspaɪt/", "...-ga qaramasdan"],
      ["in spite of", "/ɪn spaɪt əv/", "...-ga qaramasdan"],
      ["furthermore", "/ˈfərðərˌmɔr/", "bundan tashqari"],
      ["moreover", "/mɔˈroʊvər/", "qolaversa, ustiga-ustak"],
      ["consequently", "/ˈkɑnsəkˌwɛntli/", "natijada, shuning uchun"],
      ["therefore", "/ˈðɛrˌfɔr/", "shuning uchun, shu sababli"],
      ["in order to", "/ɪn ˈɔrdər tɪ/", "... maqsadida, ... uchun"],
      ["whereas", "/wɛˈræz/", "hollarda, holbuki"],
    ], 'Link words', 'Language focus: word building'),
    unit(31, [
      ["straight road", "/streɪt roʊd/", "to\'g\'ri yo\'q"],
      ["bend", "/bɛnd/", "burilish, egri joy"],
      ["roundabout", "/ˈraʊndəˌbaʊt/", "aylanma yo\'l (krugovoy)"],
      ["traffic lights", "/ˈtræfɪk laɪts/", "svetofor"],
      ["pavement", "/ˈpeɪvmənt/", "piyodalar yo\'lagi (trotuar)"],
      ["crossing", "/ˈkrɔsɪŋ/", "piyodalar o\'tish joyi (zebira)"],
      ["skid", "/skɪd/", "sirpanib ketmoq (mashina haqida)"],
      ["surface", "/ˈsərfəs/", "yuza, yo\'l qoplamasi"],
      ["lane", "/leɪn/", "harakat bo\'lagi (yo\'l qismi)"],
      ["block", "/blɑk/", "to\'sib qo\'ymoq"],
    ], 'Roads', 'Transport and travel'),
    unit(32, [
      ["concentrate", "/ˈkɑnsənˌtreɪt/", "diqqatni jamlamoq"],
      ["speed limit", "/spid ˈlɪmət/", "tezlik cheklovi"],
      ["fasten seat belt", "/ˈfæsən sit bɛlt/", "xavfsizlik kamarini taqmoq"],
      ["signal", "/ˈsɪgnəl/", "burilish chirog\'ini bermoq, ishora qilmoq"],
      ["driving licence", "/ˈdraɪvɪŋ ˈlaɪsəns/", "haydovchilik guvohnomasi"],
      ["speeding", "/ˈspidɪŋ/", "tezlikni oshirib yuborish"],
      ["red light", "/rɛd laɪt/", "qizil chiroq"],
      ["fine", "/faɪn/", "jarima"],
      ["insurance", "/ˌɪnˈʃʊrəns/", "sug\'urta"],
    ], 'Driving', 'Transport and travel'),
    unit(33, [
      ["direct train", "/dɪˈrɛkt treɪn/", "to\'g\'ridan-to\'g\'ri poyezd"],
      ["stopping train", "/ˈstɑpɪŋ treɪn/", "hamma bekatda to\'xtovchi poyezd"],
      ["express train", "/ɪkˈsprɛs treɪn/", "tezurar poyezd"],
      ["destination", "/ˌdɛstɪˈneɪʃən/", "boradigan manzil"],
      ["single ticket", "/ˈsɪŋgəl ˈtɪkɪt/", "bir tomonlama chipta"],
      ["return ticket", "/rɪˈtərn ˈtɪkɪt/", "borish-kelish chiptasi"],
      ["platform", "/ˈplætˌfɔrm/", "perron, platforma"],
      ["miss a train", "/mɪs ə treɪn/", "poyezddan qolib ketmoq"],
      ["catch a train", "/kæʧ ə treɪn/", "poyezdga ulgurib chiqmoq"],
      ["change trains", "/ʧeɪnʤ treɪnz/", "boshqa poyezdga o\'tirmoq (pereplavka)"],
    ], 'Trains and buses', 'Transport and travel'),
    unit(34, [
      ["airfare", "/ˈɛrˌfɛr/", "aviachipta narxi"],
      ["check-in desk", "/check-in* dɛsk/", "ro\'yxatdan o\'tish punkti"],
      ["departure lounge", "/dɪˈpɑrʧər laʊnʤ/", "kutish zali (aeroportda)"],
      ["take-off", "/take-off*/", "havoga ko\'tarilish (uchish)"],
      ["landing", "/ˈlændɪŋ/", "yerga qo\'nish"],
      ["aisle seat", "/aɪəl sit/", "yo\'lak bo\'yidagi o\'rindiq"],
      ["window seat", "/ˈwɪndoʊ sit/", "deraza yonidagi o\'rindiq"],
      ["delayed", "/dɪˈleɪd/", "kechiktirilgan (reys)"],
      ["gate", "/geɪt/", "chiqish eshigi (aeroportda)"],
    ], 'Air travel', 'Transport and travel'),
    unit(35, [
      ["camp", "/kæmp/", "lagerda yoki cherkovda yashamoq"],
      ["tent", "/tɛnt/", "chodir, palatka"],
      ["campsite", "/ˈkæmpˌsaɪt/", "lager maydoni"],
      ["hostel", "/ˈhɑstəl/", "hostel, arzon mehmonxona"],
      ["reservation", "/ˌrɛzərˈveɪʃən/", "bron qilish, oldindan band qilish"],
      ["sunbathe", "/ˈsənˌbeɪð/", "quyoshda toblanmoq"],
      ["sightseeing", "/ˈsaɪtˈsiɪŋ/", "diqqatga sazovor joylarni tomosha qilish"],
      ["resort", "/rɪˈzɔrt/", "kurort shaharcha, dam olish maskani"],
    ], 'Holidays', 'Transport and travel'),
    unit(36, [
      ["concentrate on", "/ˈkɑnsənˌtreɪt ɔn/", "diqqatni jamlamoq (-ga)"],
      ["depend on", "/dɪˈpɛnd ɔn/", "bog\'liq bo\'lmoq"],
      ["rely on", "/rɪˈlaɪ ɔn/", "tayanmoq, ishonmoq"],
      ["apologize for", "/əˈpɑləˌʤaɪz fər/", "uzr so\'ramoq (- uchun)"],
      ["succeed in", "/səkˈsid ɪn/", "muvaffaqiyat qozonmoq (-da)"],
      ["complain about", "/kəmˈpleɪn əˈbaʊt/", "shikoyat qilmoq (- haqida)"],
      ["belong to", "/bɪˈlɔŋ tɪ/", "tegishli bo\'lmoq (-ga)"],
      ["care about", "/kɛr əˈbaʊt/", "ahamiyat bermoq, g\'amxo\'rlik qilmoq"],
    ], 'Verb + preposition', 'Language focus: prepositions'),
    unit(37, [
      ["alternative to", "/ɔlˈtərnətɪv tɪ/", "...-ga muqobil, o\'rinbosar"],
      ["experience of", "/ɪkˈspɪriəns əv/", "... tajribasiga ega bo\'lish"],
      ["rise in", "/raɪz ɪn/", "...-da o\'sish / ko\'tarilish"],
      ["advantage of", "/ædˈvæntɪʤ əv/", "... ning afzalligi"],
      ["respect for", "/rɪˈspɛkt fər/", "...-ga nisbatan hurmat"],
      ["need for", "/nid fər/", "...-ga bo\'lgan ehtiyoj"],
      ["connection between", "/kəˈnɛkʃən bɪtˈwin/", "... o\'rtasidagi bog\'liqlik"],
      ["cause of", "/kɔz əv/", "... ning sababi"],
    ], 'Noun + preposition', 'Language focus: prepositions'),
    unit(38, [
      ["in a hurry", "/ɪn ə ˈhəri/", "shoshilib turgan holatda"],
      ["on time", "/ɔn taɪm/", "o\'z vaqtida, vaqtida"],
      ["in time", "/ɪn taɪm/", "ulgurib, vaqti bilan"],
      ["for long", "/fər lɔŋ/", "uzoq vaqt davomida (asosan inkor gapda)"],
      ["at times", "/æt taɪmz/", "ba\'zida, vaqti-vaqti bilan"],
      ["at last", "/æt læst/", "nihoyat, oxir oqibat"],
      ["in the meantime", "/ɪn ðə ˈminˌtaɪm/", "shu orada, vaqtincha"],
    ], 'Prepositions in time phrases', 'Language focus: prepositions'),
    unit(39, [
      ["interested in", "/ˈɪntəˌrɛstɪd ɪn/", "qiziqqan (-ga)"],
      ["worried about", "/ˈwərid əˈbaʊt/", "tashvishlangan (- haqida)"],
      ["famous for", "/ˈfeɪməs fər/", "mashhur (... bilan / uchun)"],
      ["frightened of", "/ˈfraɪtənd əv/", "qo\'rqqan (-dan)"],
      ["proud of", "/praʊd əv/", "faxrlanadigan (-dan)"],
      ["jealous of", "/ˈʤɛləs əv/", "hasad qiladigan (-ga)"],
      ["bored with", "/bɔrd wɪθ/", "zerikkan (-dan)"],
      ["angry with", "/ˈæŋgri wɪθ/", "jahli chiqqan (-ga o\'tgan)"],
    ], 'Adjective + preposition', 'Language focus: prepositions'),
    unit(40, [
      ["in public", "/ɪn ˈpəblɪk/", "ommaviy joyda, hammaning oldida"],
      ["for life", "/fər laɪf/", "umrbod, hayot oxirigacha"],
      ["on the streets", "/ɔn ðə strits/", "ko\'chada qolgan, uysiz"],
      ["for free", "/fər fri/", "tekinga, bepul"],
      ["at risk", "/æt rɪsk/", "xavf ostida"],
      ["in general", "/ɪn ˈʤɛnərəl/", "umumiy olganda"],
      ["by mistake", "/baɪ mɪˈsteɪk/", "xatoshilik bilan, adashib"],
      ["on average", "/ɔn ˈævərɪʤ/", "o\'rtacha hisobda"],
    ], 'Prepositional phrases', 'Language focus: prepositions'),
    unit(41, [
      ["container", "/kənˈteɪnər/", "idish, quti"],
      ["substance", "/ˈsəbstəns/", "modda, qattiq/suyuq jism"],
      ["device", "/dɪˈvaɪs/", "qurilma, moslama"],
      ["creature", "/ˈkriʧər/", "mavjudot, jonivor"],
      ["material", "/məˈtɪriəl/", "mato, material"],
      ["object", "/ˈɑbʤɛkt/", "buyum, narsa"],
      ["article", "/ˈɑrtɪkəl/", "buyum, element (masalan, kiyim-kechak)"],
      ["rubber", "/ˈrəbər/", "rezina"],
      ["steel", "/stil/", "po\'lat"],
      ["leather", "/ˈlɛðər/", "charm"],
      ["cardboard", "/ˈkɑrdˌbɔrd/", "karton"],
    ], 'Describing objects', 'Describing things'),
    unit(42, [
      ["hammer", "/ˈhæmər/", "bolg\'a"],
      ["drill", "/drɪl/", "drel (parma)"],
      ["nail", "/neɪl/", "mix"],
      ["needle", "/ˈnidəl/", "igna"],
      ["scissors", "/ˈsɪzərz/", "qaychi"],
      ["string", "/strɪŋ/", "ip, ichki arqon"],
      ["rope", "/roʊp/", "arqon"],
      ["tape", "/teɪp/", "skotch, yopishqoq lenta"],
      ["glue", "/glu/", "yelim"],
      ["mess", "/mɛs/", "tartibsizlik, kirish-chiqish"],
      ["mud", "/məd/", "loy, balchiq"],
      ["dust", "/dəst/", "chang"],
    ], 'Household tasks', 'Describing things'),
    unit(43, [
      ["property", "/ˈprɑpərti/", "ko\'chmas mulk, bino"],
      ["historic", "/hɪˈstɔrɪk/", "tarixiy"],
      ["cottage", "/ˈkɑtɪʤ/", "qishloq uyi, kottej"],
      ["setting", "/ˈsɛtɪŋ/", "joylashgan o\'rni, tabiat qo\'ynidagi muhit"],
      ["entrance", "/ˈɛntrəns/", "kirish eshigi"],
      ["ceiling", "/ˈsilɪŋ/", "shift"],
      ["balcony", "/ˈbælkəni/", "balkon"],
      ["garage", "/gərɑʒ/", "garaj"],
      ["commercial", "/kəˈmərʃəl/", "tijoriy"],
      ["resident", "/ˈrɛzɪdənt/", "shu yerda yashovchi aholi"],
    ], 'Buildings', 'Describing things'),
    unit(44, [
      ["soil", "/sɔɪl/", "tuproq, yer"],
      ["pot", "/pɑt/", "tuvak"],
      ["seed", "/sid/", "urug\'"],
      ["layer", "/leɪər/", "qatlam"],
      ["stem", "/stɛm/", "poya"],
      ["root", "/rut/", "ildiz"],
      ["support", "/səˈpɔrt/", "tayanch bo\'lmoq, qo\'llamoq"],
      ["row", "/roʊ/", "qator"],
      ["edge", "/ɛʤ/", "chekka, qirg\'oq"],
    ], 'How to grow something', 'Describing things'),
    unit(45, [
      ["circle", "/ˈsərkəl/", "doira, aylana"],
      ["square", "/skwɛr/", "kvadrat"],
      ["rectangle", "/ˈrɛktæŋgəl/", "to\'g\'ri to\'rtburchak"],
      ["triangle", "/ˈtraɪˌæŋgəl/", "uchburchak"],
      ["point", "/pɔɪnt/", "uchi, nuqta"],
      ["straight", "/streɪt/", "to\'g\'ri (chiziq)"],
      ["curved", "/kərvd/", "egri, qayrilgan"],
      ["angle", "/ˈæŋgəl/", "burchak"],
      ["chart", "/ʧɑrt/", "diagramma, jadval"],
      ["diagram", "/ˈdaɪəˌgræm/", "chizma, sxema"],
    ], 'Shapes and lines', 'Describing things'),
    unit(46, [
      ["scene", "/sin/", "manzara, voqea joyi"],
      ["foreground", "/ˈfɔrˌgraʊnd/", "oldingi fon"],
      ["background", "/ˈbækˌgraʊnd/", "orqa fon"],
      ["distance", "/ˈdɪstəns/", "masofa, uzoqlik"],
      ["ignore", "/ˌɪgˈnɔr/", "e\'tibor bermaslik"],
      ["impression", "/ˌɪmˈprɛʃən/", "taassurot"],
      ["peaceful", "/ˈpisfəl/", "tinch, osoyishta"],
      ["original", "/ərˈɪʤənəl/", "o\'ziga xos, original"],
      ["studio", "/ˈstudiˌoʊ/", "rassom ustaxonasi, studiya"],
    ], 'A painting', 'Describing things'),
    unit(47, [
      ["sight", "/saɪt/", "ko\'rish qobiliyati"],
      ["hearing", "/ˈhirɪŋ/", "eshitish qobiliyati"],
      ["smell", "/smɛl/", "hid bilish, hid"],
      ["taste", "/teɪst/", "ta\'m bilish, ta\'m"],
      ["touch", "/təʧ/", "sezish (tovlanish), ushlash"],
      ["sound", "/saʊnd/", "tovush chiqarmoq, tuyulmoq"],
      ["press", "/prɛs/", "bosmoq"],
      ["flavor", "/ˈfleɪvər/", "maza, xushbo\'y ta\'m"],
    ], 'The five senses', 'Describing things'),
    unit(48, [
      ["crime", "/kraɪm/", "jinoyat"],
      ["break the law", "/breɪk ðə lɔ/", "qonunni buzmoq"],
      ["theft", "/θɛft/", "o\'g\'rilik"],
      ["robbery", "/ˈrɑbəri/", "talash, bosqinchilik"],
      ["burglary", "/ˈbərgləri/", "xonadonga o\'g\'irlikka tushish"],
      ["assault", "/əˈsɔlt/", "jismoniy hujum qilish"],
      ["murder", "/ˈmərdər/", "qotillik"],
      ["prison", "/ˈprɪzən/", "qamoqxona"],
      ["fine", "/faɪn/", "jarima"],
      ["illegal", "/ˌɪˈligəl/", "noqonuniy"],
    ], 'Crime', 'Social and political issues'),
    unit(49, [
      ["victim", "/ˈvɪktɪm/", "jabrlanuvchi, qurbon"],
      ["investigate", "/ˌɪnˈvɛstəˌgeɪt/", "tergov qilmoq, o\'rganmoq"],
      ["witness", "/ˈwɪtnəs/", "guvoh"],
      ["evidence", "/ˈɛvədəns/", "dalil, guvohlik"],
      ["arrest", "/ərˈɛst/", "hibsga olmoq"],
      ["charge", "/ʧɑrʤ/", "ayb qo\'ymoq, ayblamoq"],
      ["court", "/kɔrt/", "sud"],
      ["trial", "/traɪəl/", "sud jarayoni"],
      ["jury", "/ˈʤʊri/", "hakamlar hay\'ati"],
      ["judge", "/ʤəʤ/", "sudya"],
      ["guilty", "/ˈgɪlti/", "aybdor"],
      ["innocent", "/ˈɪnəsənt/", "beayb, begunoh"],
    ], 'The justice system', 'Social and political issues'),
    unit(50, [
      ["disease", "/dɪˈziz/", "kasallik, dard"],
      ["asthma", "/ˈæzmə/", "astma (nafas yo\'li kasalligi)"],
      ["allergy", "/ˈælərʤi/", "allergiya"],
      ["mental health", "/ˈmɛntəl hɛlθ/", "ruhiy salomatlik"],
      ["treatment", "/ˈtritmənt/", "davolash"],
      ["ageing population", "/ageing* ˌpɑpjəˈleɪʃən/", "qarib borayotgan aholi"],
      ["tax", "/tæks/", "soliq"],
      ["fit", "/fɪt/", "badantarbiya qilib turgan, sog\'lom"],
      ["strength", "/strɛŋθ/", "kuch, quvvat"],
    ], 'Health issues', 'Social and political issues'),
    unit(51, [
      ["government", "/ˈgəvərnmənt/", "hukumat"],
      ["election", "/ɪˈlɛkʃən/", "saylov"],
      ["vote", "/voʊt/", "ovoz bermoq"],
      ["policy", "/ˈpɑləsi/", "siyosat (davlat yoki partiya maqsadi)"],
      ["minister", "/ˈmɪnɪstər/", "vazir"],
      ["parliament", "/ˈpɑrləmɛnt/", "parlament"],
      ["party", "/ˈpɑrti/", "siyosiy partiya"],
      ["campaign", "/kæmˈpeɪn/", "targ\'ibot kampaniyasi"],
      ["candidate", "/ˈkænədɪt/", "nomzod"],
      ["democracy", "/dɪˈmɑkrəsi/", "demokratiya"],
    ], 'Politics', 'Social and political issues'),
    unit(52, [
      ["peace", "/pis/", "tinchlik"],
      ["conflict", "/ˈkɑnflɪkt/", "mojaro, to\'qnashuv"],
      ["troops", "/trups/", "qo\'shinlar, askarlar"],
      ["weapon", "/ˈwɛpən/", "qurol"],
      ["attack", "/əˈtæk/", "hujum qilmoq"],
      ["defend", "/dɪˈfɛnd/", "himoya qilmoq"],
      ["victory", "/ˈvɪktəri/", "g\'alaba"],
      ["defeat", "/dɪˈfit/", "mag\'lubiyatga uchratmoq"],
      ["treaty", "/ˈtriti/", "shartnoma, sulh"],
      ["ally", "/ˈælaɪ/", "ittifoqdosh"],
    ], 'War and peace', 'Social and political issues'),
    unit(53, [
      ["century", "/ˈsɛnʧəri/", "asr, yuz yillik"],
      ["decade", "/ˈdɛkeɪd/", "o\'n yillik"],
      ["era", "/ˈɪrə/", "davr, era"],
      ["ancestor", "/ˈænˌsɛstər/", "ajdod"],
      ["civilization", "/ˌsɪvəlɪˈzeɪʃən/", "sivilizatsiya, madaniyat"],
      ["empire", "/ˈɛmpaɪər/", "imperiya"],
      ["colony", "/ˈkɑləni/", "koloniya"],
      ["revolution", "/ˌrɛvəˈluʃən/", "inqilob"],
      ["independence", "/ˌɪndɪˈpɛndəns/", "mustaqillik"],
      ["abolish", "/əˈbɑlɪʃ/", "tugatmoq, bekor qilmoq"],
    ], 'Events in history', 'Social and political issues'),
    unit(54, [
      ["poverty", "/ˈpɑvərti/", "kambag\'allik, yo\'qsizlik"],
      ["homelessness", "/ˈhoʊmləsnəs/", "uysizlik"],
      ["unemployment", "/ˌənɪmˈplɔɪmənt/", "ishsizlik"],
      ["equality", "/ɪkˈwɑləti/", "tenglik"],
      ["discrimination", "/dɪˌskrɪməˈneɪʃən/", "kamsitish, diskriminatsiya"],
      ["welfare", "/ˈwɛlˌfɛr/", "ijtimoiy ta\'minot, farovonlik"],
      ["immigration", "/ˌɪməˈgreɪʃən/", "immigratsiya"],
      ["reform", "/rɪˈfɔrm/", "islohot"],
      ["pension", "/ˈpɛnʃən/", "pensiya"],
    ], 'Social issues', 'Social and political issues'),
    unit(55, [
      ["be / was, were / been", "/bi  wɑz, wər  bɪn/", "bo\'lmoq"],
      ["begin / began / begun", "/bɪˈgɪn  bɪˈgæn  ˈbeɪgən/", "boshlamoq"],
      ["break / broke / broken", "/breɪk  broʊk  ˈbroʊkən/", "sinmoq, sindirmoq"],
      ["choose / chose / chosen", "/ʧuz  ʧoʊz  ˈʧoʊzən/", "tanlamoq"],
      ["fall / fell / fallen", "/fɔl  fɛl  ˈfɑlən/", "yiqilmoq"],
      ["forget / forgot / forgotten", "/fərˈgɛt  fərˈgɑt  fərˈgɑtən/", "unutmoq"],
      ["grow / grew / grown", "/groʊ  gru  groʊn/", "o\'stirmoq, o\'smoq"],
      ["hide / hid / hidden", "/haɪd  hɪd  ˈhɪdən/", "yashirinmoq, yashirmoq"],
      ["ring / rang / rung", "/rɪŋ  ræŋ  rəŋ/", "qo\'ng\'iroq qilmoq"],
      ["throw / threw / thrown", "/θroʊ  θru  θroʊn/", "otmoq, irg\'itmoq"],
    ], 'Irregular verbs', 'Language focus: verbs'),
    unit(56, [
      ["want to do", "/wɔnt tɪ du/", "qilmoqni xohlamoq"],
      ["hope to do", "/hoʊp tɪ du/", "umid qilmoq"],
      ["decide to do", "/ˌdɪˈsaɪd tɪ du/", "qaror qilmoq"],
      ["enjoy doing", "/ˌɛnˈʤɔɪ duɪŋ/", "zavqlanib bajarmoq"],
      ["finish doing", "/ˈfɪnɪʃ duɪŋ/", "tugatmoq"],
      ["mind doing", "/maɪnd duɪŋ/", "e\'tiroz bildirmoq, qarshi bo\'lmoq"],
      ["stop doing", "/stɑp duɪŋ/", "to\'xtatmoq"],
      ["start doing", "/stɑrt duɪŋ/", "boshlamoq"],
    ], 'Verb + infinitive or -ing form', 'Language focus: verbs'),
    unit(57, [
      ["enjoy oneself", "/ˌɛnˈʤɔɪ ˌwənˈsɛlf/", "zavqlanmoq, miriqib dam olmoq"],
      ["hurt oneself", "/hərt ˌwənˈsɛlf/", "o\'zini jarohatlab qo\'ymoq"],
      ["introduce oneself", "/ˌɪntrəˈdus ˌwənˈsɛlf/", "tanishmoq, o\'zini tanishtirmoq"],
      ["behave oneself", "/bɪˈheɪv ˌwənˈsɛlf/", "o\'zini yaxshi tutmoq"],
      ["help oneself", "/hɛlp ˌwənˈsɛlf/", "o\'zi olib yemoq / xizmat qilmoq"],
      ["cut oneself", "/kət ˌwənˈsɛlf/", "o\'zini kesib olmoq"],
    ], 'Using verbs with reflexive pronouns', 'Language focus: verbs'),
    unit(58, [
      ["take time", "/teɪk taɪm/", "vaqt olmoq"],
      ["take a photo", "/teɪk ə ˈfoʊˌtoʊ/", "rasmga olmoq"],
      ["take a test", "/teɪk ə tɛst/", "imtihon topshirmoq"],
      ["take place", "/teɪk pleɪs/", "sodir bo\'lmoq, o\'tmoq"],
      ["take care of", "/teɪk kɛr əv/", "g\'amxo\'rlik qilmoq"],
      ["take off", "/teɪk ɔf/", "yechmoq (kiyimni) / uchmoq (samolyot)"],
      ["take part", "/teɪk pɑrt/", "ishtirok etmoq"],
    ], 'take', 'Language focus: verbs'),
    unit(59, [
      ["painting", "/ˈpeɪnɪŋ/", "tasviriy san\'at asari, rasm"],
      ["sculpture", "/ˈskəlpʧər/", "haykaltaroshlik asari, haykal"],
      ["gallery", "/ˈgæləri/", "galereya, ko\'rgazma zali"],
      ["exhibition", "/ˌɛksəˈbɪʃən/", "ko\'rgazma"],
      ["artist", "/ˈɑrtɪst/", "rassom"],
      ["portrait", "/ˈpɔrtrət/", "portret"],
      ["landscape", "/ˈlænˌskeɪp/", "tabiat manzarasi"],
      ["masterpiece", "/ˈmæstərˌpis/", "shohasar"],
      ["brush", "/brəʃ/", "mo\'yqalam"],
    ], 'Art', 'Media and entertainment'),
    unit(60, [
      ["director", "/dɪˈrɛktər/", "rejissyor"],
      ["producer", "/prəˈdusər/", "produser"],
      ["script", "/skrɪpt/", "ssenariy"],
      ["plot", "/plɑt/", "syujet, voqealar rivoji"],
      ["subtitles", "/ˈsəbˌtaɪtəlz/", "subtitrlar"],
      ["sequel", "/ˈsikwəl/", "davomi (filmning)"],
      ["review", "/ˌrivˈju/", "taqriz, sharh"],
      ["action film", "/ˈækʃən fɪlm/", "ekshn, jangari film"],
      ["comedy", "/ˈkɑmədi/", "komediya"],
      ["thriller", "/θˈrɪlər/", "triller, detektiv"],
    ], 'Films', 'Media and entertainment'),
    unit(61, [
      ["stage", "/steɪʤ/", "sahna"],
      ["audience", "/ˈɔdiəns/", "tomoshabinlar, zal"],
      ["performance", "/pərˈfɔrməns/", "spektakl, ijro, namoyish"],
      ["actor", "/ˈæktər/", "aktyor"],
      ["actress", "/ˈæktrəs/", "aktrisa"],
      ["play", "/pleɪ/", "pesa, sahna asari"],
      ["musical", "/mˈjuzɪkəl/", "myuzikl"],
      ["rehearsal", "/rɪˈhərsəl/", "mashq, repetitsiya"],
      ["curtain", "/ˈkərtən/", "parda (teatrda)"],
      ["box office", "/bɑks ˈɔfəs/", "chipta kassasi"],
    ], 'Theatre', 'Media and entertainment'),
    unit(62, [
      ["concert", "/ˈkɑnsərt/", "konsert"],
      ["band", "/bænd/", "musiqiy guruh"],
      ["orchestra", "/ˈɔrkəstrə/", "orkestr"],
      ["composer", "/kəmˈpoʊzər/", "kompozitor"],
      ["lyrics", "/ˈlɪrɪks/", "qo\'shiq matni"],
      ["album", "/ˈælbəm/", "albom"],
      ["track", "/træk/", "trek, qo\'shiq qismi"],
      ["pop", "/pɑp/", "pop musiqa"],
      ["classical music", "/ˈklæsɪkəl mˈjuzɪk/", "klassik musiqa"],
      ["rhythm", "/ˈrɪðəm/", "ritm, ohang"],
    ], 'Music', 'Media and entertainment'),
    unit(63, [
      ["channel", "/ˈʧænəl/", "kanal (televideniye)"],
      ["documentary", "/ˌdɑkjəˈmɛnəri/", "hujjatli film"],
      ["soap opera", "/soʊp ˈɑprə/", "serial, telenovela"],
      ["advertisement", "/ˌædvərˈtaɪzmənt/", "reklama"],
      ["episode", "/ˈɛpɪˌsoʊd/", "qism, epizod"],
      ["series", "/ˈsɪriz/", "ko\'p qismli serial"],
      ["presenter", "/ˈprɛzəntər/", "boshlovchi"],
      ["viewer", "/vjuər/", "teletomoshabin"],
      ["stream", "/strim/", "onlayn uzatmoq / ko\'rmoq"],
      ["remote control", "/rɪˈmoʊt kənˈtroʊl/", "pult (televizor uchun)"],
    ], 'TV and online viewing', 'Media and entertainment'),
    unit(64, [
      ["headline", "/ˈhɛˌdlaɪn/", "sarlavha"],
      ["journalist", "/ˈʤərnəlɪst/", "jurnalist"],
      ["editor", "/ˈɛdɪtər/", "redaktor"],
      ["article", "/ˈɑrtɪkəl/", "maqola"],
      ["press", "/prɛs/", "matbuot"],
      ["tabloid", "/ˈtæblɔɪd/", "sariq matbuot (mayda-chuyda xabarlar gazetasi)"],
      ["broadsheet", "/broadsheet*/", "kattajon shakldagi jiddiy gazeta"],
      ["reporter", "/rɪˈpɔrtər/", "muxbir"],
      ["interview", "/ˈɪntərvˌju/", "intervyu, suhbat"],
      ["issue", "/ˈɪʃu/", "nashr, son (gazeta haqida)"],
    ], 'Newspapers', 'Media and entertainment'),
    unit(65, [
      ["novel", "/ˈnɑvəl/", "roman"],
      ["author", "/ˈɔθər/", "muallif, yozuvchi"],
      ["fiction", "/ˈfɪkʃən/", "badiiy adabiyot"],
      ["non-fiction", "/nɑnˈfɪkʃən/", "hujjatli-ilmiy adabiyot"],
      ["biography", "/baɪˈɑgrəfi/", "tarjimai hol"],
      ["chapter", "/ˈʧæptər/", "bob, fasl"],
      ["character", "/ˈkɛrɪktər/", "personaj, qahramon"],
      ["plot", "/plɑt/", "syujet"],
      ["bestseller", "/ˈbɛˈsɛlər/", "eng ko\'p sotilgan kitob"],
      ["library", "/ˈlaɪbrɛˌri/", "kutubxona"],
    ], 'Books', 'Media and entertainment'),
    unit(66, [
      ["competition", "/ˌkɑmpəˈtɪʃən/", "musobaqa"],
      ["match", "/mæʧ/", "o\'yin, matchList"],
      ["championship", "/ˈʧæmpiənˌʃɪp/", "chempionat"],
      ["race", "/reɪs/", "poyga, yugurish musobaqasi"],
      ["score", "/skɔr/", "hisob (o\'yindagi)"],
      ["winner", "/ˈwɪnər/", "g\'olib"],
      ["loser", "/ˈluzər/", "mag\'lub bo\'lgan"],
      ["gold medal", "/goʊld ˈmɛdəl/", "oltin medal"],
      ["world record", "/wərld ˈrɛkərd/", "jahon rekordi"],
      ["host", "/hoʊst/", "mezbon (mamlakat/shahar)"],
    ], 'Sporting events', 'Media and entertainment'),
    unit(67, [
      ["athlete", "/ˈæθˌlit/", "atlet, sportchi"],
      ["gymnast", "/ˈʤɪmnəst/", "gimnast"],
      ["cyclist", "/ˈsaɪkəlɪst/", "velosipedchi"],
      ["swimmer", "/sˈwɪmər/", "suzuvchi"],
      ["boxing ring", "/ˈbɑksɪŋ rɪŋ/", "boks ringi"],
      ["running track", "/ˈrənɪŋ træk/", "yugurish yo\'lakchasi"],
      ["football pitch", "/ˈfʊtˌbɔl pɪʧ/", "futbol maydoni"],
      ["tennis court", "/ˈtɛnɪs kɔrt/", "tennis korti"],
      ["golf course", "/gɔlf kɔrs/", "golf maydoni"],
      ["gymnasium", "/ʤɪmˈneɪziəm/", "sport zali"],
    ], 'Sport: people and places', 'Media and entertainment'),
    unit(68, [
      ["celebration", "/ˌsɛləˈbreɪʃən/", "bayram qilish, nishonlash"],
      ["parade", "/pəreɪd/", "tantanali yurish, parad"],
      ["costume", "/ˈkɑstum/", "bayramona libos"],
      ["mask", "/mæsk/", "niqob"],
      ["feast", "/fist/", "ziyofat, to\'kin dasturxon"],
      ["ritual", "/ˈrɪʧuəl/", "marosim, rasm-rusum"],
      ["public holiday", "/ˈpəblɪk ˈhɑlɪˌdeɪ/", "umumxalq dam olish kuni (bayram)"],
      ["commemorate", "/kəˈmɛmərˌeɪt/", "xotirlamoq, yodga olmoq"],
      ["atmosphere", "/ˈætməsˌfɪr/", "bayramona muhit"],
      ["spectacular", "/spɛkˈtækjələr/", "dabdabali, ko\'rkam"],
    ], 'Festivals', 'Media and entertainment'),
    unit(69, [
      ["hardware", "/ˈhɑrdˌwɛr/", "apparat ta\'minoti (kompyuter qismlari)"],
      ["software", "/ˈsɔfˌwɛr/", "dasturiy ta\'minot"],
      ["website", "/ˈwɛbˌsaɪt/", "veb-sayt"],
      ["homepage", "/homepage*/", "asosiy sahifa"],
      ["hyperlink", "/ˈhaɪpərlɪŋk/", "giperhavola"],
      ["download", "/ˈdaʊnˌloʊd/", "yuklab olmoq"],
      ["upload", "/ˈəˌploʊd/", "yuklamoq"],
      ["network", "/ˈnɛtˌwərk/", "tarmoq"],
      ["cybercrime", "/cybercrime*/", "kiberjinoyat"],
      ["secure", "/sɪˈkjʊr/", "xavfsiz, himoyalangan"],
    ], 'The internet', 'Media and entertainment'),
    unit(70, [
      ["social network", "/ˈsoʊʃəl ˈnɛtˌwərk/", "ijtimoiy tarmoq"],
      ["account", "/əˈkaʊnt/", "akkaunt, shaxsiy sahifa"],
      ["post", "/poʊst/", "xabar qoldirmoq"],
      ["share", "/ʃɛr/", "bo\'lishmoq, ulashmoq"],
      ["tag", "/tæg/", "belgilamoq (tag qilmoq)"],
      ["follower", "/ˈfɑloʊər/", "obunachi, kuzatuvchi"],
      ["influencer", "/influencer*/", "bloger, ta\'sir o\'tkazuvchi shaxs"],
      ["viral", "/ˈvaɪrəl/", "ommabop bo\'lib ketgan (video/post)"],
      ["chat room", "/ʧæt rum/", "chat xonasi"],
      ["direct message", "/dɪˈrɛkt ˈmɛsɪʤ/", "shaxsiy xabar (DM)"],
    ], 'Email and social media', 'Media and entertainment'),
    unit(71, [
      ["prefix", "/ˈprifɪks/", "old qo\'shimcha"],
      ["international", "/ˌɪnərˈnæʃənɑl/", "xalqaro"],
      ["supermarket", "/ˈsupərˌmɑrkɪt/", "supermarket"],
      ["submarine", "/ˌsəbmərˈin/", "suv osti kemasi"],
      ["ex-boss", "/ex-boss*/", "sobiq boshliq"],
      ["autopilot", "/ˈɔtoʊˌpaɪlət/", "avtopilot"],
      ["co-worker", "/ˈkoʊˈwərkər/", "hamkasb"],
      ["antisocial", "/ˌæntɪˈsoʊʃəl/", "jamiyatga qarshi, odamovi"],
      ["bilingual", "/baɪˈlɪŋgwəl/", "ikki tilda so\'zlashuvchi"],
      ["polyglot", "/ˌpɑlɪˈglɑt/", "ko\'p tillarni biluvchi"],
    ], 'Word building: prefixes', 'Language focus: word building'),
    unit(72, [
      ["suffix", "/ˈsəfɪks/", "ort qo\'shimcha"],
      ["usefulness", "/ˈjusfəlnəs/", "foydalilik"],
      ["baker", "/ˈbeɪkər/", "novvoy"],
      ["employment", "/ɪmˈplɔɪmənt/", "bandlik, ish bilan ta\'minlash"],
      ["freedom", "/ˈfridəm/", "erkinlik"],
      ["childhood", "/ˈʧaɪlˌdhʊd/", "bolalik"],
      ["dangerous", "/ˈdeɪnʤərəs/", "xavfli"],
      ["active", "/ˈæktɪv/", "faol"],
      ["modernize", "/ˈmɑdərˌnaɪz/", "zamonaviylashtirmoq"],
      ["comfortably", "/ˈkəmfərtəbli/", "qulay tarzda"],
    ], 'Word building: suffixes', 'Language focus: word building'),
    unit(73, [
      ["furthermore", "/ˈfərðərˌmɔr/", "bundan tashqari"],
      ["moreover", "/mɔˈroʊvər/", "qolaversa"],
      ["in addition", "/ɪn əˈdɪʃən/", "bunga qo\'shimcha ravishda"],
      ["consequently", "/ˈkɑnsəkˌwɛntli/", "natijada"],
      ["therefore", "/ˈðɛrˌfɔr/", "shu sababli"],
      ["meanwhile", "/ˈminˌwaɪl/", "shu orada"],
      ["whereas", "/wɛˈræz/", "holbuki, -ga qaraganda"],
      ["otherwise", "/ˈəðərˌwaɪz/", "aks holda"],
      ["instead of", "/ˌɪnˈstɛd əv/", "... o\'rniga"],
      ["in spite of", "/ɪn spaɪt əv/", "...-ga qaramasdan"],
    ], 'Link words', 'Language focus: word building'),
    unit(74, [
      ["primary school", "/ˈpraɪˌmɛri skul/", "boshlang\'ich maktab"],
      ["secondary school", "/ˈsɛkənˌdɛri skul/", "o\'rta maktab"],
      ["term", "/tərm/", "o\'quv choragi, semestr"],
      ["pupil", "/ˈpjupəl/", "o\'quvchi"],
      ["subject", "/ˈsəbʤɪkt/", "fan, o\'quv fani"],
      ["timetable", "/ˈtaɪmˌteɪbəl/", "dars jadvali"],
      ["exam", "/ɪgˈzæm/", "imtihon"],
      ["pass an exam", "/pæs ən ɪgˈzæm/", "imtihondan o\'tmoq"],
      ["fail an exam", "/feɪl ən ɪgˈzæm/", "imtihondan yiqilmoq"],
      ["homework", "/ˈhoʊmˌwərk/", "uy vazifasi"],
    ], 'School', 'Study and work'),
    unit(75, [
      ["university", "/ˌjunəˈvərsəti/", "universitet"],
      ["degree", "/dɪˈgri/", "daraja (oliy ma\'lumot)"],
      ["undergraduate", "/ˌəndərˈgræʤəwət/", "bakalavr talabasi"],
      ["graduate", "/ˈgræʤəˌweɪt/", "oliy o\'quv yurtini bitirgan shaxs"],
      ["professor", "/prəˈfɛsər/", "professor"],
      ["lecture", "/ˈlɛkʧər/", "ma\'ruza"],
      ["seminar", "/ˈsɛməˌnɑr/", "seminar darsi"],
      ["assignment", "/əˈsaɪnmənt/", "vazifa, topshiriq"],
      ["research", "/ˈrisərʧ/", "ilmiy tadqiqot"],
      ["thesis", "/ˈθiˌsɪs/", "diplom ishi, dissertatsiya"],
    ], 'Academic life', 'Study and work'),
    unit(76, [
      ["dormitory", "/ˈdɔrməˌtɔri/", "talabalar yotoqxonasi (dorm)"],
      ["tuition fee", "/tjuˈɪʃən fi/", "o\'qish uchun to\'lov (kontrakt)"],
      ["scholarship", "/ˈskɑlərˌʃɪp/", "stipendiya"],
      ["loan", "/loʊn/", "talabalik krediti, qarz"],
      ["campus", "/ˈkæmpəs/", "universitet shaharchasi (kampus)"],
      ["society", "/soʊˈsaɪɪti/", "talabalar uyushmasi / jamiyat"],
      ["fresher", "/ˈfrɛʃər/", "birinchi kurs talabasi"],
      ["essay", "/ˈɛˌseɪ/", "insho"],
      ["deadline", "/ˈdɛˌdlaɪn/", "oxirgi muddat"],
    ], 'Student life', 'Study and work'),
    unit(77, [
      ["well-paid", "/well-paid*/", "yuqori maoshli"],
      ["badly-paid", "/badly-paid*/", "kam maoshli"],
      ["full-time", "/ˈfʊlˌtaɪm/", "to\'liq stavkali ish"],
      ["part-time", "/ˈpɑrtˈtaɪm/", "yarim stavkali ish"],
      ["stressful", "/ˈstrɛsfəl/", "stressli, asabni buzuvchi"],
      ["rewarding", "/rɪˈwɔrdɪŋ/", "ma\'naviy qoniqish beradigan"],
      ["repetitive", "/rɪˈpɛtɪtɪv/", "bir xil takrorlanadigan"],
      ["varied", "/ˈvɛrid/", "turfa xil, qiziqarli"],
      ["responsibility", "/riˌspɑnsəˈbɪləti/", "mas\'uliyat"],
    ], 'Describing jobs', 'Study and work'),
    unit(78, [
      ["career", "/kərɪr/", "karyera, kasbiy yo\'l"],
      ["promotion", "/pərˈmoʊʃən/", "lavozimni ko\'tarish"],
      ["resign", "/rɪˈzaɪn/", "ishdan bo\'shash haqida ariza yozmoq"],
      ["retire", "/ˌriˈtaɪər/", "nafaqaga chiqmoq"],
      ["sack", "/sæk/", "ishdan haydamoq"],
      ["unemployed", "/ˌənɛmˈplɔɪd/", "ishsiz"],
      ["applicant", "/ˈæplɪkənt/", "nomzod, da\'vogar"],
      ["interview", "/ˈɪntərvˌju/", "suhbat (ishga kirishda)"],
      ["cv", "/cv*/", "rezyume (CV)"],
    ], 'Careers', 'Study and work'),
    unit(79, [
      ["job vacancy", "/ʤɑb ˈveɪkənsi/", "bo\'sh ish o\'rni"],
      ["advertisement", "/ˌædvərˈtaɪzmənt/", "e\'lon"],
      ["application form", "/ˌæpləˈkeɪʃən fɔrm/", "anketa, ariza formasi"],
      ["qualifications", "/kˌwɑləfəˈkeɪʃənz/", "malaka, ma\'lumot sertifikati"],
      ["experience", "/ɪkˈspɪriəns/", "ish tajribasi"],
      ["skills", "/skɪlz/", "ko\'nikmalar, malakalar"],
      ["reference", "/ˈrɛfərəns/", "tavsiyanoma"],
      ["offer", "/ˈɔfər/", "taklif qilmoq (ishni)"],
      ["accept", "/əkˈsɛpt/", "qabul qilmoq"],
    ], 'Applying for a job', 'Study and work'),
    unit(80, [
      ["income", "/ˈɪnˌkəm/", "daromad"],
      ["tax", "/tæks/", "soliq"],
      ["debt", "/dɛt/", "qarz"],
      ["bank account", "/bæŋk əˈkaʊnt/", "bank hisob raqami"],
      ["save money", "/seɪv ˈməni/", "pul yig\'moq, tejamoq"],
      ["spend money", "/spɛnd ˈməni/", "pul sarflamoq"],
      ["invest", "/ˌɪnˈvɛst/", "sarmoya kiritmoq, investitsiya qilmoq"],
      ["inflation", "/ˌɪnˈfleɪʃən/", "infratsiya"],
      ["currency", "/ˈkərənsi/", "valyuta"],
    ], 'Finance', 'Study and work'),
    unit(81, [
      ["entrepreneur", "/ˌɑntrəprəˈnʊr/", "tadbirkor, biznesmen"],
      ["startup", "/ˈstɑrˌtəp/", "startap, yangi tashkil etilgan korxona"],
      ["profit", "/ˈprɑfɪt/", "foyda, daromad"],
      ["loss", "/lɔs/", "zarar, ziyon"],
      ["turnover", "/ˈtərˌnoʊvər/", "tovar aylanmasi"],
      ["bankrupt", "/ˈbæŋkrəpt/", "lutf, bankrot bo\'lgan"],
      ["investor", "/ˌɪnˈvɛstər/", "investor, sarmoyador"],
      ["shareholder", "/ˈʃɛˌrhoʊldər/", "aktsiyador"],
      ["manage", "/ˈmænɪʤ/", "boshqarmoq"],
    ], 'Running a business', 'Study and work'),
    unit(82, [
      ["market research", "/ˈmɑrkɪt ˈrisərʧ/", "bozor tadqiqoti"],
      ["target audience", "/ˈtərgət ˈɔdiəns/", "maqsadli auditoriya"],
      ["brand", "/brænd/", "brend, savdo belgisi"],
      ["logo", "/ˈloʊgoʊ/", "logotip, belgi"],
      ["commercial", "/kəˈmərʃəl/", "tijoriy reklama"],
      ["launch", "/lɔnʧ/", "bozorga chiqarmoq, ishga tushirmoq"],
      ["promote", "/prəˈmoʊt/", "targ\'ib qilmoq, reklama qilmoq"],
      ["consumer", "/kənˈsumər/", "iste\'molchi"],
      ["retailer", "/ˈriˌteɪlər/", "chakana savdogar"],
    ], 'Marketing', 'Study and work'),
    unit(83, [
      ["separable", "/separable*/", "ajraladigan (frazalli fe\'l)"],
      ["inseparable", "/ˌɪnˈsɛpərəbəl/", "ajralmaydigan (frazalli fe\'l)"],
      ["transitive", "/transitive*/", "o\'timli fe\'l"],
      ["intransitive", "/intransitive*/", "o\'timsiz fe\'l"],
      ["look up", "/lʊk əp/", "lug\'atdan qidirib topmoq"],
      ["give up", "/gɪv əp/", "to\'xtatmoq, voz kechmoq"],
      ["look after", "/lʊk ˈæftər/", "g\'amxo\'rlik qilmoq"],
      ["get on with", "/gɪt ɔn wɪθ/", "chiqishmoq, davom ettirmoq"],
    ], 'Phrasal verbs (1): grammatical patterns', 'Language focus: phrasal verbs and idioms'),
    unit(84, [
      ["break down", "/breɪk daʊn/", "buzilib qolmoq (texnika)"],
      ["carry on", "/ˈkɛri ɔn/", "davom ettirmoq"],
      ["find out", "/faɪnd aʊt/", "aniqlamoq, bilib olmoq"],
      ["give in", "/gɪv ɪn/", "taslim bo\'lmoq"],
      ["hold up", "/hoʊld əp/", "kechiktirmoq, ushlab turmoq"],
      ["log on", "/lɔg ɔn/", "tizimga kirmoq"],
      ["pick up", "/pɪk əp/", "olib ketmoq, mashinaga chiqarmoq"],
      ["put off", "/pʊt ɔf/", "boshqa vaqtga surmoq"],
    ], 'Phrasal verbs (2): meaning', 'Language focus: phrasal verbs and idioms'),
    unit(85, [
      ["make up your mind", "/meɪk əp jʊr maɪnd/", "qaror qabul qilmoq"],
      ["change your mind", "/ʧeɪnʤ jʊr maɪnd/", "fikrini o\'zgartirmoq"],
      ["keep in mind", "/kip ɪn maɪnd/", "esda tutmoq"],
      ["never mind", "/ˈnɛvər maɪnd/", "hechqisi yo\'q, ahamiyatsiz"],
      ["on time", "/ɔn taɪm/", "o\'z vaqtida"],
      ["in time", "/ɪn taɪm/", "vaqtida ulgurib"],
      ["at times", "/æt taɪmz/", "ba\'zida"],
    ], 'Expressions (1)', 'Language focus: phrasal verbs and idioms'),
    unit(86, [
      ["take a break", "/teɪk ə breɪk/", "tanaffus qilmoq"],
      ["take a chance", "/teɪk ə ʧæns/", "tavakkal qilmoq"],
      ["take notice", "/teɪk ˈnoʊtɪs/", "e\'tibor bermoq"],
      ["make sense", "/meɪk sɛns/", "ma\'noga ega bo\'lmoq, mantiqli bo\'lmoq"],
      ["make friends", "/meɪk frɛndz/", "do\'stlashmoq"],
      ["do your best", "/du jʊr bɛst/", "qo\'ldan kelganicha harakat qilmoq"],
      ["do someone a favour", "/du ˈsəmˌwən ə ˈfeɪvər/", "yordam bermoq"],
    ], 'Expressions (2)', 'Language focus: phrasal verbs and idioms'),
    unit(87, [
      ["prefer", "/prɪˈfər/", "afzal ko\'rmoq"],
      ["keen on", "/kin ɔn/", "qiziqadigan, ishqiboz"],
      ["can\'t stand", "/can\'t* stænd/", "chiday olmaslik, asabi buzilish"],
      ["dislike", "/dɪsˈlaɪk/", "yoqtirmaslik"],
      ["rather", "/ˈrəðər/", "ko\'ra, afzalroq"],
      ["fond of", "/fɑnd əv/", "yaxshi ko\'radigan"],
      ["appeal to", "/əˈpil tɪ/", "yoqmoq, jalb qilmoq"],
    ], 'Likes, dislikes and preferences', 'Language focus: social English'),
    unit(88, [
      ["likely", "/ˈlaɪkli/", "ehtimoli bor, bo\'lishi mumkin"],
      ["unlikely", "/ənˈlaɪkli/", "ehtimoli kam, bo\'lmasa kerak"],
      ["certain", "/ˈsərtən/", "aniq, shubhasiz"],
      ["definitely", "/ˈdɛfənətli/", "aniq, shubhasiz"],
      ["probably", "/ˈprɑbəˌbli/", "katta ehtimol bilan"],
      ["perhaps", "/pərˈhæps/", "ehtimol, balki"],
      ["doubt", "/daʊt/", "shubha qilmoq"],
    ], 'Probability', 'Language focus: social English'),
    unit(89, [
      ["similar to", "/ˈsɪmələr tɪ/", "...-ga o\'xshash"],
      ["differently", "/ˈdɪfərˈɛntli/", "boshqacha tarzda"],
      ["difference", "/ˈdɪfərəns/", "farq"],
      ["compare", "/kəmˈpɛr/", "taqqoslamoq"],
      ["whereas", "/wɛˈræz/", "hollarda, holbuki"],
      ["unlike", "/ənˈlaɪk/", "...-dan farqli o\'laroq"],
      ["common", "/ˈkɑmən/", "umumiy, o\'xshash"],
    ], 'Similarities and differences', 'Language focus: social English'),
    unit(90, [
      ["pleased", "/plizd/", "mamnun"],
      ["delighted", "/dɪˈlaɪtɪd/", "hursand, xushnud"],
      ["annoyed", "/əˈnɔɪd/", "jahli chiqqan, g\'ashiga tekkan"],
      ["irritated", "/ˈɪrəˌteɪtəd/", "asabiylashgan"],
      ["frustrated", "/ˈfrəˌstreɪtəd/", "hafsalasi pir bo\'lgan"],
      ["disappointed", "/ˌdɪsəˈpɔɪnɪd/", "ko\'ngli qolgan"],
      ["upset", "/ˈəpˌsɛt/", "xafa bo\'lgan"],
    ], 'Pleasure and annoyance', 'Language focus: social English'),
    unit(91, [
      ["arrange", "/əreɪnʤ/", "rejalashtirmoq, kelishib olmoq"],
      ["appointment", "/əˈpɔɪntmənt/", "uchrashuv vaqti (shifokor, idora bilan)"],
      ["postpone", "/poʊstˈpoʊn/", "boshqa vaqtga surmoq"],
      ["cancel", "/ˈkænsəl/", "bekor qilmoq"],
      ["confirm", "/kənˈfərm/", "tasdiqlamoq"],
      ["available", "/əˈveɪləbəl/", "bo\'sh, band bo\'lmagan"],
      ["convenient", "/kənˈvinjənt/", "qulay"],
    ], 'Making arrangements', 'Language focus: social English'),
    unit(92, [
      ["warn", "/wɔrn/", "ogohlantirmoq"],
      ["caution", "/ˈkɔʃən/", "ehtiyotkorlik, ogohlik"],
      ["danger", "/ˈdeɪnʤər/", "xavf"],
      ["mind out", "/maɪnd aʊt/", "ehtiyot bo\'lmoq"],
      ["watch out", "/wɔʧ aʊt/", "qarab turmoq, ehtiyot bo\'lmoq"],
      ["risk", "/rɪsk/", "tavakkal qilmoq, xavf ostiga qo\'ymoq"],
      ["threat", "/θrɛt/", "tahdid"],
    ], 'Warnings', 'Language focus: social English'),
    unit(93, [
      ["opinion", "/əˈpɪnjən/", "fikr, nuqtai nazar"],
      ["view", "/vju/", "qarash, nuqtai nazar"],
      ["believe", "/bɪˈliv/", "ishonmoq"],
      ["agree", "/əˈgri/", "qo\'shilmoq (fikrga)"],
      ["disagree", "/dɪsəˈgri/", "qarshi chiqmoq, qo\'shilmaslik"],
      ["in my view", "/ɪn maɪ vju/", "mening fikrimcha"],
      ["point of view", "/pɔɪnt əv vju/", "nuqtai nazar"],
    ], 'Opinions', 'Language focus: social English'),
    unit(94, [
      ["hope", "/hoʊp/", "umid qilmoq"],
      ["plan", "/plæn/", "rejalashtirmoq"],
      ["expect", "/ɪkˈspɛkt/", "kutmoq"],
      ["intend", "/ˌɪnˈtɛnd/", "niyat qilmoq"],
      ["dream of", "/drim əv/", "orzu qilmoq"],
      ["aim", "/eɪm/", "maqsad qilmoq"],
      ["future", "/fˈjuʧər/", "kelajak"],
    ], 'Hopes and plans', 'Language focus: social English'),
    unit(95, [
      ["must", "/məst/", "kerak, shart (majburiyat)"],
      ["have to", "/hæv tɪ/", "majbur bo\'lmoq"],
      ["should", "/ʃʊd/", "kerak (maslahat)"],
      ["ought to", "/ɔt tɪ/", "kerak, loyiq bo\'lmoq"],
      ["allowed", "/əˈlaʊd/", "ruxsat etilgan"],
      ["forbidden", "/ˈfɔrbɪdən/", "taqiqlangan"],
      ["duty", "/ˈduti/", "burch, majburiyat"],
    ], 'Obligation', 'Language focus: social English'),
    unit(96, [
      ["permission", "/pərˈmɪʃən/", "ruxsat"],
      ["allow", "/əˈlaʊ/", "ruxsat bermoq"],
      ["permit", "/ˈpərˌmɪt/", "ruxsat bermoq (rasmiy)"],
      ["let", "/lɛt/", "ruxsat etmoq"],
      ["mind", "/maɪnd/", "qarshi bo\'lmoq"],
      ["refuse", "/ˈrɛfˌjuz/", "rad etmoq"],
    ], 'Asking for permission', 'Language focus: social English'),
    unit(97, [
      ["formal", "/ˈfɔrməl/", "rasmiy"],
      ["informal", "/ˌɪnˈfɔrməl/", "norasmiy"],
      ["slang", "/slæŋ/", "sleng"],
      ["colloquial", "/kəˈloʊkwiəl/", "so\'zlashuv tiliga xos"],
      ["appropriate", "/əˈproʊpriˌeɪt/", "mos keladigan, o\'rinli"],
      ["greeting", "/ˈgritɪŋ/", "salomlashish"],
    ], 'Formal and informal English', 'Language focus: styles of language'),
    unit(98, [
      ["dear", "/dɪr/", "hurmatli (xat boshida)"],
      ["sincerely", "/sɪnˈsɪrli/", "hurmat bilan (rasmiy xat oxirida)"],
      ["best wishes", "/bɛst ˈwɪʃɪz/", "eng yaxshi tilaklar bilan"],
      ["regards", "/rɪˈgɑrdz/", "salomlar bilan"],
      ["enquiry", "/ɪnkˈwaɪˌri/", "so\'rov, ma\'lumot olish uchun xat"],
      ["attachment", "/əˈtæʧmənt/", "ilova qilingan fayl"],
    ], 'Write a letter or email', 'Language focus: styles of language'),
    unit(99, [
      ["abbreviation", "/əˌbriviˈeɪʃən/", "qisqartma so\'z"],
      ["acronym", "/ˈækrənɪm/", "bosh harflardan tuzilgan qisqartma (NASA kabi)"],
      ["etc.", "/ˌɛtˈsɛtərə./", "va hokazo"],
      ["e.g.", "/e.g*./", "masalan"],
      ["i.e.", "/i.e*./", "ya\'ni"],
    ], 'Abbreviations and short forms', 'Language focus: styles of language'),
    unit(100, [
      ["apartment", "/əˈpɑrtmənt/", "kvartira (BrE: flat)"],
      ["elevator", "/ˈɛləˌveɪtər/", "lift (BrE: lift)"],
      ["fall", "/fɔl/", "kuz (BrE: autumn)"],
      ["gasoline", "/ˈgæsəˌlin/", "benzin (BrE: petrol)"],
      ["line", "/laɪn/", "navbat (BrE: queue)"],
      ["pants", "/pænts/", "shim (BrE: trousers)"],
      ["sidewalk", "/ˈsaɪdˌwɔk/", "trotuar (BrE: pavement)"],
      ["sneakers", "/sˈnikərz/", "krossovka (BrE: trainers)"],
    ], 'American English', 'Language focus: styles of language'),
  ],
};
