import { Book, createUnit as unit } from "../book-types";

export const oxfordBasic: Book = {
  id: "ows_basic",
  title: "Oxford Word Skills Basic",
  subtitle: "Basic",
  totalUnits: 80,
  units: [
    unit(1, [
      ["one", "/wən/", "bir"],
      ["two", "/tu/", "ikki"],
      ["three", "/θri/", "uch"],
      ["four", "/fɔr/", "to\'rt"],
      ["five", "/faɪv/", "besh"],
      ["six", "/sɪks/", "olti"],
      ["seven", "/ˈsɛvən/", "yetti"],
      ["eight", "/eɪt/", "sakkiz"],
      ["nine", "/naɪn/", "to\'qqiz"],
      ["ten", "/tɛn/", "o\'n"],
      ["eleven", "/ˈilɛvən/", "o\'n bir"],
      ["twelve", "/twɛlv/", "o\'n ikki"],
      ["thirteen", "/ˈθərˈtin/", "o\'n uch"],
      ["fourteen", "/ˌfɔrˈtin/", "o\'n to\'rt"],
      ["fifteen", "/ˈfɪfˈtin/", "o\'n besh"],
      ["sixteen", "/ˈsɪkˈstin/", "o\'n olti"],
      ["seventeen", "/ˈsɛvənˈtin/", "o\'n yetti"],
      ["eighteen", "/ˈeɪˈtin/", "o\'n sakkiz"],
      ["nineteen", "/ˈnaɪnˈtin/", "o\'n to\'qqiz"],
      ["twenty", "/tˈwɛnti/", "yigirma"],
      ["thirty", "/ˈθərˌdi/", "o\'ttiz"],
      ["forty", "/ˈfɔrti/", "qirq"],
      ["fifty", "/ˈfɪfti/", "ellik"],
      ["sixty", "/ˈsɪksti/", "oltmish"],
      ["seventy", "/ˈsɛvənti/", "yetmish"],
      ["eighty", "/ˈeɪti/", "sakson"],
      ["ninety", "/ˈnaɪnti/", "to\'qson"],
      ["hundred", "/ˈhənərd/", "yuz"],
      ["thousand", "/ˈθaʊzənd/", "ming"],
      ["million", "/ˈmɪljən/", "million"],
      ["about", "/əˈbaʊt/", "taxminan, ... atrofida"],
    ], 'I can understand and say numbers', 'Basic English'),
    unit(2, [
      ["time", "/taɪm/", "vaqt"],
      ["o\'clock", "/o\'clock*/", "soat (aniq vaqtda)"],
      ["past", "/pæst/", "dan o\'tdi"],
      ["to", "/tɪ/", "qoldi (soatga)"],
      ["quarter", "/kˈwɔrtər/", "chorak (15 daqiqa)"],
      ["half", "/hæf/", "yarim (30 daqiqa)"],
      ["morning", "/ˈmɔrnɪŋ/", "ertalab"],
      ["afternoon", "/ˌæftərˈnun/", "tushdan keyin"],
      ["evening", "/ˈivnɪŋ/", "kechqurun"],
      ["night", "/naɪt/", "tun"],
      ["midday", "/ˈmɪdˌdeɪ/", "tush payti (soat 12:00)"],
      ["midnight", "/ˈmɪdˌnaɪt/", "yarim tunda (soat 12:00)"],
      ["nearly", "/ˈnɪrli/", "deyarli"],
      ["almost", "/ˈɔlˌmoʊst/", "deyarli"],
      ["just after", "/ʤɪst ˈæftər/", "ozgina o\'tib"],
    ], 'I can tell the time', 'Basic English'),
    unit(3, [
      ["Monday", "/ˈmənˌdeɪ/", "Dushanba"],
      ["Tuesday", "/ˈtuzˌdeɪ/", "Seshanba"],
      ["Wednesday", "/ˈwɛnzˌdeɪ/", "Chorshanba"],
      ["Thursday", "/ˈθərzˌdeɪ/", "Payshanba"],
      ["Friday", "/ˈfraɪˌdeɪ/", "Juma"],
      ["Saturday", "/ˈsæˌtɪˌdeɪ/", "Shanba"],
      ["Sunday", "/ˈsənˌdi/", "Yakshanba"],
      ["January", "/ˈʤænjuˌɛri/", "Yanvar"],
      ["February", "/ˈfɛbruˌɛri/", "Fevral"],
      ["March", "/mɑrʧ/", "Mart"],
      ["April", "/ˈeɪprəl/", "Aprel"],
      ["May", "/meɪ/", "May"],
      ["June", "/ʤun/", "Iyun"],
      ["July", "/ˌʤuˈlaɪ/", "Iyul"],
      ["August", "/ˈɔgəst/", "Avgust"],
      ["September", "/sɛpˈtɛmbər/", "Sentabr"],
      ["October", "/ɑkˈtoʊbər/", "Oktabr"],
      ["November", "/noʊˈvɛmbər/", "Noyabr"],
      ["December", "/dɪˈsɛmbər/", "Dekabr"],
      ["spring", "/spərɪŋ/", "bahor"],
      ["summer", "/ˈsəmər/", "yoz"],
      ["autumn", "/ˈɔtəm/", "kuz"],
      ["winter", "/ˈwɪntər/", "qish"],
      ["birthday", "/ˈbərθˌdeɪ/", "tug\'ilgan kun"],
    ], 'I can say days and dates', 'Basic English'),
    unit(4, [
      ["country", "/ˈkəntri/", "davlat, mamlakat"],
      ["nationality", "/ˌnæʃəˈnælɪti/", "millat"],
      ["language", "/ˈlæŋgwɪʤ/", "til"],
      ["France", "/fræns/", "Fransiya"],
      ["French", "/frɛnʧ/", "fransuz, fransuz tili"],
      ["Germany", "/ˈʤərməni/", "Germaniya"],
      ["German", "/ˈʤərmən/", "nemis, nemis tili"],
      ["Italy", "/ˈɪtəli/", "Italiya"],
      ["Italian", "/ˌɪˈtæljən/", "italyan, italyan tili"],
      ["Spain", "/speɪn/", "Ispaniya"],
      ["Spanish", "/ˈspænɪʃ/", "ispan, ispan tili"],
      ["Japan", "/ʤəˈpæn/", "Yaponiya"],
      ["Japanese", "/ˌʤæpəˈniz/", "yapon, yapon tili"],
      ["China", "/ˈʧaɪnə/", "Xitoy"],
      ["Chinese", "/ʧaɪˈniz/", "xitoy, xitoy tili"],
      ["Russia", "/ˈrəʃə/", "Rossiya"],
      ["Russian", "/ˈrəʃən/", "rus, rus tili"],
    ], 'I can say countries and nationalities', 'Basic English'),
    unit(5, [
      ["board", "/bɔrd/", "doska"],
      ["board pen", "/bɔrd pɛn/", "doska uchun marker"],
      ["noticeboard", "/noticeboard*/", "e\'lonlar taxtasi"],
      ["bag", "/bæg/", "sumka"],
      ["desk", "/dɛsk/", "parta, yozuv stoli"],
      ["CD player", "/ˈsiˈdi pleɪər/", "CD pleyer"],
      ["pen", "/pɛn/", "ruchka"],
      ["pencil sharpener", "/ˈpɛnsəl sharpener*/", "qalamtarosh"],
      ["ruler", "/ˈrulər/", "chizg\'ich"],
      ["pencil", "/ˈpɛnsəl/", "qalam"],
      ["folder", "/ˈfoʊldər/", "papka"],
      ["piece of paper", "/pis əv ˈpeɪpər/", "bir parcha qog\'oz"],
      ["rubber", "/ˈrəbər/", "o\'chirg\'ich"],
      ["notebook", "/ˈnoʊtˌbʊk/", "daftar"],
      ["dictionary", "/ˈdɪkʃəˌnɛri/", "lug\'at"],
      ["table", "/ˈteɪbəl/", "stol"],
      ["chair", "/ʧɛr/", "stul"],
    ], 'I can use classroom vocabulary', 'Basic English'),
    unit(6, [
      ["sentence", "/ˈsɛntəns/", "gap"],
      ["noun", "/naʊn/", "ot"],
      ["adjective", "/ˈæʤɪktɪv/", "sifat"],
      ["verb", "/vərb/", "fe\'l"],
      ["adverb", "/ˈædvərb/", "ravish"],
      ["preposition", "/preposition*/", "predlog"],
      ["article", "/ˈɑrtɪkəl/", "artikl"],
      ["pronoun", "/ˈproʊnaʊn/", "olmosh"],
      ["singular", "/ˈsɪŋgjələr/", "birlik (son)"],
      ["plural", "/ˈplʊrəl/", "ko\'plik (son)"],
      ["regular verb", "/ˈrɛgjələr vərb/", "to\'g\'ri fe\'l"],
      ["irregular verb", "/ˌɪˈrɛgjələr vərb/", "noto\'g\'ri fe\'l"],
    ], 'I can use English language words', 'Basic English'),
    unit(7, [
      ["mean", "/min/", "anglatmoq, ma\'noni anglatmoq"],
      ["remember", "/rɪˈmɛmbər/", "esda saqlamoq, eslamoq"],
      ["spell", "/spɛl/", "harflab yozmoq"],
      ["pronounce", "/prəˈnaʊns/", "talaffuz qilmoq"],
      ["right", "/raɪt/", "to\'g\'ri"],
      ["wrong", "/rɔŋ/", "noto\'g\'ri, xato"],
      ["opposite", "/ˈɑpəzɪt/", "qarama-qarshi ma\'noli"],
      ["difference", "/ˈdɪfərəns/", "farq"],
    ], 'I can ask and answer questions about language', 'Basic English'),
    unit(8, [
      ["family name", "/ˈfæməli neɪm/", "familiya"],
      ["first name", "/fərst neɪm/", "ism"],
      ["address", "/ˈæˌdrɛs/", "manzil"],
      ["postcode", "/postcode*/", "pochta indeksi"],
      ["job", "/ʤɑb/", "ish, kasb"],
      ["married", "/ˈmɛrid/", "uylangan / turmush qurgan"],
      ["single", "/ˈsɪŋgəl/", "bo\'ydoq / turmush qurmagan"],
      ["children", "/ˈʧɪldrən/", "bolalar"],
      ["boy", "/bɔɪ/", "o\'g\'il bola"],
      ["girl", "/gərl/", "qiz bola"],
    ], 'I can give personal information', 'People'),
    unit(9, [
      ["form", "/fɔrm/", "anketa, ariza formasi"],
      ["surname", "/ˈsərˌneɪm/", "familiya"],
      ["forename", "/forename*/", "ism"],
      ["date of birth", "/deɪt əv bərθ/", "tug\'ilgan sana"],
      ["mother tongue", "/ˈməðər təŋ/", "ona tili"],
      ["marital status", "/ˈmærətəl ˈstætəs/", "oilaviy ahvoli"],
      ["occupation", "/ˌɑkjəˈpeɪʃən/", "kasb, mashg\'ulot"],
      ["signature", "/ˈsɪgnəʧər/", "imzo"],
      ["phone number", "/foʊn ˈnəmbər/", "telefon raqami"],
      ["email address", "/iˈmeɪl ˈæˌdrɛs/", "elektron pochta manzili"],
    ], 'I can fill in a form', 'People'),
    unit(10, [
      ["family", "/ˈfæməli/", "oila"],
      ["mother", "/ˈməðər/", "ona"],
      ["father", "/ˈfɑðər/", "ota"],
      ["parents", "/ˈpɛrənts/", "ota-ona"],
      ["brother", "/ˈbrəðər/", "aka, uka"],
      ["sister", "/ˈsɪstər/", "opa, singil"],
      ["wife", "/waɪf/", "xotin, rafiqa"],
      ["husband", "/ˈhəzbənd/", "er"],
      ["grandmother", "/ˈgrændˌməðər/", "buvi"],
      ["grandfather", "/ˈgrænˌfɑðər/", "bobo"],
      ["son", "/sən/", "o\'g\'il farzand"],
      ["daughter", "/ˈdɔtər/", "qiz farzand"],
      ["uncle", "/ˈəŋkəl/", "amaki, tog\'a"],
      ["aunt", "/ɔnt/", "xola, ammacha"],
      ["cousin", "/ˈkəzən/", "amakivachcha, xolavachcha"],
    ], 'I can talk about my family', 'People'),
    unit(11, [
      ["jump", "/ʤəmp/", "sakramoq"],
      ["dance", "/dæns/", "raqsetmoq"],
      ["climb", "/klaɪm/", "tirmashib chiqmoq"],
      ["sit down", "/sɪt daʊn/", "o\'tirmoq"],
      ["stand up", "/stænd əp/", "o\'rindan turmoq"],
      ["lie down", "/laɪ daʊn/", "cho\'zilib yotmoq"],
      ["fall over", "/fɔl ˈoʊvər/", "yiqilib tushmoq"],
      ["run", "/rən/", "yugurmoq"],
      ["walk", "/wɔk/", "piyoda yurmoq"],
      ["push", "/pʊʃ/", "itarmoq"],
      ["pull", "/pʊl/", "tortmoq"],
      ["carry", "/ˈkɛri/", "ko\'tarib yurmoq, tashimoq"],
      ["touch", "/təʧ/", "ushlab ko\'rmoq, tegmoq"],
      ["hold", "/hoʊld/", "ushlab turmoq"],
    ], 'I can describe physical actions', 'People'),
    unit(12, [
      ["head", "/hɛd/", "bosh"],
      ["face", "/feɪs/", "yuz"],
      ["hair", "/hɛr/", "soch"],
      ["eye", "/aɪ/", "ko\'z"],
      ["ear", "/ɪr/", "quloq"],
      ["nose", "/noʊz/", "burun"],
      ["mouth", "/maʊθ/", "og\'iz"],
      ["neck", "/nɛk/", "bo\'yin"],
      ["shoulder", "/ˈʃoʊldər/", "elka"],
      ["arm", "/ɑrm/", "qo\'l"],
      ["hand", "/hænd/", "kaft, qo\'l"],
      ["finger", "/ˈfɪŋgər/", "barmoq (qo\'l)"],
      ["chest", "/ʧɛst/", "ko\'krak"],
      ["stomach", "/ˈstəmək/", "qorin"],
      ["back", "/bæk/", "orqa, bel"],
      ["leg", "/lɛg/", "oyoq"],
      ["knee", "/ni/", "tizza"],
      ["foot", "/fʊt/", "oyoq kafti"],
      ["toe", "/toʊ/", "oyoq barmog\'i"],
    ], 'I can name parts of the body', 'People'),
    unit(13, [
      ["tall", "/tɔl/", "bo\'yi baland, uzun bo\'yli"],
      ["short", "/ʃɔrt/", "past bo\'yli, kalta"],
      ["slim", "/slɪm/", "ozg\'in, kelishgan"],
      ["overweight", "/ˌoʊvərˈweɪt/", "vazni ortiqcha, to\'lacha"],
      ["good-looking", "/ˈgʊˌdlʊkɪŋ/", "kelishgan, chiroyli"],
      ["attractive", "/əˈtræktɪv/", "jozidali, yoqimli"],
      ["blonde", "/blɑnd/", "sariq sochli"],
      ["dark hair", "/dɑrk hɛr/", "to\'q rangli soch"],
      ["beard", "/bɪrd/", "soqol"],
      ["moustache", "/ˈməˌstæʃ/", "mo\'ylov"],
      ["baby", "/ˈbeɪbi/", "go\'dak, chaqaloq"],
      ["teenager", "/ˈtiˌneɪʤər/", "o\'smir"],
      ["adult", "/ˈædəlt/", "katta yoshdagi kishi"],
      ["middle-aged", "/ˈmɪdəˌleɪgd/", "o\'rta yoshli"],
      ["elderly", "/ˈɛldərli/", "keksa, yoshi ulug\'"],
    ], 'I can describe people', 'People'),
    unit(14, [
      ["friendly", "/ˈfrɛndli/", "do\'stona, ochiqko\'ngil"],
      ["unfriendly", "/ənˈfrɛndli/", "do\'stona bo\'lmagan, sovuq"],
      ["kind", "/kaɪnd/", "mehribon"],
      ["nice", "/nis/", "yoqimli, yaxshi"],
      ["funny", "/ˈfəni/", "quvnoq, kulgili"],
      ["clever", "/ˈklɛvər/", "aqlli"],
      ["quiet", "/kwaɪət/", "tinch, kamgap"],
      ["serious", "/ˈsɪriəs/", "jiddiy"],
      ["shy", "/ʃaɪ/", "uyatchan, tortinchoq"],
      ["sociable", "/ˈsoʊʃəbəl/", "kirishuvchan"],
      ["sporty", "/ˈspɔrti/", "sportsevar"],
      ["tidy", "/ˈtaɪdi/", "tartibli, ozoda"],
      ["lazy", "/ˈleɪzi/", "dangasa"],
      ["hardworking", "/ˈhɑrdˌwərkɪŋ/", "mehnatsevar"],
    ], 'I can talk about character', 'People'),
    unit(15, [
      ["partner", "/ˈpɑrtnər/", "juft, sherik"],
      ["boyfriend", "/ˈbɔɪˌfrɛnd/", "yigit (sevishgan)"],
      ["girlfriend", "/ˈgərlˌfrɛnd/", "qiz (sevishgan)"],
      ["get married", "/gɪt ˈmɛrid/", "turmush qurmoq"],
      ["divorced", "/dɪˈvɔrst/", "ajrashgan"],
      ["split up", "/splɪt əp/", "ajralib ketmoq (munosabatni tugatmoq)"],
      ["flatmate", "/flatmate*/", "kvartiradosh"],
      ["friend", "/frɛnd/", "do\'st"],
      ["best friend", "/bɛst frɛnd/", "eng yaqin do\'st"],
      ["advice", "/ədˈvaɪs/", "maslahat"],
    ], 'I can describe relationships', 'People'),
    unit(16, [
      ["tired", "/taɪərd/", "charchagan"],
      ["hungry", "/ˈhəŋgri/", "ochqqan"],
      ["thirsty", "/ˈθərsti/", "chanqagan"],
      ["boiling", "/ˈbɔɪlɪŋ/", "juda issiq"],
      ["freezing", "/ˈfrizɪŋ/", "muzlab qolayotgan (juda sovuq)"],
      ["nervous", "/ˈnərvəs/", "hayajonlangan, asabiylashgan"],
      ["ill", "/ɪl/", "kasal"],
      ["happy", "/ˈhæpi/", "baxtli, xursand"],
      ["sad", "/sæd/", "xafa, g\'amgin"],
      ["angry", "/ˈæŋgri/", "jahli chiqqan"],
      ["frightened", "/ˈfraɪtənd/", "qo\'rqqan"],
      ["surprised", "/səˈpraɪzd/", "hayratda qolgan"],
      ["in love", "/ɪn ləv/", "sevib qolgan"],
    ], 'I can say how I feel', 'People'),
    unit(17, [
      ["get up", "/gɪt əp/", "o\'rindan turmoq"],
      ["have a shower", "/hæv ə ʃaʊər/", "dush qabul qilmoq"],
      ["get dressed", "/gɪt drɛst/", "kiyinmoq"],
      ["have breakfast", "/hæv ˈbrɛkfəst/", "nonushta qilmoq"],
      ["leave home", "/liv hoʊm/", "uydan chiqib ketmoq"],
      ["get to work", "/gɪt tɪ wərk/", "ishga yetib bormoq"],
      ["finish work", "/ˈfɪnɪʃ wərk/", "ishni tugatmoq"],
      ["have dinner", "/hæv ˈdɪnər/", "kechki ovqatlanmoq"],
      ["go to bed", "/goʊ tɪ bɛd/", "uxlagani yotmoq"],
      ["stay in", "/steɪ ɪn/", "uyda qolmoq"],
      ["go out", "/goʊ aʊt/", "ko\'chaga chiqmoq, aylanib kelmoq"],
      ["go shopping", "/goʊ ˈʃɑpɪŋ/", "xaridga bormoq"],
      ["always", "/ˈɔlˌweɪz/", "har doim"],
      ["often", "/ˈɔfən/", "tez-tez"],
      ["sometimes", "/ˈsəmˌtaɪmz/", "ba\'zida"],
      ["never", "/ˈnɛvər/", "hech qachon"],
    ], 'I can describe my routine', 'Everyday life'),
    unit(18, [
      ["shirt", "/ʃərt/", "ko\'ylak (erkaklar uchun)"],
      ["jumper", "/ˈʤəmpər/", "jemper, sviter"],
      ["trousers", "/ˈtraʊzərz/", "shim"],
      ["jeans", "/ʤinz/", "jinsi shim"],
      ["skirt", "/skərt/", "yubka"],
      ["dress", "/drɛs/", "ko\'ylak (ayollar uchun)"],
      ["jacket", "/ˈʤækɪt/", "kurtka, jaket"],
      ["suit", "/sut/", "kostyum-shim"],
      ["coat", "/koʊt/", "paltolar, ustki kiyim"],
      ["shoes", "/ʃuz/", "tufli, poyabzal"],
      ["boots", "/buts/", "etik"],
      ["hat", "/hæt/", "bosh kiyim, do\'ppi, shlyapa"],
      ["scarf", "/skɑrf/", "sharf"],
      ["gloves", "/gləvz/", "qo\'lqop"],
    ], 'I can talk about clothes', 'Everyday life'),
    unit(19, [
      ["cheap", "/ʧip/", "arzon"],
      ["expensive", "/ɪkˈspɛnsɪv/", "qimmat"],
      ["smart", "/smɑrt/", "dabdabali, bichimli, toza kiyingan"],
      ["casual", "/ˈkæʒəwəl/", "oddiy, kundalik kiyim"],
      ["tight", "/taɪt/", "tor, yopishgan"],
      ["loose", "/lus/", "keng, osilib turadigan"],
      ["size", "/saɪz/", "o\'lcham"],
      ["fit", "/fɪt/", "o\'lchami mos kelmoq"],
      ["shop assistant", "/ʃɑp əˈsɪstənt/", "sotuvchi"],
      ["customer", "/ˈkəstəmər/", "xaridor"],
      ["changing room", "/ˈʧeɪnʤɪŋ rum/", "kiyinish xonasi"],
      ["pay", "/peɪ/", "pul to\'lamoq"],
    ], 'I can buy clothes', 'Everyday life'),
    unit(20, [
      ["cash", "/kæʃ/", "naqd pul"],
      ["notes", "/noʊts/", "qog\'oz pul, kupyura"],
      ["coins", "/kɔɪnz/", "tangalar"],
      ["credit card", "/ˈkrɛdɪt kɑrd/", "kredit karta"],
      ["debit card", "/ˈdɛbɪt kɑrd/", "debet karta"],
      ["receipt", "/rɪˈsit/", "chek (kassadan)"],
      ["price", "/praɪs/", "narx"],
      ["spend", "/spɛnd/", "pul sarflamoq"],
      ["save", "/seɪv/", "pul tejamoq"],
      ["earn", "/ərn/", "pul topmoq, ish haqi olmoq"],
      ["win", "/wɪn/", "yutib olmoq (pulni)"],
      ["bill", "/bɪl/", "to\'lov qog\'ozi, schyot"],
    ], 'I can talk about money', 'Everyday life'),
    unit(21, [
      ["sunny", "/ˈsəni/", "quyoshli"],
      ["cloudy", "/ˈklaʊdi/", "bulutli"],
      ["wet", "/wɛt/", "nam, yomg\'irli"],
      ["windy", "/ˈwɪndi/", "shamolli"],
      ["icy", "/ˈaɪsi/", "muzlagan, muzli"],
      ["foggy", "/ˈfɑgi/", "tumanli"],
      ["sun", "/sən/", "quyosh"],
      ["snow", "/snoʊ/", "qor"],
      ["cloud", "/klaʊd/", "bulut"],
      ["rain", "/reɪn/", "yomg\'ir"],
      ["wind", "/wɪnd/", "shamol"],
      ["ice", "/aɪs/", "muz"],
      ["fog", "/fɔg/", "tuman"],
      ["storm", "/stɔrm/", "bo\'ron"],
      ["lightning", "/ˈlaɪtnɪŋ/", "chaqmoq"],
      ["thunder", "/ˈθəndər/", "momaqaldiroq"],
    ], 'I can talk about the weather', 'Everyday life'),
    unit(22, [
      ["headache", "/ˈhɛˌdeɪk/", "bosh og\'rig\'i"],
      ["toothache", "/toothache*/", "tish og\'rig\'i"],
      ["stomach-ache", "/stomach-ache*/", "qorin og\'rig\'i"],
      ["backache", "/ˈbæˌkeɪk/", "bel og\'rig\'i"],
      ["cold", "/koʊld/", "shamollash, zukkom"],
      ["cough", "/kɔf/", "yo\'tal"],
      ["sore throat", "/sɔr θroʊt/", "tomoq og\'rig\'i"],
      ["flu", "/flu/", "gripp"],
      ["temperature", "/ˈtɛmpərəʧər/", "harorat (isitma)"],
      ["pain", "/peɪn/", "og\'riq"],
      ["hurt", "/hərt/", "og\'rimoq"],
      ["ill", "/ɪl/", "kasal"],
      ["sick", "/sɪk/", "ko\'ngil aynigan, qusmoqchi bo\'lgan"],
    ], 'I can talk about illness', 'Everyday life'),
    unit(23, [
      ["chemist\'s", "/chemist\'s*/", "dorixona"],
      ["antiseptic cream", "/ˌæntəˈsɛptɪk krim/", "antiseptik krem"],
      ["plasters", "/ˈplæstərz/", "leykopoplastir"],
      ["cotton wool", "/ˈkɔtən wʊl/", "paxta"],
      ["tablets", "/ˈtæbləts/", "dori tabletkalari"],
      ["medicine", "/ˈmɛdəsən/", "dori, sharbat dori"],
      ["tissues", "/ˈtɪʃuz/", "qog\'oz salfetka"],
      ["cough medicine", "/kɔf ˈmɛdəsən/", "yo\'tal siropi"],
    ], 'I can get help at the chemist\'s', 'Everyday life'),
    unit(24, [
      ["meat", "/mit/", "go\'sht"],
      ["beef", "/bif/", "mol go\'shti"],
      ["lamb", "/læm/", "qo\'y go\'shti"],
      ["pork", "/pɔrk/", "cho\'chqa go\'shti"],
      ["bacon", "/ˈbeɪkən/", "bekon (duxovka qilingan cho\'chqa go\'shti)"],
      ["sausages", "/ˈsɔsɪʤɪz/", "sosiska, sirkol"],
      ["chicken", "/ˈʧɪkən/", "tovuq go\'shti"],
      ["duck", "/dək/", "o\'rdak go\'shti"],
      ["fish", "/fɪʃ/", "baliq"],
      ["seafood", "/ˈsiˌfud/", "dengiz mahsulotlari"],
      ["salmon", "/ˈsæmən/", "qizil baliq (losin)"],
      ["tuna", "/ˈtunə/", "tunets baliqi"],
      ["prawns", "/prɔnz/", "krevetkalar"],
      ["crab", "/kræb/", "qisqichbaqa (krab)"],
      ["mussels", "/ˈməsəlz/", "midiyalar"],
      ["squid", "/skwɪd/", "kalmar"],
    ], 'I can name meat and fish', 'Food and drink'),
    unit(25, [
      ["banana", "/bəˈnænə/", "banan"],
      ["orange", "/ˈɔrɪnʤ/", "apelsin"],
      ["peach", "/piʧ/", "shaftoli"],
      ["apple", "/ˈæpəl/", "olma"],
      ["pear", "/pɛr/", "nok"],
      ["lemon", "/ˈlɛmən/", "limon"],
      ["mango", "/ˈmæŋgoʊ/", "mango"],
      ["pineapple", "/ˈpaɪˌnæpəl/", "ananas"],
      ["avocado", "/ˌævəˈkɑdoʊ/", "avakado"],
      ["strawberry", "/ˈstrɔˌbɛri/", "qulupnay"],
      ["cherry", "/ˈʧɛri/", "olcha, gilos"],
      ["melon", "/ˈmɛlən/", "qovun"],
      ["grapes", "/greɪps/", "uzum"],
      ["potato", "/pəˈteɪˌtoʊ/", "kartoshka"],
      ["onion", "/ˈənjən/", "piyoz"],
      ["carrot", "/ˈkɛrət/", "sabzi"],
      ["peas", "/piz/", "no\'xat"],
      ["beans", "/binz/", "loviya"],
      ["cabbage", "/ˈkæbɪʤ/", "karam"],
      ["tomato", "/təˈmɑˌtoʊ/", "pomidor"],
      ["cucumber", "/ˈkjukəmbər/", "bodring"],
      ["garlic", "/ˈgɑrlɪk/", "sarimsoq"],
    ], 'I can name fruit and vegetables', 'Food and drink'),
    unit(26, [
      ["milk", "/mɪlk/", "sut"],
      ["bread", "/brɛd/", "non"],
      ["butter", "/ˈbətər/", "sariyog\'"],
      ["cheese", "/ʧiz/", "pishloq"],
      ["eggs", "/ɛgz/", "tuxumlar"],
      ["sugar", "/ˈʃʊgər/", "shakar"],
      ["jam", "/ʤæm/", "murabbo"],
      ["biscuits", "/ˈbɪskəts/", "pechene"],
      ["olive oil", "/ˈɑlɪv ɔɪl/", "zaytun moyi"],
      ["rice", "/raɪs/", "guruch"],
      ["pasta", "/ˈpɑstə/", "makaron"],
      ["chocolate", "/ˈʧɔklət/", "shokolad"],
      ["carton", "/ˈkɑrtən/", "quti (qog\'oz qadoq)"],
      ["packet", "/ˈpækɪt/", "paket, pachka"],
      ["jar", "/ʤɑr/", "banka (shisha)"],
      ["tin", "/tɪn/", "konserva bankasi (oziq-ovqat)"],
      ["can", "/kən/", "temir banka (ichimlik)"],
      ["bottle", "/ˈbɑtəl/", "shisha idish, butilka"],
      ["box", "/bɑks/", "quti"],
    ], 'I can buy food in a shop', 'Food and drink'),
    unit(27, [
      ["coffee", "/ˈkɔfi/", "kofe"],
      ["cappuccino", "/ˌkæˌpuˈʧinoʊ/", "kapuchino"],
      ["espresso", "/ˌɛˈsprɛsoʊ/", "espresso"],
      ["tea", "/ti/", "choy"],
      ["hot chocolate", "/hɑt ˈʧɔklət/", "issiq shokolad"],
      ["orange juice", "/ˈɔrɪnʤ ʤus/", "apelsin sharbati"],
      ["baguette", "/ˌbæˈgɛt/", "baget (fransuz noni)"],
      ["sandwich", "/ˈsænwɪʧ/", "sendvich"],
      ["roll", "/roʊl/", "bulochka"],
      ["waiter", "/ˈweɪtər/", "ofitsiant"],
      ["customer", "/ˈkəstəmər/", "xaridor"],
    ], 'I can order in a café', 'Food and drink'),
    unit(28, [
      ["menu", "/ˈmɛnju/", "menyu"],
      ["starter", "/ˈstɑrtər/", "dastlabki taom, zakuska"],
      ["main course", "/meɪn kɔrs/", "asosiy taom"],
      ["dessert", "/dɪˈzərt/", "shirinlik, desert"],
      ["soup", "/sup/", "sho\'rva"],
      ["chips", "/ʧɪps/", "friturda qovurilgan kartoshka"],
      ["salad", "/ˈsæləd/", "salat"],
      ["rare", "/rɛr/", "ozgina pishgan (go\'sht)"],
      ["medium", "/ˈmidiəm/", "o\'rtacha pishgan"],
      ["well done", "/wɛl dən/", "to\'liq pishgan"],
      ["bill", "/bɪl/", "schyot, to\'lov qog\'ozi"],
    ], 'I can order in a restaurant', 'Food and drink'),
    unit(29, [
      ["bus stop", "/bəs stɑp/", "avtobus bekati"],
      ["timetable", "/ˈtaɪmˌteɪbəl/", "jadval, vaqt jadvali"],
      ["route", "/rut/", "yo\'nalish, marshrut"],
      ["station", "/ˈsteɪʃən/", "stansiya, vokzal"],
      ["get on", "/gɪt ɔn/", "chiqmoq (transportga)"],
      ["get off", "/gɪt ɔf/", "tushmoq (transportdan)"],
      ["stop", "/stɑp/", "bekat, to\'xtash"],
    ], 'I can get around on buses', 'Getting around'),
    unit(30, [
      ["train", "/treɪn/", "poyezd"],
      ["platform", "/ˈplætˌfɔrm/", "perron, platforma"],
      ["ticket office", "/ˈtɪkɪt ˈɔfəs/", "chipta kassasi"],
      ["single ticket", "/ˈsɪŋgəl ˈtɪkɪt/", "bir tomonlama chipta"],
      ["return ticket", "/rɪˈtərn ˈtɪkɪt/", "borish-kelish chiptasi"],
      ["journey", "/ˈʤərni/", "sayohat, yo\'l"],
      ["change trains", "/ʧeɪnʤ treɪnz/", "boshqa poyezdga o\'tirmoq"],
      ["direct", "/dɪˈrɛkt/", "to\'g\'ridan-to\'g\'ri"],
    ], 'I can get around on trains', 'Getting around'),
    unit(31, [
      ["turn left", "/tərn lɛft/", "chapga burilmoq"],
      ["turn right", "/tərn raɪt/", "o\'ngga burilmoq"],
      ["go straight on", "/goʊ streɪt ɔn/", "to\'g\'ridan-to\'g\'ri yurmoq"],
      ["corner", "/ˈkɔrnər/", "burchak"],
      ["opposite", "/ˈɑpəzɪt/", "ro\'parada, qarama-qarshi"],
    ], 'I can ask for and give directions', 'Getting around'),
    unit(32, [
      ["traffic lights", "/ˈtræfɪk laɪts/", "svetofor"],
      ["roundabout", "/ˈraʊndəˌbaʊt/", "aylanma yo\'l"],
      ["traffic jam", "/ˈtræfɪk ʤæm/", "tirbandlik (probka)"],
      ["car park", "/kɑr pɑrk/", "avtoturargoh"],
      ["petrol station", "/ˈpɛtroʊl ˈsteɪʃən/", "yoqilg\'i quyish shoxobchasi"],
      ["motorway", "/motorway*/", "katta tezlikdagi yo\'l (magistral)"],
      ["speed limit", "/spid ˈlɪmət/", "tezlik cheklovi"],
      ["accident", "/ˈæksədənt/", "avariya, baxtsiz hodisa"],
    ], 'I can talk about roads and traffic', 'Getting around'),
    unit(33, [
      ["entrance", "/ˈɛntrəns/", "kirish joyi"],
      ["exit", "/ˈɛksət/", "chiqish joyi"],
      ["no smoking", "/noʊ sˈmoʊkɪŋ/", "chekish taqiqlanadi"],
      ["no parking", "/noʊ ˈpɑrkɪŋ/", "mashina qo\'yish taqiqlanadi"],
      ["sale", "/seɪl/", "chegirma, savdo"],
      ["out of order", "/aʊt əv ˈɔrdər/", "ishlamayapti, buzilgan"],
    ], 'I can understand signs and notices', 'Getting around'),
    unit(34, [
      ["capital", "/ˈkæpɪtəl/", "poytaxt"],
      ["border", "/ˈbɔrdər/", "chegara"],
      ["mountain", "/ˈmaʊntən/", "tog\'"],
      ["river", "/ˈrɪvər/", "daryo"],
      ["coast", "/koʊst/", "qirg\'oq, dengiz bo\'yi"],
      ["north", "/nɔrθ/", "shimol"],
      ["south", "/saʊθ/", "janub"],
      ["east", "/ist/", "sharq"],
      ["west", "/wɛst/", "g\'arb"],
    ], 'I can talk about my country', 'Places'),
    unit(35, [
      ["city", "/ˈsɪti/", "katta shahar"],
      ["town", "/taʊn/", "shahar"],
      ["village", "/ˈvɪlɪʤ/", "qishloq"],
      ["castle", "/ˈkæsəl/", "qal\'a, qasr"],
      ["market", "/ˈmɑrkɪt/", "bozor"],
      ["museum", "/mˈjuziəm/", "muzey"],
      ["bridge", "/brɪʤ/", "ko\'prik"],
      ["busy", "/ˈbɪzi/", "gavjum, band"],
      ["quiet", "/kwaɪət/", "tinch"],
      ["safe", "/seɪf/", "xavfsiz"],
    ], 'I can talk about my town', 'Places'),
    unit(36, [
      ["countryside", "/ˈkəntriˌsaɪd/", "qishloq joylari, tabiat"],
      ["field", "/fild/", "dala"],
      ["hill", "/hɪl/", "tepalik"],
      ["wood", "/wʊd/", "o\'rmoncha"],
      ["lake", "/leɪk/", "ko\'l"],
      ["farmer", "/ˈfɑrmər/", "fermer, dehqon"],
      ["fresh", "/frɛʃ/", "taza"],
      ["alone", "/əˈloʊn/", " yolg\'iz"],
    ], 'I can describe the countryside', 'Places'),
    unit(37, [
      ["shopping centre", "/ˈʃɑpɪŋ ˈsɛntər/", "savdo markazi"],
      ["department store", "/dɪˈpɑrtmənt stɔr/", "univermag"],
      ["supermarket", "/ˈsupərˌmɑrkɪt/", "supermarket"],
      ["butcher\'s", "/butcher\'s*/", "qassobxona"],
      ["baker\'s", "/baker\'s*/", "novvoyxona"],
      ["newsagent\'s", "/newsagent\'s*/", "matbuot do\'koni"],
      ["queue", "/kju/", "navbat"],
      ["checkout", "/ˈʧɛˌkaʊt/", "kassa (supermarketda)"],
      ["trolley", "/ˈtrɑli/", "aravacha (xarid uchun)"],
    ], 'I can talk about shops', 'Places'),
    unit(38, [
      ["flat", "/flæt/", "kvartira"],
      ["house", "/haʊs/", "hovli, uy"],
      ["floor", "/flɔr/", "qavat"],
      ["stairs", "/stɛrz/", "zinapoya"],
      ["lift", "/lɪft/", "lift"],
      ["balcony", "/ˈbælkəni/", "balkon"],
      ["garage", "/gərɑʒ/", "garaj"],
      ["garden", "/ˈgɑrdən/", "bog\'"],
    ], 'I can talk about my home', 'Places'),
    unit(39, [
      ["fridge", "/frɪʤ/", "muzlatkich"],
      ["cooker", "/ˈkʊkər/", "plita (ovqat pishirgich)"],
      ["oven", "/ˈəvən/", "duxovka, pech"],
      ["microwave", "/ˈmaɪkrəˌweɪv/", "mikroto\'lqinli pech"],
      ["sink", "/sɪŋk/", "rakvina (idish yuvadigan)"],
      ["cupboard", "/ˈkəbərd/", "javon (oshxona)"],
      ["dishwasher", "/ˈdɪʃˌwɑʃər/", "idish yuvish mashinasi"],
      ["washing machine", "/ˈwɑʃɪŋ məˈʃin/", "kir yuvish mashinasi"],
      ["shelf", "/ʃɛlf/", "javon tepsisi, tokcha"],
    ], 'I can describe a kitchen', 'Places'),
    unit(40, [
      ["bed", "/bɛd/", "krovat, to\'shak"],
      ["wardrobe", "/ˈwɔrˌdroʊb/", "kiyim javoni"],
      ["desk", "/dɛsk/", "ish stoli"],
      ["mirror", "/ˈmɪrər/", "ko\'zgu"],
      ["bath", "/bæθ/", "vanna"],
      ["shower", "/ʃaʊər/", "dush"],
      ["toilet", "/ˈtɔɪlət/", "hjatxona"],
      ["towel", "/taʊəl/", "sochiq"],
      ["soap", "/soʊp/", "sovun"],
      ["shampoo", "/ʃæmˈpu/", "shampun"],
      ["toothpaste", "/ˈtuθˌpeɪst/", "tish pastasi"],
    ], 'I can describe a bedroom and bathroom', 'Places'),
    unit(41, [
      ["sofa", "/ˈsoʊfə/", "divan"],
      ["armchair", "/ˈɑrmˌʧɛr/", "kreslo"],
      ["carpet", "/ˈkɑrpət/", "gilam"],
      ["rug", "/rəg/", "kichik gilamcha"],
      ["bookshelves", "/ˈbʊkˌʃɛlvz/", "kitob javoni"],
      ["fireplace", "/ˈfaɪərˌpleɪs/", "kamin"],
      ["curtains", "/ˈkərtənz/", "parda"],
      ["lamp", "/læmp/", "chiroq, lampa"],
      ["coffee table", "/ˈkɔfi ˈteɪbəl/", "jurnal stoli"],
      ["cushion", "/ˈkʊʃən/", "divan yostiqchasi"],
      ["radiator", "/ˈreɪdiˌeɪtər/", "batareya, radiator"],
    ], 'I can describe a living room', 'Places'),
    unit(42, [
      ["chemistry", "/ˈkɛmɪstri/", "kimyo"],
      ["physics", "/ˈfɪzɪks/", "fizika"],
      ["biology", "/baɪˈɑləʤi/", "biologiya"],
      ["maths", "/maths*/", "matematika"],
      ["history", "/ˈhɪstəri/", "tarix"],
      ["geography", "/ʤiˈɑgrəfi/", "geografiya"],
      ["literature", "/ˈlɪtərəʧər/", "adabiyot"],
      ["uniform", "/ˈjunəˌfɔrm/", "maktab formasi"],
      ["homework", "/ˈhoʊmˌwərk/", "uy vazifasi"],
      ["exam", "/ɪgˈzæm/", "imtihon"],
      ["pass", "/pæs/", "imtihondan o\'tmoq"],
      ["fail", "/feɪl/", "yiqilmoq (imtihondan)"],
    ], 'I can talk about my school', 'Study and work'),
    unit(43, [
      ["degree", "/dɪˈgri/", "oliy ma\'lumot darajasi"],
      ["undergraduate", "/ˌəndərˈgræʤəwət/", "bakalavr talabasi"],
      ["graduate", "/ˈgræʤəˌweɪt/", "universitetni bitirgan shaxs"],
      ["term", "/tərm/", "semestr, o\'quv davri"],
      ["thesis", "/ˈθiˌsɪs/", "diplom ishi"],
      ["research", "/ˈrisərʧ/", "ilmiy izlanish"],
      ["lawyer", "/ˈlɔjər/", "huquqshunos, advokat"],
      ["architect", "/ˈɑrkəˌtɛkt/", "arxitektor"],
      ["economist", "/ɪˈkɑnəmɪst/", "iqtisodchi"],
    ], 'I can talk about university', 'Study and work'),
    unit(44, [
      ["builder", "/ˈbɪldər/", "quruvchi"],
      ["chef", "/ʃɛf/", "oshpiz"],
      ["hairdresser", "/ˈhɛrˌdrɛsər/", "sartarosh"],
      ["nurse", "/nərs/", "hamshira"],
      ["pilot", "/ˈpaɪlət/", "samolyot uchuvchisi"],
      ["secretary", "/ˈsɛkrəˌtɛri/", "kotib(a)"],
      ["soldier", "/ˈsoʊlʤər/", "harbiy, askar"],
      ["unemployed", "/ˌənɛmˈplɔɪd/", "ishsiz"],
      ["retired", "/rɪˈtaɪrd/", "nafaqaxo\'r"],
    ], 'I can name jobs', 'Study and work'),
    unit(45, [
      ["full-time", "/ˈfʊlˌtaɪm/", "to\'liq stavkali ish"],
      ["part-time", "/ˈpɑrtˈtaɪm/", "yarim stavkali ish"],
      ["salary", "/ˈsæləri/", "oylik maosh (oyma-oy)"],
      ["wages", "/ˈweɪʤɪz/", "haftalik ish haqi"],
      ["earn", "/ərn/", "pul ishlab topmoq"],
      ["colleague", "/ˈkɑlig/", "hamkasb"],
      ["client", "/klaɪənt/", "mijoz"],
      ["meeting", "/ˈmitɪŋ/", "majlis, yig\'ilish"],
      ["report", "/rɪˈpɔrt/", "hisobot"],
    ], 'I can describe a job', 'Study and work'),
    unit(46, [
      ["keyboard", "/ˈkiˌbɔrd/", "klaviatura"],
      ["mouse", "/maʊs/", "mushukcha (kompyuter sichqonchasi)"],
      ["screen", "/skrin/", "ekran"],
      ["printer", "/ˈprɪnər/", "printer"],
      ["laptop", "/ˈlæpˌtɑp/", "noutbuk"],
      ["hard drive", "/hɑrd draɪv/", "qattiq disk"],
      ["memory stick", "/ˈmɛməri stɪk/", "fleshka"],
      ["webcam", "/webcam*/", "veb-kamera"],
    ], 'I can talk about using a computer', 'Study and work'),
    unit(47, [
      ["email", "/iˈmeɪl/", "elektron xat"],
      ["attachment", "/əˈtæʧmənt/", "ilova qilingan fayl"],
      ["inbox", "/inbox*/", "kiruvchi xatlar qutisi"],
      ["reply", "/rɪˈplaɪ/", "javob yozmoq"],
      ["forward", "/ˈfɔrwərd/", "boshqasiga yo\'naltirmoq"],
      ["delete", "/dɪˈlit/", "o\'chirib tashlamoq"],
      ["broadband", "/ˈbrɔdˌbænd/", "yuqori tezlikdagi internet"],
      ["download", "/ˈdaʊnˌloʊd/", "yuklab olmoq"],
    ], 'I can use email and the internet', 'Study and work'),
    unit(48, [
      ["love", "/ləv/", "juda yaxshi ko\'rmoq"],
      ["like", "/laɪk/", "yoqtirmoq"],
      ["hate", "/heɪt/", "nafratlanmoq"],
      ["favourite", "/ˈfeɪvərɪt/", "sevimli"],
      ["enjoy", "/ˌɛnˈʤɔɪ/", "zavqlanmoq"],
      ["boring", "/ˈbɔrɪŋ/", "zerikarli"],
      ["interesting", "/ˈɪntəˌrɛstɪŋ/", "qiziqarli"],
      ["prefer", "/prɪˈfər/", "afzal ko\'rmoq"],
    ], 'I can say what I like', 'Hobbies and interests'),
    unit(49, [
      ["pitch", "/pɪʧ/", "maydon (futbol uchun)"],
      ["court", "/kɔrt/", "kort (tennis, basketbol)"],
      ["goal", "/goʊl/", "gol"],
      ["score", "/skɔr/", "hisob"],
      ["win", "/wɪn/", "g\'alaba qozonmoq"],
      ["lose", "/luz/", "mag\'lub bo\'lmoq"],
      ["draw", "/drɔ/", "durang o\'ynamoq"],
      ["match", "/mæʧ/", "o\'yin, matchList"],
    ], 'I can talk about sport', 'Hobbies and interests'),
    unit(50, [
      ["hobby", "/ˈhɑbi/", "sevimli mashg\'ulot, hobbi"],
      ["fishing", "/ˈfɪʃɪŋ/", "baliq ovlash"],
      ["gardening", "/ˈgɑrdənɪŋ/", "bog\'dorchilik"],
      ["cards", "/kɑrdz/", "qart o\'yini"],
      ["collect", "/kəˈlɛkt/", "turli narsalarni yig\'moq"],
      ["guitar", "/gɪˈtɑr/", "gitara"],
      ["camping", "/ˈkæmpɪŋ/", "lagirda dam olish"],
    ], 'I can talk about my free time', 'Hobbies and interests'),
    unit(51, [
      ["band", "/bænd/", "musiqiy guruh"],
      ["single", "/ˈsɪŋgəl/", "singl (bitta qo\'shiq)"],
      ["album", "/ˈælbəm/", "albom"],
      ["lead singer", "/lɛd ˈsɪŋər/", "asosiy xonanda"],
      ["orchestra", "/ˈɔrkəstrə/", "orkestr"],
      ["conductor", "/kənˈdəktər/", "dirijyor"],
      ["opera", "/ˈɑprə/", "opera"],
      ["composer", "/kəmˈpoʊzər/", "kompozitor"],
    ], 'I can talk about music', 'Hobbies and interests'),
    unit(52, [
      ["thriller", "/θˈrɪlər/", "triller"],
      ["comedy", "/ˈkɑmədi/", "komediya"],
      ["horror film", "/ˈhɔrər fɪlm/", "dahshatli kino"],
      ["action film", "/ˈækʃən fɪlm/", "jangari film"],
      ["love story", "/ləv ˈstɔri/", "sevgi haqidagi hikoya"],
      ["star", "/stɑr/", "asosiy rolni ijro etmoq (aktyor)"],
      ["director", "/dɪˈrɛktər/", "rejissyor"],
      ["cinema", "/ˈsɪnəmə/", "kinozal, teatr"],
    ], 'I can talk about films', 'Hobbies and interests'),
    unit(53, [
      ["media", "/ˈmidiə/", "ommaviy axborot vositalari"],
      ["magazine", "/ˈmægəˌzin/", "jurnal"],
      ["report", "/rɪˈpɔrt/", "xabar tarqatmoq, hisobot"],
      ["event", "/ɪˈvɛnt/", "voqea, hodisa"],
      ["disaster", "/dɪˈzæstər/", "ofat, kulfat"],
      ["celebrity", "/səˈlɛbrɪti/", "mashhur shaxs"],
      ["advertisement", "/ˌædvərˈtaɪzmənt/", "reklama"],
      ["news", "/nuz/", "yangiliklar"],
    ], 'I can talk about the media', 'Hobbies and interests'),
    unit(54, [
      ["abroad", "/əˈbrɔd/", "chet elga"],
      ["holiday", "/ˈhɑlɪˌdeɪ/", "ta\'til, dam olish"],
      ["book", "/bʊk/", "band qilmoq (bron qilmoq)"],
      ["flight", "/flaɪt/", "parvoz"],
      ["accommodation", "/əˌkɑməˈdeɪʃən/", "yashash joyi, mehmonxona"],
      ["passport", "/ˈpæˌspɔrt/", "pasport"],
      ["visa", "/ˈvizə/", "viza"],
      ["travel insurance", "/ˈtrævəl ˌɪnˈʃʊrəns/", "sayohat sug\'urtasi"],
      ["foreign currency", "/ˈfɔrən ˈkərənsi/", "xorijiy valyuta"],
      ["suitcase", "/ˈsutˌkeɪs/", "chamadon"],
      ["hire", "/haɪər/", "ijaraga olmoq"],
    ], 'I can arrange a holiday', 'Holidays'),
    unit(55, [
      ["facilities", "/fəˈsɪlɪtiz/", "qulayliklar"],
      ["air conditioning", "/ɛr kənˈdɪʃənɪŋ/", "konditsioner"],
      ["room service", "/rum ˈsərvɪs/", "xona xizmati"],
      ["staff", "/stæf/", "xodimlar jamoasi"],
      ["guest", "/gɛst/", "mehmon"],
      ["recommend", "/ˌrɛkəˈmɛnd/", "tavsiya qilmoq"],
      ["single room", "/ˈsɪŋgəl rum/", "bir kishilik xona"],
      ["double room", "/ˈdəbəl rum/", "ikki kishilik xona"],
      ["night", "/naɪt/", "tun, kecha"],
    ], 'I can book a hotel room', 'Holidays'),
    unit(56, [
      ["passenger", "/ˈpæsənʤər/", "yo\'lovchi"],
      ["luggage", "/ˈləgɪʤ/", "bagaj, yuk"],
      ["check-in desk", "/check-in* dɛsk/", "ro\'yxatdan o\'tish stoli"],
      ["hand luggage", "/hænd ˈləgɪʤ/", "qo\'l yuki"],
      ["boarding card", "/ˈbɔrdɪŋ kɑrd/", "samolyotga chiqish kartasi"],
      ["departure", "/dɪˈpɑrʧər/", "jo\'nab ketish"],
      ["gate", "/geɪt/", "chiqish eshigi (aeroportda)"],
      ["delayed", "/dɪˈleɪd/", "kechiktirilgan"],
      ["customs", "/ˈkəstəmz/", "bojxona"],
    ], 'I can communicate in an airport', 'Holidays'),
    unit(57, [
      ["resort", "/rɪˈzɔrt/", "kurort maskani"],
      ["rent", "/rɛnt/", "ijaraga olmoq"],
      ["apartment", "/əˈpɑrtmənt/", "kvartira"],
      ["sunbathe", "/ˈsənˌbeɪð/", "quyoshda toblanmoq"],
      ["relax", "/rɪˈlæks/", "hordiq chiqarmoq, dam olmoq"],
      ["swimming costume", "/sˈwɪmɪŋ ˈkɑstum/", "cho\'milish kiyimi (ayollar)"],
      ["shorts", "/ʃɔrts/", "kalta shim"],
    ], 'I can describe a beach holiday', 'Holidays'),
    unit(58, [
      ["map", "/mæp/", "xarita"],
      ["guidebook", "/ˈgaɪdˌbʊk/", "yo\'riqnoma kitobcha (gid)"],
      ["sightseeing", "/ˈsaɪtˈsiɪŋ/", "diqqatga sazovor joylarni ko\'rish"],
      ["tourist", "/ˈtʊrɪst/", "sayyoh, turist"],
      ["gallery", "/ˈgæləri/", "galereya"],
      ["tour", "/tʊr/", "ekskursiya, safar"],
      ["get lost", "/gɪt lɔst/", "adashib qolmoq"],
    ], 'I can describe a sightseeing holiday', 'Holidays'),
    unit(59, [
      ["cash machine", "/kæʃ məˈʃin/", "bankomat"],
      ["bureau de change", "/ˈbjʊroʊ də ʧeɪnʤ/", "valyuta almashtirish shoxobchasi"],
      ["currency", "/ˈkərənsi/", "valyuta"],
      ["exchange rate", "/ɪksˈʧeɪnʤ reɪt/", "valyuta kursi"],
      ["commission", "/kəˈmɪʃən/", "komissiya haqi"],
      ["stamp", "/stæmp/", "pochta markasi"],
      ["envelope", "/ˈɛnvəˌloʊp/", "konvert"],
      ["parcel", "/ˈpɑrsəl/", "banderol, posilka"],
      ["postbox", "/postbox*/", "pochta qutisi"],
    ], 'I can use the bank and post office', 'Holidays'),
    unit(60, [
      ["good morning", "/gʊd ˈmɔrnɪŋ/", "xayrli tong"],
      ["good afternoon", "/gʊd ˌæftərˈnun/", "xayrli kun"],
      ["good evening", "/gʊd ˈivnɪŋ/", "xayrli kech"],
      ["goodbye", "/ˌgʊdˈbaɪ/", "xayr"],
      ["bye", "/baɪ/", "salomat bo\'ling (norasmiy xayrlashuv)"],
      ["meet", "/mit/", "uchrashmoq, tanishmoq"],
      ["shake hands", "/ʃeɪk hænz/", "qo\'l berib ko\'rishmoq"],
    ], 'I can meet and greet people', 'Social English'),
    unit(61, [
      ["goodnight", "/ˈgʊdˌnaɪt/", "xayrli tun (uxlash oldidan)"],
      ["sleep well", "/slip wɛl/", "tinch uxlab turing"],
      ["merry Christmas", "/ˈmɛri ˈkrɪsməs/", "Rojdestvo muborak bo\'lsin"],
      ["happy New Year", "/ˈhæpi nu jɪr/", "Yangi yil muborak bo\'lsin"],
      ["happy birthday", "/ˈhæpi ˈbərθˌdeɪ/", "tug\'ilgan kuningiz muborak bo\'lsin"],
      ["well done", "/wɛl dən/", "barakalla, ofarin"],
      ["congratulations", "/kənˌgræʧəˈleɪʃənz/", "tabriklayman"],
      ["good luck", "/gʊd lək/", "omad tilayman"],
      ["cheers", "/ʧɪrz/", "qadah urishtirish / rahmat (norasmiy)"],
    ], 'I can use special greetings', 'Social English'),
    unit(62, [
      ["whose", "/huz/", "kimning"],
      ["belong to", "/bɪˈlɔŋ tɪ/", "tegishli bo\'lmoq"],
      ["nearest", "/ˈnɪrəst/", "eng yaqin"],
      ["recommend", "/ˌrɛkəˈmɛnd/", "tavsiya qilmoq"],
      ["worth seeing", "/wərθ siɪŋ/", "ko\'rishga arziydigan"],
    ], 'I can ask for information', 'Social English'),
    unit(63, [
      ["bring", "/brɪŋ/", "olib kelmoq"],
      ["lend", "/lɛnd/", "qarzga bermoq"],
      ["borrow", "/ˈbɑˌroʊ/", "qarzga olmoq"],
      ["change places", "/ʧeɪnʤ ˈpleɪsɪz/", "o\'rin almashmoq"],
      ["wait", "/weɪt/", "kutmoq"],
      ["permission", "/pərˈmɪʃən/", "ruxsat"],
    ], 'I can ask for things', 'Social English'),
    unit(64, [
      ["invite", "/ˌɪnˈvaɪt/", "taklif qilmoq"],
      ["come round", "/kəm raʊnd/", "mehmon sifatida kelmoq, uyga kirib o\'tmoq"],
      ["party", "/ˈpɑrti/", "bazm, ziyofat"],
      ["great", "/greɪt/", "ajoyib, zo\'r"],
      ["busy", "/ˈbɪzi/", "band"],
    ], 'I can invite people', 'Social English'),
    unit(65, [
      ["suggestion", "/səˈʤɛsʧən/", "taklif"],
      ["shall we", "/ʃæl wi/", "... qilaylikmi?"],
      ["maybe", "/ˈmeɪbi/", "balki"],
      ["perhaps", "/pərˈhæps/", "ehtimol"],
      ["prefer", "/prɪˈfər/", "afzal ko\'rmoq"],
    ], 'I can make suggestions', 'Social English'),
    unit(66, [
      ["offer", "/ˈɔfər/", "taklif qilmoq (yordam yoki narsa)"],
      ["accept", "/əkˈsɛpt/", "qabul qilmoq (rozilik bildirmoq)"],
      ["refuse", "/ˈrɛfˌjuz/", "rad etmoq, yo\'q demoq"],
      ["help", "/hɛlp/", "yordam bermoq"],
      ["don\'t worry", "/don\'t* ˈwəri/", "xavotir olmang"],
    ], 'I can offer, accept, and refuse', 'Social English'),
    unit(67, [
      ["sorry", "/ˈsɑri/", "kechirasiz, uzr"],
      ["apologize", "/əˈpɑləˌʤaɪz/", "uzr so\'ramoq"],
      ["never mind", "/ˈnɛvər maɪnd/", "hechqisi yo\'q"],
      ["that\'s all right", "/that\'s* ɔl raɪt/", "hammasi joyida, hechqisi yo\'q"],
      ["problem", "/ˈprɑbləm/", "muammo"],
    ], 'I can say sorry and respond', 'Social English'),
    unit(68, [
      ["opinion", "/əˈpɪnjən/", "fikr, nuqtai nazar"],
      ["think", "/θɪŋk/", "o\'ylamoq, deb hisoblamoq"],
      ["agree", "/əˈgri/", "qo\'shilmoq (fikrga)"],
      ["disagree", "/dɪsəˈgri/", "qo\'shilmaslik"],
      ["right", "/raɪt/", "haqiqat, to\'g\'ri"],
    ], 'I can express my opinion', 'Social English'),
    unit(69, [
      ["phone", "/foʊn/", "telefon qilmoq"],
      ["call", "/kɔl/", "qo\'ng\'iroq qilmoq"],
      ["message", "/ˈmɛsɪʤ/", "xabar"],
      ["speak", "/spik/", "gaplashmoq"],
      ["wrong number", "/rɔŋ ˈnəmbər/", "xato raqam"],
    ], 'I can use the phone', 'Social English'),
    unit(70, [
      ["good", "/gʊd/", "yaxshi"],
      ["bad", "/bæd/", "yomon"],
      ["big", "/bɪg/", "katta"],
      ["small", "/smɔl/", "kichik"],
      ["new", "/nu/", "yangi"],
      ["old", "/oʊld/", "eski, qari"],
      ["hot", "/hɑt/", "issiq"],
      ["cold", "/koʊld/", "sovuq"],
      ["fast", "/fæst/", "tez"],
      ["slow", "/sloʊ/", "sekin"],
    ], 'I can use common adjectives', 'Language'),
    unit(71, [
      ["quickly", "/kˈwɪkli/", "tezda"],
      ["slowly", "/sˈloʊli/", "sekin"],
      ["well", "/wɛl/", "yaxshi"],
      ["badly", "/ˈbædli/", "yomon tarzda"],
      ["early", "/ˈərli/", "erta"],
      ["late", "/leɪt/", "kech"],
      ["loudly", "/ˈlaʊdli/", "baland ovozda"],
      ["quietly", "/kˈwaɪətli/", "tinch, past ovozda"],
    ], 'I can use common adverbs', 'Language'),
    unit(72, [
      ["be", "/bi/", "bo\'lmoq (was/were)"],
      ["do", "/du/", "bajarmoq (did)"],
      ["go", "/goʊ/", "bormoq (went)"],
      ["have", "/hæv/", "ega bo\'lmoq (had)"],
      ["make", "/meɪk/", "yasamoq, qilmoq (made)"],
      ["see", "/si/", "ko\'rmoq (saw)"],
      ["take", "/teɪk/", "olmoq (took)"],
      ["write", "/raɪt/", "yozmoq (wrote)"],
    ], 'I can use irregular verbs', 'Language'),
    unit(73, [
      ["get up", "/gɪt əp/", "o\'rindan turmoq"],
      ["sit down", "/sɪt daʊn/", "o\'tirmoq"],
      ["turn on", "/tərn ɔn/", "yoqmoq (uskunani)"],
      ["turn off", "/tərn ɔf/", "o\'chirmoq (uskunani)"],
      ["look for", "/lʊk fər/", "qidirmoq"],
      ["give back", "/gɪv bæk/", "orqaga qaytarib bermoq"],
    ], 'I can use phrasal verbs', 'Language'),
    unit(74, [
      ["in", "/ɪn/", "da (oylar, yillar, fasllar uchun)"],
      ["on", "/ɔn/", "da (kunlar va sanalar uchun)"],
      ["at", "/æt/", "da (aniq vaqt uchun)"],
      ["from... to...", "/frəm... tɪ.../", "...-dan ...-gacha"],
    ], 'I can use prepositions of time', 'Language'),
    unit(75, [
      ["yesterday", "/ˈjɛstərˌdeɪ/", "kecha"],
      ["today", "/təˈdeɪ/", "bugun"],
      ["tomorrow", "/təˈmɑˌroʊ/", "ertaga"],
      ["ago", "/əˈgoʊ/", "oldingi, burun (... -dan oldin)"],
      ["next", "/nɛkst/", "keyingi"],
      ["last", "/læst/", "o\'tgan"],
    ], 'I can use time words and phrases', 'Language'),
    unit(76, [
      ["in", "/ɪn/", "ichida"],
      ["on", "/ɔn/", "ustida"],
      ["under", "/ˈəndər/", "tagida"],
      ["next to", "/nɛkst tɪ/", "yonida"],
      ["in front of", "/ɪn frənt əv/", "oldida"],
      ["behind", "/bɪˈhaɪnd/", "orqasida"],
      ["into", "/ˈɪntu/", "ichiga (harakat)"],
      ["out of", "/aʊt əv/", "ichidan (chiqish)"],
    ], 'I can use prepositions of place and movement', 'Language'),
    unit(77, [
      ["and", "/ənd/", "va"],
      ["but", "/bət/", "lekin, biroq"],
      ["or", "/ər/", "yoki"],
      ["because", "/bɪˈkəz/", "chunki"],
      ["so", "/soʊ/", "shuning uchun"],
    ], 'I can use link words (1)', 'Language'),
    unit(78, [
      ["although", "/ˌɔlˈðoʊ/", "...-sa ham, garchi"],
      ["however", "/ˌhaʊˈɛvər/", "biroq, shunga qaramay"],
      ["then", "/ðɛn/", "keyin, so\'ngra"],
      ["after", "/ˈæftər/", "...-dan keyin"],
      ["before", "/ˌbiˈfɔr/", "...-dan oldin"],
    ], 'I can use link words (2)', 'Language'),
    unit(79, [
      ["have", "/hæv/", "ega bo\'lmoq / qilmoq"],
      ["have got", "/hæv gɑt/", "ega bo\'lmoq"],
      ["have breakfast", "/hæv ˈbrɛkfəst/", "nonushta qilmoq"],
      ["have a shower", "/hæv ə ʃaʊər/", "dush qabul qilmoq"],
    ], 'I can use \'have\' and \'have got\'', 'Language'),
    unit(80, [
      ["get", "/gɪt/", "olmoq, erishmoq, kelmoq"],
      ["get up", "/gɪt əp/", "o\'rindan turmoq"],
      ["get dressed", "/gɪt drɛst/", "kiyinmoq"],
      ["get home", "/gɪt hoʊm/", "uyga yetib kelmoq"],
      ["get a ticket", "/gɪt ə ˈtɪkɪt/", "chipta sotib olmoq / olmoq"],
    ], 'I can use \'get\'', 'Language'),
  ],
};
